import {describe,it,expect,beforeAll} from 'vitest';
import {randomUUID} from 'node:crypto';
import {gapActors} from '../fixtures/gaps/seed';
import {syntheticGap} from '../fixtures/gaps/ui';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {gapEnvelope,reviewedSyntheticGap} from '../fixtures/gaps/authoring';
import {saveGap,readGap,readGaps} from '../../lib/server/gaps/service';
describe('Gap projection scope and working/reviewed boundaries',()=>{
 let actors:Awaited<ReturnType<typeof gapActors>>;
 beforeAll(async()=>{actors=await gapActors();});
 it('conceals existence and list contents from partners',async()=>{const gap=await saveGap(actors.panel,{contractVersion:'product-gaps-v1',requestKey:randomUUID(),expectedVersion:0,content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true});await expect(readGap(actors.partner,gap.recordId!)).rejects.toMatchObject({status:404});await expect(readGaps(actors.partner,{})).rejects.toMatchObject({status:404});});
 it('filters before returning prose and binds cursor to actor and filters',async()=>{for(let i=0;i<2;i++)await saveGap(actors.panel,{contractVersion:'product-gaps-v1',requestKey:randomUUID(),expectedVersion:0,content:syntheticGap({title:`Projection Synthetic ${i}`}),sourceRefs:[],customerIndependentAcknowledgment:true});const first=await readGaps(actors.panel,{limit:1,query:'Projection Synthetic'});expect(first.items).toHaveLength(1);expect(first.items[0].reviewed).toBe(false);expect(first.nextCursor).toBeTypeOf('string');await expect(readGaps(actors.mcteer,{limit:1,query:'Projection Synthetic',cursor:first.nextCursor})).rejects.toMatchObject({code:'cursor_changed'});await expect(readGaps(actors.panel,{limit:1,query:'different',cursor:first.nextCursor})).rejects.toMatchObject({code:'cursor_changed'});expect((await readGaps(actors.panel,{limit:1,query:'Projection Synthetic',cursor:first.nextCursor})).items).toHaveLength(1);});
 it('invalidates ordering cursors after a gap changes and conceals cross-workspace detail',async()=>{const prefix='Synthetic cursor generation '+randomUUID(),one=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:prefix+' one'});await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:prefix+' two'});const first=await readGaps(actors.panel,{limit:1,query:prefix});expect(first.nextCursor).toBeTypeOf('string');await saveGap(actors.panel,{...gapEnvelope(one.version),content:syntheticGap({title:prefix+' changed'}),sourceRefs:[],customerIndependentAcknowledgment:true},one.id);await expect(readGaps(actors.panel,{limit:1,query:prefix,cursor:first.nextCursor})).rejects.toMatchObject({status:409,code:'cursor_changed'});const workspaceId=randomUUID(),membershipId=randomUUID();await withGapDatabase(async db=>{await db.query("INSERT INTO workspaces(id,name) VALUES($1,'Synthetic unrelated gap workspace')",[workspaceId]);await db.query("INSERT INTO memberships(id,principal_id,workspace_id,kind,role) VALUES($1,$2,$3,'internal','member')",[membershipId,actors.panel.principalId,workspaceId]);await db.query('INSERT INTO gap_workspace_state(environment_id,workspace_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[process.env.TURAS_ENVIRONMENT_ID,workspaceId]);});await expect(readGap({...actors.panel,workspaceId,membershipId},one.id)).rejects.toMatchObject({status:404});});

});
