import type { DemoData } from "./types";

export const DEMO_DATA: DemoData = {
  version: "2026-09-19.1",
  reportingDate: "2026-09-18",
  workspaceId: "synthetic-interview-demo",
  customers: [
    {
      id: "acct-notion-labs",
      name: "Notion Labs (fictional engagement)",
      aliases: ["Notion", "Notion Labs"],
      objective: "Help workspace administrators reach a reliable pilot launch with named operating ownership.",
      workspaceId: "synthetic-interview-demo",
    },
    {
      id: "acct-linearworks",
      name: "LinearWorks (fictional engagement)",
      aliases: ["Linear", "LinearWorks"],
      objective: "Reduce release-review friction for the first two product teams.",
      workspaceId: "synthetic-interview-demo",
    },
    {
      id: "acct-coda-collective",
      name: "Coda Collective (fictional engagement)",
      aliases: ["Coda", "Coda Collective"],
      objective: "Establish a repeatable content publishing workflow with measurable adoption.",
      workspaceId: "synthetic-interview-demo",
    },
  ],
  engagements: [
    {
      id: "eng-notion-pilot",
      accountId: "acct-notion-labs",
      name: "Pilot launch and operating handoff",
      stage: "Prove",
      customerOwner: "Maya Chen, fictional customer sponsor",
      deliveryOwner: "Avery Morgan, fictional FDE lead",
      nextDecision: "Approve a bounded 40-hour enablement intervention or defer the pilot gate.",
      decisionDeadline: "2026-09-23",
      outcome: "Pilot administrators complete a governed rollout and own the first 30-day adoption review.",
      scope: "Pilot readiness, enablement, launch support, and an operating handoff for 40 administrators.",
      exclusions: "Broad platform migration, permanent support staffing, and customer-system mutations.",
      fee: 60000,
      actualHours: 240,
      remainingHours: 80,
      loadedHourlyCost: 125,
      nonLaborCost: 3000,
      risk: "High delivery risk: unresolved enablement ownership may turn a fixed-fee overrun into a delayed launch.",
      maturity: "Activate: sponsor and pilot boundary are clear; operating-owner acceptance evidence is incomplete.",
      evidence: [
        { id: "ev-notion-brief", label: "Synthetic pilot-readiness brief", observedAt: "2026-09-16", confidence: "High", detail: "12 of 40 administrators completed readiness training; customer support owner is not yet named." },
        { id: "ev-notion-plan", label: "Synthetic delivery forecast", observedAt: "2026-09-18", confidence: "High", detail: "Forecast shows 80 remaining hours without a bounded enablement intervention." },
      ],
      proposedIntervention: {
        id: "proposal-notion-enablement",
        description: "Fund a 40-hour train-the-trainer and launch-readiness intervention, then require customer-owner acceptance before the wider pilot.",
        remainingHours: 40,
        requiredSkill: "Enablement lead",
        startDate: "2026-09-22",
        owner: "Avery Morgan, fictional FDE lead",
      },
    },
    {
      id: "eng-linear-release",
      accountId: "acct-linearworks",
      name: "Release workflow acceleration",
      stage: "Promote",
      customerOwner: "Jordan Patel, fictional product owner",
      deliveryOwner: "Riley Brooks, fictional PS lead",
      nextDecision: "Confirm the production release gate and retrospective owner.",
      decisionDeadline: "2026-09-29",
      outcome: "Two product teams ship under a controlled review workflow.",
      scope: "Release controls, stakeholder review, and a production-readiness workshop.",
      exclusions: "Organization-wide process redesign.",
      fee: 42000,
      actualHours: 180,
      remainingHours: 40,
      loadedHourlyCost: 135,
      nonLaborCost: 1800,
      risk: "Medium schedule risk: security review is awaiting a named approver.",
      maturity: "Accelerate: delivery collaboration is repeatable for the selected teams.",
      evidence: [{ id: "ev-linear-gate", label: "Synthetic release-gate checklist", observedAt: "2026-09-17", confidence: "Medium", detail: "Technical checks are complete; security approval is pending." }],
    },
    {
      id: "eng-coda-content",
      accountId: "acct-coda-collective",
      name: "Content workflow discovery",
      stage: "Discover",
      customerOwner: "Sam Rivera, fictional marketing sponsor",
      deliveryOwner: "Quinn Taylor, fictional FDE lead",
      nextDecision: "Select a measurable first publishing workflow.",
      decisionDeadline: "2026-10-02",
      outcome: "A named content team can publish a priority journey with an agreed baseline.",
      scope: "Discovery, baseline design, and a bounded proof plan.",
      exclusions: "Implementation or adoption commitments before the baseline is accepted.",
      fee: 18000,
      actualHours: 48,
      remainingHours: 48,
      loadedHourlyCost: 120,
      nonLaborCost: 600,
      risk: "Unknown outcome risk: adoption baseline has not been observed.",
      maturity: "Explore: a sponsor exists, but workflow ownership and baseline evidence remain incomplete.",
      evidence: [{ id: "ev-coda-discovery", label: "Synthetic discovery note", observedAt: "2026-09-15", confidence: "Low", detail: "The sponsor identified several workflows; no priority outcome is selected." }],
    },
    {
      id: "eng-linear-enablement",
      accountId: "acct-linearworks",
      name: "Team enablement follow-through",
      stage: "Prove",
      customerOwner: "Jordan Patel, fictional product owner",
      deliveryOwner: "Riley Brooks, fictional PS lead",
      nextDecision: "Review adoption evidence after enablement.",
      decisionDeadline: "2026-10-06",
      outcome: "Release coordinators complete the new review workflow without shadow support.",
      scope: "Coordinator enablement and office hours.",
      exclusions: "Additional engineering implementation.",
      fee: 24000,
      actualHours: 80,
      remainingHours: 40,
      loadedHourlyCost: 115,
      nonLaborCost: 500,
      risk: "Low delivery risk; evidence is due after the first live release.",
      maturity: "Activate: named coordinators and a feedback cadence are in place.",
      evidence: [{ id: "ev-linear-training", label: "Synthetic training attendance", observedAt: "2026-09-18", confidence: "High", detail: "All six pilot coordinators completed training." }],
    },
  ],
  team: [
    { id: "team-avery", name: "Avery Morgan", role: "FDE lead", skill: "Enablement lead", weeklyAvailableHours: 40, committedHours: 28, protectedHours: 8 },
    { id: "team-riley", name: "Riley Brooks", role: "PS lead", skill: "Delivery lead", weeklyAvailableHours: 40, committedHours: 30, protectedHours: 6 },
    { id: "team-quinn", name: "Quinn Taylor", role: "FDE lead", skill: "Discovery", weeklyAvailableHours: 40, committedHours: 24, protectedHours: 8 },
  ],
};
