import {z} from 'zod';
import {gapAudienceSchema,gapContentSchema,gapImpactContentSchema,gapSourcesSchema,gapSourceSchema,type GapContent,type GapImpactContent,type GapSource} from '../contracts/product-gaps';
import {impactSets} from './impact';
import type {GapRank} from './ranking';
export type GapReportSnapshot={reportId:string;revisionId:string;kind:'detail'|'portfolio';preparedAt:string;asOf:string;comparisonAt:string|null;audience:z.infer<typeof gapAudienceSchema>;preparer:string;customers:{id:string;name:string}[];gaps:{id:string;revisionId:string;content:GapContent;disposition:string;revisitAt:string|null;counts:{confirmed:number;suspectedOnly:number;resolvedHistory:number};comparison:unknown;ranking:{methodVersion:string;factors:GapRank;freshness:string};impacts:{id:string;revisionId:string;customerId:string;classification:GapImpactContent['classification'];content:GapImpactContent;sourceRefs:GapSource[]}[];sources:{reference:GapSource;text:string;metadata:unknown}[];lineage:unknown[];handoffs:unknown[]}[]};
export type GapReportDocument={schemaVersion:'gap-recipient-v1';header:{reportId:string;revisionId:string;templateVersion:'gap-detail-v1'|'gap-portfolio-v1';impactMethod:'gap-impact-v1';orderMethod:'gap-order-v1';preparedAt:string;asOf:string;comparisonAt:string|null;audience:GapReportSnapshot['audience'];classification:string;preparer:string;selectedGapIds:string[];view:string};customers:GapReportSnapshot['customers'];sections:{id:number;title:string;content:unknown}[];review:{designatedReviewer:'mcteer';approval:string}};
function safeLocators(value:unknown):void{if(Array.isArray(value)){value.forEach(safeLocators);return;}if(value&&typeof value==='object'){for(const [key,item]of Object.entries(value)){if(/url$/i.test(key)&&typeof item==='string'){const u=new URL(item);if(u.protocol!=='https:'||u.username||u.password||[...u.searchParams.keys()].some(k=>/token|secret|password|signature|credential|api.?key|^sig$/i.test(k)))throw Error('Unsafe source URL');}safeLocators(item);}}}
export function composeGapReport(input:GapReportSnapshot):GapReportDocument{
 z.uuid().parse(input.reportId);z.uuid().parse(input.revisionId);gapAudienceSchema.parse(input.audience);if(input.gaps.length>100||input.kind==='detail'&&input.gaps.length!==1||input.customers.length>200||new Set(input.gaps.map(g=>g.id)).size!==input.gaps.length||new Set(input.customers.map(c=>c.id)).size!==input.customers.length)throw Error('Report scope exceeds bounds');
 const customers=new Set(input.customers.map(c=>c.id));for(const customer of input.customers){z.uuid().parse(customer.id);if(!customer.name.trim())throw Error('Missing disclosed customer label');}
 for(const gap of input.gaps){z.uuid().parse(gap.id);z.uuid().parse(gap.revisionId);gapContentSchema.parse(gap.content);if(input.kind==='portfolio'&&gap.content.kind!=='product_gap')throw Error('Portfolio requires product gaps');const sources=new Map(gap.sources.map(s=>[s.reference.id+':'+s.reference.purpose,s]));if(gap.sources.length>2000||sources.size!==gap.sources.length)throw Error('Report citation scope exceeds bounds');gap.sources.forEach(s=>gapSourceSchema.parse(s.reference));for(const source of gap.sources){if(source.reference.customerId&&!customers.has(source.reference.customerId))throw Error('Undisclosed citation customer');safeLocators(source.reference.locator);}
  for(const impact of gap.impacts){if(!customers.has(impact.customerId)||impact.classification!==impact.content.classification)throw Error('Undisclosed impact or inconsistent classification');gapImpactContentSchema.parse(impact.content);gapSourcesSchema.parse(impact.sourceRefs);for(const ref of impact.sourceRefs)if(!sources.has(ref.id+':'+ref.purpose))throw Error('Unresolved original citation');for(const assertion of impact.content.assertions)if(assertion.sourceKeys.some(key=>!impact.sourceRefs.some(r=>r.id===key)))throw Error('Unresolved assertion citation');}
  const sets=impactSets(gap.impacts.map(i=>({customerId:i.customerId,classification:i.classification})));if(gap.counts.confirmed!==sets.confirmed.length||gap.counts.suspectedOnly!==sets.suspectedOnly.length||gap.counts.resolvedHistory!==sets.resolvedHistory.length)throw Error('Impact set parity failed');
 }
 const header:GapReportDocument['header']={reportId:input.reportId,revisionId:input.revisionId,templateVersion:input.kind==='detail'?'gap-detail-v1':'gap-portfolio-v1',impactMethod:'gap-impact-v1',orderMethod:'gap-order-v1',preparedAt:input.preparedAt,asOf:input.asOf,comparisonAt:input.comparisonAt,audience:input.audience,classification:'Internal confidential — use only for the named engineering audience and purpose',preparer:input.preparer,selectedGapIds:input.gaps.map(g=>g.id),view:'Current reviewed canonical narrative and relations; impact recomputed at cutoff under current access'};
 const limits={selection:input.gaps.map(g=>g.id),cutoff:input.asOf,comparison:input.comparisonAt??'Unknown — no comparison requested',deduplication:'One canonical customer per gap. Confirmed suppresses suspected-only. Resolved history is nonadditive and may overlap recurrence.',authority:'Every selected original is eligible at cutoff and now under current internal access. No hidden-customer totals.',unknowns:'Missing dates, costs, evidence and non-goals remain Unknown; no ARR or roadmap promise is inferred.',lineage:input.gaps.map(g=>({gapId:g.id,relations:g.lineage})),methods:['gap-impact-v1','gap-order-v1']};
 let sections:GapReportDocument['sections'];
 if(input.kind==='detail'){const gap=input.gaps[0],c=gap.content;sections=[
  {id:1,title:'Problem',content:{gapId:gap.id,revisionId:gap.revisionId,kind:c.kind,product:c.productKey,capability:c.capability,productVersion:c.productVersion??'Unknown',title:c.title,problem:c.problem,workflow:c.workflow,desiredOutcome:c.desiredOutcome}},
  {id:2,title:'Evidence and scope',content:{reproduction:c.reproduction,constraints:c.constraints,currentProductChecks:gap.sources.filter(s=>s.reference.purpose==='product_limitation'),confirmedCustomers:gap.counts.confirmed,suspectedOnlyCustomers:gap.counts.suspectedOnly}},
  {id:3,title:'Impact',content:{counts:gap.counts,nonadditivity:'Resolved history is nonadditive',severity:c.severity,severityRationale:c.severityRationale,observations:gap.impacts,commercialAttribution:'Unknown — no ARR attribution calculated'}},
  {id:4,title:'Workarounds',content:{steps:c.workaround,limitations:c.workaroundLimitations,feasibility:c.workaroundFeasibility,cost:'Unknown — reviewed operational burden is in each observation',supportability:c.constraints}},
  {id:5,title:'Proposed capability',content:{proposal:c.proposedCapability,userNeed:c.desiredOutcome,acceptanceCriteria:c.acceptanceCriteria,constraintsAndNonGoals:c.constraints,alternatives:c.alternatives}},
  {id:6,title:'Engineering handoff',content:{requestedDecision:c.requestedDecision,unknowns:c.unknowns,triageTeam:c.triageTeam,disposition:gap.disposition,revisitAt:gap.revisitAt??'Unknown',duplicateLineage:gap.lineage,humanReportedHistory:gap.handoffs,commitment:'No product commitment or delivery date is implied'}},
  {id:7,title:'Evidence appendix and review',content:{sources:gap.sources,customerDisclosure:input.customers,methods:limits,review:'Designated reviewer mcteer; actual approval is verified separately by download receipt'}}];
 }else sections=[
  {id:1,title:'Executive summary',content:{scope:input.gaps.length?'Explicit selected reviewed product gaps':'No gaps selected',blockers:input.gaps.map(g=>({gapId:g.id,problem:g.content.problem,requestedDecision:g.content.requestedDecision,comparison:g.comparison??'Unknown — no comparison requested'}))}},
  {id:2,title:'Gap table',content:input.gaps.map(g=>{const dates=g.impacts.map(i=>i.content.observedAt).filter((d):d is string=>Boolean(d)).sort();return {gapId:g.id,revisionId:g.revisionId,product:g.content.productKey,capability:g.content.capability,title:g.content.title,problem:g.content.problem,severity:g.content.severity,counts:g.counts,firstObserved:dates[0]??'Unknown',lastObserved:dates.at(-1)??'Unknown',trend:g.comparison??'Unknown — no comparison requested',workaround:g.content.workaround,feasibility:g.content.workaroundFeasibility,triageTeam:g.content.triageTeam,disposition:g.disposition,detailReference:`/product-gaps/${g.id}`,evidence:g.sources,observations:g.impacts};})},
  {id:3,title:'Prioritization',content:{method:'gap-order-v1',rationale:'Due revisit, reviewed severity, confirmed breadth, workaround feasibility, oldest review, canonical identity. No numeric weights.',factors:input.gaps.map(g=>({gapId:g.id,...g.ranking}))}},
  {id:4,title:'Actions',content:input.gaps.map(g=>({gapId:g.id,disposition:g.disposition,requestedDecision:g.content.requestedDecision,revisitAt:g.revisitAt??'Unknown',humanReportedHistory:g.handoffs}))},
  {id:5,title:'Method and limits',content:limits}];
 const document:GapReportDocument={schemaVersion:'gap-recipient-v1',header,customers:input.customers,sections,review:{designatedReviewer:'mcteer',approval:'Approval is verified separately by the digest-matched download receipt'}};if(Buffer.byteLength(JSON.stringify(document))>2*1024*1024)throw Error('Structured report exceeds limit');return document;
}
