import type {ReportDocument} from '../lib/reports/document';
export function escapeReportText(text:string){return text.replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));}
export function renderWeeklyTemplate(document:ReportDocument){
 const escape=escapeReportText;
 const sections=document.sections.map(section=>`<section><h2>${escape(section.heading)}</h2>${section.blocks.map(block=>`<p>${escape(block.text)}${block.citations.length?` <small>[${block.citations.map(escape).join(', ')}]</small>`:''}</p>`).join('')}</section>`).join('');
 const metrics=document.metrics.length?`<section aria-label="Effort Measures"><table><thead><tr><th scope="col">Measure</th><th scope="col">Value</th></tr></thead><tbody>${document.metrics.map(metric=>`<tr><th scope="row">${escape(metric.label)}</th><td>${escape(metric.value===null?`Unknown — ${metric.reason??'No reviewed input'}`:`${metric.value} ${metric.unit}`)}${metric.citations.length?` <small>[${metric.citations.map(escape).join(', ')}]</small>`:''}</td></tr>`).join('')}</tbody></table></section>`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escape(document.title)}</title></head><body style="margin:0;background:#fafafa;color:#171717;font-family:Geist,Arial,sans-serif"><main style="max-width:720px;margin:24px auto;background:#fff;border:1px solid #e5e5e5;padding:32px"><p>${escape(document.classification)}</p><h1>${escape(document.title)}</h1><p>${escape(document.period.fromDate)} – ${escape(document.period.toDate)} · ${escape(document.timezone)}${document.partial?' · Partial Period':''}</p><p>Accountable Owner: ${escape(document.ownerLabel)}<br>Executive Sponsor: ${escape(document.sponsorLabel)}</p>${sections}${metrics}${document.annotations.length?`<section><h2>Reviewer Annotations</h2>${document.annotations.map(annotation=>`<p>Annotation (not an accepted fact): ${escape(annotation)}</p>`).join('')}</section>`:''}<footer><h2>Evidence References</h2>${document.citations.map(citation=>`<p>${escape(citation.label)} — ${escape(citation.description)}</p>`).join('')}<p>Captured ${escape(document.asOf)} · ${escape(document.templateVersion)}</p></footer></main></body></html>`;
}
export function renderReportPlainText(document:ReportDocument){return [document.title,document.classification,`${document.period.fromDate} to ${document.period.toDate} (${document.timezone})${document.partial?' — Partial Period':''}`,
 `Accountable Owner: ${document.ownerLabel}`,`Executive Sponsor: ${document.sponsorLabel}`,
 ...document.sections.flatMap(section=>[section.heading,...section.blocks.map(block=>`${block.text}${block.citations.length?' ['+block.citations.join(', ')+']':''}`)]),
 'Measures',...document.metrics.map(metric=>`${metric.label}: ${metric.value===null?'Unknown — '+(metric.reason??'No reviewed input'):metric.value+' '+metric.unit}${metric.citations.length?' ['+metric.citations.join(', ')+']':''}`),
 ...document.annotations.map(annotation=>'Reviewer annotation (not an accepted fact): '+annotation),
 'Evidence References',...document.citations.map(citation=>`${citation.label} — ${citation.description}`),`Captured ${document.asOf} · ${document.templateVersion}`].join('\n\n');}
