'use client';
import {useEffect,useRef,useState} from 'react';
import {reportGet} from './client';
type Policy={policyId:string;version:number;state:string;selection:{kind:string;audience:string};recipients:Array<{address:string}>};
type Delivery={deliveryId:string;version:number;state:string;attemptCount:number;address:string|null;providerMessageId:string|null;failureCode:string|null};
type SendPreview={previewId:string;previewDigest:string;expiresAt:string;binding:{senderAddress:string;subject:string;html:string;plainText:string;recipients:Array<{address:string}>}};
type Props={customerId:string;reportId:string;version:number;kind:string;audience:string;csrfToken:string;canSend:boolean;busy:boolean;onSave:(url:string,input:Record<string,unknown>)=>Promise<unknown>};
export function DeliveryReview(props:Props){
 const [policies,setPolicies]=useState<Policy[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[policyId,setPolicyId]=useState(''),[preview,setPreview]=useState<SendPreview|null>(null),[rationale,setRationale]=useState(''),[message,setMessage]=useState(''),[providerId,setProviderId]=useState(''),[selectedDelivery,setSelectedDelivery]=useState<Delivery|null>(null);
 const sequence=useRef(0),previewSequence=useRef(0),controller=useRef<AbortController|null>(null),heading=useRef<HTMLHeadingElement|null>(null);
 useEffect(()=>{const ticket=++sequence.current,abort=new AbortController();controller.current=abort;setPolicies([]);setDeliveries([]);setPreview(null);
  Promise.all([reportGet<{policies:Policy[]}>(`/api/reports/customers/${props.customerId}/policies`,abort.signal),reportGet<{deliveries:Delivery[]}>(`/api/reports/${props.reportId}/deliveries`,abort.signal)]).then(([policies,delivery])=>{if(ticket!==sequence.current)return;setPolicies(policies.policies.filter(policy=>policy.state==='approved'&&policy.selection.kind===props.kind&&policy.selection.audience===props.audience));setDeliveries(delivery.deliveries);}).catch(error=>{if(ticket===sequence.current)setMessage(error instanceof Error?error.message:'Delivery review unavailable');});
  return()=>{++sequence.current;abort.abort();};
 },[props.customerId,props.reportId,props.version,props.kind,props.audience]);
 useEffect(()=>{if(!preview)return;heading.current?.focus();const timer=setTimeout(()=>{setPreview(null);setMessage('Send preview expired. Review it again.');},Math.max(0,Date.parse(preview.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[preview]);
 async function openPreview(){
  const policy=policies.find(item=>item.policyId===policyId);if(!policy)return;const ticket=sequence.current,previewTicket=++previewSequence.current;setMessage('');
  try{const response=await fetch(`/api/reports/${props.reportId}/preview`,{method:'POST',signal:controller.current?.signal,headers:{'content-type':'application/json','x-csrf-token':props.csrfToken},body:JSON.stringify({action:'send',policyId,expectedVersion:props.version,expectedPolicyVersion:policy.version})}),body=await response.json();if(ticket!==sequence.current||previewTicket!==previewSequence.current)return;if(!response.ok)throw new Error(body.error?.message??'Send review unavailable');setRationale('');setPreview(body.data);}catch(error){if(ticket===sequence.current&&previewTicket===previewSequence.current)setMessage(error instanceof Error?error.message:'Send review unavailable');}
 }
 async function send(event:React.FormEvent){event.preventDefault();const policy=policies.find(item=>item.policyId===policyId);if(!preview||!policy)return;
  await props.onSave(`/api/reports/${props.reportId}/decisions`,{action:'send',policyId,expectedVersion:props.version,expectedPolicyVersion:policy.version,previewId:preview.previewId,previewDigest:preview.previewDigest,rationale});
 }
 async function deliveryCommand(event:React.FormEvent){event.preventDefault();if(!selectedDelivery)return;await props.onSave(`/api/reports/deliveries/${selectedDelivery.deliveryId}/commands`,{action:'reconcile',expectedVersion:selectedDelivery.version,rationale,...(providerId.trim()?{providerMessageId:providerId.trim()}:{})});}
 return <section className="profile-card report-delivery"><h2>Email Delivery</h2><p className="muted">Publishing does not send email. Review the exact message and recipients before approving each send.</p>
  {message&&<p role="alert">{message}</p>}
  {!deliveries.length&&props.canSend&&<><label>Approved Recipient Policy<select className="field" value={policyId} onChange={event=>{++previewSequence.current;setPolicyId(event.target.value);setPreview(null);}}><option value="">Select Approved Policy</option>{policies.map(policy=><option value={policy.policyId} key={policy.policyId}>{policy.recipients.map(recipient=>recipient.address).join(', ')}</option>)}</select></label>{!policies.length&&<p>No matching approved policy is available. Create and approve one in report management.</p>}<button className="secondary-button" disabled={props.busy||!policyId} onClick={()=>void openPreview()}>Review This Send</button></>}
  {preview&&<form className="report-review" onSubmit={send}><h3 ref={heading} tabIndex={-1}>Review Exact Email</h3><dl className="report-summary"><div><dt>Sender</dt><dd>{preview.binding.senderAddress}</dd></div><div><dt>Recipients</dt><dd>{preview.binding.recipients.map(recipient=>recipient.address).join(', ')}</dd></div><div><dt>Subject</dt><dd>{preview.binding.subject}</dd></div></dl><iframe className="report-mail-preview" title="Exact Email Preview" sandbox="" srcDoc={preview.binding.html}/><details><summary>Plain Text Version</summary><pre className="report-mail-text">{preview.binding.plainText}</pre></details><label>Send Approval Rationale<textarea className="field" required maxLength={2000} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><p className="muted">This approval authorizes only this message and these recipients. Preview expires {new Date(preview.expiresAt).toLocaleTimeString()}.</p><div className="report-actions"><button className="primary-button" disabled={props.busy||!rationale.trim()}>Approve This Send</button><button type="button" className="secondary-button" onClick={()=>{++previewSequence.current;setPreview(null);}}>Cancel Review</button></div></form>}
  {deliveries.length>0&&<div className="report-delivery-list">{deliveries.map(delivery=><article className="report-delivery-row" key={delivery.deliveryId}><div><h3>{delivery.address??'Recipient Address Expired'}</h3><p>{delivery.state.replaceAll('_',' ')} · {delivery.attemptCount} attempt{delivery.attemptCount===1?'':'s'}</p>{delivery.state==='provider_accepted'&&<p className="muted">The provider accepted the email. Delivery has not been confirmed.</p>}{delivery.state==='uncertain'&&<p className="muted">The outcome is unknown. Reconcile provider evidence before taking further action.</p>}</div><div className="report-actions">{['uncertain','provider_accepted'].includes(delivery.state)&&<button className="secondary-button" disabled={props.busy} onClick={()=>{setSelectedDelivery(delivery);setRationale('');setProviderId(delivery.providerMessageId??'');}}>Reconcile Evidence</button>}{['queued','authorized','retryable_failure','uncertain'].includes(delivery.state)&&<button className="secondary-button" disabled={props.busy} onClick={()=>void props.onSave(`/api/reports/deliveries/${delivery.deliveryId}/commands`,{action:'cancel',expectedVersion:delivery.version,rationale:'Operator cancelled further delivery attempts'})}>Cancel Further Attempts</button>}</div></article>)}</div>}
  {selectedDelivery&&<form className="report-review" onSubmit={deliveryCommand}><h3>Reconcile Delivery Evidence</h3><p>This checks the existing provider message. It does not send a new email.</p><label>Known Provider Message ID<input className="field" required value={providerId} onChange={event=>setProviderId(event.target.value)}/></label><label>Reconciliation Rationale<textarea className="field" required maxLength={2000} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><div className="report-actions"><button className="primary-button" disabled={props.busy||!rationale.trim()}>Check Provider Evidence</button><button type="button" className="secondary-button" onClick={()=>setSelectedDelivery(null)}>Cancel</button></div></form>}
 </section>;
}
