'use client';
import {useEffect,useRef,useState} from 'react';
import {reportGet} from './client';
type Selection={kind:string;audience:string;timezone:string;engagementIds:string[];workloadIds:string[];includeCustomerLevel:boolean};
type Recipient={address:string;membershipId:string|null;entitlementRationale:string|null};
type Policy={policyId:string;version:number;state:string;selection:Selection;senderId:string;recipients:Recipient[];schedules:Array<{scheduleId:string;state:string;version:number;localTime:string;timezone:string;nextRunAt:string}>};
type Management={canManage:boolean;policies:Policy[];senders:Array<{senderId:string;address:string}>;memberships:Array<{membershipId:string;label:string}>;cursor:string|null};
type Preview={previewId:string;previewDigest:string;expiresAt:string;binding:{action:string;recipients:Recipient[];version:number}};
type Options={engagements:Array<{id:string;label:string;workloadId:string|null}>;workloads:Array<{id:string;label:string}>};
export function PolicyManagement({customerId,csrfToken,options,busy,onSave}:{customerId:string;csrfToken:string;options:Options;busy:boolean;onSave:(url:string,body:Record<string,unknown>)=>Promise<unknown>}){
 const [data,setData]=useState<Management|null>(null),[message,setMessage]=useState(''),[epoch,setEpoch]=useState(0),[form,setForm]=useState(false),[editing,setEditing]=useState<Policy|null>(null),[selection,setSelection]=useState<Selection>({kind:'weekly',audience:'delivery',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,engagementIds:[],workloadIds:[],includeCustomerLevel:false}),[senderId,setSenderId]=useState(''),[recipients,setRecipients]=useState<Recipient[]>([{address:'',membershipId:null,entitlementRationale:null}]),[rationale,setRationale]=useState(''),[review,setReview]=useState<{policy:Policy;action:string;preview:Preview}|null>(null);
 const sequence=useRef(0),reviewSequence=useRef(0),abort=useRef<AbortController|null>(null),heading=useRef<HTMLHeadingElement|null>(null);
 useEffect(()=>{const ticket=++sequence.current,controller=new AbortController();abort.current=controller;setData(null);setReview(null);setForm(false);
  reportGet<Management>(`/api/reports/customers/${customerId}/policies`,controller.signal).then(current=>{if(ticket===sequence.current)setData(current);}).catch(error=>{if(ticket===sequence.current)setMessage(error instanceof Error?error.message:'Report management unavailable');});
  return()=>{++sequence.current;controller.abort();};
 },[customerId,csrfToken,epoch]);
 useEffect(()=>{if(!review)return;heading.current?.focus();const timer=setTimeout(()=>{setReview(null);setMessage('Policy review expired. Review it again.');},Math.max(0,Date.parse(review.preview.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[review]);
 if(!data?.canManage)return message?<p role="status">{message}</p>:null;
 const management=data;
 function openForm(policy:Policy|null){setEditing(policy);setSelection(policy?.selection??{kind:'weekly',audience:'delivery',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,engagementIds:[],workloadIds:[],includeCustomerLevel:false});setRecipients(policy?.recipients.length?policy.recipients:[{address:'',membershipId:null,entitlementRationale:null}]);setSenderId(policy?.senderId??management.senders[0]?.senderId??'');setForm(true);setReview(null);setMessage('');}
 async function savePolicy(event:React.FormEvent){event.preventDefault();
  const engagements=options.engagements.filter(item=>selection.engagementIds.includes(item.id));
  const workloads=[...new Set([...selection.workloadIds,...engagements.flatMap(item=>item.workloadId?[item.workloadId]:[])])];
  const policy={selection:{...selection,workloadIds:workloads},senderId,recipients:recipients.map(recipient=>selection.audience==='delivery'?{address:recipient.address,entitlementRationale:recipient.entitlementRationale}:{address:recipient.address,membershipId:recipient.membershipId})};
  const saved=await onSave(`/api/reports/customers/${customerId}/commands`,{action:editing?'revise_policy':'create_policy',expectedVersion:editing?.version??0,...(editing?{policyId:editing.policyId}:{}),policy});if(saved)setEpoch(current=>current+1);
 }
 async function preview(policy:Policy,action:string){const ticket=sequence.current,reviewTicket=++reviewSequence.current;setMessage('');setReview(null);setRationale('');
  try{const response=await fetch(`/api/reports/policies/${policy.policyId}/preview`,{method:'POST',signal:abort.current?.signal,headers:{'content-type':'application/json','x-csrf-token':csrfToken},body:JSON.stringify({action,expectedVersion:policy.version})}),body=await response.json();if(ticket!==sequence.current||reviewTicket!==reviewSequence.current)return;if(!response.ok)throw new Error(body.error?.message??'Policy review unavailable');setReview({policy,action,preview:body.data});}catch(error){if(ticket===sequence.current&&reviewTicket===reviewSequence.current)setMessage(error instanceof Error?error.message:'Policy review unavailable');}
 }
 async function decide(event:React.FormEvent){event.preventDefault();if(!review)return;const saved=await onSave(`/api/reports/policies/${review.policy.policyId}/decisions`,{action:review.action,expectedVersion:review.policy.version,previewId:review.preview.previewId,previewDigest:review.preview.previewDigest,rationale});if(saved)setEpoch(current=>current+1);}
 async function more(){if(!management.cursor)return;const ticket=sequence.current;try{const page=await reportGet<Management>(`/api/reports/customers/${customerId}/policies?cursor=${encodeURIComponent(management.cursor)}`,abort.current?.signal);if(ticket===sequence.current)setData(current=>current?{...page,policies:[...current.policies,...page.policies]}:page);}catch(error){if(ticket===sequence.current){setData(null);setMessage(error instanceof Error?error.message:'Policies unavailable');}}}
 return <section className="profile-section report-management"><div className="profile-section-head"><div><h2>Recipient Policies and Schedules</h2><p className="muted">Approved policies define recipients. Weekly schedules prepare drafts; every send still needs your approval.</p></div><button className="secondary-button" disabled={busy} onClick={()=>openForm(null)}>New Recipient Policy</button></div>
  {message&&<p role="alert">{message}</p>}
  {form&&<form className="profile-card report-policy-form" onSubmit={savePolicy}><h3>{editing?'Revise Recipient Policy':'New Recipient Policy'}</h3><div className="report-fields">
   <label>Report Type<select className="field" value={selection.kind} onChange={event=>setSelection(current=>({...current,kind:event.target.value,engagementIds:event.target.value==='weekly'?current.engagementIds.slice(0,1):current.engagementIds}))}><option value="weekly">Weekly Update</option><option value="monthly">Monthly Review</option><option value="quarterly">Quarterly Review</option></select></label>
   <label>Audience<select className="field" value={selection.audience} onChange={event=>{setSelection(current=>({...current,audience:event.target.value}));setRecipients(current=>current.map(recipient=>({...recipient,membershipId:null,entitlementRationale:null})));}}><option value="delivery">Delivery</option><option value="account_team">Account Team</option><option value="leadership">Leadership</option></select></label>
   <label>Timezone<input className="field" required value={selection.timezone} onChange={event=>setSelection(current=>({...current,timezone:event.target.value}))}/></label>
   <label>Verified Sender<select className="field" required value={senderId} onChange={event=>setSenderId(event.target.value)}><option value="">Select Verified Sender</option>{management.senders.map(sender=><option value={sender.senderId} key={sender.senderId}>{sender.address}</option>)}</select></label>
  </div>{!management.senders.length&&<p>Complete verified sender preparation before creating a policy.</p>}
  <fieldset className="report-selection"><legend>Engagement Scope</legend>{options.engagements.map(item=><label key={item.id}><input type={selection.kind==='weekly'?'radio':'checkbox'} name="policy-engagement" checked={selection.engagementIds.includes(item.id)} disabled={selection.kind!=='weekly'&&!selection.engagementIds.includes(item.id)&&selection.engagementIds.length>=20} onChange={event=>setSelection(current=>({...current,engagementIds:current.kind==='weekly'?[item.id]:event.target.checked?[...current.engagementIds,item.id]:current.engagementIds.filter(id=>id!==item.id)}))}/>{item.label}{item.workloadId?'':' · No Workload Assigned'}</label>)}</fieldset>
  {selection.kind!=='weekly'&&options.workloads.length>0&&<fieldset className="report-selection"><legend>Additional Workload Scope</legend>{options.workloads.map(item=><label key={item.id}><input type="checkbox" checked={selection.workloadIds.includes(item.id)} onChange={event=>setSelection(current=>({...current,workloadIds:event.target.checked?[...current.workloadIds,item.id]:current.workloadIds.filter(id=>id!==item.id)}))}/>{item.label}</label>)}</fieldset>}
  <label className="report-checkbox"><input type="checkbox" checked={selection.includeCustomerLevel} onChange={event=>setSelection(current=>({...current,includeCustomerLevel:event.target.checked}))}/>Include Customer-Level Inputs</label>
  <fieldset className="report-selection"><legend>Exact Recipients</legend>{recipients.map((recipient,index)=><div className="report-recipient-fields" key={index}><label>Email Address {index+1}<input className="field" type="email" required maxLength={254} value={recipient.address} onChange={event=>setRecipients(current=>current.map((row,i)=>i===index?{...row,address:event.target.value}:row))}/></label>{selection.audience==='delivery'?<label>Delivery Entitlement {index+1}<textarea className="field" required maxLength={500} value={recipient.entitlementRationale??''} onChange={event=>setRecipients(current=>current.map((row,i)=>i===index?{...row,entitlementRationale:event.target.value}:row))}/></label>:<label>Active Internal Membership {index+1}<select className="field" required value={recipient.membershipId??''} onChange={event=>setRecipients(current=>current.map((row,i)=>i===index?{...row,membershipId:event.target.value}:row))}><option value="">Select Internal Member</option>{management.memberships.map(member=><option key={member.membershipId} value={member.membershipId}>{member.label}</option>)}</select></label>}{recipients.length>1&&<button type="button" className="secondary-button" onClick={()=>setRecipients(current=>current.filter((_,i)=>i!==index))}>Remove Recipient {index+1}</button>}</div>)}<button type="button" className="secondary-button" disabled={recipients.length>=20} onClick={()=>setRecipients(current=>[...current,{address:'',membershipId:null,entitlementRationale:null}])}>Add Recipient</button></fieldset>
  <p className="muted">Saving creates a draft policy. Review the exact addresses and scope before approving it.</p><div className="report-actions"><button className="primary-button" disabled={busy||!senderId||!selection.engagementIds.length}>Save Draft Policy</button><button type="button" className="secondary-button" onClick={()=>setForm(false)}>Cancel</button></div></form>}
  <div className="profile-grid">{management.policies.map(policy=><article className="profile-card" key={policy.policyId}><div className="profile-card-head"><h3>{policy.selection.kind==='weekly'?'Weekly':policy.selection.kind==='monthly'?'Monthly':'Quarterly'} · {policy.selection.audience.replaceAll('_',' ')}</h3><span className="profile-badge">{policy.state}</span></div><p className="muted">{policy.selection.timezone} · {policy.selection.engagementIds.length} engagement{policy.selection.engagementIds.length===1?'':'s'}</p><ul className="report-recipient-list">{policy.recipients.map(recipient=><li key={recipient.address}>{recipient.address}</li>)}</ul>{!policy.recipients.length&&<p>Recipient addresses have expired.</p>}<div className="report-actions">{policy.state!=='revoked'&&<button className="secondary-button" disabled={busy} onClick={()=>openForm(policy)}>Edit Policy</button>}{policy.state==='draft'&&<button className="primary-button" disabled={busy} onClick={()=>void preview(policy,'approve')}>Review Approval</button>}{policy.state==='approved'&&<button className="secondary-button" disabled={busy} onClick={()=>void preview(policy,'pause')}>Review Pause</button>}{policy.state==='paused'&&<button className="secondary-button" disabled={busy} onClick={()=>void preview(policy,'resume')}>Review Resume</button>}{policy.state!=='revoked'&&<button className="secondary-button" disabled={busy} onClick={()=>void preview(policy,'revoke')}>Review Revocation</button>}</div>
   {policy.state==='approved'&&policy.selection.kind==='weekly'&&!policy.schedules.some(schedule=>schedule.state==='active')&&<button className="secondary-button" disabled={busy} onClick={()=>void onSave(`/api/reports/customers/${customerId}/commands`,{action:'create_schedule',expectedVersion:0,schedule:{policyId:policy.policyId,localTime:'09:00'}}).then(saved=>{if(saved)setEpoch(current=>current+1);})}>Schedule Weekly Drafts at 09:00</button>}
   {policy.schedules.map(schedule=><div className="report-schedule" key={schedule.scheduleId}><p>Weekly Draft Schedule · {schedule.localTime} {schedule.timezone} · {schedule.state}</p>{schedule.state!=='revoked'&&<button className="secondary-button" disabled={busy} onClick={()=>void onSave(`/api/reports/customers/${customerId}/commands`,{action:schedule.state==='active'?'pause_schedule':'resume_schedule',scheduleId:schedule.scheduleId,expectedVersion:Number(schedule.version)}).then(saved=>{if(saved)setEpoch(current=>current+1);})}>{schedule.state==='active'?'Pause Draft Schedule':'Resume Draft Schedule'}</button>}</div>)}
  </article>)}</div>
  {review&&<form className="profile-card report-review" onSubmit={decide}><h3 ref={heading} tabIndex={-1}>Review Policy {review.action==='approve'?'Approval':review.action==='pause'?'Pause':review.action==='resume'?'Resume':'Revocation'}</h3><p>{review.policy.selection.kind} · {review.policy.selection.audience.replaceAll('_',' ')} · {review.policy.selection.timezone}</p><ul>{review.preview.binding.recipients.map(recipient=><li key={recipient.address}>{recipient.address}{recipient.entitlementRationale?` — ${recipient.entitlementRationale}`:''}</li>)}</ul><p className="muted">This does not authorize an email send. Preview expires {new Date(review.preview.expiresAt).toLocaleTimeString()}.</p><label>Policy Decision Rationale<textarea className="field" required maxLength={2000} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><div className="report-actions"><button className="primary-button" disabled={busy||!rationale.trim()}>Confirm Policy Decision</button><button type="button" className="secondary-button" onClick={()=>{++reviewSequence.current;setReview(null);}}>Cancel Review</button></div></form>}
  {management.cursor&&<button className="secondary-button" onClick={()=>void more()}>Load More Policies</button>}
 </section>;
}
