'use client';
import Link from 'next/link';
import {LearningFeedbackButton} from '../learning/feedback-button';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ReportDocument} from '../../../lib/reports/document';
import {WeeklyReportContent} from './weekly-review';
import {reportGet,useReportCommand} from './client';
import {DeliveryReview} from './delivery-review';
import {ReportHistory} from './history';
type Detail={reportId:string;customerId:string;revisionId:string;version:number;revisionNumber:number;kind:string;audience:string;state:string;visibility:string;asOf:string;partial:boolean;period:{fromDate:string;toDate:string};timezone:string;canReview:boolean;publicationId:string|null;document:ReportDocument|null;artifacts:Array<{id:string;format:string;sizeBytes:number}>};
type Session={csrfToken:string;membership:{kind:'internal'|'partner'}};
type Preview={previewId:string;previewDigest:string;expectedVersion:number;expiresAt:string;binding:{revisionId:string;contentDigest?:string;sourceSetDigest?:string;mailDigest?:string}};
export function ReportDetail({customerId,reportId,revisionId}:{customerId:string;reportId:string;revisionId?:string}){
 const [detail,setDetail]=useState<Detail|null>(null),[session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[preview,setPreview]=useState<Preview|null>(null),[action,setAction]=useState<'publish'|'reject'|'withdraw'>('publish'),[rationale,setRationale]=useState(''),[annotation,setAnnotation]=useState('');
 const sequence=useRef(0),abort=useRef<AbortController|null>(null),reviewHeading=useRef<HTMLHeadingElement|null>(null),trigger=useRef<HTMLElement|null>(null);
 const previewSequence=useRef(0),previewAbort=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{
  const ticket=++sequence.current;++previewSequence.current;previewAbort.current?.abort();abort.current?.abort();const controller=new AbortController();abort.current=controller;setLoading(true);setDetail(null);setPreview(null);
   try{const [currentSession,current]=await Promise.all([reportGet<Session>('/api/auth/session',controller.signal),reportGet<Detail>(`/api/reports/${reportId}${revisionId?`?revisionId=${encodeURIComponent(revisionId)}`:''}`,controller.signal)]);
    if(ticket!==sequence.current)return;if(current.customerId!==customerId)throw new Error('Report unavailable');setSession(currentSession);setDetail({...current,canReview:current.canReview&&!revisionId});setMessage('');
  }catch(error){if(ticket!==sequence.current)return;setDetail(null);setSession(null);setMessage(error instanceof Error?error.message:'Report unavailable');}finally{if(ticket===sequence.current)setLoading(false);}
  },[customerId,reportId,revisionId]);
 const commands=useReportCommand(session?.csrfToken??'',refresh);
 useEffect(()=>{void refresh();return()=>{++sequence.current;++previewSequence.current;abort.current?.abort();previewAbort.current?.abort();};},[refresh]);
 useEffect(()=>{const focus=()=>void refresh(),visibility=()=>{if(document.visibilityState==='hidden'){++sequence.current;++previewSequence.current;previewAbort.current?.abort();abort.current?.abort();setDetail(null);setSession(null);setPreview(null);}else void refresh();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visibility);};},[refresh]);
 useEffect(()=>{if(!preview)return;reviewHeading.current?.focus();const timer=setTimeout(()=>{setPreview(null);setMessage('Review preview expired. Refresh it before deciding.');},Math.max(0,new Date(preview.expiresAt).getTime()-Date.now()));return()=>clearTimeout(timer);},[preview]);
 async function openPreview(next:'publish'|'reject'|'withdraw'){
  if(!detail||!session)return;trigger.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setAction(next);setRationale('');setMessage('');
  const ticket=++previewSequence.current,scopeTicket=sequence.current;previewAbort.current?.abort();const controller=new AbortController();previewAbort.current=controller;
  try{const response=await fetch(`/api/reports/${reportId}/preview`,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify({action:next,expectedVersion:detail.version})}),body=await response.json();if(ticket!==previewSequence.current||scopeTicket!==sequence.current||document.visibilityState==='hidden')return;if(!response.ok)throw new Error(body.error?.message??'Review unavailable');setPreview(body.data);}
  catch(error){if(ticket!==previewSequence.current||scopeTicket!==sequence.current)return;setPreview(null);setMessage(error instanceof Error?error.message:'Review unavailable');}
 }
 function closePreview(){++previewSequence.current;previewAbort.current?.abort();setPreview(null);trigger.current?.focus();}
 useEffect(()=>{if(detail?.state!=='rendering')return;const timer=setTimeout(()=>void refresh(),2000);return()=>clearTimeout(timer);},[detail?.state,refresh]);
 async function decide(event:React.FormEvent){event.preventDefault();if(!preview)return;const result=await commands.save(`/api/reports/${reportId}/decisions`,{action,expectedVersion:preview.expectedVersion,previewId:preview.previewId,previewDigest:preview.previewDigest,rationale});if(result)closePreview();}
 async function revise(event:React.FormEvent){event.preventDefault();if(!detail)return;const result=await commands.save(`/api/reports/${reportId}/commands`,{action:detail.publicationId?'correct':'revise',expectedVersion:detail.version,rationale:'Prepare a fresh source-bound report revision',annotations:annotation.trim()?[annotation.trim()]:[],...(detail.publicationId?{predecessorRevisionId:detail.revisionId}:{})});if(result)setAnnotation('');}
 return <main className="profile-page report-page"><nav className="profile-breadcrumb" aria-label="Breadcrumb"><Link href="/customers">Customers</Link><span aria-hidden="true">/</span><Link href={`/customers/${customerId}/reports`}>Reports</Link><span aria-hidden="true">/</span><span>Report Detail</span></nav>
  <header className="profile-header"><div><p className="profile-eyebrow">Customer Delivery</p><h1>{detail?.document?.title??'Report Detail'}</h1><p className="muted">An exact snapshot of reviewed delivery evidence.</p></div>{detail && <span className="profile-badge">{detail.visibility==='review_required'?'Fresh Review Required':detail.state.replaceAll('_',' ')}</span>}</header>
  {message && <p role="alert">{message}</p>}{commands.message && <p role="status">{commands.message}</p>}{loading && <p role="status">Checking current report access…</p>}
  {commands.uncertain && <div className="report-actions"><button className="secondary-button" disabled={commands.busy} onClick={()=>void commands.recover()}>Check Original Request</button><button className="secondary-button" disabled={commands.busy} onClick={()=>void commands.retryExact()}>Retry Exact Request</button></div>}
  {!detail && !loading && <button className="secondary-button" onClick={()=>void refresh()}>Refresh Access</button>}
  {detail && <><dl className="report-summary"><div><dt>Period</dt><dd>{detail.period.fromDate} — {detail.period.toDate}</dd></div><div><dt>Audience</dt><dd>{detail.audience.replaceAll('_',' ')}</dd></div><div><dt>Snapshot</dt><dd>Revision {detail.revisionNumber}{detail.partial?' · Partial Period':''}</dd></div><div><dt>Captured</dt><dd>{new Date(detail.asOf).toLocaleString()} · {detail.timezone}</dd></div></dl>
   {detail.visibility==='review_required' && <div className="profile-state"><h2>New Delivery Inputs</h2><p>This dated snapshot has new eligible inputs. Create and review a fresh revision before sending.</p></div>}
   {!detail.document && <div className="profile-state"><h2>Content Withheld</h2><p>Current evidence or brand approval no longer permits release of this content.</p></div>}
   {detail.document && <>{detail.visibility==='current'&&<LearningFeedbackButton kind="report" id={reportId} revisionId={detail.revisionId}/>}<div className="report-actions">
     {!revisionId&&session?.membership.kind==='internal' && detail.state==='draft' && <button className="primary-button" disabled={commands.busy||commands.uncertain} onClick={()=>void commands.save(`/api/reports/${reportId}/commands`,{action:'render',expectedVersion:detail.version,rationale:'Validate the exact report for review'})}>Prepare Review</button>}
    {detail.canReview && detail.state==='review_ready' && <button className="primary-button" disabled={commands.busy||commands.uncertain} onClick={()=>void openPreview('publish')}>Review Publication</button>}
    {detail.canReview && !detail.publicationId && <button className="secondary-button" disabled={commands.busy||commands.uncertain} onClick={()=>void openPreview('reject')}>Reject Revision</button>}
    {detail.canReview && detail.publicationId && <button className="secondary-button" disabled={commands.busy||commands.uncertain} onClick={()=>void openPreview('withdraw')}>Withdraw Publication</button>}
   </div>{detail.kind!=='weekly' && <section className="profile-card"><h2>Executive Artifacts</h2><p className="muted">The slide deck contains editable text, tables and charts. Install the approved Geist font before editing.</p>{detail.artifacts.length? <div className="report-actions">{detail.artifacts.map(artifact=><a key={artifact.id} className="secondary-button" href={`/api/reports/artifacts/${artifact.id}`}>Download {artifact.format.toUpperCase()}</a>)}</div>:<p role="status">{detail.state==='rendering'?'Rendering and validating the exact PDF and slide deck…':'Prepare review to render and validate the PDF and slide deck.'}</p>}</section>}<WeeklyReportContent document={detail.document}/></>}
   {preview && <form className="profile-card report-review" onSubmit={decide}><h2 ref={reviewHeading} tabIndex={-1}>Review {action==='publish'?'Publication':action==='withdraw'?'Withdrawal':'Rejection'}</h2><p>Decision applies to revision {detail.revisionNumber} and the exact preview shown. This does not authorize email delivery.</p><p className="muted">Preview expires {new Date(preview.expiresAt).toLocaleTimeString()}.</p><label>Decision Rationale<textarea className="field" value={rationale} minLength={1} maxLength={2000} required onChange={event=>setRationale(event.target.value)}/></label><div className="report-actions"><button className="primary-button" disabled={commands.busy||commands.uncertain||!rationale.trim()}>Confirm {action==='publish'?'Publication':action==='withdraw'?'Withdrawal':'Rejection'}</button><button type="button" className="secondary-button" onClick={closePreview}>Cancel Review</button></div></form>}
    {!revisionId&&session?.membership.kind==='internal' && <form className="profile-card report-revision" onSubmit={revise}><h2>{detail.publicationId?'Prepare Correction':'New Revision'}</h2><p className="muted">Refresh accepted sources. An annotation cannot approve a new fact.</p><label>Reviewer Annotation (Optional)<textarea className="field" maxLength={2000} value={annotation} onChange={event=>setAnnotation(event.target.value)}/></label><button className="secondary-button" disabled={commands.busy||commands.uncertain}>Prepare New Revision</button></form>}
    {detail.canReview&&session&&<DeliveryReview customerId={customerId} reportId={reportId} version={detail.version} kind={detail.kind} audience={detail.audience} csrfToken={session.csrfToken} canSend={detail.state==='published'&&detail.visibility==='current'&&Boolean(detail.document)} busy={commands.busy||commands.uncertain} onSave={commands.save}/>}
    <ReportHistory reportId={reportId} version={detail.version}/>
  </>}
 </main>;
}
