import {projectPartnerAssignment,projectPartnerAttempt,partnerAssignmentPreview} from "./projection";
export {projectPartnerAssignment} from "./projection";
import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import {partnerAssignmentReviewSchema,partnerAssignmentCommandSchema,partnerContractVersion,partnerId,partnerPageQuery,type PartnerAssignmentInput,type PartnerAvailability,type PartnerAttemptContent} from "../../contracts/partners";
import {HttpFailure,hiddenRecord} from "../../contracts/http";
import {getServerConfig} from "../config";
import {partnerRead,partnerCommand} from "./commands";
import {lockPartnerActor,requirePartnerReviewer,requirePartnerSchema,isPartnerReviewer,type PartnerActor,type TargetAuthority} from "./policy";
import {partnerHash,partnerTransaction,expectPartnerVersion} from "./repository";
import {loadPartnerGuide,loadPartnerGuideRevision,guideAvailability,revisionScope,type GuideRow,type GuideRevision} from "./guides";
import {partnerSourceFence,lockPartnerSourceUnion} from "./sources";
import {calculatePartnerProgress} from "./progress";
import {partnerAuthorityDigest,readPartnerCursor,issuePartnerCursor} from "./cursors";
export type AssignmentRow={id:string;environment_id:string;workspace_id:string;customer_id:string;guide_id:string;guide_revision_id:string;accepted_plan_revision_id:string;baseline_id:string;membership_id:string;membership_revision:string;organization_id:string;organization_revision:string;grant_revision:string;state:"active"|"withdrawn"|"superseded";version:string;predecessor_id:string|null;successor_id:string|null;obsolete_at:Date|null};
export async function loadPartnerAssignment(db:PoolClient,actor:PartnerActor,id:string,lock=false):Promise<AssignmentRow>{const row=(await db.query<AssignmentRow>(`SELECT * FROM partner_learning_assignments WHERE id=$1 AND environment_id=$2 AND workspace_id=$3 ${lock?"FOR UPDATE":""}`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0];if(!row||actor.kind==="partner"&&row.membership_id!==actor.membershipId)throw hiddenRecord();return row;}
export async function partnerAssignmentScope(actor:PartnerActor,id:string){if(!partnerId.safeParse(id).success)throw hiddenRecord();return partnerTransaction(async db=>{const a=await loadPartnerAssignment(db,actor,id);await lockPartnerActor(db,actor,a.customer_id,a.membership_id,false,true);await requirePartnerSchema(db,true);return a;});}
export async function assignmentAvailability(db:PoolClient,actor:PartnerActor,a:AssignmentRow,guide:GuideRow,revision:GuideRevision):Promise<PartnerAvailability>{
 if(a.state!=="active")return a.state==="withdrawn"?"withdrawn":"obsolete";
 const authority=(await db.query(`SELECT m.revision,m.active,m.kind,m.partner_org_id,p.active AS principal_active,o.active AS org_active,o.authority_revision,g.state,g.revision AS grant_revision FROM memberships m JOIN principals p ON p.id=m.principal_id JOIN partner_organizations o ON o.id=m.partner_org_id LEFT JOIN customer_grants g ON g.membership_id=m.id AND g.customer_id=$2 WHERE m.id=$1 AND m.workspace_id=$3`,[a.membership_id,a.customer_id,actor.workspaceId])).rows[0];
 if(!authority||!authority.active||!authority.principal_active||!authority.org_active||authority.kind!=="partner"||authority.state!=="active"||Number(authority.revision)!==Number(a.membership_revision)||authority.partner_org_id!==a.organization_id||Number(authority.authority_revision)!==Number(a.organization_revision)||Number(authority.grant_revision)!==Number(a.grant_revision))return "authority_changed";
 if(guide.published_revision_id!==a.guide_revision_id||guide.disposition!=="active")return "obsolete";
 if(a.obsolete_at)return "obsolete";
 return guideAvailability(db,actor,guide,revision);
}
export async function lockPartnerAssignmentSources(db:PoolClient,actor:PartnerActor,a:AssignmentRow){const guide=await loadPartnerGuide(db,actor,a.guide_id),revision=await loadPartnerGuideRevision(db,guide,a.guide_revision_id),scope=revisionScope(guide,revision),heads=(await db.query(`SELECT p.content FROM (SELECT DISTINCT ON(checkpoint_id) head_revision_id FROM partner_checkpoint_attempts WHERE assignment_id=$1 ORDER BY checkpoint_id,attempt_number DESC) t JOIN partner_checkpoint_payloads p ON p.revision_id=t.head_revision_id`,[a.id])).rows;await lockPartnerSourceUnion(db,actor,[{scope,refs:revision.content?.sources??[]},...heads.map(r=>({scope,refs:(r.content as PartnerAttemptContent).sources}))],true);}
export async function assignmentContext(db:PoolClient,actor:PartnerActor,a:AssignmentRow){const guide=await loadPartnerGuide(db,actor,a.guide_id),revision=await loadPartnerGuideRevision(db,guide,a.guide_revision_id),availability=await assignmentAvailability(db,actor,a,guide,revision);return {guide,revision,availability};}
function proposal(input:PartnerAssignmentInput){const {requestId,...rest}=input;void requestId;return rest;}
async function binding(db:PoolClient,actor:PartnerActor,input:PartnerAssignmentInput,target:TargetAuthority){
 const old=input.action==="assignment.create"?null:await loadPartnerAssignment(db,actor,input.assignmentId),guide=await loadPartnerGuide(db,actor,input.action==="assignment.withdraw"?old!.guide_id:input.guideId),revision=await loadPartnerGuideRevision(db,guide,input.action==="assignment.withdraw"?old!.guide_revision_id:input.revisionId);
 if(old){expectPartnerVersion(old.version,input.expectedVersion);if(old.state!=="active"||old.membership_id!==target.membershipId||old.guide_id!==guide.id)throw new HttpFailure(409,"assignment_changed","Reload the current assignment");}
 if(input.action!=="assignment.withdraw"&&(guide.disposition!=="active"||guide.published_revision_id!==revision.id||await guideAvailability(db,actor,guide,revision)!=="eligible"))throw new HttpFailure(409,"guide_unavailable","Select the current eligible published guide");
 await loadPartnerGuide(db,actor,guide.id,"share");if(old)await loadPartnerAssignment(db,actor,old.id,true);
 return {old,guide,revision,value:{proposal:proposal(input),target,actorAuthority:await partnerAuthorityDigest(db,actor,guide.customer_id),sessionId:actor.sessionId,guideVersion:Number(guide.version),revisionGeneration:Number(revision.generation),sourceDigest:revision.source_digest}};
}
async function assignmentCommandScope(actor:PartnerActor,input:PartnerAssignmentInput){requirePartnerReviewer(actor);if(input.action==="assignment.create"){return partnerTransaction(async db=>{await lockPartnerActor(db,actor);const guide=await loadPartnerGuide(db,actor,input.guideId);return {customerId:guide.customer_id,targetMembershipId:input.membershipId};});}const old=await partnerAssignmentScope(actor,input.assignmentId);return {customerId:old.customer_id,targetMembershipId:old.membership_id};}
export async function previewPartnerAssignment(actor:PartnerActor,raw:unknown){const input=partnerAssignmentReviewSchema.parse(raw),scope=await assignmentCommandScope(actor,input),receipt=await partnerCommand(actor,{...input,action:"preview."+input.action},scope,async db=>{await requirePartnerSchema(db,true);const target=await lockPartnerActor(db,actor,scope.customerId,scope.targetMembershipId,true),bound=await binding(db,actor,input,target!),id=randomUUID();await db.query(`INSERT INTO partner_review_previews(id,environment_id,workspace_id,actor_membership_id,session_id,customer_id,action,input_digest,binding_digest,binding) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId,actor.sessionId,scope.customerId,input.action,partnerHash(proposal(input)),partnerHash(bound.value),JSON.stringify(bound.value)]);return {targetId:id,version:1};});return partnerRead(actor,scope.customerId,async db=>{const target=await lockPartnerActor(db,actor,scope.customerId,scope.targetMembershipId),bound=await binding(db,actor,input,target!),p=(await db.query("SELECT binding_digest,expires_at FROM partner_review_previews WHERE id=$1 AND actor_membership_id=$2 AND session_id=$3",[receipt.targetId,actor.membershipId,actor.sessionId])).rows[0];if(!p||p.expires_at.getTime()<=Date.now())throw new HttpFailure(410,"preview_expired","Prepare a new assignment preview");if(p.binding_digest!==partnerHash(bound.value))throw new HttpFailure(409,"preview_changed","Prepare a new assignment preview");return partnerAssignmentPreview({requestId:receipt.requestId,previewId:receipt.targetId!,expiresAt:p.expires_at.toISOString(),action:input.action,guideId:bound.guide.id,revisionId:bound.revision.id,membershipId:target!.membershipId,version:input.expectedVersion});},scope.targetMembershipId);}
export async function decidePartnerAssignment(actor:PartnerActor,raw:unknown){const input=partnerAssignmentCommandSchema.parse(raw),scope=await assignmentCommandScope(actor,input);return partnerCommand(actor,input,scope,async db=>{await requirePartnerSchema(db,true);const {previewId,...review}=input,target=await lockPartnerActor(db,actor,scope.customerId,scope.targetMembershipId,true),bound=await binding(db,actor,review,target!),p=(await db.query("SELECT * FROM partner_review_previews WHERE id=$1 AND environment_id=$2 AND actor_membership_id=$3 AND session_id=$4",[previewId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.membershipId,actor.sessionId])).rows[0];if(!p||p.action!==input.action||p.input_digest!==partnerHash(proposal(review))||p.binding_digest!==partnerHash(bound.value))throw new HttpFailure(409,"preview_changed","Prepare a new assignment preview");if(p.expires_at.getTime()<=Date.now())throw new HttpFailure(410,"preview_expired","Prepare a new assignment preview");
 let id=bound.old?.id??randomUUID(),version=bound.old?Number(bound.old.version)+1:1;
 if(bound.old)await db.query("UPDATE partner_learning_assignments SET state=$1,version=version+1,obsolete_at=COALESCE(obsolete_at,clock_timestamp()),purge_at=LEAST(purge_at,clock_timestamp()+interval '90 days') WHERE id=$2",[input.action==="assignment.withdraw"?"withdrawn":"superseded",bound.old.id]);
 if(input.action!=="assignment.withdraw"){
  const count=Number((await db.query("SELECT count(*) FROM partner_learning_assignments WHERE membership_id=$1 AND customer_id=$2 AND state='active'",[target!.membershipId,scope.customerId])).rows[0].count);if(count>=100)throw new HttpFailure(409,"assignment_limit","Withdraw an assignment before creating another");
  if((await db.query("SELECT 1 FROM partner_learning_assignments WHERE membership_id=$1 AND guide_id=$2 AND state='active'",[target!.membershipId,bound.guide.id])).rowCount)throw new HttpFailure(409,"assignment_exists","Replace the current assignment");
  id=randomUUID();version=1;await db.query(`INSERT INTO partner_learning_assignments(id,environment_id,workspace_id,customer_id,guide_id,guide_revision_id,accepted_plan_revision_id,baseline_id,membership_id,membership_revision,organization_id,organization_revision,grant_revision,creator_membership_id,predecessor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,scope.customerId,bound.guide.id,bound.revision.id,bound.revision.accepted_plan_revision_id,bound.revision.baseline_id,target!.membershipId,target!.membershipRevision,target!.organizationId,target!.organizationRevision,target!.grantRevision,actor.membershipId,bound.old?.id??null]);await db.query("INSERT INTO partner_assignment_payloads(assignment_id,content) VALUES($1,$2)",[id,JSON.stringify({rationale:input.rationale})]);if(bound.old)await db.query("UPDATE partner_learning_assignments SET successor_id=$1 WHERE id=$2",[id,bound.old.id]);
 }
 const decisionId=randomUUID();await db.query(`INSERT INTO partner_review_decisions(id,environment_id,workspace_id,guide_id,guide_revision_id,assignment_id,action,reviewer_membership_id,content_digest,binding_digest,self_review) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[decisionId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,bound.guide.id,bound.revision.id,id,input.action==="assignment.create"?"assign":input.action.slice(11),actor.membershipId,bound.revision.content_digest,p.binding_digest,input.selfReview]);await db.query("INSERT INTO partner_decision_payloads(decision_id,content) VALUES($1,$2)",[decisionId,JSON.stringify({rationale:input.rationale})]);return {targetId:id,version};});}
export async function readPartnerAssignment(actor:PartnerActor,id:string){const scoped=await partnerAssignmentScope(actor,id);return partnerRead(actor,scoped.customer_id,async db=>{await lockPartnerActor(db,actor,scoped.customer_id,scoped.membership_id,false,true);return projectPartnerAssignment(db,actor,await loadPartnerAssignment(db,actor,id));},scoped.membership_id);}
export async function listPartnerMembers(actor:PartnerActor,customerId:string,raw:unknown){requirePartnerReviewer(actor);partnerId.parse(customerId);const input=partnerPageQuery.parse(raw);return partnerRead(actor,customerId,async db=>{await requirePartnerSchema(db,true);const scope=partnerHash({kind:"members",customerId,limit:input.limit,search:input.search}),authority=await partnerAuthorityDigest(db,actor,customerId),after=await readPartnerCursor(db,actor,input.cursor,scope,authority);const rows=(await db.query(`SELECT m.id,p.display_name,o.name AS organization_label FROM memberships m JOIN principals p ON p.id=m.principal_id JOIN partner_organizations o ON o.id=m.partner_org_id JOIN customer_grants g ON g.membership_id=m.id WHERE m.workspace_id=$1 AND m.kind='partner' AND m.active AND p.active AND o.active AND g.customer_id=$2 AND g.state='active' AND ($3='' OR strpos(lower(p.display_name),lower($3))>0) AND ($4::uuid IS NULL OR m.id>$4) ORDER BY m.id LIMIT $5`,[actor.workspaceId,customerId,input.search,after?.id??null,input.limit+1])).rows,items=rows.slice(0,input.limit).map(row=>({membershipId:row.id,displayName:row.display_name,organizationLabel:row.organization_label})),hasMore=rows.length>input.limit;return {contractVersion:partnerContractVersion,items,hasMore,nextCursor:hasMore?await issuePartnerCursor(db,actor,scope,authority,{id:items.at(-1)!.membershipId}):null};});}
export async function listPartnerAssignments(actor:PartnerActor,raw:unknown){const input=partnerPageQuery.extend({customerId:partnerId,guideId:partnerId.optional(),engagementId:partnerId.optional(),memberId:partnerId.optional()}).parse(raw);if(actor.kind==="partner"&&input.memberId&&input.memberId!==actor.membershipId)throw hiddenRecord();return partnerRead(actor,input.customerId,async db=>{await requirePartnerSchema(db,true);const scope=partnerHash({kind:"assignments",customerId:input.customerId,guideId:input.guideId,engagementId:input.engagementId,memberId:input.memberId,limit:input.limit,search:input.search}),authority=await partnerAuthorityDigest(db,actor,input.customerId),after=await readPartnerCursor(db,actor,input.cursor,scope,authority);const rows=(await db.query<AssignmentRow>(`SELECT * FROM partner_learning_assignments WHERE environment_id=$1 AND workspace_id=$2 AND customer_id=$3 AND ($4::uuid IS NULL OR guide_id=$4) AND ($5::boolean OR membership_id=$6) AND ($7::uuid IS NULL OR id>$7) AND ($9::uuid IS NULL OR membership_id=$9) AND ($10::uuid IS NULL OR guide_id IN(SELECT id FROM partner_guides WHERE engagement_id=$10 AND customer_id=$3 AND workspace_id=$2)) ORDER BY id LIMIT $8`,[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,input.customerId,input.guideId??null,actor.kind==="internal",actor.membershipId,after?.id??null,input.limit+1,input.memberId??null,input.engagementId??null])).rows,items=[];for(const a of rows.slice(0,input.limit)){const c=await assignmentContext(db,actor,a),title=c.availability==="eligible"?c.revision.content?.title??"Guide unavailable":"Guide unavailable";if(input.search&&!title.toLocaleLowerCase().includes(input.search.toLocaleLowerCase()))continue;items.push({assignmentId:a.id,guideId:a.guide_id,membershipId:a.membership_id,version:Number(a.version),title,state:a.state,availability:c.availability,href:`/partners/assignments/${a.id}`});}const hasMore=rows.length>input.limit;return {contractVersion:partnerContractVersion,items,hasMore,nextCursor:hasMore?await issuePartnerCursor(db,actor,scope,authority,{id:rows[input.limit-1].id}):null};});}

export async function readPartnerAttemptHistory(actor:PartnerActor,id:string,raw:unknown){const input=partnerPageQuery.extend({checkpointId:partnerId}).parse(raw),scoped=await partnerAssignmentScope(actor,id);return partnerRead(actor,scoped.customer_id,async db=>{const a=await loadPartnerAssignment(db,actor,id),guide=await loadPartnerGuide(db,actor,a.guide_id),revision=await loadPartnerGuideRevision(db,guide,a.guide_revision_id),sourceScope=revisionScope(guide,revision);if(!revision.content?.checkpoints.some(cp=>cp.id===input.checkpointId))throw hiddenRecord();const scope=partnerHash({kind:"attempt-history",assignmentId:id,version:a.version,checkpointId:input.checkpointId,limit:input.limit,search:input.search}),authority=await partnerAuthorityDigest(db,actor,a.customer_id),after=await readPartnerCursor(db,actor,input.cursor,scope,authority),rows=(await db.query(`SELECT t.id AS attempt_id,t.attempt_number,t.state,t.head_revision_id,r.id AS revision_id,r.revision_number,r.content_digest,r.created_at,r.author_membership_id,s.invalidated_at,p.content FROM partner_checkpoint_attempts t JOIN partner_checkpoint_revisions r ON r.attempt_id=t.id JOIN partner_checkpoint_revision_states s ON s.revision_id=r.id LEFT JOIN partner_checkpoint_payloads p ON p.revision_id=r.id WHERE t.assignment_id=$1 AND t.checkpoint_id=$2 AND ($3::bigint IS NULL OR (t.attempt_number,r.revision_number)<($3,$4)) ORDER BY t.attempt_number DESC,r.revision_number DESC LIMIT $5`,[id,input.checkpointId,after?.attemptNumber??null,after?.revisionNumber??null,input.limit+1])).rows,scanned=rows.slice(0,input.limit);await lockPartnerSourceUnion(db,actor,[{scope:sourceScope,refs:revision.content.sources},...scanned.filter(r=>r.content).map(r=>({scope:sourceScope,refs:(r.content as PartnerAttemptContent).sources}))],true);const availability=await assignmentAvailability(db,actor,a,guide,revision),items=[];for(const row of scanned){const item=await projectPartnerAttempt(db,actor,sourceScope,row,availability);if(input.search&&(!item.content||!`${item.content.attempted} ${item.content.result}`.toLocaleLowerCase().includes(input.search.toLocaleLowerCase())))continue;items.push(item);}const hasMore=rows.length>input.limit,last=scanned.at(-1);return {contractVersion:partnerContractVersion,assignmentId:id,checkpointId:input.checkpointId,availability,items,hasMore,nextCursor:hasMore?await issuePartnerCursor(db,actor,scope,authority,{attemptNumber:String(last!.attempt_number),revisionNumber:String(last!.revision_number)}):null};},scoped.membership_id);}
