import {getServerConfig} from "../config";
import {partnerTransaction} from "./repository";
import {originalCurrent,confirmedConflictAfter} from "../retrieval/fences";
import {lockOriginalHeader} from "../plans/sources";
import {HttpFailure} from "../../contracts/http";
import {recordPartnerTelemetry,recordPartnerQueueHealth} from "./telemetry";
/** No user impersonation and no feature-enable prerequisite. Original hooks
 * establish withdrawal deadlines; this bounded scan catches recorded expiry. */
export async function runPartnerMaintenanceTick(limit=100){
 if(!Number.isInteger(limit)||limit<1||limit>100)throw Error("Invalid partner maintenance limit");const started=performance.now(),environment=getServerConfig().TURAS_ENVIRONMENT_ID;
 const dueIds:string[]=[];try{const checkedResult=await partnerTransaction(async db=>{
  const marker=(await db.query("SELECT schema_version FROM turas_environment WHERE environment_id=$1",[environment])).rows[0];if(Number(marker?.schema_version)<50||!marker)return {skipped:true,checked:0,schemaVersion:0};
  const guideQuery=`SELECT s.revision_id,s.invalidated_at,s.purge_at,p.content,g.customer_id,g.workspace_id,r.baseline_id,g.engagement_id,'guide' AS kind,s.eligibility_recheck_at FROM partner_guide_revision_states s JOIN partner_guide_revisions r ON r.id=s.revision_id JOIN partner_guides g ON g.id=r.guide_id JOIN partner_guide_payloads p ON p.revision_id=s.revision_id WHERE g.environment_id=$1 AND s.eligibility_recheck_at<=clock_timestamp()`,checkpointQuery=`SELECT s.revision_id,s.invalidated_at,LEAST(s.purge_at,a.purge_at) AS purge_at,p.content,a.customer_id,a.workspace_id,a.baseline_id,g.engagement_id,'checkpoint' AS kind,s.eligibility_recheck_at FROM partner_checkpoint_revision_states s JOIN partner_checkpoint_revisions r ON r.id=s.revision_id JOIN partner_checkpoint_attempts t ON t.id=r.attempt_id JOIN partner_learning_assignments a ON a.id=t.assignment_id JOIN partner_guides g ON g.id=a.guide_id JOIN partner_checkpoint_payloads p ON p.revision_id=s.revision_id WHERE a.environment_id=$1 AND s.eligibility_recheck_at<=clock_timestamp()`;
  const candidates=(await db.query(`SELECT * FROM (${guideQuery}${Number(marker.schema_version)>=51?` UNION ALL ${checkpointQuery}`:""}) candidates ORDER BY eligibility_recheck_at,revision_id LIMIT $2`,[environment,limit])).rows;
  // Lock the original union before changing any 013 head/state rows.
  const dependencies=(await db.query(`SELECT DISTINCT source_kind,source_revision_id FROM partner_source_dependencies WHERE guide_revision_id=ANY($1::uuid[]) OR checkpoint_revision_id=ANY($1::uuid[]) ORDER BY source_kind,source_revision_id`,[candidates.map(c=>c.revision_id)])).rows;
  for(const d of dependencies){if(performance.now()-started>8000)throw Error("Partner maintenance deadline");if(d.source_kind==="accepted_execution")continue;try{await lockOriginalHeader(db,d.source_kind,d.source_revision_id);}catch(error){if(!(error instanceof HttpFailure)||error.status!==409)throw error;}}
  let checked=0;for(const row of candidates){if(performance.now()-started>8000)break;const table=row.kind==="guide"?"partner_guide_revision_states":"partner_checkpoint_revision_states",deps=(await db.query("SELECT source_kind,source_revision_id,source_generation,source_digest FROM partner_source_dependencies WHERE guide_revision_id=$1 OR checkpoint_revision_id=$1 ORDER BY source_kind,source_revision_id",[row.revision_id])).rows;let invalidAt:Date|null=row.invalidated_at;
   for(const ref of row.content.sources??[]){const expiry=new Date(ref.quality.validUntil);if(expiry.getTime()<=Date.now()&&(!invalidAt||expiry<invalidAt))invalidAt=expiry;}
   for(const d of deps){if(d.source_kind==="accepted_execution"){
     const valid=(await db.query("SELECT 1 FROM execution_record_revisions v JOIN execution_records r ON r.id=v.record_id JOIN execution_record_payloads p ON p.revision_id=v.id WHERE v.id=$1 AND r.accepted_revision_id=v.id AND v.audience='delivery' AND v.revision_number=$2 AND v.content_digest=$3 AND v.workspace_id=$4 AND v.customer_id=$5 AND v.engagement_id=$6 FOR SHARE OF r",[d.source_revision_id,d.source_generation,d.source_digest,row.workspace_id,row.customer_id,row.engagement_id])).rowCount;if(!valid)invalidAt??=new Date();continue;
    }
    const kind=d.source_kind==="shared_knowledge"?"published_shared":d.source_kind;
    if(!await originalCurrent(db,{source_kind:kind,source_revision_id:d.source_revision_id,source_generation:d.source_generation,source_digest:d.source_digest})||await confirmedConflictAfter(db,kind,d.source_revision_id,new Date(0)))invalidAt??=new Date();
   }
   if(invalidAt){await db.query(`UPDATE ${table} SET invalidated_at=LEAST(invalidated_at,$2),purge_at=LEAST(purge_at,$2::timestamptz+interval '24 hours'),generation=generation+CASE WHEN invalidated_at IS NULL THEN 1 ELSE 0 END,eligibility_recheck_at=clock_timestamp()+interval '60 seconds' WHERE revision_id=$1`,[row.revision_id,invalidAt]);
    await db.query(`INSERT INTO partner_cleanup_jobs(id,environment_id,revision_id,kind,reason,invalidated_at,purge_at) VALUES(gen_random_uuid(),$1,$2,$3,'source_unavailable',$4,$4::timestamptz+interval '24 hours') ON CONFLICT(environment_id,kind,revision_id) DO UPDATE SET invalidated_at=LEAST(partner_cleanup_jobs.invalidated_at,EXCLUDED.invalidated_at),purge_at=LEAST(partner_cleanup_jobs.purge_at,EXCLUDED.purge_at)`,[environment,row.revision_id,row.kind,invalidAt]);
   }else await db.query(`UPDATE ${table} SET eligibility_recheck_at=clock_timestamp()+interval '60 seconds' WHERE revision_id=$1`,[row.revision_id]);checked++;
  }
  await db.query(`INSERT INTO partner_cleanup_jobs(id,environment_id,revision_id,kind,reason,invalidated_at,purge_at) SELECT gen_random_uuid(),$1,s.revision_id,'guide',CASE WHEN s.invalidated_at IS NULL THEN 'obsolete' ELSE 'source_unavailable' END,COALESCE(s.invalidated_at,s.obsolete_at,s.purge_at-interval '90 days'),s.purge_at FROM partner_guide_revision_states s JOIN partner_guide_revisions r ON r.id=s.revision_id JOIN partner_guides g ON g.id=r.guide_id WHERE g.environment_id=$1 AND s.purge_at IS NOT NULL ORDER BY s.purge_at,s.revision_id LIMIT $2 ON CONFLICT(environment_id,kind,revision_id) DO UPDATE SET invalidated_at=LEAST(partner_cleanup_jobs.invalidated_at,EXCLUDED.invalidated_at),purge_at=LEAST(partner_cleanup_jobs.purge_at,EXCLUDED.purge_at)`,[environment,limit]);
  if(Number(marker.schema_version)>=51)await db.query(`INSERT INTO partner_cleanup_jobs(id,environment_id,revision_id,kind,reason,invalidated_at,purge_at) SELECT gen_random_uuid(),$1,s.revision_id,'checkpoint',CASE WHEN s.invalidated_at IS NULL THEN 'obsolete' ELSE 'source_unavailable' END,COALESCE(s.invalidated_at,s.obsolete_at,a.obsolete_at,LEAST(s.purge_at,a.purge_at)-interval '90 days'),LEAST(s.purge_at,a.purge_at) FROM partner_checkpoint_revision_states s JOIN partner_checkpoint_revisions r ON r.id=s.revision_id JOIN partner_checkpoint_attempts t ON t.id=r.attempt_id JOIN partner_learning_assignments a ON a.id=t.assignment_id WHERE a.environment_id=$1 AND LEAST(s.purge_at,a.purge_at) IS NOT NULL ORDER BY LEAST(s.purge_at,a.purge_at),s.revision_id LIMIT $2 ON CONFLICT(environment_id,kind,revision_id) DO UPDATE SET invalidated_at=LEAST(partner_cleanup_jobs.invalidated_at,EXCLUDED.invalidated_at),purge_at=LEAST(partner_cleanup_jobs.purge_at,EXCLUDED.purge_at)`,[environment,limit]);
  return {skipped:false,checked,schemaVersion:Number(marker.schema_version)};
 });
 if(checkedResult.skipped)return {...checkedResult,purged:0,overdue:0,oldestOverdueSeconds:0};
 return await partnerTransaction(async db=>{
  const remaining=Math.floor(10000-(performance.now()-started));if(remaining<=0)throw Error("Partner maintenance deadline");await db.query("SELECT set_config('transaction_timeout',$1,true)",[`${remaining}ms`]);
  const lease=(await db.query("SELECT pg_try_advisory_xact_lock(hashtextextended($1,0)) AS claimed",[`partner-maintenance:${environment}`])).rows[0].claimed;
  if(!lease)return {...checkedResult,purged:0,overdue:0,oldestOverdueSeconds:0,busy:true};
  const due=(await db.query("SELECT id FROM partner_cleanup_jobs WHERE environment_id=$1 AND completed_at IS NULL AND purge_at<=clock_timestamp() AND next_attempt_at<=clock_timestamp() ORDER BY purge_at,id LIMIT $2 FOR UPDATE SKIP LOCKED",[environment,limit])).rows;dueIds.push(...due.map(r=>r.id));
  const purged=Number((await db.query("SELECT turas_partner_purge($1,$2) AS n",[environment,limit])).rows[0].n)+(checkedResult.schemaVersion>=51?Number((await db.query("SELECT turas_partner_purge_learning($1,$2) AS n",[environment,limit])).rows[0].n):0);
  await db.query(`UPDATE partner_cleanup_jobs SET completed_at=clock_timestamp(),attempts=attempts+1 WHERE id=ANY($1::uuid[]) AND ((kind='guide' AND NOT EXISTS(SELECT 1 FROM partner_guide_payloads p WHERE p.revision_id=partner_cleanup_jobs.revision_id)) ${checkedResult.schemaVersion>=51?"OR (kind='checkpoint' AND NOT EXISTS(SELECT 1 FROM partner_checkpoint_payloads p WHERE p.revision_id=partner_cleanup_jobs.revision_id))":""})`,[dueIds]);
  const health=(await db.query("SELECT count(*) AS overdue,COALESCE(EXTRACT(epoch FROM clock_timestamp()-min(purge_at)),0) AS age FROM partner_cleanup_jobs WHERE environment_id=$1 AND completed_at IS NULL AND purge_at<clock_timestamp()",[environment])).rows[0];recordPartnerQueueHealth(Number(health.overdue),Number(health.age));recordPartnerTelemetry({operation:"maintenance",outcome:"committed",durationMs:performance.now()-started});return {...checkedResult,purged,overdue:Number(health.overdue),oldestOverdueSeconds:Math.max(0,Number(health.age))};
 });}catch(error){if(dueIds.length)await partnerTransaction(db=>db.query("UPDATE partner_cleanup_jobs SET attempts=attempts+1,next_attempt_at=clock_timestamp()+make_interval(secs=>LEAST(300,60*power(2,LEAST(attempts,3)))::integer) WHERE id=ANY($1::uuid[]) AND completed_at IS NULL",[dueIds])).catch(()=>undefined);recordPartnerTelemetry({operation:"maintenance",outcome:"failed",durationMs:performance.now()-started});throw error;}
}
