import {partnerCheckpointPreview} from "./projection";
import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import {partnerCheckpointCommandSchema,partnerCheckpointReviewSchema,partnerCheckpointDecisionSchema,partnerContractVersion,type PartnerCheckpointReviewInput,type PartnerAttemptContent} from "../../contracts/partners";
import {HttpFailure,hiddenRecord} from "../../contracts/http";
import {getServerConfig} from "../config";
import {partnerCommand,partnerRead} from "./commands";
import {requirePartnerReviewer,requirePartnerSchema,type PartnerActor} from "./policy";
import {partnerHash,expectPartnerVersion} from "./repository";
import {partnerAssignmentScope,loadPartnerAssignment,assignmentContext,projectPartnerAssignment,lockPartnerAssignmentSources,type AssignmentRow} from "./assignments";
import {revisionScope,loadPartnerGuide,loadPartnerGuideRevision} from "./guides";
import {partnerSourceFence,partnerSourcePassages,lockPartnerSourceUnion,type PartnerDependency} from "./sources";
import {partnerAuthorityDigest} from "./cursors";
const unavailable=()=>new HttpFailure(409,"learning_unavailable","Learning work changed; refresh the current assignment");
async function context(db:PoolClient,actor:PartnerActor,a:AssignmentRow,checkpointId:string){await requirePartnerSchema(db,true);const result=await assignmentContext(db,actor,a);if(result.availability!=="eligible"||!result.revision.content)throw unavailable();const checkpoint=result.revision.content.checkpoints.find(cp=>cp.id===checkpointId);if(!checkpoint)throw hiddenRecord();return {...result,checkpoint};}
async function persistSources(db:PoolClient,id:string,refs:PartnerAttemptContent['sources'],dependencies:readonly PartnerDependency[]){for(const ref of refs.filter(r=>r.kind==="accepted_execution"))await db.query(`INSERT INTO partner_source_dependencies(id,checkpoint_revision_id,source_kind,source_revision_id,source_generation,source_digest,reference,private_lineage) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,false)`,[id,ref.kind,ref.sourceRevisionId,ref.generation,ref.contentDigest,JSON.stringify(ref)]);for(const d of dependencies){const ref=refs.find(r=>r.kind===d.kind&&r.sourceRevisionId===d.revisionId);await db.query(`INSERT INTO partner_source_dependencies(id,checkpoint_revision_id,source_kind,source_revision_id,source_generation,source_digest,reference,private_lineage) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7)`,[id,d.kind,d.revisionId,d.generation,d.contentDigest,ref?JSON.stringify(ref):null,!ref]);}}
export async function writePartnerCheckpoint(actor:PartnerActor,raw:unknown){const input=partnerCheckpointCommandSchema.parse(raw),a=await partnerAssignmentScope(actor,input.assignmentId);return partnerCommand(actor,input,{customerId:a.customer_id,targetMembershipId:a.membership_id},async db=>{
 const initial=await loadPartnerAssignment(db,actor,a.id),privateGuide=await loadPartnerGuide(db,actor,a.guide_id),privateRevision=await loadPartnerGuideRevision(db,privateGuide,a.guide_revision_id),privateScope=revisionScope(privateGuide,privateRevision);
 const otherHeads=(await db.query(`SELECT p.content FROM (SELECT DISTINCT ON(checkpoint_id) checkpoint_id,head_revision_id FROM partner_checkpoint_attempts WHERE assignment_id=$1 ORDER BY checkpoint_id,attempt_number DESC) t JOIN partner_checkpoint_payloads p ON p.revision_id=t.head_revision_id WHERE ($2::boolean OR t.checkpoint_id<>$3)`,[a.id,input.action!=="checkpoint.save",input.checkpointId])).rows;
 await lockPartnerSourceUnion(db,actor,[{scope:privateScope,refs:privateRevision.content?.sources??[]},...otherHeads.map(r=>({scope:privateScope,refs:(r.content as PartnerAttemptContent).sources})),...(input.action==="checkpoint.save"?[{scope:privateScope,refs:input.content.sources}]:[])]);
 const c=await context(db,actor,initial,input.checkpointId);
 const existing=(await db.query("SELECT * FROM partner_checkpoint_attempts WHERE assignment_id=$1 AND checkpoint_id=$2 AND state IN('draft','submitted','verified') ORDER BY attempt_number DESC LIMIT 1",[a.id,input.checkpointId])).rows[0];if(existing?.state==="verified"||existing?.state==="submitted"&&input.action==="checkpoint.save")throw unavailable();
 let content:PartnerAttemptContent|null=input.action==="checkpoint.save"?input.content:null,previous;
 if(input.action==="checkpoint.submit"){if(!existing||existing.id!==input.attemptId||existing.state!=="draft"||existing.head_revision_id!==input.revisionId)throw unavailable();previous=(await db.query("SELECT r.*,p.content FROM partner_checkpoint_revisions r JOIN partner_checkpoint_payloads p ON p.revision_id=r.id WHERE r.id=$1 AND r.attempt_id=$2",[input.revisionId,input.attemptId])).rows[0];if(!previous||previous.content_digest!==input.contentDigest)throw unavailable();content=previous.content;}
 if(!content)throw unavailable();const fence=await partnerSourceFence(db,actor,revisionScope(c.guide,c.revision),content.sources),locked=await loadPartnerAssignment(db,actor,a.id,true);expectPartnerVersion(locked.version,input.expectedVersion);
 if(input.action==="checkpoint.save"){
  const attemptId=existing?.id??randomUUID();if(!existing){const n=Number((await db.query("SELECT COALESCE(max(attempt_number),0)+1 AS n FROM partner_checkpoint_attempts WHERE assignment_id=$1 AND checkpoint_id=$2",[a.id,input.checkpointId])).rows[0].n);await db.query("INSERT INTO partner_checkpoint_attempts(id,assignment_id,checkpoint_id,attempt_number) VALUES($1,$2,$3,$4)",[attemptId,a.id,input.checkpointId,n]);}
  const revisionId=randomUUID(),number=Number((await db.query("SELECT COALESCE(max(revision_number),0)+1 AS n FROM partner_checkpoint_revisions WHERE attempt_id=$1",[attemptId])).rows[0].n);await db.query("INSERT INTO partner_checkpoint_revisions(id,attempt_id,revision_number,author_membership_id,observed_at,content_digest,source_digest) VALUES($1,$2,$3,$4,$5,$6,$7)",[revisionId,attemptId,number,actor.membershipId,content.observedAt,partnerHash(content),fence.digest]);await db.query("INSERT INTO partner_checkpoint_payloads(revision_id,content) VALUES($1,$2)",[revisionId,JSON.stringify(content)]);await db.query("INSERT INTO partner_checkpoint_revision_states(revision_id) VALUES($1)",[revisionId]);await persistSources(db,revisionId,content.sources,fence.dependencies);
  if(existing?.head_revision_id)await db.query("UPDATE partner_checkpoint_revision_states SET obsolete_at=COALESCE(obsolete_at,clock_timestamp()),purge_at=LEAST(purge_at,clock_timestamp()+interval '90 days') WHERE revision_id=$1",[existing.head_revision_id]);await db.query("UPDATE partner_checkpoint_attempts SET head_revision_id=$1 WHERE id=$2",[revisionId,attemptId]);
 }else await db.query("UPDATE partner_checkpoint_attempts SET state='submitted' WHERE id=$1",[existing.id]);
 await db.query("UPDATE partner_learning_assignments SET version=version+1 WHERE id=$1",[a.id]);return {targetId:a.id,version:Number(locked.version)+1};});}
function proposal(input:PartnerCheckpointReviewInput){const {requestId,...rest}=input;void requestId;return rest;}
async function bind(db:PoolClient,actor:PartnerActor,input:PartnerCheckpointReviewInput){const a=await loadPartnerAssignment(db,actor,input.assignmentId);await lockPartnerAssignmentSources(db,actor,a);const c=await context(db,actor,a,input.checkpointId);expectPartnerVersion(a.version,input.expectedVersion);const row=(await db.query(`SELECT t.id,t.state,t.head_revision_id,r.content_digest,r.author_membership_id,r.source_digest,s.invalidated_at,p.content FROM partner_checkpoint_attempts t JOIN partner_checkpoint_revisions r ON r.id=t.head_revision_id JOIN partner_checkpoint_revision_states s ON s.revision_id=r.id LEFT JOIN partner_checkpoint_payloads p ON p.revision_id=r.id WHERE t.id=$1 AND t.assignment_id=$2 AND t.checkpoint_id=$3`,[input.attemptId,a.id,input.checkpointId])).rows[0];if(!row||row.state!=="submitted"||row.head_revision_id!==input.revisionId||row.content_digest!==input.contentDigest)throw unavailable();if(row.author_membership_id===actor.membershipId&&!input.selfReview)throw new HttpFailure(422,"self_review_required","Acknowledge review of your own authored content");
 let content:PartnerAttemptContent|null=row.invalidated_at?null:row.content,sourceDigest=row.source_digest;
 if(input.action==="checkpoint.verify"){
  if(!content||!content.sources.some(s=>["accepted_profile","approved_excerpt","accepted_execution"].includes(s.kind)))throw new HttpFailure(409,"demonstration_evidence_required","Verification requires separately accepted evidence of the demonstration");
  sourceDigest=(await partnerSourceFence(db,actor,revisionScope(c.guide,c.revision),content.sources,true)).digest;if(sourceDigest!==row.source_digest||(await db.query("SELECT invalidated_at FROM partner_checkpoint_revision_states WHERE revision_id=$1",[input.revisionId])).rows[0]?.invalidated_at)throw unavailable();
  const current=await projectPartnerAssignment(db,actor,a),verified=new Set(current.checkpoints.filter(cp=>cp.attempts.some(attempt=>attempt.state==="verified"&&attempt.content)).map(cp=>cp.checkpointId));const byId=new Map(c.revision.content!.checkpoints.map(cp=>[cp.id,cp]));const prerequisite=(id:string):boolean=>verified.has(id)&&byId.get(id)!.prerequisiteIds.every(prerequisite);if(!c.checkpoint.prerequisiteIds.every(prerequisite))throw new HttpFailure(409,"prerequisites_unverified","Verify current prerequisite demonstrations first");
 }else if(content)try{await partnerSourceFence(db,actor,revisionScope(c.guide,c.revision),content.sources);}catch(error){if(!(error instanceof HttpFailure)||![404,409,422].includes(error.status))throw error;content=null;}
 const locked=await loadPartnerAssignment(db,actor,a.id,true);expectPartnerVersion(locked.version,input.expectedVersion);await db.query("SELECT id FROM partner_checkpoint_attempts WHERE id=$1 FOR UPDATE",[row.id]);
 return {a,c,content,value:{proposal:proposal(input),actorAuthority:await partnerAuthorityDigest(db,actor,a.customer_id),targetBinding:[a.membership_revision,a.organization_revision,a.grant_revision],sessionId:actor.sessionId,guideVersion:Number(c.guide.version),revisionGeneration:Number(c.revision.generation),sourceDigest,contentAvailable:content!==null}};
}
export async function previewPartnerCheckpoint(actor:PartnerActor,raw:unknown){requirePartnerReviewer(actor);const input=partnerCheckpointReviewSchema.parse(raw),a=await partnerAssignmentScope(actor,input.assignmentId),scope={customerId:a.customer_id,targetMembershipId:a.membership_id},receipt=await partnerCommand(actor,{...input,action:"preview."+input.action},scope,async db=>{const b=await bind(db,actor,input),id=randomUUID();await db.query(`INSERT INTO partner_review_previews(id,environment_id,workspace_id,actor_membership_id,session_id,customer_id,action,input_digest,binding_digest,binding) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId,actor.sessionId,a.customer_id,input.action,partnerHash(proposal(input)),partnerHash(b.value),JSON.stringify(b.value)]);return {targetId:id,version:1};});return partnerRead(actor,a.customer_id,async db=>{const b=await bind(db,actor,input),p=(await db.query("SELECT binding_digest,expires_at FROM partner_review_previews WHERE id=$1 AND actor_membership_id=$2 AND session_id=$3",[receipt.targetId,actor.membershipId,actor.sessionId])).rows[0];if(!p||p.expires_at.getTime()<=Date.now())throw new HttpFailure(410,"preview_expired","Prepare a new checkpoint preview");if(p.binding_digest!==partnerHash(b.value))throw unavailable();return partnerCheckpointPreview({requestId:receipt.requestId,previewId:receipt.targetId!,expiresAt:p.expires_at.toISOString(),assignmentId:a.id,version:input.expectedVersion,content:b.content,citations:b.content?await partnerSourcePassages(db,actor,revisionScope(b.c.guide,b.c.revision),b.content.sources):[]});},a.membership_id);}
export async function decidePartnerCheckpoint(actor:PartnerActor,raw:unknown){requirePartnerReviewer(actor);const input=partnerCheckpointDecisionSchema.parse(raw),a=await partnerAssignmentScope(actor,input.assignmentId);return partnerCommand(actor,input,{customerId:a.customer_id,targetMembershipId:a.membership_id},async db=>{const {previewId,...review}=input,b=await bind(db,actor,review),p=(await db.query("SELECT * FROM partner_review_previews WHERE id=$1 AND environment_id=$2 AND actor_membership_id=$3 AND session_id=$4",[previewId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.membershipId,actor.sessionId])).rows[0];if(!p||p.action!==input.action||p.input_digest!==partnerHash(proposal(review))||p.binding_digest!==partnerHash(b.value))throw unavailable();if(p.expires_at.getTime()<=Date.now())throw new HttpFailure(410,"preview_expired","Prepare a new checkpoint preview");const id=randomUUID();await db.query(`INSERT INTO partner_review_decisions(id,environment_id,workspace_id,guide_id,guide_revision_id,assignment_id,checkpoint_revision_id,action,reviewer_membership_id,content_digest,binding_digest,self_review) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,a.guide_id,a.guide_revision_id,a.id,input.revisionId,input.action.slice(11),actor.membershipId,input.contentDigest,p.binding_digest,input.selfReview]);await db.query("INSERT INTO partner_decision_payloads(decision_id,content) VALUES($1,$2)",[id,JSON.stringify({rationale:input.rationale})]);await db.query("UPDATE partner_checkpoint_attempts SET state=$1 WHERE id=$2",[input.action==="checkpoint.verify"?"verified":"request_changes",input.attemptId]);await db.query("UPDATE partner_learning_assignments SET version=version+1 WHERE id=$1",[a.id]);return {targetId:a.id,version:input.expectedVersion+1};});}
