import { ProtectedShell } from "@/app/_components/protected-shell";
import { ServicesPlanControls } from "@/app/_components/services-plan";

export default function OperatingModelPage() {
  return <ProtectedShell returnTo="/operating-model"><main className="mx-auto max-w-6xl space-y-7 p-6 pt-16 md:pt-8">
    <header><p className="text-sm text-amber-800">Synthetic planning model · proposed operating policies</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Run the services business</h1><p className="mt-2 max-w-3xl text-muted-foreground">Make pricing, staffing, and investment decisions with the whole cost base visible. Engagement contribution alone does not pay for bench time or running the function.</p></header>
    <ServicesPlanControls />
    <section className="rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">Sell a bounded outcome</h2><div className="mt-4 grid gap-5 md:grid-cols-3">
      <article><h3 className="font-semibold">Discover</h3><p className="mt-2 text-sm">Paid, fixed-scope discovery when ownership, baseline, or integration risk is unclear. Exit with a measurable outcome, acceptance criteria, estimate, and a go/no-go decision.</p></article>
      <article><h3 className="font-semibold">Prove and launch</h3><p className="mt-2 text-sm">Fixed fee only with bounded scope and dependencies. Use capped time and materials for unresolved work. Name exclusions, milestone payments, change-control owner, and handoff acceptance before signature.</p></article>
      <article><h3 className="font-semibold">Enable and hand off</h3><p className="mt-2 text-sm">Train customer operators and verify independent use. Use partners for repeatable implementation capacity; keep platform-critical discovery and reusable learning close to FDE.</p></article>
    </div><p className="mt-4 text-sm text-muted-foreground">Illustrative quote: 120 hours × $125 + $2,000 nonlabor = $17,000 cost. A 20% cost contingency gives $20,400; a 35% engagement contribution target implies a $31,385 minimum fee, rounded up. Validate willingness to pay and the annual operating plan before quoting. These are proposed assumptions, not a Vercel rate card.</p></section>
    <section className="grid gap-5 md:grid-cols-2">
      <article className="rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">Decision rights and capacity</h2><p className="mt-3 text-sm">Sales owns the opportunity and customer relationship. The delivery lead signs off scope, acceptance, and skill availability. The services director owns price/margin exceptions and staffing tradeoffs. The customer sponsor owns business acceptance. Finance validates recognition and collections.</p><p className="mt-3 text-sm">Avery has 4 available Enablement lead hours this week; a 40-hour intervention cannot be promised from that capacity. Defer the gate, agree a multiweek plan, or secure a qualified alternative before approval. Free Discovery hours cannot substitute for Enablement expertise.</p><p className="mt-3 text-sm">Hire against sustained, qualified demand by skill and start date. Consider a partner for a short peak. Protect presales, learning, and recovery time; assess engineers on customer independence, quality, forecast accuracy, and reusable work as well as utilization.</p></article>
      <article className="rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">First 90 days</h2><ol className="mt-3 list-decimal space-y-3 pl-5 text-sm"><li><strong>Days 1–30:</strong> interview sellers, delivery staff, finance, customers, and partners. Reconcile rates, loaded cost, demand, effort forecasts, and skill availability. Baseline approval latency and forecast error.</li><li><strong>Days 31–60:</strong> pilot two bounded offers and weekly exception reviews. Require an owner, a scope boundary, an acceptance measure, and a pricing/capacity decision for each engagement.</li><li><strong>Days 61–90:</strong> expand only if the pilot improves forecast accuracy, acceptance, and decision speed without reducing delivery quality. Codify repeated work, review partner economics, and justify the next hire from demand.</li></ol><p className="mt-3 text-sm text-muted-foreground">Success measures are proposals, not observed improvements: hours forecast vs. actual; scope changes approved before work; customer acceptance; time to first independent operation; repeatable patterns adopted. Track product adoption separately from services revenue and avoid claiming causal ARR uplift.</p></article>
    </section>
  </main></ProtectedShell>;
}
