import { describe,it,expect,beforeAll } from 'vitest';
import { randomUUID } from 'node:crypto';
import { gapActors } from '../fixtures/gaps/seed';
import { syntheticGap,syntheticImpact } from '../fixtures/gaps/ui';
import { acceptedGapEvidence,publicGapEvidence } from '../fixtures/gaps/evidence';
import {withTransaction} from '../../lib/server/db/client';
import {gapDeliveryBaseline} from '../fixtures/gaps/delivery';
import { withGapDatabase } from '../fixtures/gaps/environment';
import { DEMO_IDS } from '../../lib/server/bootstrap-ids';
import { saveGap,readGap } from '../../lib/server/gaps/service';
import { saveGapImpact } from '../../lib/server/gaps/impacts';
import { previewGapDecision,commitGapDecision } from '../../lib/server/gaps/review';
const envelope=(version=0)=>({contractVersion:'product-gaps-v1' as const,requestKey:randomUUID(),expectedVersion:version});
describe('Gap and impact proposal, evidence review and correction',()=>{
 let actors:Awaited<ReturnType<typeof gapActors>>;
 beforeAll(async()=>{actors=await gapActors();});
 async function create(){const product=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.deniedCustomer,'product_limitation','Synthetic product documentation establishes the durable checkpoint limitation.');const gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[product.reference],customerIndependentAcknowledgment:true});const preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'gap',customerIndependentAcknowledgment:true,revisionId:gap.resultId,action:'accept',rationale:'Review exact synthetic product limitation',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest});return gap;}
 it('keeps proposals separate and rejects panel review without changing profiles',async()=>{const before=await withGapDatabase(db=>db.query('SELECT count(*) FROM profile_records'));const gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true});const detail=await readGap(actors.panel,gap.recordId!);expect(detail.working?.availability).toBe('eligible');expect(detail.reviewed).toBeNull();await expect(previewGapDecision(actors.panel,gap.recordId!,{...envelope(1),target:'gap',customerIndependentAcknowledgment:true,revisionId:gap.resultId,action:'accept',rationale:'Unauthorized review',revisitDate:null,selfReview:false})).rejects.toMatchObject({status:404});expect((await withGapDatabase(db=>db.query('SELECT count(*) FROM profile_records'))).rows).toEqual(before.rows);});
 it('accepts exact gap and customer need, with one receipt for repeated confirmation',async()=>{const gap=await create(),need=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Synthetic customer requires a durable checkpoint to avoid manual recovery.');const impact=await saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Synthetic customer requires a durable checkpoint to avoid manual recovery.',classification:'accepted_fact',sourceKeys:[need.reference.id]}]}),sourceRefs:[need.reference]});const detail=await readGap(actors.mcteer,gap.recordId!);const observation=detail.impacts[0];const preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'impact',impactId:observation.id,revisionId:impact.resultId,action:'accept',rationale:'Confirm supported synthetic customer impact',revisitDate:null,selfReview:false});const command={...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest};const a=await commitGapDecision(actors.mcteer,gap.recordId!,command),b=await commitGapDecision(actors.mcteer,gap.recordId!,command);expect(a.id).toBe(b.id);expect((await readGap(actors.panel,gap.recordId!)).impacts[0].reviewed?.content).toMatchObject({classification:'confirmed'});});
 it('replays committed review after preview expiry without repeating its decision',async()=>{const gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true}),preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'gap',customerIndependentAcknowledgment:true,revisionId:gap.resultId,action:'accept',rationale:'Synthetic exact review with expired preview replay',revisitDate:null,selfReview:false}),command={...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest};const receipt=await commitGapDecision(actors.mcteer,gap.recordId!,command);await withGapDatabase(async db=>{await db.query('BEGIN');try{await db.query("SELECT set_config('turas.gap_cleanup','yes',true)");await db.query("UPDATE gap_previews SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[preview.resultId]);await db.query('SELECT turas_gap_purge_payloads($1,100)',[process.env.TURAS_ENVIRONMENT_ID]);await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}});expect(await commitGapDecision(actors.mcteer,gap.recordId!,command)).toEqual(receipt);expect((await readGap(actors.panel,gap.recordId!)).history).toHaveLength(1);});
 it('editing preserves reviewed head and rejects stale previews',async()=>{const gap=await create(),before=await readGap(actors.panel,gap.recordId!);const edit=await saveGap(actors.panel,{...envelope(before.version),content:syntheticGap({title:'Changed proposed title'}),sourceRefs:before.reviewed!.sourceRefs,customerIndependentAcknowledgment:true},gap.recordId!);const after=await readGap(actors.panel,gap.recordId!);expect((after.reviewed!.content as {title:string}).title).toBe(syntheticGap().title);expect(after.working!.id).toBe(edit.resultId);await expect(saveGap(actors.panel,{...envelope(before.version),content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true},gap.recordId!)).rejects.toMatchObject({code:'stale_version'});});
 it('public-only impact cannot be confirmed or mislabeled an accepted fact',async()=>{const gap=await create(),weak=await publicGapEvidence(actors.panel,DEMO_IDS.sharedCustomer);await expect(saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Public attributed observation',classification:'attributed_research',sourceKeys:[weak.reference.id]}]}),sourceRefs:[weak.reference]})).rejects.toMatchObject({code:'source_unavailable'});});
 async function decide(gapId:string,version:number,revisionId:string,action:'accept'|'reject'|'defer'|'dismiss'|'reopen',selfReview=false){const preview=await previewGapDecision(actors.mcteer,gapId,{...envelope(version),target:'gap',customerIndependentAcknowledgment:true,revisionId,action,rationale:'Explicit synthetic review transition',revisitDate:action==='defer'?new Date(Date.now()+86400000).toISOString():null,selfReview});return commitGapDecision(actors.mcteer,gapId,{...envelope(version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});}
 it('rejects proposed edits without replacing the reviewed narrative',async()=>{const gap=await create(),before=await readGap(actors.panel,gap.recordId!);const edit=await saveGap(actors.panel,{...envelope(before.version),content:syntheticGap({title:'Rejected synthetic proposal'}),sourceRefs:before.reviewed!.sourceRefs,customerIndependentAcknowledgment:true},gap.recordId!);await decide(gap.recordId!,edit.version,edit.resultId!,'reject');const after=await readGap(actors.panel,gap.recordId!);expect(after.reviewed!.id).toBe(before.reviewed!.id);expect(after.working!.id).toBe(edit.resultId);expect(after.history[0].action).toBe('reject');});
 it('defers, dismisses and reopens with explicit history and increasing versions',async()=>{const gap=await create();let version=2;for(const action of ['defer','dismiss','reopen'] as const){await decide(gap.recordId!,version,gap.resultId!,action);const detail=await readGap(actors.panel,gap.recordId!);expect(detail.version).toBe(++version);expect(detail.disposition).toBe(action==='defer'?'deferred':action==='dismiss'?'dismissed':'open');expect(Boolean(detail.revisitAt)).toBe(action==='defer');}expect((await readGap(actors.panel,gap.recordId!)).history.map(h=>h.action)).toEqual(['reopen','dismiss','defer','accept']);});
 it('requires self-review acknowledgment for an administrator’s own proposal',async()=>{const gap=await saveGap(actors.mcteer,{...envelope(),content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true});await expect(decide(gap.recordId!,1,gap.resultId!,'accept')).rejects.toMatchObject({status:400});await decide(gap.recordId!,1,gap.resultId!,'accept',true);expect((await readGap(actors.mcteer,gap.recordId!)).history[0].selfReview).toBe(true);});
 it('rejects immutable observation identity correction and planned-only confirmation',async()=>{const gap=await create(),base={...envelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact(),sourceRefs:[]};await saveGapImpact(actors.panel,gap.recordId!,base);const detail=await readGap(actors.panel,gap.recordId!);await expect(saveGapImpact(actors.panel,gap.recordId!,{...base,...envelope(1),expectedGapVersion:detail.version,customerId:DEMO_IDS.deniedCustomer},detail.impacts[0].id)).rejects.toMatchObject({code:'invalid_input'});const planned=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Synthetic planned intent without observed deployment.',{state:'planned'});await expect(saveGapImpact(actors.panel,gap.recordId!,{...base,...envelope(),expectedGapVersion:detail.version,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Synthetic planned intent',classification:'accepted_fact',sourceKeys:[planned.reference.id]}]}),sourceRefs:[planned.reference]})).rejects.toMatchObject({code:'source_unavailable'});});

 async function acceptImpact(gapId:string,impactId:string,revisionId:string,version:number){const preview=await previewGapDecision(actors.mcteer,gapId,{...envelope(version),target:'impact',impactId,revisionId,action:'accept',rationale:'Explicit review of synthetic observation episode',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,gapId,{...envelope(version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});}
 it('reclassifies confirmed impact to suspected and separately retires its observation',async()=>{const gap=await create(),need=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Synthetic accepted customer impact for explicit reclassification.');const base={customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null};const confirmed=await saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:2,...base,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Synthetic accepted customer impact for explicit reclassification.',classification:'accepted_fact',sourceKeys:[need.reference.id]}]}),sourceRefs:[need.reference]});let detail=await readGap(actors.panel,gap.recordId!),observation=detail.impacts[0];await acceptImpact(gap.recordId!,observation.id,confirmed.resultId!,1);detail=await readGap(actors.panel,gap.recordId!);observation=detail.impacts[0];const suspected=await saveGapImpact(actors.panel,gap.recordId!,{...envelope(observation.version),expectedGapVersion:detail.version,...base,content:syntheticImpact({classification:'suspected',observedAt:null}),sourceRefs:[]},observation.id);await acceptImpact(gap.recordId!,observation.id,suspected.resultId!,suspected.version);detail=await readGap(actors.panel,gap.recordId!);observation=detail.impacts[0];expect(observation.reviewed?.content).toMatchObject({classification:'suspected',observedAt:null});const preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(observation.version),target:'impact',impactId:observation.id,revisionId:observation.reviewed!.id,action:'retire',rationale:'Retire the mistaken synthetic episode',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,gap.recordId!,{...envelope(observation.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});expect((await readGap(actors.panel,gap.recordId!)).impacts[0].state).toBe('retired');});
 it('preserves a resolved episode and creates a separately linked recurrence',async()=>{const gap=await create(),workloadId=randomUUID();await withGapDatabase(db=>db.query("INSERT INTO customer_workloads(id,workspace_id,customer_id,display_name) VALUES($1,$2,$3,'Synthetic resolution evidence workload')",[workloadId,actors.panel.workspaceId,DEMO_IDS.sharedCustomer]));const resolution=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'resolution','Synthetic customer reports the observed problem resolved.',{workloadId});const observedAt=new Date(Date.now()-7200000).toISOString(),resolvedAt=new Date(Date.now()-3600000).toISOString(),base={customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null};const resolved=await saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:2,...base,content:syntheticImpact({classification:'resolved',observedAt,resolvedAt,assertions:[{text:'Synthetic customer reports the observed problem resolved.',classification:'accepted_fact',sourceKeys:[resolution.reference.id]}]}),sourceRefs:[resolution.reference]});let detail=await readGap(actors.panel,gap.recordId!),prior=detail.impacts[0];await acceptImpact(gap.recordId!,prior.id,resolved.resultId!,1);detail=await readGap(actors.panel,gap.recordId!);prior=detail.impacts[0];await expect(saveGapImpact(actors.panel,gap.recordId!,{...envelope(prior.version),expectedGapVersion:detail.version,...base,content:syntheticImpact(),sourceRefs:[]},prior.id)).rejects.toMatchObject({code:'invalid_input'});await saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:detail.version,...base,recurrenceParent:prior.id,content:syntheticImpact(),sourceRefs:[]});const after=await readGap(actors.panel,gap.recordId!);expect(after.impacts).toHaveLength(2);expect(after.impacts.find(i=>i.id!==prior.id)?.recurrenceParent).toBe(prior.id);expect(after.impacts.find(i=>i.id===prior.id)?.reviewed?.content).toMatchObject({classification:'resolved',resolvedAt});});

 it('rejects cross-customer workload scope before persisting an observation',async()=>{const gap=await create(),workloadId=randomUUID();await withGapDatabase(db=>db.query("INSERT INTO customer_workloads(id,workspace_id,customer_id,display_name) VALUES($1,$2,$3,'Synthetic other-customer workload')",[workloadId,actors.panel.workspaceId,DEMO_IDS.deniedCustomer]));await expect(saveGapImpact(actors.panel,gap.recordId!,{...envelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId,engagementId:null,recurrenceParent:null,content:syntheticImpact(),sourceRefs:[]})).rejects.toMatchObject({status:404});expect((await readGap(actors.panel,gap.recordId!)).impacts).toHaveLength(0);});

 it('rejects cross-customer engagement and each independently weak critical citation',async()=>{const gap=await create(),delivery=await withTransaction(db=>gapDeliveryBaseline(db,actors.panel,actors.mcteer,DEMO_IDS.deniedCustomer)),base={...envelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:delivery.engagementId,recurrenceParent:null,content:syntheticImpact(),sourceRefs:[]};await expect(saveGapImpact(actors.panel,gap.recordId!,base)).rejects.toMatchObject({status:404});const need=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Weak synthetic directness cannot be compensated by product evidence.',{directness:2});await expect(saveGapImpact(actors.panel,gap.recordId!,{...base,...envelope(),engagementId:null,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Weak synthetic customer claim',classification:'accepted_fact',sourceKeys:[need.reference.id]}]}),sourceRefs:[need.reference]})).rejects.toMatchObject({code:'source_unavailable'});});
 it('binds previews to one session and refuses expired uncommitted previews',async()=>{const gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[],customerIndependentAcknowledgment:true}),preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'gap',revisionId:gap.resultId,action:'accept',rationale:'Synthetic actor-session exact preview boundary',revisitDate:null,selfReview:false,customerIndependentAcknowledgment:true}),fresh=await gapActors();await expect(commitGapDecision(fresh.mcteer,gap.recordId!,{...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({status:404});await withGapDatabase(async db=>{await db.query('BEGIN');try{await db.query("SELECT set_config('turas.gap_cleanup','yes',true)");await db.query("UPDATE gap_previews SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[preview.resultId]);await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}});await expect(commitGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({code:'preview_expired'});expect((await readGap(actors.panel,gap.recordId!)).reviewed).toBeNull();});

});
