import {describe,it,expect,vi} from 'vitest';
import {approvedGapReport} from '../fixtures/gaps/reports';
import {gapEnvelope} from '../fixtures/gaps/authoring';
import {recordGapHandoff,readGapHandoffs} from '../../lib/server/gaps/handoffs';
import {readGapReport} from '../../lib/server/gaps/reports';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {randomUUID} from 'node:crypto';
const action=(version:number,audienceDigest:string)=>({...gapEnvelope(version),kind:'handed_off',eventAt:new Date().toISOString(),audienceDigest,predecessorId:null,correctedId:null,metadataOnly:false,note:'Manually delivered the exact approved synthetic report to the named engineering audience.',reference:'https://example.com/synthetic-engineering/issue/1',sourceRefs:[]});
describe('Attributable manual handoff without external action',()=>{
 it('records and replays one exact initial action without fetch or customer mutation',async()=>{const f=await approvedGapReport(),command=action(f.report.version,f.report.revision!.audienceDigest),before=(await withGapDatabase(db=>db.query('SELECT count(*) AS n FROM profile_revisions'))).rows[0].n,network=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No external fetch permitted'));try{const receipt=await recordGapHandoff(f.actors.mcteer,f.report.id,command);expect(await recordGapHandoff(f.actors.mcteer,f.report.id,command)).toEqual(receipt);expect(network).not.toHaveBeenCalled();expect((await readGapHandoffs(f.actors.panel,f.report.id))[0]).toMatchObject({id:receipt.resultId,kind:'handed_off',humanReported:true});expect((await withGapDatabase(db=>db.query('SELECT count(*) AS n FROM profile_revisions'))).rows[0].n).toBe(before);const current=await readGapReport(f.actors.panel,f.report.id);await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...command,...gapEnvelope(current.version),note:'Different initial action'})).rejects.toMatchObject({code:'handoff_exists'});}finally{network.mockRestore();}});
 it('denies ordinary members, wrong audience, unsafe reference and pre-approval occurrence',async()=>{const f=await approvedGapReport(),command=action(f.report.version,f.report.revision!.audienceDigest);await expect(recordGapHandoff(f.actors.panel,f.report.id,command)).rejects.toMatchObject({status:404});await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...command,audienceDigest:'a'.repeat(64)})).rejects.toMatchObject({status:409});await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...command,eventAt:new Date(Date.parse(f.report.review!.approvedAt)-1).toISOString()})).rejects.toMatchObject({status:400});expect(()=>recordGapHandoff(f.actors.mcteer,f.report.id,{...command,reference:'https://user:password@example.com/private'})).toThrow();});
 it('appends ordered follow-up and immutable correction without resolving customer impact',async()=>{const f=await approvedGapReport(),initial=await recordGapHandoff(f.actors.mcteer,f.report.id,action(f.report.version,f.report.revision!.audienceDigest)),follow=await recordGapHandoff(f.actors.mcteer,f.report.id,{...action(initial.version,f.report.revision!.audienceDigest),kind:'resolution_reported',predecessorId:initial.resultId,note:'An engineer verbally reported a possible resolution; customer verification remains unknown.'}),correction=await recordGapHandoff(f.actors.mcteer,f.report.id,{...action(follow.version,f.report.revision!.audienceDigest),kind:'correction',predecessorId:follow.resultId,correctedId:follow.resultId,note:'The earlier resolution report was premature and requires customer verification.'});const rows=await readGapHandoffs(f.actors.panel,f.report.id);expect(rows.map(r=>r.id)).toEqual([initial.resultId,follow.resultId,correction.resultId]);expect(rows[1].needsHumanFollowUp).toBe(true);expect(rows[2].correctedId).toBe(follow.resultId);expect(rows[0].payload?.reference).toBe('https://example.com/synthetic-engineering/issue/1');});
 it('refuses foreign or backdated predecessors and leaves no partial event',async()=>{const f=await approvedGapReport(),initial=await recordGapHandoff(f.actors.mcteer,f.report.id,action(f.report.version,f.report.revision!.audienceDigest)),rows=await readGapHandoffs(f.actors.panel,f.report.id);for(const patch of [{predecessorId:randomUUID()},{eventAt:new Date(Date.parse(rows[0].eventAt)-1).toISOString()}])await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...action(initial.version,f.report.revision!.audienceDigest),kind:'acknowledged',predecessorId:initial.resultId,...patch})).rejects.toThrow();expect(await readGapHandoffs(f.actors.panel,f.report.id)).toHaveLength(1);});
 it('permits metadata-only correction after withdrawal without storing or returning withdrawn prose',async()=>{const f=await approvedGapReport(),initial=await recordGapHandoff(f.actors.mcteer,f.report.id,action(f.report.version,f.report.revision!.audienceDigest));await withGapDatabase(db=>db.query("UPDATE gap_report_revision_states SET invalidated_at=clock_timestamp(),purge_at=clock_timestamp()+interval '24 hours' WHERE revision_id=$1",[f.report.revision!.id]));await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...action(initial.version,f.report.revision!.audienceDigest),kind:'acknowledged',predecessorId:initial.resultId})).rejects.toMatchObject({status:409});const receipt=await recordGapHandoff(f.actors.mcteer,f.report.id,{...gapEnvelope(initial.version),kind:'correction',eventAt:new Date().toISOString(),audienceDigest:f.report.revision!.audienceDigest,predecessorId:initial.resultId,correctedId:initial.resultId,metadataOnly:true,note:null,reference:null,sourceRefs:[]});const rows=await readGapHandoffs(f.actors.panel,f.report.id);expect(rows.every(r=>r.payload===null)).toBe(true);expect(rows.every(r=>r.needsHumanFollowUp)).toBe(true);expect((await withGapDatabase(db=>db.query('SELECT 1 FROM gap_handoff_payloads WHERE receipt_id=$1',[receipt.resultId]))).rowCount).toBe(0);});
 it('permits only metadata follow-up after exact thirty-day expiry and revoked reviewers cannot replay',async()=>{const f=await approvedGapReport(true),command=action(f.report.version,f.report.revision!.audienceDigest),initial=await recordGapHandoff(f.actors.mcteer,f.report.id,command);await withGapDatabase(async db=>{await db.query('BEGIN');try{await db.query('ALTER TABLE gap_report_revisions DISABLE TRIGGER gap_immutable');await db.query("UPDATE gap_report_revisions SET prepared_at=current_timestamp-interval '31 days',expires_at=current_timestamp-interval '1 day' WHERE id=$1",[f.report.revision!.id]);await db.query('ALTER TABLE gap_report_revisions ENABLE TRIGGER gap_immutable');await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}});expect((await readGapReport(f.actors.panel,f.report.id)).availability).toBe('expired');await expect(recordGapHandoff(f.actors.mcteer,f.report.id,{...action(initial.version,f.report.revision!.audienceDigest),kind:'acknowledged',predecessorId:initial.resultId})).rejects.toMatchObject({status:409});await recordGapHandoff(f.actors.mcteer,f.report.id,{...gapEnvelope(initial.version),kind:'acknowledged',eventAt:new Date().toISOString(),audienceDigest:f.report.revision!.audienceDigest,predecessorId:initial.resultId,correctedId:null,metadataOnly:true,note:null,reference:null,sourceRefs:[]});await withGapDatabase(db=>db.query("UPDATE memberships SET role='member' WHERE id=$1",[f.actors.mcteer.membershipId]));try{await expect(recordGapHandoff(f.actors.mcteer,f.report.id,command)).rejects.toThrow();}finally{await withGapDatabase(db=>db.query("UPDATE memberships SET role='admin' WHERE id=$1",[f.actors.mcteer.membershipId]));}});

});
