import {beforeAll,describe,it,expect} from 'vitest';
import {gapActors} from '../fixtures/gaps/seed';
import {reviewedSyntheticGap,reviewedSuspectedImpact,gapEnvelope} from '../fixtures/gaps/authoring';
import {randomUUID} from 'node:crypto';
import {lockGapActor} from '../../lib/server/gaps/policy';
import {getServerConfig} from '../../lib/server/config';
import {gapCountMetadata,readGapCounts} from '../../lib/server/gaps/counts';
import {readGap,saveGap} from '../../lib/server/gaps/service';
import {previewGapDecision,commitGapDecision} from '../../lib/server/gaps/review';
import {syntheticGap} from '../fixtures/gaps/ui';
import {acceptedGapEvidence} from '../fixtures/gaps/evidence';
import {saveGapImpact} from '../../lib/server/gaps/impacts';
import {syntheticImpact} from '../fixtures/gaps/ui';
import {submitProfileCommand} from '../../lib/server/profiles/service';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
describe('Authorized current customer sets',()=>{
 let actors:Awaited<ReturnType<typeof gapActors>>;beforeAll(async()=>{actors=await gapActors();});
 it('counts two customers once each despite repeated observations',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer);for(const customer of [DEMO_IDS.sharedCustomer,DEMO_IDS.sharedCustomer,DEMO_IDS.deniedCustomer])await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,customer);const result=await readGapCounts(actors.panel,[gap.id]);expect(result.items[0]).toMatchObject({id:gap.id,confirmed:0,suspectedOnly:2,resolvedHistory:0,evidenceFreshness:'no_evidence'});});
 it('does not silently reapprove impacts under a new product context',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer);await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);const detail=await readGap(actors.panel,gap.id),edit=await saveGap(actors.panel,{...gapEnvelope(detail.version),content:syntheticGap({kind:'documentation'}),sourceRefs:[],customerIndependentAcknowledgment:true},gap.id),preview=await previewGapDecision(actors.mcteer,gap.id,{...gapEnvelope(edit.version),target:'gap',revisionId:edit.resultId,action:'accept',rationale:'Explicit changed context requires impact re-review',revisitDate:null,selfReview:false,customerIndependentAcknowledgment:true});await commitGapDecision(actors.mcteer,gap.id,{...gapEnvelope(edit.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});expect((await readGapCounts(actors.panel,[gap.id])).items[0].suspectedOnly).toBe(0);});
 it('denies partners and unknown selected identities uniformly',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer);await expect(readGapCounts(actors.partner,[gap.id])).rejects.toMatchObject({status:404});await expect(readGapCounts(actors.panel,['00000000-0000-4000-8000-000000000000'])).rejects.toMatchObject({status:404});});
 it('matches source-qualified confirmation and immediately removes withdrawn evidence without maintenance',async()=>{const product=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.deniedCustomer,'product_limitation','Synthetic product documentation for metadata parity.'),need=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Synthetic accepted actual customer need for counts.'),saved=await saveGap(actors.panel,{...gapEnvelope(),content:syntheticGap(),sourceRefs:[product.reference],customerIndependentAcknowledgment:true});let preview=await previewGapDecision(actors.mcteer,saved.recordId!,{...gapEnvelope(1),target:'gap',revisionId:saved.resultId,action:'accept',rationale:'Review synthetic parity product context',revisitDate:null,selfReview:false,customerIndependentAcknowledgment:true});await commitGapDecision(actors.mcteer,saved.recordId!,{...gapEnvelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest});const impact=await saveGapImpact(actors.panel,saved.recordId!,{...gapEnvelope(),expectedGapVersion:2,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact({classification:'confirmed',assertions:[{text:'Synthetic accepted actual customer need for counts.',classification:'accepted_fact',sourceKeys:[need.reference.id]}]}),sourceRefs:[need.reference]}),detail=await readGap(actors.panel,saved.recordId!);preview=await previewGapDecision(actors.mcteer,saved.recordId!,{...gapEnvelope(1),target:'impact',impactId:detail.impacts[0].id,revisionId:impact.resultId,action:'accept',rationale:'Review independently supported actual impact',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,saved.recordId!,{...gapEnvelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest});expect((await readGapCounts(actors.panel,[saved.recordId!])).items[0]).toMatchObject({confirmed:1,evidenceFreshness:'recent'});const row=(await withGapDatabase(db=>db.query('SELECT r.version FROM profile_records r JOIN profile_revisions v ON v.record_id=r.id WHERE v.id=$1',[need.revisionId]))).rows[0];await submitProfileCommand(actors.mcteer,DEMO_IDS.sharedCustomer,{action:'retract_revision',requestKey:gapEnvelope().requestKey,revisionId:need.revisionId,expectedRecordVersion:Number(row.version),rationale:'Synthetic parity source withdrawal'});expect((await readGap(actors.panel,saved.recordId!)).impacts[0].reviewed?.availability).toBe('withheld');expect((await readGapCounts(actors.panel,[saved.recordId!])).items[0]).toMatchObject({confirmed:0,evidenceFreshness:'unavailable'});});
 it('uses review decision time at cutoff rather than future observation membership',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer),cutoff=new Date();await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);expect((await readGapCounts(actors.panel,[gap.id],cutoff)).items[0].suspectedOnly).toBe(0);expect((await readGapCounts(actors.panel,[gap.id])).items[0].suspectedOnly).toBe(1);});

 it('allows reconstructible source-free transitions and refuses purged historical trends',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer),before=new Date();await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);let result=await readGapCounts(actors.panel,[gap.id],new Date(),before);expect(result.items[0].comparison).toMatchObject({availability:'available',confirmed:0,suspectedOnly:1,resolvedHistory:0});const detail=await readGap(actors.panel,gap.id),impact=detail.impacts[0],cutoff=new Date();const saved=await saveGapImpact(actors.panel,gap.id,{...gapEnvelope(impact.version),expectedGapVersion:detail.version,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact({consequences:'Corrected synthetic consequence'}),sourceRefs:[]},impact.id),preview=await previewGapDecision(actors.mcteer,gap.id,{...gapEnvelope(saved.version),target:'impact',impactId:impact.id,revisionId:saved.resultId,action:'accept',rationale:'Explicit synthetic historical correction',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,gap.id,{...gapEnvelope(saved.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});await withGapDatabase(db=>db.query('DELETE FROM gap_revision_payloads WHERE revision_id=$1',[impact.reviewed!.id]));result=await readGapCounts(actors.panel,[gap.id],new Date(),cutoff);expect(result.items[0].comparison).toMatchObject({availability:'unavailable'});expect(result.items[0].suspectedOnly).toBe(1);});
 it('returns unavailable instead of fabricated zero totals when primary historical payload is gone',async()=>{const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer);await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);const detail=await readGap(actors.panel,gap.id);await withGapDatabase(async db=>{await db.query('BEGIN');try{await db.query('DELETE FROM gap_revision_payloads WHERE revision_id=$1',[detail.impacts[0].reviewed!.id]);await expect(gapCountMetadata(db,actors.panel,[gap.id])).rejects.toMatchObject({status:409,code:'history_unavailable'});}finally{await db.query('ROLLBACK');}});});
 it('suppresses repeated suspected impact, retains resolved history across recurrence and excludes a retired mistake',async()=>{
  const product=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.deniedCustomer,'product_limitation','Synthetic applicable product constraint'),need=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'customer_need','Synthetic independently accepted actual need and customer resolution'),saved=await saveGap(actors.panel,{...gapEnvelope(),content:syntheticGap(),sourceRefs:[product.reference],customerIndependentAcknowledgment:true}),gapId=saved.recordId!;
  const accept=async(target:'gap'|'impact',revisionId:string,version:number,impactId?:string)=>{const preview=await previewGapDecision(actors.mcteer,gapId,{...gapEnvelope(version),target,revisionId,impactId,action:'accept',rationale:'Independent synthetic episode review',revisitDate:null,selfReview:false,...(target==='gap'?{customerIndependentAcknowledgment:true}:{})});await commitGapDecision(actors.mcteer,gapId,{...gapEnvelope(version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});};
  await accept('gap',saved.resultId!,1);const suspected=await reviewedSuspectedImpact(actors.panel,actors.mcteer,gapId,DEMO_IDS.sharedCustomer);
  const other=await reviewedSuspectedImpact(actors.panel,actors.mcteer,gapId,DEMO_IDS.deniedCustomer);
  const propose=async(classification:'confirmed'|'resolved',id?:string,parent:string|null=null)=>{const detail=await readGap(actors.panel,gapId),current=detail.impacts.find(i=>i.id===id),ref=classification==='resolved'?{...need.reference,purpose:'resolution' as const}:need.reference,content=syntheticImpact({classification,observedAt:new Date(Date.now()-2000).toISOString(),resolvedAt:classification==='resolved'?new Date(Date.now()-1000).toISOString():null,assertions:[{text:'Synthetic independently accepted actual need and customer resolution',classification:'accepted_fact',sourceKeys:[ref.id]}]}),result=await saveGapImpact(actors.panel,gapId,{...gapEnvelope(current?.version??0),expectedGapVersion:detail.version,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:parent,content,sourceRefs:[ref]},id);const after=await readGap(actors.panel,gapId),impact=after.impacts.find(i=>i.working?.id===result.resultId)!;await accept('impact',result.resultId!,result.version,impact.id);return impact.id;};
  const confirmed=await propose('confirmed');expect((await readGapCounts(actors.panel,[gapId])).items[0]).toMatchObject({confirmed:1,suspectedOnly:1,resolvedHistory:0});
  await propose('resolved',confirmed);expect((await readGapCounts(actors.panel,[gapId])).items[0]).toMatchObject({confirmed:0,suspectedOnly:2,resolvedHistory:1});
  // The recurrence's observation is later than its resolved predecessor.
  await new Promise(resolve=>setTimeout(resolve,1100));await propose('confirmed',undefined,confirmed);expect((await readGapCounts(actors.panel,[gapId])).items[0]).toMatchObject({confirmed:1,suspectedOnly:1,resolvedHistory:1});
  const detail=await readGap(actors.panel,gapId),mistake=detail.impacts.find(i=>i.id===other)!,preview=await previewGapDecision(actors.mcteer,gapId,{...gapEnvelope(mistake.version),target:'impact',impactId:other,revisionId:mistake.reviewed!.id,action:'retire',rationale:'Synthetic retired erroneous customer identity',revisitDate:null,selfReview:false});await commitGapDecision(actors.mcteer,gapId,{...gapEnvelope(mistake.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});
  expect((await readGapCounts(actors.panel,[gapId])).items[0]).toMatchObject({confirmed:1,suspectedOnly:0,resolvedHistory:1});expect((await readGap(actors.panel,gapId)).impacts.some(i=>i.id===suspected)).toBe(true);
 });
 it('fails on each C10 scope overflow instead of returning a partial total',async()=>{
  const gap=await reviewedSyntheticGap(actors.panel,actors.mcteer),env=getServerConfig().TURAS_ENVIRONMENT_ID;
  for(const kind of ['gaps','observations','dependencies'])await withGapDatabase(async db=>{await db.query('BEGIN');try{
   await lockGapActor(db,actors.panel);
   if(kind==='gaps')await db.query("INSERT INTO product_gaps(id,environment_id,workspace_id,creator_membership_id) SELECT gen_random_uuid(),$1,$2,$3 FROM generate_series(1,2001)",[env,actors.panel.workspaceId,actors.panel.membershipId]);
   if(kind==='observations'){const rows=Array.from({length:10001},()=>({id:randomUUID(),event:randomUUID()}));await db.query('INSERT INTO gap_impact_observations(id,environment_id,workspace_id,original_gap_id,customer_id,creator_membership_id) SELECT x.id,$2,$3,$4,$5,$6 FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,event uuid)',[JSON.stringify(rows),env,actors.panel.workspaceId,gap.id,DEMO_IDS.sharedCustomer,actors.panel.membershipId]);await db.query('INSERT INTO gap_assignment_events(id,environment_id,workspace_id,observation_id,canonical_gap_id) SELECT x.event,$2,$3,x.id,$4 FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,event uuid)',[JSON.stringify(rows),env,actors.panel.workspaceId,gap.id]);await db.query('INSERT INTO gap_observation_assignments(observation_id,environment_id,workspace_id,canonical_gap_id,event_id) SELECT x.id,$2,$3,$4,x.event FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,event uuid)',[JSON.stringify(rows),env,actors.panel.workspaceId,gap.id]);}
   if(kind==='dependencies')await db.query("INSERT INTO gap_source_dependencies(id,revision_id,source_kind,source_revision_id,source_generation,source_digest,reference) SELECT gen_random_uuid(),$1,'accepted_profile',gen_random_uuid(),1,repeat('a',64),'{}'::jsonb FROM generate_series(1,20001)",[gap.reviewed!.id]);
   await expect(gapCountMetadata(db,actors.panel,kind==='gaps'?undefined:[gap.id])).rejects.toMatchObject({status:413,code:'scope_too_large'});
  }finally{await db.query('ROLLBACK');}});
  expect((await readGapCounts(actors.panel,[gap.id])).items[0]).toMatchObject({confirmed:0,suspectedOnly:0});
 });

});
