import { beforeAll,describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { gapActors } from '../fixtures/gaps/seed';
import { withGapDatabase } from '../fixtures/gaps/environment';
import { acceptedGapEvidence } from '../fixtures/gaps/evidence';
import { syntheticGap } from '../fixtures/gaps/ui';
import { DEMO_IDS } from '../../lib/server/bootstrap-ids';
import { saveGap,readGap,gapDetail } from '../../lib/server/gaps/service';
import { previewGapDecision,commitGapDecision } from '../../lib/server/gaps/review';
import {withTransaction} from '../../lib/server/db/client';
import {lockGapActor} from '../../lib/server/gaps/policy';
import {gapDependencyUnion} from '../../lib/server/gaps/dependencies';
import {gapHash} from '../../lib/server/gaps/commands';
import {sharedGapEvidence,excerptGapEvidence} from '../fixtures/gaps/originals';
import {gapDeliveryBaseline} from '../fixtures/gaps/delivery';
import {readGapCounts} from '../../lib/server/gaps/counts';
import {saveRegister,submitRegister,reviewRegister,raidRecord,executionCommand} from '../fixtures/execution/registers';
import {submitExecutionCommand} from '../../lib/server/execution/service';
import type {GapSource} from '../../lib/contracts/product-gaps';
import {lockGapSourceUnion,createFencedGapVerifier} from '../../lib/server/gaps/sources';
import { submitProfileCommand } from '../../lib/server/profiles/service';
const envelope=(expectedVersion=0)=>({contractVersion:'product-gaps-v1' as const,requestKey:randomUUID(),expectedVersion});
describe('Current evidence fences with maintenance stopped',()=>{
 let actors:Awaited<ReturnType<typeof gapActors>>;
 beforeAll(async()=>{actors=await gapActors();});
 async function proposed(){const source=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'product_limitation','Synthetic exact source for withdrawal fence.');const gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[source.reference],customerIndependentAcknowledgment:true});return {source,gap};}
 async function retract(revisionId:string){const row=await withGapDatabase(async db=>(await db.query('SELECT r.version FROM profile_records r JOIN profile_revisions v ON v.record_id=r.id WHERE v.id=$1',[revisionId])).rows[0]);await submitProfileCommand(actors.mcteer,DEMO_IDS.sharedCustomer,{action:'retract_revision',requestKey:randomUUID(),revisionId,expectedRecordVersion:Number(row.version),rationale:'Synthetic source withdrawal'});}
 it('withholds prose immediately on retraction without a worker',async()=>{const {source,gap}=await proposed();expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('eligible');await retract(source.revisionId);const detail=await readGap(actors.panel,gap.recordId!);expect(detail.working).toMatchObject({availability:'withheld',content:null,sourceRefs:[]});const state=await withGapDatabase(async db=>(await db.query('SELECT invalidated_at,purge_at FROM gap_revision_states WHERE revision_id=$1',[gap.resultId])).rows[0]);expect(state.invalidated_at).toBeInstanceOf(Date);expect(state.purge_at.getTime()-state.invalidated_at.getTime()).toBeLessThanOrEqual(86400100);});
 it('rejects a previously valid exact acceptance preview after source withdrawal',async()=>{const {source,gap}=await proposed();const preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'gap',customerIndependentAcknowledgment:true,revisionId:gap.resultId,action:'accept',rationale:'Review current synthetic evidence',revisitDate:null,selfReview:false});await retract(source.revisionId);await expect(commitGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({code:'source_unavailable'});expect((await readGap(actors.panel,gap.recordId!)).reviewed).toBeNull();});
 it('revoking one actor does not globally invalidate another actor’s eligible prose',async()=>{const {gap}=await proposed(),revoked=await gapActors();await withGapDatabase(db=>db.query('UPDATE login_sessions SET revoked_at=now() WHERE id=$1',[revoked.panel.sessionId]));await expect(readGap(revoked.panel,gap.recordId!)).rejects.toMatchObject({status:401});expect((await readGap(actors.mcteer,gap.recordId!)).working?.availability).toBe('eligible');});
 it('serializes a source writer against detail release without lock inversion',async()=>{const {source,gap}=await proposed();const [read,write]=await Promise.allSettled([readGap(actors.panel,gap.recordId!),retract(source.revisionId)]);expect(write.status).toBe('fulfilled');expect(read.status).toBe('fulfilled');if(read.status==='fulfilled')expect(['eligible','withheld']).toContain(read.value.working?.availability);expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('withheld');});

 it('holds a controlled reader fence until the source writer can commit',async()=>{const {source,gap}=await proposed();const held=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();const reader=withTransaction(async db=>{await lockGapActor(db,actors.panel);await lockGapSourceUnion(db,actors.panel,[source.reference]);held.resolve();await release.promise;return gapDetail(db,actors.panel,gap.recordId!);});await held.promise;const writer=retract(source.revisionId);try{await withGapDatabase(async db=>{let waiting=false;for(let i=0;i<30;i++){waiting=Boolean((await db.query("SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND (query LIKE '%customer_profile_state%' OR query LIKE '%workspaces%') LIMIT 1")).rowCount);if(waiting)break;await new Promise(r=>setTimeout(r,20));}expect(waiting).toBe(true);});}finally{release.resolve();}const detail=await reader;await writer;expect(detail.working?.availability).toBe('eligible');expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('withheld');});

 it('rejects conflicting original generations across the whole operation',async()=>{const {source}=await proposed();await expect(withTransaction(async db=>{await lockGapActor(db,actors.panel);return lockGapSourceUnion(db,actors.panel,[source.reference,{...source.reference,id:randomUUID(),generation:source.reference.generation+1}]);})).rejects.toMatchObject({status:409});});

 it('accepts exactly 200 original headers and fails explicitly at 201 before release',async()=>{const {source}=await proposed(),children=Array.from({length:200},()=>({recordId:randomUUID(),id:randomUUID()})),payload={kind:'claim',text:'Synthetic bounded dependency identity',sourceType:'manual'},digest=gapHash(payload);await withGapDatabase(async db=>{await db.query("INSERT INTO profile_records(id,workspace_id,customer_id,kind,created_by) SELECT x.\"recordId\",$2,$3,'claim',$4 FROM jsonb_to_recordset($1::jsonb) AS x(\"recordId\" uuid,id uuid)",[JSON.stringify(children),actors.panel.workspaceId,DEMO_IDS.sharedCustomer,actors.panel.membershipId]);await db.query("INSERT INTO profile_revisions(id,record_id,workspace_id,customer_id,revision_number,payload_schema_version,payload,quality_input,author_membership_id,origin,audience,data_category,content_digest) SELECT x.id,x.\"recordId\",$2,$3,1,'profile-v1',$4,'{}'::jsonb,$5,'manual','internal','internal_operations',$6 FROM jsonb_to_recordset($1::jsonb) AS x(\"recordId\" uuid,id uuid)",[JSON.stringify(children),actors.panel.workspaceId,DEMO_IDS.sharedCustomer,JSON.stringify(payload),actors.panel.membershipId,digest]);const chain=[source.revisionId,...children.map(c=>c.id)],links=chain.slice(0,199).map((id,index)=>({id:randomUUID(),from:id,to:chain[index+1]}));await db.query("INSERT INTO profile_evidence_links(id,workspace_id,customer_id,profile_revision_id,supporting_profile_revision_id,support_role,scope_explanation) SELECT x.id,$2,$3,x.\"from\",x.\"to\",'corroboration','Synthetic closure boundary' FROM jsonb_to_recordset($1::jsonb) AS x(id uuid,\"from\" uuid,\"to\" uuid)",[JSON.stringify(links),actors.panel.workspaceId,DEMO_IDS.sharedCustomer]);});expect(await withTransaction(async db=>{await lockGapActor(db,actors.panel);return (await gapDependencyUnion(db,actors.panel,[source.reference],200)).length;})).toBe(200);await withGapDatabase(db=>db.query("INSERT INTO profile_evidence_links(id,workspace_id,customer_id,profile_revision_id,supporting_profile_revision_id,support_role,scope_explanation) VALUES($1,$2,$3,$4,$5,'corroboration','Synthetic overflow edge')",[randomUUID(),actors.panel.workspaceId,DEMO_IDS.sharedCustomer,children[198].id,children[199].id]));await expect(withTransaction(async db=>{await lockGapActor(db,actors.panel);return gapDependencyUnion(db,actors.panel,[source.reference],200);})).rejects.toMatchObject({status:413,code:'scope_too_large'});});

 it('retains published shared lineage and evaluates quality expiry with maintenance stopped',async()=>{const source=await sharedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer),gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[source.reference],customerIndependentAcknowledgment:true});expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('eligible');expect((await readGapCounts(actors.panel,[gap.recordId!])).items[0].eligible).toBe(true);await withGapDatabase(db=>db.query("UPDATE knowledge_publications SET public_quality=jsonb_set(public_quality,'{validUntil}',to_jsonb($2::text)) WHERE revision_id=$1",[source.revisionId,new Date(Date.now()-1000).toISOString()]));expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('withheld');expect((await readGapCounts(actors.panel,[gap.recordId!])).items[0].eligible).toBe(false);});
 it('releases an exact reviewed excerpt and withholds it immediately after artifact withdrawal',async()=>{const source=await excerptGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer),gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:[source.reference],customerIndependentAcknowledgment:true});expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('eligible');expect((await readGapCounts(actors.panel,[gap.recordId!])).items[0].eligible).toBe(true);await withGapDatabase(db=>db.query("UPDATE artifact_versions SET state='withdrawn',lifecycle_generation=lifecycle_generation+1 WHERE id=$1",[source.versionId]));expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('withheld');expect((await readGapCounts(actors.panel,[gap.recordId!])).items[0].eligible).toBe(false);});
 it('binds actual reviewed execution and its transitive active planning baseline without treating a plan as customer intent',async()=>{const delivery=await withTransaction(db=>gapDeliveryBaseline(db,actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer));await submitExecutionCommand(actors.panel,delivery.engagementId,executionCommand('setup',{baseline:1,plan:delivery.decision.aggregateVersion},{baselineId:delivery.baselineId}));const baseline=(await withGapDatabase(db=>db.query('SELECT baseline_number,content_digest FROM milestone_baselines WHERE id=$1',[delivery.baselineId]))).rows[0],baseRef={id:delivery.baselineId,kind:'milestone_baseline' as const,sourceRevisionId:delivery.baselineId,generation:Number(baseline.baseline_number),contentDigest:baseline.content_digest},record=await saveRegister(delivery,{...raidRecord(),references:[baseRef]}),submitted=await submitRegister(delivery,record);await reviewRegister(delivery,submitted);const head=(await withGapDatabase(db=>db.query('SELECT v.id,v.revision_number,v.content_digest FROM execution_records r JOIN execution_record_revisions v ON v.id=r.accepted_revision_id WHERE r.id=$1',[record.id]))).rows[0],refs:GapSource[]=[{...baseRef,id:randomUUID(),customerId:DEMO_IDS.sharedCustomer,engagementId:delivery.engagementId,purpose:'corroboration'},{id:randomUUID(),kind:'execution_record',sourceRevisionId:head.id,generation:Number(head.revision_number),contentDigest:head.content_digest,customerId:DEMO_IDS.sharedCustomer,engagementId:delivery.engagementId,purpose:'corroboration'}],gap=await saveGap(actors.panel,{...envelope(),content:syntheticGap(),sourceRefs:refs,customerIndependentAcknowledgment:true});expect((await readGap(actors.panel,gap.recordId!)).working?.availability).toBe('eligible');expect((await readGapCounts(actors.panel,[gap.recordId!])).items[0].eligible).toBe(true);expect((await withGapDatabase(db=>db.query('SELECT DISTINCT source_kind FROM gap_source_dependencies WHERE revision_id=$1 ORDER BY source_kind',[gap.resultId]))).rows.map(r=>r.source_kind)).toEqual(['execution_record','milestone_baseline']);});

 it('cannot reuse a request-local source verifier after its transaction ends',async()=>{await withGapDatabase(async db=>{await db.query('BEGIN');const verifier=await createFencedGapVerifier(db,actors.panel);await verifier([]);await verifier([]);await db.query('COMMIT');await db.query('BEGIN');try{await expect(verifier([])).rejects.toMatchObject({status:409,code:'source_unavailable'});}finally{await db.query('ROLLBACK');}});});

 it('rejects exact acceptance after a controlled source or gap-head writer wins its final fence',async()=>{for(const change of ['source','head'] as const){const {source,gap}=await proposed(),preview=await previewGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),target:'gap',revisionId:gap.resultId,action:'accept',rationale:'Synthetic final acceptance barrier',revisitDate:null,selfReview:false,customerIndependentAcknowledgment:true});let command:Promise<unknown>|undefined;await withGapDatabase(async db=>{await db.query('BEGIN');try{if(change==='source'){await db.query('SELECT customer_id FROM customer_profile_state WHERE customer_id=$1 FOR UPDATE',[DEMO_IDS.sharedCustomer]);await db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=(SELECT record_id FROM profile_revisions WHERE id=$1)',[source.revisionId]);}else await db.query('UPDATE product_gaps SET version=version+1 WHERE id=$1',[gap.recordId]);command=commitGapDecision(actors.mcteer,gap.recordId!,{...envelope(1),previewId:preview.resultId,bindingDigest:preview.bindingDigest}).then(()=>null,error=>error);let blocked=false;for(let i=0;i<50;i++){blocked=Boolean((await db.query("SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND pg_backend_pid()=ANY(pg_blocking_pids(pid)) LIMIT 1")).rowCount);if(blocked)break;await new Promise(r=>setTimeout(r,20));}expect(blocked,change+' writer must hold the acceptance fence').toBe(true);await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}});const result=await command;expect(result).toMatchObject({status:409});expect((await readGap(actors.panel,gap.recordId!)).reviewed).toBeNull();expect((await withGapDatabase(db=>db.query('SELECT 1 FROM gap_decisions WHERE gap_id=$1',[gap.recordId]))).rowCount).toBe(0);}});

});
