import {describe,it,expect} from 'vitest';
import {preparedGapReport,approvedGapReport} from '../fixtures/gaps/reports';
import {gapEnvelope,reviewedSuspectedImpact} from '../fixtures/gaps/authoring';
import {previewGapReportReview,commitGapReportReview} from '../../lib/server/gaps/report-review';
import {admitGapExport,gapExportChunks,cancelGapExport} from '../../lib/server/gaps/report-release';
import {readGapReport} from '../../lib/server/gaps/reports';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
describe('Exact reviewed disclosure and per-chunk release',()=>{
 it('denies drafts, ordinary members and partners before artifact release',async()=>{const f=await preparedGapReport();await expect(admitGapExport(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),format:'json',reviewId:f.receipt.id})).rejects.toMatchObject({status:409});await expect(admitGapExport(f.actors.panel,f.report.id,{...gapEnvelope(f.report.version),format:'json',reviewId:f.receipt.id})).rejects.toMatchObject({status:404});await expect(readGapReport(f.actors.partner,f.report.id)).rejects.toMatchObject({status:404});});
 it('requires exact audience and every included customer before approval',async()=>{const f=await preparedGapReport(),gap=f.gap!;await reviewedSuspectedImpact(f.actors.panel,f.actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);const fresh=await import('../../lib/server/gaps/reports');const receipt=await fresh.prepareGapReport(f.actors.panel,{...f.input,...gapEnvelope(),asOf:new Date().toISOString()}),jobs=await import('../../lib/server/gaps/report-jobs');await jobs.runGapReportJob((await jobs.claimGapReportJobs()).find(j=>j.id===receipt.resultId)!);const report=await readGapReport(f.actors.panel,receipt.recordId!),base={...gapEnvelope(report.version),action:'approve',revisionId:report.revision!.id,customerDisclosures:[],audienceDigest:report.revision!.audienceDigest,rationale:'Synthetic disclosure review',selfReview:false};await expect(previewGapReportReview(f.actors.mcteer,report.id,base)).rejects.toMatchObject({code:'disclosure_required'});await expect(previewGapReportReview(f.actors.mcteer,report.id,{...base,customerDisclosures:[DEMO_IDS.sharedCustomer],audienceDigest:'a'.repeat(64)})).rejects.toMatchObject({code:'stale_version'});});
 it('replays one export and returns JSON/Markdown with identical disclosed scope and approval receipt',async()=>{const f=await approvedGapReport(true);for(const format of ['json','markdown'] as const){const command={...gapEnvelope(f.report.version),format,reviewId:f.report.review!.id},receipt=await admitGapExport(f.actors.mcteer,f.report.id,command);expect(await admitGapExport(f.actors.mcteer,f.report.id,command)).toEqual(receipt);const chunks=[];for await(const chunk of gapExportChunks(f.actors.mcteer,f.report.id,receipt.resultId!))chunks.push(chunk);const text=Buffer.concat(chunks).toString();expect(text).toContain('gap-portfolio-v1');expect(text).not.toContain('objectKey');if(format==='json')expect(JSON.parse(text)).toEqual(f.report.document);}});
 it('stops the next chunk after cancellation and detects exact-store tampering',async()=>{const f=await approvedGapReport(),receipt=await admitGapExport(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),format:'json',reviewId:f.report.review!.id}),iterator=gapExportChunks(f.actors.mcteer,f.report.id,receipt.resultId!,{chunkSize:128});expect((await iterator.next()).value?.length).toBe(128);await cancelGapExport(f.actors.mcteer,f.report.id,receipt.resultId!);await expect(iterator.next()).rejects.toMatchObject({status:409});const other=await admitGapExport(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),format:'markdown',reviewId:f.report.review!.id}),object=(await withGapDatabase(db=>db.query('SELECT o.object_key FROM gap_report_store_objects o JOIN gap_export_artifacts a ON a.object_key=o.object_key WHERE a.revision_id=$1 AND a.format=\'markdown\'',[f.report.revision!.id]))).rows[0],path=join(process.env.TURAS_REPORT_STORE_ROOT!,'objects',object.object_key),original=await readFile(path);await writeFile(path,Buffer.alloc(original.length,65));const broken=gapExportChunks(f.actors.mcteer,f.report.id,other.resultId!);await expect(broken.next()).rejects.toMatchObject({status:503});});
 it('rechecks session authority between chunks without globally withdrawing another member’s report',async()=>{const f=await approvedGapReport(),receipt=await admitGapExport(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),format:'json',reviewId:f.report.review!.id}),iterator=gapExportChunks(f.actors.mcteer,f.report.id,receipt.resultId!,{chunkSize:128});expect((await iterator.next()).done).toBe(false);await withGapDatabase(db=>db.query('UPDATE login_sessions SET revoked_at=clock_timestamp() WHERE id=$1',[f.actors.mcteer.sessionId]));await expect(iterator.next()).rejects.toMatchObject({status:401});expect((await readGapReport(f.actors.panel,f.report.id)).availability).toBe('eligible');});
 it('rejects the next chunk when the reviewed gap changes with maintenance stopped',async()=>{const f=await approvedGapReport(),receipt=await admitGapExport(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),format:'json',reviewId:f.report.review!.id}),iterator=gapExportChunks(f.actors.mcteer,f.report.id,receipt.resultId!,{chunkSize:128});expect((await iterator.next()).done).toBe(false);await withGapDatabase(db=>db.query('UPDATE product_gaps SET version=version+1 WHERE id=$1',[f.gap!.id]));await expect(iterator.next()).rejects.toMatchObject({code:'approval_unavailable'});expect((await readGapReport(f.actors.panel,f.report.id)).document).toBeNull();});
 it('binds previews to a live session and requires explicit review of a changed audience revision',async()=>{const f=await preparedGapReport(),base={...gapEnvelope(f.report.version),action:'approve',revisionId:f.report.revision!.id,customerDisclosures:[],audienceDigest:f.report.revision!.audienceDigest,rationale:'Synthetic exact audience review',selfReview:false},preview=await previewGapReportReview(f.actors.mcteer,f.report.id,base),freshActors=await import('../fixtures/gaps/seed').then(m=>m.gapActors());await expect(commitGapReportReview(freshActors.mcteer,f.report.id,{...gapEnvelope(f.report.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({status:404});const {prepareGapReport}=await import('../../lib/server/gaps/reports');const changed=await prepareGapReport(f.actors.panel,{...f.input,...gapEnvelope(f.report.version),reportId:f.report.id,audience:{...f.input.audience,purpose:'Changed audience purpose'}});await expect(commitGapReportReview(f.actors.mcteer,f.report.id,{...gapEnvelope(f.report.version),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({status:409});const {cancelGapReport}=await import('../../lib/server/gaps/reports');await cancelGapReport(f.actors.panel,f.report.id,gapEnvelope(changed.version));});
});
