import {beforeAll,describe,it,expect} from 'vitest';
import {gapActors} from '../fixtures/gaps/seed';
import {reviewedSyntheticGap,reviewedSuspectedImpact,gapEnvelope} from '../fixtures/gaps/authoring';
import {previewGapCanonicalization,commitGapCanonicalization} from '../../lib/server/gaps/canonicalization';
import {readGap} from '../../lib/server/gaps/service';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
import {syntheticGap} from '../fixtures/gaps/ui';
import {acceptedGapEvidence} from '../fixtures/gaps/evidence';
import {saveGapImpact} from '../../lib/server/gaps/impacts';
import {previewGapDecision,commitGapDecision} from '../../lib/server/gaps/review';
import {submitProfileCommand} from '../../lib/server/profiles/service';
import {syntheticImpact} from '../fixtures/gaps/ui';
import {withGapDatabase} from '../fixtures/gaps/environment';
describe('Explicit atomic canonicalization',()=>{
 let actors:Awaited<ReturnType<typeof gapActors>>;beforeAll(async()=>{actors=await gapActors();});
 async function mergeInput(){const a=await reviewedSyntheticGap(actors.panel,actors.mcteer),b=await reviewedSyntheticGap(actors.panel,actors.mcteer);const x=await reviewedSuspectedImpact(actors.panel,actors.mcteer,a.id,DEMO_IDS.sharedCustomer),y=await reviewedSuspectedImpact(actors.panel,actors.mcteer,b.id,DEMO_IDS.deniedCustomer);return {...gapEnvelope((await readGap(actors.panel,a.id)).version),operation:'merge' as const,gapIds:[a.id,b.id],versions:{[a.id]:(await readGap(actors.panel,a.id)).version,[b.id]:(await readGap(actors.panel,b.id)).version},survivorId:a.id,assignments:[{observationId:x,resultKey:a.id},{observationId:y,resultKey:a.id}],results:[],rationale:'Explicit synthetic duplicate mapping',selfReview:true as const};}
 async function commit(input:Awaited<ReturnType<typeof mergeInput>>){const preview=await previewGapCanonicalization(actors.mcteer,input);return commitGapCanonicalization(actors.mcteer,{...gapEnvelope(input.expectedVersion),previewId:preview.resultId,bindingDigest:preview.bindingDigest});}
 it('merges exhaustive assignments once and redirects authorized aliases',async()=>{const input=await mergeInput(),preview=await previewGapCanonicalization(actors.mcteer,input),command={...gapEnvelope(input.expectedVersion),previewId:preview.resultId,bindingDigest:preview.bindingDigest};const receipt=await commitGapCanonicalization(actors.mcteer,command);expect(await commitGapCanonicalization(actors.mcteer,command)).toEqual(receipt);expect((await readGap(actors.panel,input.survivorId)).impacts.map(i=>i.id).sort()).toEqual(input.assignments.map(a=>a.observationId).sort());expect(await readGap(actors.panel,input.gapIds[1])).toMatchObject({canonicalTarget:input.survivorId});});
 it('denies member review and rejects missing assignments with no partial movement',async()=>{const input=await mergeInput();await expect(previewGapCanonicalization(actors.panel,input)).rejects.toMatchObject({status:404});await expect(previewGapCanonicalization(actors.mcteer,{...input,assignments:input.assignments.slice(0,1)})).rejects.toMatchObject({status:400});expect((await readGap(actors.panel,input.gapIds[1])).impacts).toHaveLength(1);});
 it('rejects stale mapping after a new observation and preserves every original assignment',async()=>{const input=await mergeInput(),preview=await previewGapCanonicalization(actors.mcteer,input);await reviewedSuspectedImpact(actors.panel,actors.mcteer,input.gapIds[1],DEMO_IDS.sharedCustomer);await expect(commitGapCanonicalization(actors.mcteer,{...gapEnvelope(input.expectedVersion),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({code:'stale_version'});expect((await readGap(actors.panel,input.gapIds[0])).impacts).toHaveLength(1);expect((await readGap(actors.panel,input.gapIds[1])).impacts).toHaveLength(2);});
 it('rejects unlike product or kind before accepting a relation',async()=>{const input=await mergeInput(),other=await reviewedSyntheticGap(actors.panel,actors.mcteer,{kind:'documentation'});await expect(previewGapCanonicalization(actors.mcteer,{...input,gapIds:[input.survivorId,other.id],versions:{[input.survivorId]:input.expectedVersion,[other.id]:other.version}})).rejects.toMatchObject({status:400});});
 it('splits into an original survivor and fresh identity with immutable assignment lineage',async()=>{const original=await reviewedSyntheticGap(actors.panel,actors.mcteer),x=await reviewedSuspectedImpact(actors.panel,actors.mcteer,original.id,DEMO_IDS.sharedCustomer),y=await reviewedSuspectedImpact(actors.panel,actors.mcteer,original.id,DEMO_IDS.deniedCustomer),version=(await readGap(actors.panel,original.id)).version;const input={...gapEnvelope(version),operation:'split' as const,gapIds:[original.id],versions:{[original.id]:version},survivorId:original.id,assignments:[{observationId:x,resultKey:'retained'},{observationId:y,resultKey:'new'}],results:[{key:'retained',retainOriginal:true,content:syntheticGap({title:'Retained synthetic capability'}),sourceRefs:[]},{key:'new',retainOriginal:false,content:syntheticGap({title:'Separated synthetic capability'}),sourceRefs:[]}],rationale:'Explicit synthetic split',selfReview:true as const};const preview=await previewGapCanonicalization(actors.mcteer,input);await commitGapCanonicalization(actors.mcteer,{...gapEnvelope(version),previewId:preview.resultId,bindingDigest:preview.bindingDigest});expect((await readGap(actors.panel,original.id)).impacts.map(i=>i.id)).toEqual([x]);const target=(await withGapDatabase(db=>db.query('SELECT canonical_gap_id FROM gap_observation_assignments WHERE observation_id=$1',[y]))).rows[0].canonical_gap_id;expect(target).not.toBe(original.id);expect((await readGap(actors.panel,target)).impacts.map(i=>i.id)).toEqual([y]);expect((await withGapDatabase(db=>db.query('SELECT count(*) FROM gap_assignment_events WHERE observation_id=$1',[y]))).rows[0].count).toBe('2');});
 it('serializes overlapping previews and rejects a cycle through an alias',async()=>{const input=await mergeInput(),first=await previewGapCanonicalization(actors.mcteer,input),second=await previewGapCanonicalization(actors.mcteer,{...input,requestKey:gapEnvelope().requestKey});await commitGapCanonicalization(actors.mcteer,{...gapEnvelope(input.expectedVersion),previewId:first.resultId,bindingDigest:first.bindingDigest});await expect(commitGapCanonicalization(actors.mcteer,{...gapEnvelope(input.expectedVersion),previewId:second.resultId,bindingDigest:second.bindingDigest})).rejects.toMatchObject({code:'stale_version'});const version=(await readGap(actors.panel,input.survivorId)).version;await expect(previewGapCanonicalization(actors.mcteer,{...input,...gapEnvelope(version),versions:{[input.survivorId]:version,[input.gapIds[1]]:(await readGap(actors.panel,input.gapIds[1])).version},survivorId:input.gapIds[1],assignments:input.assignments.map(a=>({...a,resultKey:input.gapIds[1]}))})).rejects.toMatchObject({code:'stale_version'});});
 it('flattens older aliases directly into the new active survivor',async()=>{const input=await mergeInput();await commit(input);const third=await reviewedSyntheticGap(actors.panel,actors.mcteer),survivor=await readGap(actors.panel,input.survivorId);await commit({...input,...gapEnvelope(third.version),gapIds:[third.id,survivor.id],survivorId:third.id,versions:{[third.id]:third.version,[survivor.id]:survivor.version},assignments:input.assignments.map(a=>({...a,resultKey:third.id}))});expect(await readGap(actors.panel,input.gapIds[1])).toMatchObject({canonicalTarget:third.id});expect((await readGap(actors.panel,third.id)).impacts).toHaveLength(2);});
 it('rejects a merge preview after an impact original is withdrawn without changing its observation version',async()=>{
  const input=await mergeInput(),impactId=input.assignments[0].observationId,source=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'corroboration','Synthetic corroborating customer observation');
  const saved=await saveGapImpact(actors.panel,input.survivorId,{...gapEnvelope(2),expectedGapVersion:input.expectedVersion,customerId:DEMO_IDS.sharedCustomer,workloadId:null,engagementId:null,recurrenceParent:null,content:syntheticImpact(),sourceRefs:[source.reference]},impactId);
  const review=await previewGapDecision(actors.mcteer,input.survivorId,{...gapEnvelope(3),target:'impact',impactId,revisionId:saved.resultId,action:'accept',rationale:'Independent synthetic evidence review',revisitDate:null,selfReview:false});
  await commitGapDecision(actors.mcteer,input.survivorId,{...gapEnvelope(3),previewId:review.resultId,bindingDigest:review.bindingDigest});
  const version=(await readGap(actors.panel,input.survivorId)).version,updated={...input,...gapEnvelope(version),versions:{...input.versions,[input.survivorId]:version}},preview=await previewGapCanonicalization(actors.mcteer,updated);
  const record=(await withGapDatabase(db=>db.query('SELECT r.version FROM profile_records r JOIN profile_revisions v ON v.record_id=r.id WHERE v.id=$1',[source.revisionId]))).rows[0];
  await submitProfileCommand(actors.mcteer,DEMO_IDS.sharedCustomer,{action:'retract_revision',requestKey:gapEnvelope().requestKey,revisionId:source.revisionId,expectedRecordVersion:Number(record.version),rationale:'Synthetic original withdrawal'});
  await expect(commitGapCanonicalization(actors.mcteer,{...gapEnvelope(version),previewId:preview.resultId,bindingDigest:preview.bindingDigest})).rejects.toMatchObject({code:'stale_version'});
  expect((await readGap(actors.panel,input.gapIds[1])).canonicalTarget).toBeNull();
 });

});
