import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {withLearningDatabase} from '../fixtures/learning/environment';
import {learningAcceptedOriginal,learningTestActors} from '../fixtures/learning/setup';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
import {createKnowledgeCandidate,submitKnowledgeCandidate} from '../../lib/server/knowledge/service';
import {readLearningCandidate,readLearningCandidateControl,readLearningCandidateOriginal,listLearningCandidates,reviewLearningCandidate,revokeLearningReview} from '../../lib/server/learning/reviews';
import {currentLearningReview} from '../../lib/server/learning/eligibility';
describe('exact administrator reuse grants',()=>{
 it('preserves author boundaries, independently reviews originals and irreversibly revokes grants',()=>withLearningDatabase(async db=>{
  const actors=await learningTestActors(db),lineage=await learningAcceptedOriginal(db,actors.member,actors.admin,DEMO_IDS.sharedCustomer);
  const payload={title:'Synthetic current reuse grant',productVersion:'Unknown',problem:'An observed reusable engineering concern',prerequisites:'Check applicability',solution:'Measure accepted original evidence',reasoning:'Ground decisions in observations',applicability:'Engineering contexts',limitations:'No customer intent claim',validation:'Verify originals'};
  const candidate=await createKnowledgeCandidate(db,actors.member,{idempotencyKey:randomUUID(),customerId:DEMO_IDS.sharedCustomer,payload,lineage:[lineage]});
  await submitKnowledgeCandidate(db,actors.member,candidate.id,{idempotencyKey:randomUUID(),expectedRevision:candidate.revision,expectedDigest:candidate.digest});
  await db.query('UPDATE learning_workspace_state SET enabled=true WHERE workspace_id=$1',[DEMO_IDS.workspace]);
  const view=await readLearningCandidate(actors.member,candidate.id);
  expect((await readLearningCandidateOriginal(actors.admin,candidate.id,lineage.sourceRevisionId)).revisionId).toBe(lineage.sourceRevisionId);
  await expect(readLearningCandidateOriginal(actors.partner,candidate.id,lineage.sourceRevisionId)).rejects.toMatchObject({status:404});
  await expect(readLearningCandidateOriginal(actors.admin,candidate.id,randomUUID())).rejects.toMatchObject({status:404});
  const queue=await listLearningCandidates(actors.member,{limit:1,search:payload.title});
  expect(queue.items).toEqual([expect.objectContaining({id:candidate.id,revisionId:view.revisionId,title:payload.title})]);
  expect(queue.items[0]).not.toHaveProperty('payload');
  await expect(listLearningCandidates(actors.partner,{limit:20})).rejects.toMatchObject({status:403});
  await expect(listLearningCandidates(actors.member,{limit:21})).rejects.toThrow();
  await expect(listLearningCandidates(actors.member,{customerId:DEMO_IDS.sharedCustomer})).rejects.toThrow();
  await expect(readLearningCandidate(actors.partner,candidate.id)).rejects.toMatchObject({status:404});
  const input={contractVersion:'learning-v1',requestId:randomUUID(),expectedVersion:view.revision,revisionId:view.revisionId,contentDigest:view.digest,closureDigest:view.closureDigest,decision:'accept',rightsAttested:true,rationale:'Separately reviewed synthetic original rights and sanitization',checklist:{namesAndDomainsRemoved:true,repositoriesAndLinksRemoved:true,peopleAndCommercialDetailsRemoved:true,identifyingConfigurationAndOutcomesRemoved:true,countsAndCombinedInferenceReviewed:true}};
  await expect(reviewLearningCandidate(actors.member,candidate.id,input)).rejects.toMatchObject({status:403});
  await expect(reviewLearningCandidate(actors.admin,candidate.id,{...input,closureDigest:'a'.repeat(64)})).rejects.toMatchObject({status:409});
  const reviewed=await reviewLearningCandidate(actors.admin,candidate.id,input);
  expect((await reviewLearningCandidate(actors.admin,candidate.id,input)).targetId).toBe(reviewed.targetId);
  await expect(reviewLearningCandidate(actors.admin,candidate.id,{...input,rationale:'Changed replay'})).rejects.toMatchObject({status:409});
  expect((await currentLearningReview(db,actors.member,reviewed.targetId!)).review.id).toBe(reviewed.targetId);
  await db.query('UPDATE learning_workspace_state SET enabled=false WHERE workspace_id=$1',[DEMO_IDS.workspace]);
  await revokeLearningReview(actors.admin,reviewed.targetId!,{contractVersion:'learning-v1',requestId:randomUUID(),expectedVersion:1,rationale:'Synthetic rights withdrawal'});
  await expect(currentLearningReview(db,actors.member,reviewed.targetId!)).rejects.toMatchObject({status:409});
  expect((await db.query("SELECT purge_at-invalidated_at AS delay FROM learning_payload_states WHERE owner_id=$1 AND kind='review'",[reviewed.targetId])).rows[0].delay.days).toBe(1);
  expect((await db.query("SELECT p.content->>'rationale' rationale FROM learning_review_payloads p WHERE p.content->>'revokedReviewId'=$1",[reviewed.targetId])).rows[0].rationale).toBe('Synthetic rights withdrawal');
  await expect(db.query('UPDATE learning_review_states SET revoked_at=NULL WHERE review_id=$1',[reviewed.targetId])).rejects.toMatchObject({code:'23514'});
 }));
});

import {learningScopedFixture} from '../fixtures/learning/setup';
import {decideKnowledgeCandidate,reviseKnowledgeCandidate,withdrawKnowledge} from '../../lib/server/knowledge/service';
import {activateLearning} from '../../scripts/learning-activate';
import {requireOwnedLearningDatabase} from '../../scripts/learning-environment';
import {prepareLearningRollback} from '../../lib/server/learning/rollback';
import {withTransaction} from '../../lib/server/db/client';
import {readLearningRequest} from '../../lib/server/learning/commands';
it('withdraws the actual published head with a newer draft and restores words only as a new proposed revision',()=>withLearningDatabase(async db=>{
 const {actors,workspaceId,customerId}=await learningScopedFixture(db),lineage=await learningAcceptedOriginal(db,actors.member,actors.admin,customerId),payload={title:'Synthetic rollback practice',productVersion:'Unknown',problem:'An observed reusable concern',prerequisites:'Check applicability',solution:'Measure accepted evidence',reasoning:'Use independently observed facts',applicability:'Engineering workflows',limitations:'No causal claim',validation:'Verify originals'};
 const created=await createKnowledgeCandidate(db,actors.member,{idempotencyKey:randomUUID(),customerId,payload,lineage:[lineage]});await submitKnowledgeCandidate(db,actors.member,created.id,{idempotencyKey:randomUUID(),expectedRevision:1,expectedDigest:created.digest});
 const published=await decideKnowledgeCandidate(db,actors.admin,created.id,{idempotencyKey:randomUUID(),expectedRevision:1,expectedDigest:created.digest,action:'publish',rightsAttested:true,sanitizationRationale:'Reviewed synthetic historical practice',checklist:{namesAndDomainsRemoved:true,repositoriesAndLinksRemoved:true,peopleAndCommercialDetailsRemoved:true,identifyingConfigurationAndOutcomesRemoved:true,countsAndCombinedInferenceReviewed:true}});
 await activateLearning(process.env.TURAS_ENVIRONMENT_ID!,workspaceId,true,requireOwnedLearningDatabase(process.env,true));
 await reviseKnowledgeCandidate(db,actors.member,created.id,{idempotencyKey:randomUUID(),expectedRevision:1,expectedDigest:created.digest,payload:{...payload,title:'Synthetic newer private working draft'},lineage:[lineage]});
 const head=(await db.query('SELECT id,head_generation FROM knowledge_publications WHERE contribution_id=$1',[created.id])).rows[0];await activateLearning(process.env.TURAS_ENVIRONMENT_ID!,workspaceId,false,requireOwnedLearningDatabase(process.env,true));
 expect(await readLearningCandidateControl(actors.admin,created.id)).toMatchObject({revision:2,enabled:false,activated:true,publication:{id:head.id,revision:1,generation:1,digest:created.digest}});
 await expect(readLearningCandidateControl(actors.member,created.id)).rejects.toMatchObject({status:403});
 await expect(readLearningCandidateControl(actors.partner,created.id)).rejects.toMatchObject({status:403});
 const withdrawalKey=randomUUID();await withTransaction(client=>withdrawKnowledge(client,actors.admin,head.id,{idempotencyKey:withdrawalKey,expectedRevision:1,expectedDigest:created.digest,expectedPublicationGeneration:Number(head.head_generation),rationale:'Withdraw the actual published practice while retaining a newer draft'}));
 expect(await readLearningRequest(actors.admin,withdrawalKey)).toMatchObject({outcome:'committed',action:'release.withdraw',version:2});
 expect((await db.query('SELECT state,head_generation FROM knowledge_publications WHERE id=$1',[head.id])).rows[0]).toMatchObject({state:'withdrawn',head_generation:'2'});
 await activateLearning(process.env.TURAS_ENVIRONMENT_ID!,workspaceId,true,requireOwnedLearningDatabase(process.env,true));
 const input={contractVersion:'learning-v1',requestId:randomUUID(),expectedVersion:2,historicalRevisionId:published.revisionId,lineage:[lineage],rationale:'Prepare a separately reviewed rollback proposal'};
 await expect(prepareLearningRollback(actors.partner,created.id,input)).rejects.toMatchObject({status:403});const rollback=await prepareLearningRollback(actors.admin,created.id,input);expect(rollback.version).toBe(3);expect((await prepareLearningRollback(actors.admin,created.id,input)).version).toBe(3);
 expect((await db.query('SELECT state,current_revision_number FROM knowledge_contributions WHERE id=$1',[created.id])).rows[0]).toMatchObject({state:'draft',current_revision_number:3});expect((await db.query('SELECT state,head_generation FROM knowledge_publications WHERE id=$1',[head.id])).rows[0]).toMatchObject({state:'withdrawn',head_generation:'2'});expect((await db.query('SELECT count(*)::int n FROM learning_release_decisions WHERE contribution_id=$1',[created.id])).rows[0].n).toBe(0);
}));
