import {fenceLearningActor} from '../../lib/server/learning/invalidation';
import { randomUUID } from 'node:crypto';
import { describe,it,expect } from 'vitest';
import { withLearningDatabase } from '../fixtures/learning/environment';
import { learningTestActors,learningAcceptedOriginal } from '../fixtures/learning/setup';
import { DEMO_IDS } from '../../lib/server/bootstrap-ids';
import { prepareLearningDraft,learningDraftMeta } from '../../lib/server/learning/advisory';
import { captureLearningDraftContext } from '../../lib/server/learning/context';
import { conversationFeature } from '../../lib/server/conversations/feature';
import { prepareAttempt } from '../../lib/server/conversations/dispatch';
import { prepareLearningNativeAttempt,claimLearningNativeDispatch } from '../../lib/server/learning/native';
import { learningDraftPrompt } from '../../lib/server/learning/context';
import { readLearningDraftInitialContext } from '../../lib/server/learning/native-context';
import { admitLearningDraftModelStep,assertLearningDraftProviderRelease } from '../../lib/server/learning/native-admission';
import { projectLearningNativeEventInTransaction } from '../../lib/server/learning/native-events';
import type { wrapLanguageModel } from 'ai';
import { readLearningDraft,saveLearningDraft } from '../../lib/server/learning/drafts';
import { runLearningRead } from '../../lib/server/learning/tools';
import { staffingResponseScope } from '../../lib/server/staffing/native-context';
import { admitGovernedStaffingModelStep,assertGovernedStaffingProviderRelease } from '../../lib/server/staffing/native-admission';
import { wrapStaffingModel } from '../../lib/server/staffing/model-budget';
import { prepareGovernedNativeRelease,assertGovernedNativeRelease } from '../../lib/server/conversations/native-release';
import { listLearningOriginals } from '../../lib/server/learning/catalog';

describe('governed learning draft preparation',()=>{
 it('captures exact originals, reserves no paid dispatch, and fences replay after source withdrawal',()=>withLearningDatabase(async db=>{
  const actors=await learningTestActors(db),lineage=await learningAcceptedOriginal(db,actors.member,actors.admin,DEMO_IDS.sharedCustomer);
  const previous=process.env.TURAS_014_PRICE_CONTRACT;
  process.env.TURAS_014_PRICE_CONTRACT=JSON.stringify({version:'learning-price-v1',modelId:'spacexai/grok-4.7',inputMicroUsdPerMillion:'8000000',outputMicroUsdPerMillion:'24000000',providerInputLimit:500000,providerOutputLimit:500000,hardOutputCapIncludesReasoning:true,pricingSource:'https://ai-gateway.vercel.sh/v1/models',outputContractSource:'https://vercel.com/ai-gateway/models/grok-4.7',pricingCaptureDigest:'a'.repeat(64),outputContractCaptureDigest:'b'.repeat(64),verifiedAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()});
  await db.query('UPDATE learning_workspace_state SET enabled=true WHERE workspace_id=$1',[DEMO_IDS.workspace]);
  try{
   const input={contractVersion:'learning-v1' as const,requestId:randomUUID(),expectedVersion:0 as const,customerId:DEMO_IDS.sharedCustomer,lineage:[lineage],feedbackIds:[],question:'Draft a reusable practice from this accepted observation',budgetUsd:'25'};
   const context=await captureLearningDraftContext(db,actors.member,input);
   expect((await listLearningOriginals(actors.member,input.customerId,{})).items.some(source=>source.sourceRevisionId===lineage.sourceRevisionId)).toBe(true);
   expect(context.sourceMap.map(s=>s.key)).toEqual(['original-1']);
   await expect(prepareLearningDraft(actors.member,{...input,requestId:randomUUID(),budgetUsd:'10'})).rejects.toMatchObject({status:409,code:'budget_insufficient'});
   await expect(prepareLearningDraft(actors.partner,input)).rejects.toMatchObject({status:403});
   const receipt=await prepareLearningDraft(actors.member,input);
   expect((await prepareLearningDraft(actors.member,input)).targetId).toBe(receipt.targetId);
   const meta=await learningDraftMeta(actors.member,receipt.targetId!);
   expect(meta.state).toBe('prepared');
   expect((await conversationFeature(db,meta.conversationId)).kind).toBe('learning');
   await expect(prepareAttempt(actors.member,meta.conversationId,'synthetic-unbound-session',randomUUID(),'Ordinary send')).rejects.toMatchObject({status:409});
   expect(Number((await db.query('SELECT count(*) FROM learning_budget_reservations WHERE budget_id=$1',[meta.budgetId])).rows[0].count)).toBe(0);
   await expect(learningDraftMeta(actors.admin,receipt.targetId!)).rejects.toMatchObject({status:404});
   await expect(prepareLearningDraft(actors.member,{...input,question:'Changed replay input'})).rejects.toMatchObject({status:409});
   const nativeSessionId=`synthetic-learning-${randomUUID()}`,turnId=`synthetic-turn-${randomUUID()}`;
   await db.query("UPDATE conversations SET binding_state='bound',eve_session_id=$2 WHERE id=$1",[meta.conversationId,nativeSessionId]);
   await db.query("INSERT INTO maintenance_workers(environment_id,worker_id,last_seen_at) VALUES($1,'learning-domain-fixture',clock_timestamp()) ON CONFLICT(environment_id,worker_id) DO UPDATE SET last_seen_at=excluded.last_seen_at",[process.env.TURAS_ENVIRONMENT_ID]);
   const native=await prepareLearningNativeAttempt(actors.member,meta.conversationId,nativeSessionId,meta.nativeRequestId,learningDraftPrompt,false);
   await claimLearningNativeDispatch(actors.member,meta.conversationId,native.attemptId,0);
   const event=(type:string,data:Record<string,unknown>)=>({type,meta:{id:`evt_learning_${randomUUID().replaceAll('-','')}`,at:new Date().toISOString()},data:{turnId,...data}});
   await projectLearningNativeEventInTransaction(db,nativeSessionId,native.attemptId,event('message.received',{message:learningDraftPrompt}));
   const principal={principalId:actors.member.principalId,attributes:{turasAttemptId:native.attemptId}},identity={nativeSessionId,responseAttemptId:native.attemptId,turnId,stepIndex:0};
   await expect(admitLearningDraftModelStep(principal,identity)).rejects.toMatchObject({status:409});
   await readLearningDraftInitialContext(principal,turnId,nativeSessionId);
   const summaryCall=randomUUID();
   await runLearningRead(principal,'learning_summary',{},summaryCall);
   await runLearningRead(principal,'learning_summary',{},summaryCall);
   expect(Number((await db.query('SELECT read_calls FROM learning_attempts WHERE id=$1',[meta.id])).rows[0].read_calls)).toBe(1);
   await expect(runLearningRead(principal,'learning_evidence',{sourceKeys:['feedback-1']},randomUUID())).rejects.toMatchObject({status:404});
   await runLearningRead(principal,'learning_evidence',{sourceKeys:['original-1']},randomUUID());
   expect(await runLearningRead(principal,'load_skill',{skill:'governed-learning'},randomUUID())).toContain('Human review');
   for(let i=0;i<3;i++)await runLearningRead(principal,'learning_summary',{},randomUUID());
   await expect(runLearningRead(principal,'learning_summary',{},randomUUID())).rejects.toMatchObject({status:429});
   expect(await staffingResponseScope(principal)).toMatchObject({purpose:'draft'});
   const admitted=await admitGovernedStaffingModelStep(principal,identity);
   expect(admitted.mode).toBe('learning');
   await expect(admitLearningDraftModelStep(principal,identity)).rejects.toMatchObject({status:409});
   const output={contractVersion:'learning-v1',proposal:{title:'Synthetic draft',productVersion:'Unknown',problem:'An observed delivery concern',prerequisites:'Verify current applicability',solution:'Measure accepted delivery evidence',reasoning:'Use independent observations',applicability:'Reviewed delivery contexts',limitations:'Does not establish commercial intent',validation:'Check originals'},citationKeys:['original-1'],unknowns:['Applicability remains to be reviewed'],intendedImprovement:'Explain the accepted observation clearly'};
   const model={specificationVersion:'v4',provider:'synthetic',modelId:'spacexai/grok-4.7',supportedUrls:{},doGenerate:async()=>({content:[{type:'text',text:JSON.stringify(output)}],finishReason:'stop',usage:{inputTokens:{total:100},outputTokens:{total:200}},providerMetadata:{gateway:{cost:'0.001',generationId:'synthetic-domain-generation'}},warnings:[]})} as unknown as Parameters<typeof wrapLanguageModel>[0]['model'];
   await wrapStaffingModel(model,admitted.mode,{deadlineAt:admitted.deadlineAt,beforeProvider:()=>assertGovernedStaffingProviderRelease(principal,identity)}).doGenerate({prompt:[]});
   await expect(assertLearningDraftProviderRelease(principal,identity)).rejects.toBeDefined();
   await projectLearningNativeEventInTransaction(db,nativeSessionId,native.attemptId,event('message.completed',{message:JSON.stringify(output),finishReason:'stop'}));
   await projectLearningNativeEventInTransaction(db,nativeSessionId,native.attemptId,event('turn.completed',{}));
   const captured=await readLearningDraft(actors.member,meta.id);
   const release=await prepareGovernedNativeRelease(meta.conversationId,{actor:actors.member});
   expect(release?.kind).toBe('learning');expect((await assertGovernedNativeRelease(db,release!,actors.member)).actor.principalId).toBe(actors.member.principalId);
   const save={contractVersion:'learning-v1',requestId:randomUUID(),expectedVersion:captured.version,outputDigest:captured.outputDigest,proposalIndex:0,payload:output.proposal};
   await expect(saveLearningDraft(actors.member,meta.id,{...save,payload:{...output.proposal,solution:'Edited unsupported fact'}})).rejects.toMatchObject({status:409});
   const saved=await saveLearningDraft(actors.member,meta.id,save);
   expect((await saveLearningDraft(actors.member,meta.id,{...save,requestId:randomUUID()})).targetId).toBe(saved.targetId);
   const actorLost=await prepareLearningDraft(actors.member,{...input,requestId:randomUUID()});
   const publicationBefore=(await db.query("SELECT id,state,head_generation FROM knowledge_publications WHERE state='published' ORDER BY id")).rows;
   await fenceLearningActor(db,actors.member.workspaceId,actors.member.membershipId);
   expect((await db.query('SELECT state FROM learning_attempts WHERE id=$1',[actorLost.targetId])).rows[0].state).toBe('invalidated');
   expect((await db.query("SELECT invalidated_at,obsolete_at FROM learning_payload_states WHERE owner_id=$1 AND kind='attempt'",[actorLost.targetId])).rows[0]).toMatchObject({invalidated_at:null,obsolete_at:expect.any(Date)});
   expect((await db.query("SELECT id,state,head_generation FROM knowledge_publications WHERE state='published' ORDER BY id")).rows).toEqual(publicationBefore);
   await db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=(SELECT record_id FROM profile_revisions WHERE id=$1)',[lineage.sourceRevisionId]);
   await expect(prepareLearningDraft(actors.member,input)).rejects.toMatchObject({status:404});
  }finally{
   await db.query('UPDATE learning_workspace_state SET enabled=false WHERE workspace_id=$1',[DEMO_IDS.workspace]);
   if(previous===undefined)delete process.env.TURAS_014_PRICE_CONTRACT;else process.env.TURAS_014_PRICE_CONTRACT=previous;
  }
 }));
});
