import {describe,it,expect,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {partnerGuideFixture,partnerCommandEnvelope} from "../fixtures/partners/guides";
import {withPartnerDatabase} from "../fixtures/partners/environment";
import {readPartnerGuide} from "../../lib/server/partners/guides";
import {runPartnerMaintenanceTick} from "../../lib/server/partners/maintenance";
import {DEMO_IDS} from "../../lib/server/bootstrap-ids";
import {readPartnerRequest} from "../../lib/server/partners/receipts";
describe("partner retention and recovery fences",()=>{
 it("backs off an interrupted purge without extending its original deletion deadline",async()=>{
  const f=await partnerGuideFixture("Synthetic interrupted purge",true);await withPartnerDatabase(async db=>{await db.query("UPDATE partner_guide_revision_states SET invalidated_at=clock_timestamp()-interval '2 days',purge_at=clock_timestamp()-interval '1 day' WHERE revision_id=$1",[f.revisionId]);await db.query("CREATE FUNCTION turas_test_013_purge_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic purge interruption';END $$");await db.query("CREATE TRIGGER turas_test_013_purge_failure BEFORE DELETE ON partner_guide_payloads FOR EACH ROW EXECUTE FUNCTION turas_test_013_purge_failure()");});
  try{await expect(runPartnerMaintenanceTick()).rejects.toThrow();const first=await withPartnerDatabase(async db=>(await db.query("SELECT purge_at,attempts,next_attempt_at FROM partner_cleanup_jobs WHERE revision_id=$1",[f.revisionId])).rows[0]);expect(first.attempts).toBe(1);expect(first.next_attempt_at.getTime()-Date.now()).toBeGreaterThan(55000);const health=await runPartnerMaintenanceTick();expect(health.overdue).toBeGreaterThanOrEqual(1);await withPartnerDatabase(async db=>{const next=(await db.query("SELECT purge_at,attempts FROM partner_cleanup_jobs WHERE revision_id=$1",[f.revisionId])).rows[0];expect(next.purge_at).toEqual(first.purge_at);expect(next.attempts).toBe(1);expect((await db.query("SELECT 1 FROM partner_guide_payloads WHERE revision_id=$1",[f.revisionId])).rowCount).toBe(1);});}finally{await withPartnerDatabase(async db=>{await db.query("DROP TRIGGER turas_test_013_purge_failure ON partner_guide_payloads");await db.query("DROP FUNCTION turas_test_013_purge_failure()");});}
  await withPartnerDatabase(db=>db.query("UPDATE partner_cleanup_jobs SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE revision_id=$1",[f.revisionId]));await runPartnerMaintenanceTick();await withPartnerDatabase(async db=>{expect((await db.query("SELECT 1 FROM partner_guide_payloads WHERE revision_id=$1",[f.revisionId])).rowCount).toBe(0);expect((await db.query("SELECT completed_at FROM partner_cleanup_jobs WHERE revision_id=$1",[f.revisionId])).rows[0].completed_at).toBeInstanceOf(Date);});
 });
 it("withholds expired evidence without maintenance and records its exact original expiry",async()=>{
  const f=await partnerGuideFixture("Synthetic expired source retention",true),expiry=new Date(f.evidence!.reference.quality.validUntil);await withPartnerDatabase(db=>db.query("UPDATE login_sessions SET expires_at=$1 WHERE id=$2",[new Date(expiry.getTime()+3600000),f.partner.sessionId]));vi.useFakeTimers({toFake:["Date"]});vi.setSystemTime(new Date(expiry.getTime()+1000));try{expect((await readPartnerGuide(f.partner,f.guideId)).content).toBeNull();await runPartnerMaintenanceTick();const state=await withPartnerDatabase(async db=>(await db.query("SELECT invalidated_at,purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[f.revisionId])).rows[0]);expect(state.invalidated_at).toEqual(expiry);expect(state.purge_at.getTime()).toBe(expiry.getTime()+86400000);}finally{vi.useRealTimers();}
 });
 it("prevents deadline extension and minimizes old decisions and all request outcomes without reusing identities",async()=>{
  const f=await partnerGuideFixture("Synthetic minimized audit retention",true),requestId=randomUUID();await readPartnerRequest(f.partner,requestId,true);
  await withPartnerDatabase(async db=>{
   await db.query("UPDATE partner_guide_revision_states SET obsolete_at=clock_timestamp(),purge_at=clock_timestamp()+interval '90 days' WHERE revision_id=$1",[f.revisionId]);
   await expect(db.query("UPDATE partner_guide_revision_states SET purge_at=purge_at+interval '1 day' WHERE revision_id=$1",[f.revisionId])).rejects.toMatchObject({code:"23514"});
   await expect(db.query("UPDATE partner_guide_revision_states SET purge_at=NULL WHERE revision_id=$1",[f.revisionId])).rejects.toMatchObject({code:"23514"});
   await db.query("BEGIN");try{await db.query("SELECT set_config('turas.partner_cleanup','yes',true)");await db.query("UPDATE partner_review_decisions SET created_at=clock_timestamp()-interval '366 days' WHERE guide_id=$1",[f.guideId]);await db.query("UPDATE partner_commands SET retire_at=clock_timestamp()-interval '1 day' WHERE request_id=$1",[requestId]);await db.query("COMMIT");}catch(error){await db.query("ROLLBACK");throw error;}
  });
  await runPartnerMaintenanceTick();await withPartnerDatabase(async db=>{const d=(await db.query("SELECT reviewer_membership_id,created_at,minimized FROM partner_review_decisions WHERE guide_id=$1",[f.guideId])).rows[0];expect(d).toEqual({reviewer_membership_id:null,created_at:null,minimized:true});const r=(await db.query("SELECT outcome,actor_membership_id,created_at,target_id,version FROM partner_commands WHERE request_id=$1",[requestId])).rows[0];expect(r).toEqual({outcome:"retired",actor_membership_id:null,created_at:null,target_id:null,version:null});});
  expect((await readPartnerRequest(f.partner,requestId,true)).outcome).toBe("retired");
 });
 it("records the authoritative original withdrawal and never extends its deadline or restores withdrawn prose",async()=>{
  const f=await partnerGuideFixture("Synthetic terminal source retention",true);await withPartnerDatabase(db=>db.query("UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=$1",[f.evidence!.recordId]));
  const before=await withPartnerDatabase(async db=>(await db.query("SELECT invalidated_at,purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[f.revisionId])).rows[0]);expect(before.invalidated_at).toBeInstanceOf(Date);expect(before.purge_at.getTime()-before.invalidated_at.getTime()).toBeLessThanOrEqual(86400001);
  await withPartnerDatabase(db=>db.query("UPDATE profile_records SET current_accepted_revision_id=$1 WHERE id=$2",[f.evidence!.revisionId,f.evidence!.recordId]));expect((await readPartnerGuide(f.partner,f.guideId)).content).toBeNull();
  await runPartnerMaintenanceTick();await runPartnerMaintenanceTick();const after=await withPartnerDatabase(async db=>(await db.query("SELECT purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[f.revisionId])).rows[0]);expect(after.purge_at).toEqual(before.purge_at);
 });
 it("keeps otherwise eligible team guides after an individual's grant loss and runs while disabled",async()=>{
  const f=await partnerGuideFixture("Synthetic retained team guide",true);await withPartnerDatabase(db=>db.query("UPDATE customer_grants SET state='revoked',revision=revision+1 WHERE membership_id=$1 AND customer_id=$2",[f.partner.membershipId,DEMO_IDS.sharedCustomer]));const previous=process.env.TURAS_013_DISABLED;process.env.TURAS_013_DISABLED="1";try{await runPartnerMaintenanceTick();expect((await readPartnerGuide(f.author,f.guideId)).content?.title).toBe(f.content.title);const row=await withPartnerDatabase(async db=>(await db.query("SELECT purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[f.revisionId])).rows[0]);expect(row.purge_at).toBeNull();}finally{await withPartnerDatabase(db=>db.query("UPDATE customer_grants SET state='active',revision=revision+1 WHERE membership_id=$1 AND customer_id=$2",[f.partner.membershipId,DEMO_IDS.sharedCustomer]));if(previous===undefined)delete process.env.TURAS_013_DISABLED;else process.env.TURAS_013_DISABLED=previous;}
 });
 it("purges due immutable payloads through the narrow owner function and retains minimal identities",async()=>{
  const f=await partnerGuideFixture("Synthetic due payload retention",true);await withPartnerDatabase(db=>db.query("UPDATE partner_guide_revision_states SET invalidated_at=clock_timestamp()-interval '2 days',purge_at=clock_timestamp()-interval '1 day' WHERE revision_id=$1",[f.revisionId]));await runPartnerMaintenanceTick();await withPartnerDatabase(async db=>{expect((await db.query("SELECT 1 FROM partner_guide_payloads WHERE revision_id=$1",[f.revisionId])).rowCount).toBe(0);expect((await db.query("SELECT 1 FROM partner_guide_revisions WHERE id=$1",[f.revisionId])).rowCount).toBe(1);});expect((await readPartnerGuide(f.partner,f.guideId)).content).toBeNull();
 });
});
