import {describe,it,expect} from "vitest";
import {randomUUID} from "node:crypto";
import {partnerGuideFixture,partnerCommandEnvelope} from "../fixtures/partners/guides";
import {withPartnerDatabase} from "../fixtures/partners/environment";
import {partnerAcceptedEvidence} from "../fixtures/partners/originals";
import {partnerAdditionalMember} from "../fixtures/partners/seed";
import {DEMO_IDS} from "../../lib/server/bootstrap-ids";
import {previewPartnerAssignment,decidePartnerAssignment,readPartnerAssignment,readPartnerAttemptHistory} from "../../lib/server/partners/assignments";
import {writePartnerCheckpoint,previewPartnerCheckpoint,decidePartnerCheckpoint} from "../../lib/server/partners/submissions";
async function assign(f:Awaited<ReturnType<typeof partnerGuideFixture>>){const input={...partnerCommandEnvelope(),action:"assignment.create",guideId:f.guideId,revisionId:f.revisionId,membershipId:f.partner.membershipId,rationale:"Assign the exact reviewed demonstration",selfReview:false},preview=await previewPartnerAssignment(f.reviewer,input);return decidePartnerAssignment(f.reviewer,{...input,requestId:randomUUID(),previewId:preview.previewId});}
describe("individual reviewed partner learning",()=>{
 it("removes dependent verification when prerequisite evidence is withdrawn with maintenance stopped",async()=>{
  const f=await partnerGuideFixture("Synthetic prerequisite evidence lifecycle",true,undefined,undefined,content=>({...content,checkpoints:[content.checkpoints[0],{...content.checkpoints[0],id:randomUUID(),order:2,title:"Demonstrate the dependent practice",prerequisiteIds:[content.checkpoints[0].id]}]})),assigned=await assign(f),id=assigned.targetId!;
  const original=await partnerAcceptedEvidence(f.author,f.reviewer,DEMO_IDS.sharedCustomer,"Synthetic independent prerequisite demonstration"),dependent=await partnerAcceptedEvidence(f.author,f.reviewer,DEMO_IDS.sharedCustomer,"Synthetic independent dependent demonstration");
  for(const [index,cp] of f.content.checkpoints.entries()){
   const before=await readPartnerAssignment(f.partner,id),draft=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:cp.id,expectedVersion:before.version,content:{attempted:"Synthetic separately evidenced demonstrated practice",result:"Synthetic independently accepted demonstration",blockers:[],observedAt:new Date(Date.now()-1000).toISOString(),sources:[(index?dependent:original).reference]}}),attempt=(await readPartnerAssignment(f.partner,id)).checkpoints[index].attempts[0];
   const submitted=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.submit",assignmentId:id,checkpointId:cp.id,attemptId:attempt.attemptId,revisionId:attempt.revisionId,contentDigest:attempt.contentDigest,expectedVersion:draft.version!}),input={...partnerCommandEnvelope(),action:"checkpoint.verify",assignmentId:id,checkpointId:cp.id,attemptId:attempt.attemptId,revisionId:attempt.revisionId,contentDigest:attempt.contentDigest,expectedVersion:submitted.version!,rationale:"Accepted independent source supports this demonstration",selfReview:false},preview=await previewPartnerCheckpoint(f.reviewer,input);
   await decidePartnerCheckpoint(f.reviewer,{...input,requestId:randomUUID(),previewId:preview.previewId});
  }
  expect((await readPartnerAssignment(f.partner,id)).progress).toEqual({verifiedRequired:2,totalRequired:2,percentage:100});
  await withPartnerDatabase(db=>db.query("UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=$1",[original.recordId]));
  const current=await readPartnerAssignment(f.partner,id);expect(current.availability).toBe("eligible");expect(current.progress).toEqual({verifiedRequired:0,totalRequired:2,percentage:0});expect(current.checkpoints[0].attempts[0].content).toBeNull();
 });

 it("appends immutable draft revisions and refuses verification without separately accepted proof",async()=>{
  const f=await partnerGuideFixture("Synthetic unproven demonstration",true),assigned=await assign(f),id=assigned.targetId!;
  const body={attempted:"Synthetic unproven attempted practice",result:"The author's assertion cannot establish accepted proof",blockers:["Awaiting independently accepted evidence"],observedAt:new Date(Date.now()-1000).toISOString(),sources:[]};
  const first=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:assigned.version!,content:body});
  const original=(await readPartnerAssignment(f.partner,id)).checkpoints[0].attempts[0];
  const second=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:first.version!,content:{...body,result:"Synthetic revised unproven assertion"}});
  const revised=(await readPartnerAssignment(f.partner,id)).checkpoints[0].attempts[0];expect(revised.attemptId).toBe(original.attemptId);expect(revised.revisionId).not.toBe(original.revisionId);
  await withPartnerDatabase(async db=>{expect((await db.query("SELECT content->>'result' AS result FROM partner_checkpoint_payloads WHERE revision_id=$1",[original.revisionId])).rows[0].result).toBe(body.result);await expect(db.query("UPDATE partner_checkpoint_payloads SET content='{}' WHERE revision_id=$1",[original.revisionId])).rejects.toMatchObject({code:"23514"});});
  const submitted=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.submit",assignmentId:id,checkpointId:f.checkpointId,attemptId:revised.attemptId,revisionId:revised.revisionId,contentDigest:revised.contentDigest,expectedVersion:second.version!});
  await expect(previewPartnerCheckpoint(f.reviewer,{...partnerCommandEnvelope(),action:"checkpoint.verify",assignmentId:id,checkpointId:f.checkpointId,attemptId:revised.attemptId,revisionId:revised.revisionId,contentDigest:revised.contentDigest,expectedVersion:submitted.version!,rationale:"Author text alone is not accepted proof",selfReview:false})).rejects.toMatchObject({status:409});
  expect((await readPartnerAssignment(f.partner,id)).progress?.percentage).toBe(0);
 });
 it("keeps attempts private, appends corrections and counts only separately accepted verified demonstrations",async()=>{
  const f=await partnerGuideFixture("Synthetic private learning",true),assigned=await assign(f),id=assigned.targetId!,initial=await readPartnerAssignment(f.partner,id);expect(initial.progress).toEqual({verifiedRequired:0,totalRequired:1,percentage:0});
  const other=await withPartnerDatabase(db=>partnerAdditionalMember(db,DEMO_IDS.sharedCustomer));await expect(readPartnerAssignment(other,id)).rejects.toMatchObject({status:404});
  const body={attempted:"Synthetic demonstrated delivery practice",result:"Synthetic independently accepted demonstration",blockers:[],observedAt:new Date(Date.now()-1000).toISOString(),sources:[f.evidence!.reference]};
  const draft=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:initial.version,content:body});const view=await readPartnerAssignment(f.partner,id),attempt=view.checkpoints[0].attempts[0];expect(attempt.content?.result).toBe(body.result);
  await expect(writePartnerCheckpoint(f.author,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:draft.version!,content:body})).rejects.toMatchObject({status:403});
  const submitted=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.submit",assignmentId:id,checkpointId:f.checkpointId,attemptId:attempt.attemptId,revisionId:attempt.revisionId,contentDigest:attempt.contentDigest,expectedVersion:draft.version!});
  await expect(writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:submitted.version!,content:body})).rejects.toMatchObject({status:409});
  const review={...partnerCommandEnvelope(),action:"checkpoint.request_changes",assignmentId:id,checkpointId:f.checkpointId,attemptId:attempt.attemptId,revisionId:attempt.revisionId,contentDigest:attempt.contentDigest,expectedVersion:submitted.version!,rationale:"Clarify the independently accepted result",selfReview:false},preview=await previewPartnerCheckpoint(f.reviewer,review),changed=await decidePartnerCheckpoint(f.reviewer,{...review,requestId:randomUUID(),previewId:preview.previewId});
  const corrected=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:changed.version!,content:{...body,result:"Synthetic corrected independently accepted result"}}),correctedView=await readPartnerAssignment(f.partner,id),newAttempt=correctedView.checkpoints[0].attempts[0];expect(newAttempt.attemptId).not.toBe(attempt.attemptId);expect(correctedView.checkpoints[0].attempts).toHaveLength(2);const history=await readPartnerAttemptHistory(f.partner,id,{checkpointId:f.checkpointId,limit:1});expect(history.items[0].content?.result).toBe("Synthetic corrected independently accepted result");expect(history.nextCursor).toBeTruthy();const earlier=await readPartnerAttemptHistory(f.partner,id,{checkpointId:f.checkpointId,limit:1,cursor:history.nextCursor});expect(earlier.items[0].content?.result).toBe(body.result);expect(earlier.items[0].decision?.action).toBe("request_changes");await expect(readPartnerAttemptHistory(other,id,{checkpointId:f.checkpointId,limit:1,cursor:history.nextCursor})).rejects.toMatchObject({status:404});
  const submittedAgain=await writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.submit",assignmentId:id,checkpointId:f.checkpointId,attemptId:newAttempt.attemptId,revisionId:newAttempt.revisionId,contentDigest:newAttempt.contentDigest,expectedVersion:corrected.version!}),verify={...review,requestId:randomUUID(),action:"checkpoint.verify",attemptId:newAttempt.attemptId,revisionId:newAttempt.revisionId,contentDigest:newAttempt.contentDigest,expectedVersion:submittedAgain.version!,rationale:"Exact accepted evidence supports the demonstrated criterion"},ready=await previewPartnerCheckpoint(f.reviewer,verify),competing=await previewPartnerCheckpoint(f.reviewer,{...verify,requestId:randomUUID()}),decisions=await Promise.allSettled([decidePartnerCheckpoint(f.reviewer,{...verify,requestId:randomUUID(),previewId:ready.previewId}),decidePartnerCheckpoint(f.reviewer,{...verify,requestId:randomUUID(),previewId:competing.previewId})]);expect(decisions.filter(d=>d.status==="fulfilled")).toHaveLength(1);expect(decisions.find(d=>d.status==="rejected")).toMatchObject({reason:{status:409}});const verified=(decisions.find(d=>d.status==="fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof decidePartnerCheckpoint>>>).value;expect((await readPartnerAssignment(f.partner,id)).progress).toEqual({verifiedRequired:1,totalRequired:1,percentage:100});
  await expect(writePartnerCheckpoint(f.partner,{...partnerCommandEnvelope(),action:"checkpoint.save",assignmentId:id,checkpointId:f.checkpointId,expectedVersion:verified.version!,content:body})).rejects.toMatchObject({status:409});
 });
 it("blocks reviewer writes after target revocation and requires explicit replacement after regrant",async()=>{
  const f=await partnerGuideFixture("Synthetic authority replacement",true),assigned=await assign(f),id=assigned.targetId!;await withPartnerDatabase(db=>db.query("UPDATE customer_grants SET state='revoked',revision=revision+1 WHERE membership_id=$1 AND customer_id=$2",[f.partner.membershipId,DEMO_IDS.sharedCustomer]));
  const withdraw={...partnerCommandEnvelope(),action:"assignment.withdraw",assignmentId:id,expectedVersion:assigned.version!,rationale:"Withdraw revoked target",selfReview:false};await expect(previewPartnerAssignment(f.reviewer,withdraw)).rejects.toMatchObject({status:404});
  await withPartnerDatabase(db=>db.query("UPDATE customer_grants SET state='active',revision=revision+1 WHERE membership_id=$1 AND customer_id=$2",[f.partner.membershipId,DEMO_IDS.sharedCustomer]));const old=await readPartnerAssignment(f.partner,id);expect(old.availability).toBe("authority_changed");expect(old.progress).toBeNull();
  const replace={...withdraw,action:"assignment.replace",guideId:f.guideId,revisionId:f.revisionId},preview=await previewPartnerAssignment(f.reviewer,replace),replacement=await decidePartnerAssignment(f.reviewer,{...replace,requestId:randomUUID(),previewId:preview.previewId});expect(replacement.targetId).not.toBe(id);expect((await readPartnerAssignment(f.partner,replacement.targetId!)).progress?.verifiedRequired).toBe(0);expect((await readPartnerAssignment(f.partner,id)).progress).toBeNull();
 });
});
