import {randomUUID} from 'node:crypto';import {describe,it,expect} from 'vitest';import {execFileSync} from 'node:child_process';
import {reportsDeliveryFixture} from '../fixtures/reports/delivery';import {reportTransaction} from '../../lib/server/reports/commands';
import {submitReportCustomerCommand,submitReportRevisionCommand} from '../../lib/server/reports/service';
import {claimReportJobs} from '../../lib/server/reports/jobs';import {runReportRenderJob} from '../../lib/server/reports/render-jobs';
import {readReport} from '../../lib/server/reports/read';import {downloadReportArtifact} from '../../lib/server/reports/artifacts';
async function prepare(){const fixture=await reportsDeliveryFixture();process.env.TURAS_REPORTS_ENABLED='true';process.env.TURAS_REPORT_RENDERER_IMAGE=execFileSync('docker',['image','inspect','turas-report-renderer:009-executive-v1','--format','{{.Id}}'],{encoding:'utf8'}).trim();const view=await submitReportCustomerCommand(fixture.author,fixture.customerId,{action:'prepare',requestKey:randomUUID(),expectedVersion:0,selection:{kind:'monthly',audience:'delivery',timezone:'UTC',engagementIds:[fixture.engagementId],workloadIds:[],includeCustomerLevel:true},fromDate:'2026-09-01',toDate:'2026-09-30',partial:false}) as any;return {fixture,view};}
describe('governed executive rendering and download',()=>{
 it('queues immutable render authority, promotes only validated exact bytes, and downloads through current authorization',async()=>{const {fixture,view}=await prepare();const queued=await submitReportRevisionCommand(fixture.author,view.reportId,{action:'render',requestKey:randomUUID(),expectedVersion:view.version,rationale:'Validate synthetic executive review'}) as any;expect(queued.state).toBe('rendering');const [job]=await reportTransaction(db=>claimReportJobs(db,'render'));expect(job.revision_id).toBe(view.revisionId);await runReportRenderJob(job);const ready=await readReport(fixture.author,view.reportId) as any;expect(ready.state).toBe('review_ready');expect(ready.artifacts.map((a:any)=>a.format)).toEqual(['pdf','pptx']);const artifact=ready.artifacts[0];const bytes=await downloadReportArtifact(fixture.author,view.reportId,artifact.id);expect(bytes.bytes.length).toBe(artifact.sizeBytes);expect(bytes.contentType).toBe('application/pdf');});
 it('refuses stale leases before rendering or reading protected payloads',async()=>{const {fixture,view}=await prepare();await submitReportRevisionCommand(fixture.author,view.reportId,{action:'render',requestKey:randomUUID(),expectedVersion:view.version,rationale:'Validate synthetic stale lease boundary'});const [job]=await reportTransaction(db=>claimReportJobs(db,'render'));await reportTransaction(db=>db.query('UPDATE report_jobs SET lease_token=$2 WHERE id=$1',[job.id,randomUUID()]));await expect(runReportRenderJob(job)).rejects.toMatchObject({code:'version_conflict'});expect((await readReport(fixture.author,view.reportId) as any).artifacts).toEqual([]);});
});
