import {test,expect as baseExpect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import {signIn} from "../fixtures/ui";
import {requireOwnedExecutionClone} from "../../scripts/execution-eval-environment";
import {timeFixture,draftTime,submitTime,timeCandidate,decideTime,timeCommand} from "../fixtures/execution/time";
import {registerBase,saveRegister,submitRegister,reviewRegister} from "../fixtures/execution/registers";
import {handoffRecord,referenceTo,waiveMilestones} from "../fixtures/execution/handoff";
import {readExecutionOverview,submitExecutionCommand,readExecutionRecords} from "../../lib/server/execution/service";
import {readExecutionTime} from "../../lib/server/execution/time";
const expect=baseExpect.configure({timeout:30000});
test.beforeEach(({page},testInfo)=>{
  page.on("response",async response=>{const path=new URL(response.url()).pathname;if(path.startsWith("/api/execution")&&response.status()>=400){const body=await response.json().catch(()=>({}));await testInfo.attach("execution-response",{body:JSON.stringify({path,status:response.status(),code:body.error?.code}),contentType:"application/json"});}});
  page.on("framenavigated",async frame=>{if(frame===page.mainFrame())await testInfo.attach("navigation",{body:new URL(frame.url()).pathname,contentType:"text/plain"});});page.setDefaultTimeout(30000);requireOwnedExecutionClone();if(process.env.TURAS_EXECUTION_FIXTURE_READY!=="1")throw new Error("Use owned008 UI runner");});
test("forecast shows exact lifetime and period quantities, reviewed estimate input, and late-actual incompleteness",async({page},testInfo)=>{
  test.setTimeout(240000);const f=await timeFixture({calendar:true});await decideTime(f,await timeCandidate(f,[await submitTime(f,await draftTime(f))],"time.approve",{unplanned:"Human verifies unbooked work"}));
  for(const [key,budget,remaining] of [["proof",120,30],["readiness",0,0]] as const){
    await reviewRegister(f,await submitRegister(f,await saveRegister(f,{...registerBase(),title:`Budget ${key}`,kind:"effort_budget",workPackageKey:key,minutes:budget})));
    await reviewRegister(f,await submitRegister(f,await saveRegister(f,{...registerBase(),title:`Remaining ${key}`,kind:"estimate",workPackageKey:key,minutes:remaining,asOf:new Date().toISOString(),explicitZero:remaining===0})));
  }
  const url=`/customers/${f.customerId}/engagements/${f.engagementId}/execution`;
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Forecast",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Effort Forecast",exact:true})).toBeVisible();
  const forecast=page.getByRole("region",{name:"Effort Forecast",exact:true});
  await expect(forecast.locator(".execution-metric").filter({has:page.getByText("Forecast Total",{exact:true})})).toContainText("90 min");
  await page.getByLabel("Period start",{exact:true}).fill(f.date);await page.getByLabel("Period end",{exact:true}).fill(f.date);await page.getByRole("button",{name:"Apply period",exact:true}).click();
  await expect(forecast.locator(".execution-metric").filter({has:page.getByText("Period Actual",{exact:true})})).toContainText("60 min");
  await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("estimate");
  await page.getByLabel("Delivery title",{exact:true}).fill("Refreshed remaining work");await page.getByLabel("Delivery context",{exact:true}).fill("The owner reviewed remaining work after the completed activity");
  await page.getByLabel("Remaining minutes",{exact:true}).fill("15");await page.getByLabel("Estimate as of (UTC)",{exact:true}).fill(new Date().toISOString());
  await page.getByRole("button",{name:"Save delivery draft",exact:true}).click();const record=page.getByRole("article",{name:"Delivery record Refreshed remaining work",exact:true});
  await record.getByRole("button",{name:"Submit delivery record",exact:true}).click();await expect(record.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Forecast",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("estimate");
  await record.getByRole("button",{name:"Review delivery record",exact:true}).click();await page.getByLabel("Review rationale",{exact:true}).fill("Human checked the exact current package estimate");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).focus();await page.keyboard.press("Enter");await expect(record.getByText("accepted",{exact:true})).toBeVisible();
  await expect(forecast.locator(".execution-metric").filter({has:page.getByText("Forecast Total",{exact:true})})).toContainText("75 min");
  await page.getByLabel("Period start",{exact:true}).fill(f.date);await page.getByLabel("Period end",{exact:true}).fill(f.date);await page.getByRole("button",{name:"Apply period",exact:true}).click();
  const utilization=page.getByRole("region",{name:"Actual Utilization",exact:true});await utilization.getByRole("checkbox").first().check();await utilization.getByRole("button",{name:"Calculate actual utilization",exact:true}).click();
  await expect(utilization.getByText("12.50%",{exact:true})).toBeVisible();
  expect((await page.request.get(`/api/execution/utilization?from=${f.date}&to=${f.date}&resourceIds=${f.resourceId},${f.resourceId}`)).status()).toBe(400);
  expect((await page.request.get(`/api/execution/engagements/${f.engagementId}/summary?from=${f.date}&to=${f.date}&extra=1`)).status()).toBe(400);
  await page.screenshot({path:testInfo.outputPath("reviewed-forecast.png"),fullPage:true});
  await signIn(page,"partner");await page.goto(url);await page.getByRole("tab",{name:"Forecast",exact:true}).click();await expect(page.getByRole("heading",{name:"Work Package Coverage",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Save delivery draft",exact:true})).toHaveCount(0);await expect(page.getByRole("region",{name:"Actual Utilization",exact:true})).toHaveCount(0);
  expect((await page.request.get(`/api/execution/utilization?from=${f.date}&to=${f.date}&resourceIds=${f.resourceId}`)).status()).toBe(403);
  const entry=(await readExecutionTime(f.author,f.engagementId,f.period)).entries[0],view=await readExecutionOverview(f.author,f.engagementId);
  await submitExecutionCommand(f.author,f.engagementId,timeCommand("time.revise",{execution:view.version,time:entry.version},{entryId:entry.id,time:{...f.time,minutes:45}}));
  const correction=await submitTime(f,(await readExecutionTime(f.author,f.engagementId,f.period)).entries[0]);
  await decideTime(f,await timeCandidate(f,[correction],"time.approve",{unplanned:"Human verifies corrected unbooked quantity"}));
  await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(forecast.locator(".execution-metric").filter({has:page.getByText("Forecast Total",{exact:true})})).toContainText("Incomplete");await expect(page.getByText("actuals after estimate",{exact:true})).toBeVisible();
  expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test("closeout blocks pending time, records evidenced acknowledgement, and requires review after a late correction",async({page},testInfo)=>{
  test.setTimeout(240000);const f=await timeFixture(),reference=referenceTo(f.activity),record={...handoffRecord(reference),acknowledgement:{state:"recorded",eventDate:f.date,evidenceReferenceIds:[reference.id]}};
  const handoff=await submitRegister(f,await saveRegister(f,record));await reviewRegister(f,handoff);await waiveMilestones(f);
  let time=await submitTime(f,await draftTime(f));const url=`/customers/${f.customerId}/engagements/${f.engagementId}/execution`;
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("closeout");
  await page.getByLabel("Delivery title",{exact:true}).fill("Reviewed delivery closeout");await page.getByLabel("Delivery context",{exact:true}).fill("The receiver acknowledges the reviewed criterion and follow-up record");
  await page.getByRole("group",{name:"Supporting Reviewed Evidence",exact:true}).getByRole("checkbox",{name:"Synthetic observed work",exact:true}).check();
  await page.getByRole("combobox",{name:"Accepted handoff",exact:true}).selectOption(handoff.revisionId);await page.getByLabel("Receiver label",{exact:true}).fill("Synthetic receiving owner");
  await page.getByRole("combobox",{name:"Evidence for Proof reviewed",exact:true}).selectOption(reference.id);
  await page.getByRole("combobox",{name:"Receiver acknowledgement",exact:true}).selectOption("recorded");await page.getByLabel("Acknowledgement date",{exact:true}).fill(f.date);
  await page.getByRole("group",{name:"Acknowledgement Evidence",exact:true}).getByRole("checkbox",{name:"Synthetic observed work",exact:true}).check();
  await page.getByRole("button",{name:"Save delivery draft",exact:true}).click();const close=page.getByRole("article",{name:"Delivery record Reviewed delivery closeout",exact:true});
  await close.getByRole("button",{name:"Submit delivery record",exact:true}).click();await expect(close.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("closeout");
  await close.getByRole("button",{name:"Review delivery record",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"submitted_time_pending"})).toBeVisible();await expect(page.getByRole("button",{name:"Confirm reviewed decision",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Close review",exact:true}).click();
  await decideTime(f,await timeCandidate(f,[time]));const ready=await readExecutionOverview(f.reviewer,f.engagementId);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));
  await expect(page.locator("#execution-panel")).toHaveAttribute("data-execution-generation",String(ready.generation));
  await close.getByRole("button",{name:"Review delivery record",exact:true}).click();await page.getByLabel("Review rationale",{exact:true}).fill("Human verified receiver evidence, milestones and reviewed time");await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(close.getByText("accepted",{exact:true})).toBeVisible();await expect(page.getByText("Delivery state: closed",{exact:true})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("reviewed-closeout.png"),fullPage:true});
  time=(await readExecutionTime(f.reviewer,f.engagementId,f.period)).entries[0];const view=await readExecutionOverview(f.reviewer,f.engagementId);
  await submitExecutionCommand(f.reviewer,f.engagementId,timeCommand("time.revise",{execution:view.version,time:time.version},{entryId:time.id,time:{...f.time,minutes:45,onBehalfRationale:"Reviewer records the attributed late correction"}}));
  time=await submitTime(f,(await readExecutionTime(f.reviewer,f.engagementId,f.period)).entries[0],f.reviewer);
  await decideTime(f,await timeCandidate(f,[time],"time.approve",{on_behalf:"Reviewer verifies contributor attribution",unplanned:"Historical work was not booked",unknown_capacity:"Reviewer verifies UTC date",post_closeout:"Human accepts the late actual correction"}));
  await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByText("Closeout requires a new review because delivery, time, or supporting evidence changed.",{exact:true})).toBeVisible();
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("closeout");
  await close.getByRole("button",{name:"Revise delivery record",exact:true}).click();await expect(page.getByLabel("Delivery title",{exact:true})).toHaveValue("Reviewed delivery closeout");
  const activity=(await readExecutionRecords(f.reviewer,f.engagementId,{recordId:f.activity.id})).records[0];await reviewRegister(f,activity,"record.retract");await page.evaluate(()=>window.dispatchEvent(new Event("focus")));
  await expect(page.getByLabel("Delivery title",{exact:true})).toHaveValue("");await expect(page.getByRole("article",{name:"Delivery record Reviewed delivery closeout",exact:true})).toHaveCount(0);
  expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test("outcomes retain unknown measurements and accept an evidenced observation only after review",async({page},testInfo)=>{
  test.setTimeout(180000);const f=await timeFixture(),url=`/customers/${f.customerId}/engagements/${f.engagementId}/execution`;
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("outcome");
  await page.getByLabel("Delivery title",{exact:true}).fill("Response time observation");await page.getByLabel("Delivery context",{exact:true}).fill("A bounded synthetic measurement with explicit unknown comparison");
  await expect(page.getByLabel("Outcome limitation",{exact:true})).toHaveValue("Measurement has not been collected");await expect(page.getByLabel("Measured value",{exact:true})).toHaveCount(0);
  await page.getByRole("combobox",{name:"Outcome status",exact:true}).selectOption("observed");await page.getByLabel("Outcome measure",{exact:true}).fill("Response time");await page.getByLabel("Measurement unit",{exact:true}).fill("ms");await page.getByLabel("Measured value",{exact:true}).fill("112.125");
  await page.getByRole("group",{name:"Supporting Reviewed Evidence",exact:true}).getByRole("checkbox",{name:"Synthetic observed work",exact:true}).check();
  await expect(page.getByLabel("Unknown baseline reason",{exact:true})).toHaveValue("No prior comparable measurement");await expect(page.getByLabel("Unknown comparison reason",{exact:true})).toHaveValue("No comparison group");
  await page.getByRole("button",{name:"Save delivery draft",exact:true}).click();const outcome=page.getByRole("article",{name:"Delivery record Response time observation",exact:true});
  await outcome.getByRole("button",{name:"Submit delivery record",exact:true}).click();await expect(outcome.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("outcome");
  await outcome.getByRole("button",{name:"Review delivery record",exact:true}).click();await page.getByLabel("Review rationale",{exact:true}).fill("Human verifies the observation, measurement window and explicit limits");await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(outcome.getByText("accepted",{exact:true})).toBeVisible();
  await signIn(page,"partner");await page.goto(url);await page.getByRole("tab",{name:"Handoff",exact:true}).click();await page.getByRole("combobox",{name:"Record type",exact:true}).selectOption("outcome");await expect(outcome).toContainText("112.125 ms");await expect(outcome).toContainText("Baseline: No prior comparable measurement");await expect(outcome).toContainText("Comparison: No comparison group");
  await page.screenshot({path:testInfo.outputPath("reviewed-outcome.png"),fullPage:true});expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
