import {test,expect as baseExpect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import {signIn} from "../fixtures/ui";
import {requireOwnedExecutionClone} from "../../scripts/execution-eval-environment";
import {timeFixture,draftTime,submitTime,timeCandidate,decideTime} from "../fixtures/execution/time";
import {registerFixture,replaceBaseline,saveRegister,registerBase} from "../fixtures/execution/registers";
import {withTransaction} from "../../lib/server/db/client";
const expect=baseExpect.configure({timeout:30000});
test.beforeEach(({page})=>{page.setDefaultTimeout(30000);requireOwnedExecutionClone();if(process.env.TURAS_EXECUTION_FIXTURE_READY!=="1")throw new Error("Use owned008 UI runner");});
test("reviewed RAID and scope replacement retain actuals and require explicit one-to-one mapping",async({page},testInfo)=>{
  test.setTimeout(180000);const f=await timeFixture();await decideTime(f,await timeCandidate(f,[await submitTime(f,await draftTime(f))]));
  const url=`/customers/${f.customerId}/engagements/${f.engagementId}/execution`;
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();
  await page.getByLabel("Register title",{exact:true}).fill("Synthetic rollout concern");
  await page.getByRole("textbox",{name:"Register context",exact:true}).fill("Delivery owner must verify the rollout sequence");
  await page.getByRole("textbox",{name:"Delivery impact",exact:true}).fill("May delay the planned handoff");
  await page.getByRole("button",{name:"Save register draft",exact:true}).click();
  const risk=page.getByRole("article",{name:"RAID record Synthetic rollout concern",exact:true});
  await risk.getByRole("button",{name:"Submit register record",exact:true}).click();await expect(risk.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"partner");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await expect(page.getByRole("heading",{name:"Registers and Scope Changes",exact:true})).toBeVisible();
  await expect(page.getByText("Synthetic rollout concern",{exact:true})).toHaveCount(0);
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await risk.getByRole("button",{name:"Review register record",exact:true}).click();
  await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human reviewed the delivery concern and explicit unknown owner/date");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).focus();await page.keyboard.press("Enter");await expect(risk.getByText("accepted",{exact:true})).toBeVisible();
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("scope_change");
  await page.getByLabel("Register title",{exact:true}).fill("Synthetic replacement scope");await page.getByRole("textbox",{name:"Register context",exact:true}).fill("A new work package needs independent planning review");
  await page.getByRole("textbox",{name:"Delivery impact",exact:true}).fill("Retire the old readiness package and add verification");
  await page.getByRole("combobox",{name:"Scope change state",exact:true}).selectOption("approved_for_planning");
  await page.getByRole("button",{name:"Save register draft",exact:true}).click();
  const scope=page.getByRole("article",{name:"Scope Changes record Synthetic replacement scope",exact:true});
  await scope.getByRole("button",{name:"Submit register record",exact:true}).click();await expect(scope.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("scope_change");
  await scope.getByRole("button",{name:"Review register record",exact:true}).click();await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human approves only the planning proposal");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(scope.getByText("accepted",{exact:true})).toBeVisible();
  const content=structuredClone(f.content);content.workPackages[0].key="delivery";content.workPackages[1].key="verification";
  content.milestones[0].key="delivery_done";content.milestones[1].dependencies=["delivery_done"];
  const replacement=await replaceBaseline(f,content);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));
  const mapping=page.getByRole("region",{name:"Baseline Reconciliation",exact:true});await expect(mapping).toBeVisible();
  await mapping.getByRole("combobox",{name:"Map work_package proof",exact:true}).selectOption("delivery");
  await expect(mapping.getByRole("combobox",{name:"Map work_package readiness",exact:true}).getByRole("option",{name:/\(delivery\)/})).toHaveJSProperty("disabled",true);
  await mapping.getByRole("combobox",{name:"Map work_package readiness",exact:true}).selectOption("__retired__");
  await mapping.getByRole("combobox",{name:"Map milestone proof_done",exact:true}).selectOption("delivery_done");
  await mapping.getByRole("combobox",{name:"Map milestone ready",exact:true}).selectOption("ready");
  await expect(mapping.getByRole("button",{name:"Review baseline mapping",exact:true})).toBeDisabled();
  await mapping.getByRole("checkbox",{name:/Add Prepare rollback \(verification\)/}).check();
  await mapping.getByRole("button",{name:"Review baseline mapping",exact:true}).click();await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human maps exact historical and replacement keys without transferring completion");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(mapping).toHaveCount(0);
  expect(await withTransaction(async db=>(await db.query("SELECT current_baseline_id FROM execution_workspaces WHERE engagement_id=$1",[f.engagementId])).rows[0].current_baseline_id)).toBe(replacement.baselineId);
  expect(await withTransaction(async db=>(await db.query("SELECT baseline_id,minutes FROM execution_actual_days WHERE engagement_id=$1",[f.engagementId])).rows)).toEqual([{baseline_id:f.baselineId,minutes:60}]);
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("scope_change");
  await scope.getByRole("button",{name:"Revise register record",exact:true}).click();
  await page.getByRole("combobox",{name:"Scope change state",exact:true}).selectOption("implemented");
  await page.getByRole("combobox",{name:"Accepted replacement baseline",exact:true}).selectOption(replacement.baselineId);
  await page.getByRole("button",{name:"Save register draft",exact:true}).click();
  await scope.getByRole("button",{name:"Submit register record",exact:true}).click();await expect(scope.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("scope_change");
  await scope.getByRole("button",{name:"Review register record",exact:true}).click();await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human verified the accepted replacement and complete explicit reconciliation");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(scope.getByText("accepted",{exact:true})).toBeVisible();await expect(scope.getByText("implemented",{exact:true})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("reviewed-registers.png"),fullPage:true});
  await signIn(page,"partner");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await expect(page.getByText("Synthetic rollout concern",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Review register record",exact:true})).toHaveCount(0);
  const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test("decision review rejects an intercepted stale preview and requires a new human decision",async({page})=>{
  test.setTimeout(180000);const f=await registerFixture(),url=`/customers/${f.customerId}/engagements/${f.engagementId}/execution`;
  await signIn(page,"panel");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("decision");
  await page.getByLabel("Register title",{exact:true}).fill("Synthetic human decision");await page.getByRole("textbox",{name:"Register context",exact:true}).fill("An explicitly attributed delivery choice");
  await page.getByLabel("Decision maker",{exact:true}).fill("Synthetic delivery lead");await page.getByRole("textbox",{name:"Decision rationale",exact:true}).fill("Human compared the implementation alternatives");
  await page.getByRole("button",{name:"Save register draft",exact:true}).click();
  const decision=page.getByRole("article",{name:"Decisions record Synthetic human decision",exact:true});
  await decision.getByRole("button",{name:"Submit register record",exact:true}).click();await expect(decision.getByText("submitted",{exact:true})).toBeVisible();
  await signIn(page,"mcteer");await page.goto(url);await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("decision");
  await decision.getByRole("button",{name:"Review register record",exact:true}).click();await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human reviewed the exact decision");
  let intercepted=false;
  await page.route(`**/api/execution/engagements/${f.engagementId}/commands`,async route=>{
    if(!intercepted&&route.request().postDataJSON().action==="record.accept"){
      intercepted=true;await saveRegister(f,{...registerBase(),kind:"activity",subtype:"work",title:"Concurrent owned draft"});
      const response=await route.fetch();expect(response.status()).toBe(409);await route.fulfill({response});return;
    }await route.continue();
  });
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(page.getByText("Execution changed; refresh",{exact:true})).toBeVisible();expect(intercepted).toBe(true);
  await page.reload();await page.getByRole("tab",{name:"Registers",exact:true}).click();await page.getByRole("combobox",{name:"Register",exact:true}).selectOption("decision");await expect(decision.getByText("submitted",{exact:true})).toBeVisible();
  await decision.getByRole("button",{name:"Review register record",exact:true}).click();await page.getByRole("textbox",{name:"Review rationale",exact:true}).fill("Human independently reviewed the refreshed exact decision");
  await page.getByRole("button",{name:"Confirm reviewed decision",exact:true}).click();await expect(decision.getByText("accepted",{exact:true})).toBeVisible();
});
