import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {gapActors} from '../fixtures/gaps/seed';
import {reviewedSyntheticGap,reviewedSuspectedImpact} from '../fixtures/gaps/authoring';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
import {testCredentials} from '../fixtures/ui';
import {withGapDatabase} from '../fixtures/gaps/environment';
test.beforeEach(async()=>{if(process.env.TURAS_GAPS_UI_FIXTURE_READY!=='1')throw Error('Owned gap UI runner required');await withGapDatabase(db=>db.query("DELETE FROM rate_windows WHERE environment_id=$1 AND category LIKE 'gap_%'",[process.env.TURAS_ENVIRONMENT_ID]));});
async function login(page:Page,identity:'mcteer'|'panel'='mcteer'){expect((await page.request.post('/api/auth/login',{headers:{origin:process.env.TURAS_UI_BASE_URL!},data:{...testCredentials(identity),returnTo:'/product-gaps'}})).ok()).toBe(true);}
async function fillAudience(page:Page){await page.getByLabel('Engineering Team',{exact:true}).fill('Synthetic Functions engineering');await page.getByLabel('Named Recipients (One per Line)',{exact:true}).fill('Synthetic Engineer');await page.getByLabel('Report Purpose',{exact:true}).fill('Assess the exact reviewed synthetic capability and customer scope.');}
async function prepare(page:Page){await fillAudience(page);await page.getByRole('button',{name:'Prepare Private Draft',exact:true}).click();await page.waitForURL(/\/product-gaps\/reports\/[a-f0-9-]+$/);const id=page.url().split('/').at(-1);await expect.poll(async()=>(await withGapDatabase(db=>db.query('SELECT j.state FROM gap_report_jobs j JOIN gap_reports r ON r.current_job_id=j.id WHERE r.id=$1',[id]))).rows[0]?.state,{timeout:35000,intervals:[200,500]}).toBe('prepared');await page.getByRole('button',{name:'Refresh Report',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Preparation: prepared · Content: eligible'})).toBeVisible();}
async function review(page:Page){await page.getByRole('checkbox',{name:/I reviewed the complete document, exact recipients/}).check();await page.getByLabel('Report Review Rationale',{exact:true}).fill('Review exact synthetic sections, evidence, audience and export parity.');await page.getByRole('checkbox',{name:/I acknowledge reviewing my own report preparation/}).check();await page.getByRole('button',{name:'Preview Report Review',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Confirm Report Review',exact:true})).toBeVisible();await page.getByRole('button',{name:'Confirm Report Review',exact:true}).click();await expect(page.getByRole('heading',{name:'Approved Private Exports',exact:true})).toBeVisible();}
test('prepares complete detail, requires disclosure and downloads matching approved JSON and Markdown',async({page},info)=>{const actors=await gapActors(),token=randomUUID().slice(0,8),gap=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Report Detail '+token});await reviewedSuspectedImpact(actors.panel,actors.mcteer,gap.id,DEMO_IDS.sharedCustomer);await login(page,'panel');await page.goto('/product-gaps/'+gap.id);await page.getByRole('button',{name:'Prepare Detail Report',exact:true}).click();await prepare(page);for(const heading of ['1. Problem','2. Evidence and scope','3. Impact','4. Workarounds','5. Proposed capability','6. Engineering handoff','7. Evidence appendix and review'])await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toHaveCount(0);await login(page);await page.reload();await expect(page.getByRole('heading',{name:'Exact Report Review',exact:true})).toBeVisible();await page.getByRole('checkbox',{name:/I reviewed the complete document, exact recipients/}).check();await expect(page.getByRole('button',{name:'Preview Report Review',exact:true})).toBeDisabled();await page.getByRole('checkbox',{name:/I authorize disclosure of Cedar/}).check();await review(page);const downloaded=[];for(const format of ['JSON','Markdown']){const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download '+format,exact:true}).click();const download=await event,path=info.outputPath('approved-report.'+(format==='JSON'?'json':'md'));await download.saveAs(path);expect(await download.failure()).toBeNull();downloaded.push(await readFile(path,'utf8'));}const json=JSON.parse(downloaded[0]);expect(json.sections).toHaveLength(7);expect(json.customers).toHaveLength(1);expect(json.sections[2].content.counts).toEqual({confirmed:0,suspectedOnly:1,resolvedHistory:0});expect(downloaded[1]).toContain('## 7. Evidence appendix and review');expect(downloaded[1]).toContain('Synthetic Engineer');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toHaveLength(0);await page.screenshot({path:info.outputPath('approved-detail-report.png'),fullPage:true});});
test('prepares and reviews a zero-gap portfolio with all five sections',async({page},info)=>{await login(page);await page.goto('/product-gaps');await page.getByRole('button',{name:'Prepare Engineering Report',exact:true}).click();await prepare(page);for(const heading of ['1. Executive summary','2. Gap table','3. Prioritization','4. Actions','5. Method and limits'])await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();await expect(page.getByText('No gaps selected',{exact:true})).toBeVisible();await review(page);await page.screenshot({path:info.outputPath('approved-empty-portfolio.png'),fullPage:true});});
test('prepares an explicit two-gap portfolio and explains its qualitative order',async({page})=>{const actors=await gapActors(),token=randomUUID().slice(0,8),a=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Report Portfolio A '+token}),b=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Report Portfolio B '+token});await login(page);await page.goto('/product-gaps');await page.getByLabel('Search Gaps',{exact:true}).fill(token);await expect(page.locator('article.profile-card')).toHaveCount(2);await expect(page.getByRole('link',{name:'Report Portfolio B '+token,exact:true})).toBeVisible();await page.getByRole('button',{name:'Prepare Engineering Report',exact:true}).click();for(const title of ['Report Portfolio A '+token,'Report Portfolio B '+token])await page.getByRole('checkbox',{name:title,exact:true}).check();for(const title of ['Report Portfolio A '+token,'Report Portfolio B '+token])await expect(page.getByRole('checkbox',{name:title,exact:true})).toBeChecked();await expect(page.getByText('Selected: 2. A detail report requires exactly one gap.',{exact:true})).toBeVisible();await prepare(page);await expect(page.getByText('Due revisit, reviewed severity, confirmed breadth, workaround feasibility, oldest review, canonical identity. No numeric weights.',{exact:true})).toBeVisible();const id=page.url().split('/').at(-1);const row=(await withGapDatabase(db=>db.query('SELECT gap_ids FROM gap_report_revisions r JOIN gap_reports p ON p.current_revision_id=r.id WHERE p.id=$1',[id]))).rows[0];expect(row.gap_ids.sort()).toEqual([a.id,b.id].sort());});
test('clears a prepared document and all download controls after reviewed scope changes',async({page})=>{const actors=await gapActors(),gap=await reviewedSyntheticGap(actors.panel,actors.mcteer);await login(page);await page.goto('/product-gaps/'+gap.id);await page.getByRole('button',{name:'Prepare Detail Report',exact:true}).click();await prepare(page);await review(page);await withGapDatabase(db=>db.query('UPDATE product_gaps SET version=version+1 WHERE id=$1',[gap.id]));await page.getByRole('button',{name:'Refresh Report',exact:true}).click();await expect(page.getByText('The original evidence or reviewed scope changed. This report is withheld.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'1. Problem',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toHaveCount(0);});
