import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {syntheticGap} from '../fixtures/gaps/ui';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {requireOwnedGapDatabase} from '../../scripts/gaps-eval-environment';
import {testCredentials} from '../fixtures/ui';
async function signIn(page:Page,account:'panel'|'mcteer'|'partner'){const response=await page.request.post('/api/auth/login',{headers:{origin:process.env.TURAS_UI_BASE_URL!},data:{...testCredentials(account),returnTo:'/product-gaps'}});expect(response.ok()).toBe(true);}

test.beforeEach(async()=>{requireOwnedGapDatabase();if(process.env.TURAS_GAPS_UI_FIXTURE_READY!=='1')throw Error('Use the owned gap UI runner');await withGapDatabase(db=>db.query("DELETE FROM rate_windows WHERE environment_id=$1 AND category IN ('gap_read','gap_write','gap_preparation','profile_read','profile_write')",[process.env.TURAS_ENVIRONMENT_ID]));});
async function draft(page:Page,title:string,confirm=true){await page.getByRole('button',{name:'New Gap',exact:true}).click();const value=syntheticGap({title});for(const [label,key] of [['Gap Title','title'],['Product Key','productKey'],['Capability','capability'],['Triage Team','triageTeam'],['Problem','problem'],['Workflow','workflow'],['Desired Outcome','desiredOutcome'],['Reproduction','reproduction'],['Constraints','constraints'],['Workaround','workaround'],['Workaround Limitations','workaroundLimitations'],['Proposed Capability','proposedCapability'],['Alternatives','alternatives'],['Unknowns','unknowns'],['Requested Decision','requestedDecision'],['Severity Rationale','severityRationale']] as const)await page.getByLabel(label,{exact:true}).fill(value[key] as string);await page.getByLabel('Acceptance Criteria (One per Line)',{exact:true}).fill(value.acceptanceCriteria.join('\n'));await page.getByRole('checkbox',{name:/The common narrative/}).check();await page.getByRole('button',{name:'Save as Proposed',exact:true}).focus();await page.keyboard.press('Enter');if(confirm)await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();return new URL(page.url()).pathname.split('/').at(-1)!;}
test('authors a keyboard proposal, preserves proposed status and edits its narrative',async({page},info)=>{const before=(await withGapDatabase(db=>db.query('SELECT count(*) AS n FROM profile_records'))).rows[0].n;await signIn(page,'panel');await page.goto('/product-gaps');const title=`Synthetic Gap ${info.project.name}`;await draft(page,title);await expect(page.getByRole('heading',{name:'Reviewed Narrative',exact:true})).toBeVisible();await expect(page.getByText('No reviewed revision yet.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit Gap Proposal',exact:true}).click();await page.getByLabel('Gap Title',{exact:true}).fill(`${title} Edited`);await page.getByRole('checkbox',{name:/The common narrative/}).check();await page.getByRole('button',{name:'Save as Proposed',exact:true}).click();await expect(page.getByRole('heading',{name:`${title} Edited`,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toHaveLength(0);expect((await withGapDatabase(db=>db.query('SELECT count(*) AS n FROM profile_records'))).rows[0].n).toBe(before);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:info.outputPath('gap-proposal.png'),fullPage:true});});
test('requires self-review and commits one exact preview',async({page},info)=>{await signIn(page,'mcteer');await page.goto('/product-gaps');const title=`Synthetic Self Review ${info.project.name}`;await draft(page,title);await page.getByLabel('Review Rationale',{exact:true}).fill('Review this exact synthetic authored narrative.');await page.getByRole('checkbox',{name:/I reviewed the common narrative/}).check();await page.getByRole('button',{name:'Preview Decision',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Explicit self-review'})).toContainText('self-review');await page.getByRole('checkbox',{name:/I acknowledge reviewing my own/}).check();await page.getByRole('button',{name:'Preview Decision',exact:true}).click();await page.getByRole('button',{name:'Confirm Decision',exact:true}).click();await expect(page.getByText('Self-review acknowledged',{exact:false})).toBeVisible();await expect(page.getByRole('heading',{name:'Proposed Narrative',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('gap-reviewed.png'),fullPage:true});});
test('partners receive no gap navigation or feature page',async({page})=>{await signIn(page,'partner');await page.goto('/s');await expect(page.locator('a[href="/product-gaps"]')).toHaveCount(0);const response=await page.goto('/product-gaps');expect(response?.status()).toBe(404);await expect(page.getByRole('heading',{name:'Product Gaps',exact:true})).toHaveCount(0);});

test('confirmed impact without originals fails safely and leaves no observation',async({page},info)=>{await signIn(page,'mcteer');await page.goto('/product-gaps');const id=await draft(page,`Synthetic Missing Evidence ${info.project.name}`);await page.getByLabel('Review Rationale',{exact:true}).fill('Review exact customer-independent synthetic narrative.');await page.getByRole('checkbox',{name:/I reviewed the common narrative/}).check();await page.getByRole('checkbox',{name:/I acknowledge reviewing my own/}).check();await page.getByRole('button',{name:'Preview Decision',exact:true}).click();await page.getByRole('button',{name:'Confirm Decision',exact:true}).click();await expect(page.getByText('Self-review acknowledged',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Propose Customer Impact',exact:true}).click();await page.getByRole('combobox',{name:'Impact Customer',exact:true}).selectOption({index:1});await page.getByRole('combobox',{name:'Impact Classification',exact:true}).selectOption('confirmed');await page.getByLabel('Observed At (UTC; Leave Blank if Unknown)',{exact:true}).fill(new Date(Date.now()-7200000).toISOString().slice(0,16));await page.getByLabel('Consequences',{exact:true}).fill('Synthetic impact needs accepted customer and product originals.');await page.getByLabel('Workaround Burden',{exact:true}).fill('Operating burden remains unverified.');await page.getByLabel('Impact Severity Rationale',{exact:true}).fill('Unknown pending source review.');await page.getByRole('button',{name:'Save Impact as Proposed',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Critical original evidence required'})).toBeVisible();expect((await withGapDatabase(db=>db.query('SELECT count(*) AS n FROM gap_impact_observations WHERE original_gap_id=$1',[id]))).rows[0].n).toBe('0');});
test('lost save acknowledgment retains only identities and reconciles one revision',async({page},info)=>{await signIn(page,'panel');await page.goto('/product-gaps');let key:string|null=null;const completed=Promise.withResolvers<void>();await page.route('**/api/product-gaps',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}key=route.request().postDataJSON().requestKey;const response=await route.fetch();expect(response.status()).toBe(201);await route.abort('failed');completed.resolve();});const title=`Synthetic Lost Acknowledgment ${info.project.name}`;await draft(page,title,false);await expect(page.getByRole('button',{name:'Check Request Status',exact:true})).toBeVisible();await completed.promise;await page.unroute('**/api/product-gaps');await page.reload();await expect(page.getByRole('button',{name:'New Gap',exact:true})).toBeDisabled();const retained=await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('turas-gap-command:')).map(k=>sessionStorage.getItem(k)).join(''));expect(retained).not.toContain(title);expect(retained).not.toContain('sourceRefs');await page.getByRole('button',{name:'Check Request Status',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Request confirmed.'})).toBeVisible();expect((await withGapDatabase(db=>db.query("SELECT count(*) AS n FROM gap_request_receipts WHERE request_key=$1 AND operation='save_gap'",[key]))).rows[0].n).toBe('1');});
