import {installGapUiDiagnostics} from '../fixtures/gaps/ui-diagnostics';
import {test,expect,type Page} from '@playwright/test';
import {reviewedSyntheticGap} from '../fixtures/gaps/authoring';
import {gapActors} from '../fixtures/gaps/seed';
import {withGapDatabase} from '../fixtures/gaps/environment';
import {saveGap} from '../../lib/server/gaps/service';
import {gapEnvelope} from '../fixtures/gaps/authoring';
import {acceptedGapEvidence} from '../fixtures/gaps/evidence';
import {syntheticGap} from '../fixtures/gaps/ui';
import {DEMO_IDS} from '../../lib/server/bootstrap-ids';
import {approvedGapReport} from '../fixtures/gaps/reports';
import {testCredentials} from '../fixtures/ui';
installGapUiDiagnostics();
test.beforeEach(async()=>{if(process.env.TURAS_GAPS_UI_FIXTURE_READY!=='1')throw Error('Owned gap UI runner required');await withGapDatabase(db=>db.query("DELETE FROM rate_windows WHERE environment_id=$1 AND category LIKE 'gap_%'",[process.env.TURAS_ENVIRONMENT_ID]));});
async function login(page:Page,who:'panel'|'partner'|'mcteer'='panel'){expect((await page.request.post('/api/auth/login',{headers:{origin:process.env.TURAS_UI_BASE_URL!},data:{...testCredentials(who),returnTo:'/product-gaps'}})).ok()).toBe(true);}
test('clears private gap DOM on focus after changing session and persists no narrative',async({page})=>{const actors=await gapActors(),gap=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Synthetic private session-bound narrative'});await login(page);await page.goto('/product-gaps/'+gap.id);await expect(page.getByRole('heading',{name:'Synthetic private session-bound narrative',exact:true})).toBeVisible();const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));expect(storage).not.toContain('Synthetic private session-bound narrative');await login(page,'partner');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Synthetic private session-bound narrative',exact:true})).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'Product gaps are unavailable'})).toBeVisible();});
test('suppresses a delayed stale private result after a newer denied refresh',async({page})=>{const actors=await gapActors(),gap=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Synthetic delayed private result'});await login(page);await page.goto('/product-gaps/'+gap.id);await expect(page.getByRole('heading',{name:'Synthetic delayed private result',exact:true})).toBeVisible();const ready=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();let delayed=true;await page.route('**/api/product-gaps/'+gap.id+'**',async route=>{if(!delayed){await route.continue();return;}delayed=false;const response=await route.fetch();ready.resolve();await release.promise;await route.fulfill({response});});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await ready.promise;await login(page,'partner');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('status').filter({hasText:'Product gaps are unavailable'})).toBeVisible();release.resolve();await page.unrouteAll({behavior:'wait'});await expect(page.getByRole('heading',{name:'Synthetic delayed private result',exact:true})).toHaveCount(0);});

test('clears hidden-tab prose and refreshes withdrawn originals before showing it again',async({page})=>{const actors=await gapActors(),source=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'corroboration','Synthetic source withdrawal during hidden tab'),saved=await saveGap(actors.panel,{...gapEnvelope(),content:syntheticGap({title:'Synthetic hidden-tab source narrative'}),sourceRefs:[source.reference],customerIndependentAcknowledgment:true});await login(page);await page.goto('/product-gaps/'+saved.recordId);await expect(page.getByRole('heading',{name:'Synthetic hidden-tab source narrative',exact:true})).toBeVisible();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByRole('heading',{name:'Synthetic hidden-tab source narrative',exact:true})).toHaveCount(0);await withGapDatabase(db=>db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=(SELECT record_id FROM profile_revisions WHERE id=$1)',[source.revisionId]));await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByRole('heading',{name:'Proposed Narrative',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Synthetic hidden-tab source narrative',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain('Synthetic hidden-tab source narrative');});
test('cancels an in-flight export without creating a browser download',async({page})=>{const fixture=await approvedGapReport(true);await login(page,'mcteer');await page.goto('/product-gaps/reports/'+fixture.report.id);const ready=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();let downloads=0;page.on('download',()=>downloads++);await page.route('**/api/product-gaps/reports/'+fixture.report.id+'/exports/*',async route=>{ready.resolve();await release.promise;await route.abort().catch(()=>{});});await page.getByRole('button',{name:'Download JSON',exact:true}).click();await ready.promise;await page.getByRole('button',{name:'Cancel Export',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Export cancelled; this identity cannot be reused.'})).toBeVisible();release.resolve();await page.unrouteAll({behavior:'wait'});expect(downloads).toBe(0);expect((await withGapDatabase(db=>db.query('SELECT state FROM gap_export_receipts WHERE report_id=$1',[fixture.report.id]))).rows).toEqual([{state:'cancelled'}]);});

test('does not restore a pending private response after the tab becomes hidden',async({page})=>{const actors=await gapActors(),gap=await reviewedSyntheticGap(actors.panel,actors.mcteer,{title:'Synthetic hidden pending response'});await login(page);await page.goto('/product-gaps/'+gap.id);await expect(page.getByRole('heading',{name:'Synthetic hidden pending response',exact:true})).toBeVisible();const ready=Promise.withResolvers<void>(),release=Promise.withResolvers<void>();await page.route('**/api/product-gaps/'+gap.id+'**',async route=>{const response=await route.fetch();ready.resolve();await release.promise;await route.fulfill({response}).catch(()=>{});});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await ready.promise;await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});release.resolve();await page.unrouteAll({behavior:'wait'});await expect(page.getByRole('heading',{name:'Synthetic hidden pending response',exact:true})).toHaveCount(0);});
