import {learningMeasurementPopulation} from '../fixtures/learning/accepted-measurements';
import {createLearningMeasurement} from '../../lib/server/learning/measurements';
import {markDueLearningReviews} from '../../lib/server/learning/refresh';
import AxeBuilder from '@axe-core/playwright';
import {test,expect} from '@playwright/test';
import {withLearningDatabase} from '../fixtures/learning/environment';
import {learningNativeFixture} from '../fixtures/learning/native';
test.beforeEach(()=>{if(process.env.TURAS_LEARNING_UI_FIXTURE_READY!=='1')throw Error('Owned learning UI runner required');});
test('health keeps evidence, evaluation and operations separate through disabled, source-loss, unavailable and partner states',async({page})=>{
 const f=await withLearningDatabase(async db=>{const fixture=await learningNativeFixture(db,{baseline:true});await db.query('UPDATE learning_workspace_state SET enabled=false WHERE workspace_id=$1',[fixture.workspaceId]);return fixture;});
 const cookie=(token:string)=>({name:'turas_session',value:token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax' as const});await page.context().addCookies([cookie(f.actor.token)]);await page.goto('/learning/health');
 await expect(page.getByRole('heading',{name:'Evidence Quality',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Release Evaluation',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Operations',exact:true})).toBeVisible();await expect(page.getByText('New learning work is disabled. Eligible reads, withdrawal, reconciliation and cleanup remain available.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Synthetic original baseline practice',exact:true})).toBeVisible();await expect(page.getByText(/published Unknown/)).toBeVisible();
 expect(await page.locator('body').innerText()).not.toContain('participantCount');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>v.id)).toEqual([]);await page.screenshot({path:test.info().outputPath('learning-health.png'),fullPage:true});
 await withLearningDatabase(async db=>{await db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE current_accepted_revision_id=$1',[f.lineage.sourceRevisionId]);});await page.getByRole('button',{name:'Refresh Learning Health',exact:true}).click();await expect(page.getByRole('heading',{name:'Synthetic original baseline practice',exact:true})).toHaveCount(0);await expect(page.getByText('No currently eligible practices on this authorized page.',{exact:true})).toBeVisible();
 const originalSchema=await withLearningDatabase(async db=>(await db.query('SELECT schema_version FROM turas_environment')).rows[0].schema_version);await withLearningDatabase(async db=>{await db.query('UPDATE turas_environment SET schema_version=51');});try{await page.reload();await expect(page.getByRole('status').filter({hasText:'Learning is unavailable'})).toBeVisible();await expect(page.getByRole('heading',{name:'Evidence Quality',exact:true})).toHaveCount(0);}finally{await withLearningDatabase(async db=>{await db.query('UPDATE turas_environment SET schema_version=$1',[originalSchema]);});}
 await page.context().addCookies([cookie(f.actors.partner.token)]);await page.reload();await expect(page.getByRole('status').filter({hasText:'Action not allowed'})).toBeVisible();await expect(page.getByRole('heading',{name:'Evidence Quality',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Open Due Practice Review',exact:true})).toHaveCount(0);
});

test('due review remains a metadata handoff while disabled and never admits research automatically',async({page})=>{
 const f=await withLearningDatabase(async db=>{const fixture=await learningMeasurementPopulation(db,1);await createLearningMeasurement(fixture.actors.member,fixture.measurements[0].input);await markDueLearningReviews(db,new Date(Date.now()+172800000));await db.query('UPDATE learning_workspace_state SET enabled=false WHERE workspace_id=$1',[fixture.workspaceId]);await db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE current_accepted_revision_id=$1',[fixture.measurements[0].original.sourceRevisionId]);return fixture;});
 await page.context().addCookies([{name:'turas_session',value:f.actors.member.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax'}]);const before=await withLearningDatabase(async db=>(await db.query('SELECT count(*)::int n FROM research_requests')).rows[0].n);
 await page.goto('/learning/health');await page.getByRole('link',{name:'Open Due Evidence Review',exact:true}).click();await expect(page.getByRole('heading',{name:'Due Evidence Review',exact:true})).toBeVisible();await expect(page.getByText('New learning work is disabled. Review and cleanup remain available.',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open Research Admission',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Open Current Review',exact:true})).toBeVisible();expect(await withLearningDatabase(async db=>(await db.query('SELECT count(*)::int n FROM research_requests')).rows[0].n)).toBe(before);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>v.id)).toEqual([]);
 await page.context().addCookies([{name:'turas_session',value:f.actors.partner.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax'}]);await page.reload();await expect(page.getByRole('status').filter({hasText:'Action not allowed'})).toBeVisible();await expect(page.getByRole('link',{name:'Open Current Review',exact:true})).toHaveCount(0);
});
