import {randomUUID} from 'node:crypto';
import {createKnowledgeCandidate,reviseKnowledgeCandidate} from '../../lib/server/knowledge/service';
import {readKnowledgeCandidate,readKnowledgeLineage} from '../../lib/server/knowledge/lineage';
import AxeBuilder from '@axe-core/playwright';
import {test,expect,type Page} from '@playwright/test';
import {withLearningDatabase} from '../fixtures/learning/environment';
import {learningTestActors,learningPartnerPeer} from '../fixtures/learning/setup';
import type {CurrentSession} from '../../lib/server/auth/sessions';
async function session(page:Page,actor:CurrentSession){await page.context().addCookies([{name:'turas_session',value:actor.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax'}]);}
test.beforeEach(()=>{if(process.env.TURAS_LEARNING_UI_FIXTURE_READY!=='1')throw Error('Owned learning UI runner required');});
test('partner submits an unverified observation, edits it and retains private access',async({page})=>{
 const actors=await withLearningDatabase(learningTestActors),peer=await withLearningDatabase(db=>learningPartnerPeer(db));
 await session(page,actors.partner);await page.goto('/knowledge');await page.getByRole('article').filter({has:page.getByRole('heading',{name:'Canonical synthetic learning practice',exact:true})}).getByRole('button',{name:'Read guidance',exact:true}).click();await page.getByRole('button',{name:'Give Feedback',exact:true}).click();await expect(page.getByRole('heading',{name:'Feedback on This Revision'})).toBeFocused();
 await page.getByRole('textbox',{name:'Your Observation',exact:true}).fill('PRIVATE_SYNTHETIC_LEARNING_OBSERVATION');await page.getByRole('button',{name:'Submit Feedback',exact:true}).click();await page.getByRole('link',{name:'View My Feedback',exact:true}).click();
 await expect(page.getByText('PRIVATE_SYNTHETIC_LEARNING_OBSERVATION',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit My Observation',exact:true}).click();await page.getByRole('textbox',{name:'Revised Observation',exact:true}).fill('PRIVATE_SYNTHETIC_CORRECTED_OBSERVATION');await page.getByRole('button',{name:'Save Observation',exact:true}).click();await expect(page.getByText('PRIVATE_SYNTHETIC_CORRECTED_OBSERVATION',{exact:true})).toBeVisible();
 const url=page.url(),title=`Synthetic feedback practice ${randomUUID().slice(0,8)}`;
 const candidate=await withLearningDatabase(async db=>{const row=(await db.query("SELECT c.id FROM knowledge_contributions c JOIN knowledge_publications p ON p.contribution_id=c.id JOIN knowledge_revision_payloads payload ON payload.revision_id=p.revision_id WHERE payload.payload->>'title'='Canonical synthetic learning practice' AND c.workspace_id=$1 LIMIT 1",[actors.member.workspaceId])).rows[0];const original=await readKnowledgeCandidate(db,actors.member,row.id),lineage=await readKnowledgeLineage(db,actors.member,row.id),payload={...original.payload,title};return {...await createKnowledgeCandidate(db,actors.member,{idempotencyKey:randomUUID(),customerId:original.customerId,lineage,payload}),payload,lineage};});
 await session(page,actors.member);await page.goto(url);await page.getByRole('combobox',{name:'Disposition',exact:true}).selectOption('linked');const picker=page.getByRole('combobox',{name:'Current Accessible Candidate',exact:true});await expect(picker).toBeEnabled();await picker.selectOption({label:`${title} · Revision 1`});await expect(page.getByLabel('Exact Candidate Revision ID',{exact:true})).toHaveCount(0);
 await page.getByLabel('Internal Rationale',{exact:true}).fill('Separately proposed current revision; linking grants no reuse or access.');await page.getByRole('button',{name:'Record Disposition',exact:true}).click();await expect(page.getByText('Disposition: Linked',{exact:true})).toBeVisible();
 await picker.selectOption({label:`${title} · Revision 1`});await withLearningDatabase(db=>reviseKnowledgeCandidate(db,actors.member,candidate.id,{idempotencyKey:randomUUID(),expectedRevision:1,expectedDigest:candidate.digest,lineage:candidate.lineage,payload:{...candidate.payload,title:`${title} revised`}}));await page.getByRole('button',{name:'Refresh Accessible Candidates',exact:true}).click();await expect(picker).toHaveValue('');await expect(picker.locator('option').filter({hasText:`${title} revised · Revision 2`})).toHaveCount(1);await expect(page.getByRole('button',{name:'Record Disposition',exact:true})).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>v.id)).toEqual([]);
 expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain('PRIVATE_SYNTHETIC');await session(page,peer);await page.goto(url);await expect(page.getByText('PRIVATE_SYNTHETIC_CORRECTED_OBSERVATION',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit My Observation',exact:true})).toHaveCount(0);
});
