import AxeBuilder from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {test,expect} from '@playwright/test';
import {withLearningDatabase} from '../fixtures/learning/environment';
import {learningMeasurementPopulation} from '../fixtures/learning/accepted-measurements';
import {createLearningMeasurement,readLearningMeasurement,reviewLearningMeasurement} from '../../lib/server/learning/measurements';
test.beforeEach(()=>{if(process.env.TURAS_LEARNING_UI_FIXTURE_READY!=='1')throw Error('Owned learning UI runner required');});
test('private review releases one fixed summary and source loss withholds it without replacement or partner disclosure',async({page})=>{
 const fixture=await withLearningDatabase(async db=>{
  const f=await learningMeasurementPopulation(db),ids=[];
  for(let index=0;index<5;index++){const created=await createLearningMeasurement(f.actors.member,f.measurements[index].input);ids.push(created.targetId!);if(index<4){const view=await readLearningMeasurement(f.actors.admin,created.targetId!);await reviewLearningMeasurement(f.actors.admin,view.id,{contractVersion:'learning-v1',requestId:randomUUID(),expectedVersion:view.version,revisionId:view.revisionId,closureDigest:view.closureDigest,decision:'approve',reuseApproved:true,rationale:'Synthetic complete population and separate reuse review'});}}
  return {...f,ids};
 });
 await page.context().addCookies([{name:'turas_session',value:fixture.actors.admin.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax'}]);await page.goto('/learning/trends');await page.getByRole('combobox',{name:'Completed UTC Quarter',exact:true}).selectOption('2026-Q3');await expect(page.getByRole('heading',{name:'Comparable Summary Unavailable',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Release Fixed Quarterly Summary',exact:true}).click();await expect(page.locator('section.profile-page').getByRole('alert')).toHaveText('Comparable outcome summary unavailable');await page.getByRole('button',{name:'Check Outcome Release Status',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'No committed result found'})).toContainText('No committed result found');await page.getByRole('button',{name:'Close Outcome Release Request',exact:true}).click();await expect(page.getByRole('button',{name:'Close Outcome Release Request',exact:true})).toHaveCount(0);
 await page.goto(`/learning/measurements/${fixture.ids[4]}`);await page.getByRole('button',{name:'Read Measurement Original 1',exact:true}).click();await expect(page.getByRole('heading',{name:'Current Accepted Original',exact:true})).toBeVisible();await expect(page.getByText('Total elapsed minutes: 10',{exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Measurement Decision',exact:true}).selectOption('approve');const rights=page.getByRole('checkbox',{name:'I verified comparable complete populations and original measurement reuse rights',exact:true}),record=page.getByRole('button',{name:'Record Measurement Reuse Decision',exact:true});await expect(rights).not.toBeChecked();await expect(record).toBeDisabled();await rights.check();await page.getByRole('textbox',{name:'Measurement Review Rationale',exact:true}).fill('PRIVATE_SYNTHETIC_MEASUREMENT_REVIEW');await record.click();await expect(record).toHaveCount(0);
 await page.goto('/learning/trends');await page.getByRole('combobox',{name:'Completed UTC Quarter',exact:true}).selectOption('2026-Q3');await page.getByRole('button',{name:'Release Fixed Quarterly Summary',exact:true}).click();await expect(page.getByRole('heading',{name:'Observed Mean Change',exact:true})).toBeVisible();await expect(page.getByText('+2.00 minutes',{exact:true})).toBeVisible();await expect(page.getByText('Equal customer weighting. Observed change does not establish causation.',{exact:true})).toBeVisible();await expect(page.getByText('Baseline: 2026-07-01 to 2026-07-15 (exclusive), UTC.',{exact:true})).toBeVisible();await expect(page.getByText('Current: 2026-09-17 to 2026-10-01 (exclusive), UTC.',{exact:true})).toBeVisible();
 expect(await page.locator('body').innerText()).not.toContain('Synthetic measurement customer');expect(await page.locator('body').innerText()).not.toContain(fixture.customerId);expect(await page.locator('body').innerText()).not.toContain('All deployments:');expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>v.id)).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('learning-trends.png'),fullPage:true});
 await withLearningDatabase(async db=>{await db.query('UPDATE profile_records SET current_accepted_revision_id=NULL WHERE current_accepted_revision_id=$1',[fixture.measurements[0].original.sourceRevisionId]);});await page.getByRole('button',{name:'Refresh Outcome Summary',exact:true}).click();await expect(page.getByRole('heading',{name:'Comparable Summary Unavailable',exact:true})).toBeVisible();await expect(page.getByText('+2.00 minutes',{exact:true})).toHaveCount(0);
 await withLearningDatabase(async db=>{await db.query('UPDATE profile_records SET current_accepted_revision_id=$1 WHERE id=(SELECT record_id FROM profile_revisions WHERE id=$1)',[fixture.measurements[0].original.sourceRevisionId]);});await page.reload();await page.getByRole('combobox',{name:'Completed UTC Quarter',exact:true}).selectOption('2026-Q3');await expect(page.getByRole('heading',{name:'Comparable Summary Unavailable',exact:true})).toBeVisible();await page.getByRole('button',{name:'Release Fixed Quarterly Summary',exact:true}).click();await expect(page.locator('section.profile-page').getByRole('alert')).toHaveText('Comparable outcome summary unavailable');await page.getByRole('button',{name:'Close Outcome Release Request',exact:true}).click();
 expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain('PRIVATE_SYNTHETIC');await page.context().addCookies([{name:'turas_session',value:fixture.actors.partner.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:'Lax'}]);await page.goto('/learning/trends');await expect(page.getByRole('combobox',{name:'Outcome Metric',exact:true})).toHaveCount(0);await page.goto(`/learning/measurements/${fixture.ids[4]}`);await expect(page.getByText('Total elapsed minutes: 10',{exact:true})).toHaveCount(0);
});
