import AxeBuilder from "@axe-core/playwright";
import {test,expect,type Page} from "@playwright/test";
import type {CurrentSession} from "../../lib/server/auth/sessions";
import {randomUUID} from "node:crypto";
import {partnerGuideFixture,partnerCommandEnvelope} from "../fixtures/partners/guides";
import {withPartnerDatabase} from "../fixtures/partners/environment";
import {partnerAdditionalMember} from "../fixtures/partners/seed";
import {previewPartnerAssignment,decidePartnerAssignment,readPartnerAssignment} from "../../lib/server/partners/assignments";
async function session(page:Page,actor:CurrentSession){await page.context().addCookies([{name:"turas_session",value:actor.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:"Lax"}]);}
test.beforeEach(async()=>{if(process.env.TURAS_PARTNERS_UI_FIXTURE_READY!=="1")throw Error("Owned partner UI runner required");await withPartnerDatabase(db=>db.query("DELETE FROM partner_rate_windows WHERE environment_id=$1",[process.env.TURAS_ENVIRONMENT_ID]));});
test("reconciles a committed draft after a lost acknowledgment without persisting or repeating its prose",async({page})=>{
 const f=await partnerGuideFixture(`Synthetic lost acknowledgment ${test.info().project.name}`,true),input={...partnerCommandEnvelope(),action:"assignment.create",guideId:f.guideId,revisionId:f.revisionId,membershipId:f.partner.membershipId,rationale:"Synthetic lost acknowledgment assignment",selfReview:false},preview=await previewPartnerAssignment(f.reviewer,input),assigned=await decidePartnerAssignment(f.reviewer,{...input,requestId:randomUUID(),previewId:preview.previewId});await session(page,f.partner);const initialResponse=await page.request.get(`/api/partners/assignments/${assigned.targetId}`);expect(initialResponse.ok()).toBe(true);const earlierProjection=await initialResponse.json();await page.goto(`/partners/assignments/${assigned.targetId}`);await page.getByRole("button",{name:"Record Demonstration",exact:true}).click();await page.getByLabel("What You Attempted",{exact:true}).fill("PRIVATE_SYNTHETIC_ATTEMPT_INPUT");await page.getByLabel("Observed Result",{exact:true}).fill("PRIVATE_SYNTHETIC_LOST_RECEIPT_RESULT");
 let committedLostAcknowledgment!:()=>void;const lostAcknowledgment=new Promise<void>(resolve=>{committedLostAcknowledgment=resolve;});let commands=0;await page.route("**/api/partners/requests/*",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:{code:"unavailable"}})}));await page.route("**/api/partners/commands",async route=>{commands++;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort();committedLostAcknowledgment();});await page.getByRole("button",{name:"Save Checkpoint Draft",exact:true}).click();await lostAcknowledgment;await expect(page.getByRole("button",{name:"Resolve Old Request",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Save Checkpoint Draft",exact:true})).toBeDisabled();
 const values=await page.evaluate(()=>Object.entries(sessionStorage).filter(([key])=>key.startsWith("turas.partner.pending:")).map(([,value])=>JSON.parse(value)));expect(values).toHaveLength(1);expect(Object.keys(values[0]).sort()).toEqual(["contractVersion","requestId","targetId"].sort());expect(JSON.stringify(values)).not.toContain("PRIVATE_SYNTHETIC");await page.unroute("**/api/partners/requests/*");let committedReceiptObserved=false;
 await page.route("**/api/partners/requests/*",async route=>{const response=await route.fetch();const envelope=await response.json();if(response.ok()&&envelope.data?.outcome==="committed")committedReceiptObserved=true;await route.fulfill({response});});
 await page.route(`**/api/partners/assignments/${assigned.targetId}`,route=>committedReceiptObserved?route.continue():route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(earlierProjection)}));await page.reload();await expect(page.getByText("Request confirmed.",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Resolve Old Request",exact:true})).toHaveCount(0);await expect(page.getByTestId("partner-protected-body")).toContainText("PRIVATE_SYNTHETIC_LOST_RECEIPT_RESULT");expect(commands).toBe(1);await withPartnerDatabase(async db=>{expect((await db.query("SELECT count(*)::int AS n FROM partner_checkpoint_attempts WHERE assignment_id=$1",[assigned.targetId])).rows[0].n).toBe(1);});await page.unrouteAll({behavior:"wait"});
});
test("resolves an absent request after reload before allowing a new demonstration",async({page})=>{
 const f=await partnerGuideFixture(`Synthetic absent request ${test.info().project.name}`,true),input={...partnerCommandEnvelope(),action:"assignment.create",guideId:f.guideId,revisionId:f.revisionId,membershipId:f.partner.membershipId,rationale:"Synthetic absent request assignment",selfReview:false},preview=await previewPartnerAssignment(f.reviewer,input),assigned=await decidePartnerAssignment(f.reviewer,{...input,requestId:randomUUID(),previewId:preview.previewId});await session(page,f.partner);await page.goto(`/partners/assignments/${assigned.targetId}`);await page.getByRole("button",{name:"Record Demonstration",exact:true}).click();await page.getByLabel("What You Attempted",{exact:true}).fill("Synthetic undispatched draft");await page.getByLabel("Observed Result",{exact:true}).fill("Synthetic undispatched result");let requestId="",intercepted!:()=>void;const undispatched=new Promise<void>(resolve=>{intercepted=resolve;});await page.route("**/api/partners/commands",async route=>{requestId=route.request().postDataJSON().requestId;await route.abort();intercepted();});await page.getByRole("button",{name:"Save Checkpoint Draft",exact:true}).click();await undispatched;await expect(page.getByRole("button",{name:"Resolve Old Request",exact:true})).toBeVisible({timeout:15000});await page.reload();await expect(page.getByRole("button",{name:"Record Demonstration",exact:true})).toBeDisabled();await expect(page.getByText("No committed request was found. Resolve the old request before starting a new action.",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Resolve Old Request",exact:true}).click();await expect(page.getByRole("button",{name:"Record Demonstration",exact:true})).toBeEnabled();await withPartnerDatabase(async db=>{expect((await db.query("SELECT outcome FROM partner_commands WHERE request_id=$1",[requestId])).rows[0].outcome).toBe("abandoned");expect((await db.query("SELECT count(*)::int AS n FROM partner_checkpoint_attempts WHERE assignment_id=$1",[assigned.targetId])).rows[0].n).toBe(0);});await page.unrouteAll({behavior:"wait"});
});
test("reviews an individually evidenced demonstration and starts an explicit replacement at zero",async({page})=>{
 test.setTimeout(90000);const f=await partnerGuideFixture(`Synthetic browser learning ${test.info().project.name}`,true,undefined,`Synthetic demonstrated delivery result ${test.info().project.name}`),peer=await withPartnerDatabase(db=>partnerAdditionalMember(db));
 const assign=async(member:CurrentSession)=>{const input={...partnerCommandEnvelope(),action:"assignment.create",guideId:f.guideId,revisionId:f.revisionId,membershipId:member.membershipId,rationale:"Synthetic individual reviewed learning assignment",selfReview:false},preview=await previewPartnerAssignment(f.reviewer,input);return decidePartnerAssignment(f.reviewer,{...input,requestId:randomUUID(),previewId:preview.previewId});};const own=await assign(f.partner),other=await assign(peer);
 await session(page,f.partner);await page.goto(`/partners/assignments/${own.targetId}`);await expect(page.getByText("0 of 1 required checkpoints verified · 0%",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Record Demonstration",exact:true}).click();await page.getByLabel("What You Attempted",{exact:true}).fill("Synthetic browser demonstrated delivery practice");await page.getByLabel("Observed Result",{exact:true}).fill("Synthetic independently accepted observed result");await page.getByLabel("Search Reviewed Evidence",{exact:true}).fill(`Synthetic demonstrated delivery result ${test.info().project.name}`);await page.getByRole("checkbox",{name:new RegExp(`Synthetic demonstrated delivery result ${test.info().project.name}`)}).check();await page.getByRole("button",{name:"Save Checkpoint Draft",exact:true}).click();await page.getByRole("button",{name:"Submit Demonstration",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("Awaiting review");
 await session(page,peer);await page.goto(`/partners/assignments/${own.targetId}`);await expect(page.getByTestId("partner-protected-body")).toHaveCount(0);expect(await page.textContent("body")).not.toContain("Synthetic independently accepted observed result");expect((await readPartnerAssignment(peer,other.targetId!)).progress?.percentage).toBe(0);
 await session(page,f.reviewer);await page.goto(`/partners/assignments/${own.targetId}`);await page.getByRole("combobox",{name:"Checkpoint Decision",exact:true}).selectOption("checkpoint.request_changes");await page.getByLabel("Checkpoint Review Rationale",{exact:true}).fill("Clarify the reviewed observed result");await page.getByRole("button",{name:"Prepare Checkpoint Review",exact:true}).click();await page.getByRole("button",{name:"Confirm Checkpoint Decision",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("Changes requested");
 await session(page,f.partner);await page.goto(`/partners/assignments/${own.targetId}`);await page.getByRole("button",{name:"Record Demonstration",exact:true}).click();await page.getByLabel("What You Attempted",{exact:true}).fill("Synthetic corrected delivery demonstration");await page.getByLabel("Observed Result",{exact:true}).fill("Synthetic corrected independently accepted result");await page.getByLabel("Search Reviewed Evidence",{exact:true}).fill(`Synthetic demonstrated delivery result ${test.info().project.name}`);await page.getByRole("checkbox",{name:new RegExp(`Synthetic demonstrated delivery result ${test.info().project.name}`)}).check();await page.getByRole("button",{name:"Save Checkpoint Draft",exact:true}).click();await page.getByRole("button",{name:"Submit Demonstration",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("Awaiting review");
 await session(page,f.reviewer);await page.goto(`/partners/assignments/${own.targetId}`);await page.getByLabel("Checkpoint Review Rationale",{exact:true}).fill("Separately accepted evidence supports the demonstrated criterion");await page.getByRole("button",{name:"Prepare Checkpoint Review",exact:true}).click();await expect(page.getByRole("heading",{name:"Exact Checkpoint Preview",exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>["serious","critical"].includes(v.impact??"")).map(v=>v.id)).toEqual([]);
 await page.screenshot({path:test.info().outputPath("synthetic-checkpoint-review.png"),fullPage:true});
 await page.getByRole("button",{name:"Cancel Checkpoint Review",exact:true}).click();await expect(page.getByRole("button",{name:"Prepare Checkpoint Review",exact:true})).toBeFocused();await page.getByRole("button",{name:"Prepare Checkpoint Review",exact:true}).click();await page.getByRole("button",{name:"Confirm Checkpoint Decision",exact:true}).click();await expect(page.getByText("1 of 1 required checkpoints verified · 100%",{exact:true})).toBeVisible();
 await page.getByRole("combobox",{name:"Assignment Action",exact:true}).selectOption("assignment.replace");await page.getByLabel("Assignment Rationale",{exact:true}).fill("Start a separate reviewed learning cycle");await page.getByRole("button",{name:"Prepare Assignment Action",exact:true}).click();await page.getByRole("button",{name:"Confirm Assignment Action",exact:true}).click();await expect(page.getByText("0 of 1 required checkpoints verified · 0%",{exact:true})).toBeVisible();await page.screenshot({path:test.info().outputPath("synthetic-learning.png"),fullPage:true});expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain("Synthetic corrected independently accepted result");
});
