import { test,expect,type Page } from "@playwright/test";
import type { CurrentSession } from "../../lib/server/auth/sessions";
import { partnerGuideFixture } from "../fixtures/partners/guides";
import { partnerTestActors,partnerDeliveryBaseline } from "../fixtures/partners/seed";
import { partnerAcceptedEvidence } from "../fixtures/partners/originals";
import { withPartnerDatabase } from "../fixtures/partners/environment";
import { DEMO_IDS } from "../../lib/server/bootstrap-ids";
async function session(page:Page,actor:CurrentSession){await page.context().addCookies([{name:"turas_session",value:actor.token,url:process.env.TURAS_UI_BASE_URL!,httpOnly:true,sameSite:"Lax"}]);}
test.beforeEach(async()=>{if(process.env.TURAS_PARTNERS_UI_FIXTURE_READY!=="1")throw Error("Owned partner UI runner required");await withPartnerDatabase(db=>db.query("DELETE FROM partner_rate_windows WHERE environment_id=$1",[process.env.TURAS_ENVIRONMENT_ID]));});
test("publishes an exact reviewed guide, follows its lessons and isolates a rejected replacement",async({page})=>{
 test.setTimeout(90000);
 const f=await partnerGuideFixture(`Synthetic browser reviewed guide ${test.info().project.name}`);await session(page,f.reviewer);await page.goto(`/partners/guides/${f.guideId}`);await expect(page.getByRole("heading",{name:f.content.title,exact:true})).toBeVisible();
 await page.getByLabel("Guide Review Rationale").fill("Exact synthetic evidence review for this guide");await page.getByRole("button",{name:"Prepare Guide Review",exact:true}).click();await expect(page.getByRole("heading",{name:"Exact Decision Preview",exact:true})).toBeVisible();await page.getByRole("button",{name:"Confirm Guide Decision",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("published");
 await session(page,f.partner);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByText("Signed in as partner",{exact:true})).toHaveCount(1);await expect(page.getByRole("link",{name:"Planning Finance",exact:true})).toHaveCount(0);await expect(page.getByRole("heading",{name:"Lesson 1: Demonstrate the reviewed customer delivery practice",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Edit Guide Draft",exact:true})).toHaveCount(0);await expect(page.getByRole("heading",{name:"Review Exact Guide",exact:true})).toHaveCount(0);
 await session(page,f.author);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await page.getByRole("button",{name:"Edit Guide Draft",exact:true}).click();await page.getByLabel("Guide Title",{exact:true}).fill("Synthetic replacement still awaiting review");await page.getByRole("button",{name:"Save Guide Draft",exact:true}).click();await page.getByRole("button",{name:"Submit Guide for Review",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("submitted");
 await session(page,f.partner);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByRole("heading",{name:f.content.title,exact:true})).toBeVisible();await expect(page.getByText("Synthetic replacement still awaiting review",{exact:true})).toHaveCount(0);
 await session(page,f.reviewer);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByRole("heading",{name:"Synthetic replacement still awaiting review",exact:true})).toBeVisible();await page.getByRole("combobox",{name:"Guide Decision",exact:true}).selectOption("guide.reject");await page.getByLabel("Guide Review Rationale",{exact:true}).fill("Keep the prior publication while the author corrects this draft");await page.getByRole("button",{name:"Prepare Guide Review",exact:true}).click();await page.getByRole("button",{name:"Confirm Guide Decision",exact:true}).click();await expect(page.getByTestId("partner-protected-body")).toContainText("rejected");
 await session(page,f.partner);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByRole("heading",{name:f.content.title,exact:true})).toBeVisible();await page.screenshot({path:test.info().outputPath("synthetic-guide.png"),fullPage:true});
});
test("authors a structured guide from current evidence using ordinary form fields",async({page})=>{
 const f=await withPartnerDatabase(async db=>{const actors=await partnerTestActors(db);await db.query("BEGIN");try{const baseline=await partnerDeliveryBaseline(db,actors.author,actors.reviewer);await db.query("COMMIT");return {...actors,baseline};}catch(error){await db.query("ROLLBACK");throw error;}}),description=`Synthetic browser authoring evidence ${test.info().project.name}`;await partnerAcceptedEvidence(f.author,f.reviewer,DEMO_IDS.sharedCustomer,description);await session(page,f.author);await page.goto(`/partners/guides/new?customerId=${DEMO_IDS.sharedCustomer}&engagementId=${f.baseline.engagementId}`);
 await page.getByLabel("Guide Title",{exact:true}).fill(`Synthetic authored browser guide ${test.info().project.name}`);await page.getByLabel("Search Reviewed Evidence",{exact:true}).fill(description);await page.getByRole("checkbox",{name:new RegExp(description)}).check();
 for(const label of ["Objective","What to Do","How to Do It","Why It Works","Alternatives","Limitations","Validation","Escalation"])await page.getByLabel(`${label} — Lesson 1`,{exact:true}).fill(`Synthetic reviewed ${label.toLowerCase()} instruction`);
 await page.getByRole("group",{name:"Lesson 1",exact:true}).getByRole("group",{name:"Supporting Sources",exact:true}).getByRole("checkbox").check();await page.getByLabel("Checkpoint Title — 1",{exact:true}).fill("Synthetic demonstrated checkpoint");await page.getByLabel("Demonstration Criterion — 1",{exact:true}).fill("Show separately accepted evidence of this reviewed delivery practice");await page.getByRole("group",{name:"Checkpoint 1",exact:true}).getByRole("group",{name:"Supporting Sources",exact:true}).getByRole("checkbox").check();await page.getByRole("button",{name:"Save Guide Draft",exact:true}).click();await expect(page).toHaveURL(/\/partners\/guides\/[a-f0-9-]{36}$/);await expect(page.getByRole("heading",{name:`Synthetic authored browser guide ${test.info().project.name}`,exact:true})).toBeVisible();
});
test("withholds a published lesson immediately after source withdrawal without a cleanup worker",async({page})=>{
 const f=await partnerGuideFixture(`Synthetic withdrawn browser guide ${test.info().project.name}`,true);await session(page,f.partner);await page.goto(`/partners/guides/${f.guideId}`);await expect(page.getByRole("heading",{name:f.content.title,exact:true})).toBeVisible();await withPartnerDatabase(db=>db.query("UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=$1",[f.evidence!.recordId]));await page.getByRole("button",{name:"Refresh Guide",exact:true}).click();await expect(page.getByRole("heading",{name:f.content.title,exact:true})).toHaveCount(0);await expect(page.getByTestId("partner-protected-body")).toContainText("source unavailable");expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain(f.content.title);
});
