import { z } from "zod";
import { artifactLocatorSchema } from "./artifacts";

export const retrievalContractVersion = "retrieval-v1" as const;
export const embeddingContractVersion = "embedding-v1" as const;

// C01. Client bodies may reference existing IDs; new IDs are generated by services.
export const governedIdSchema = z.uuid();
export const positiveRevisionSchema = z.number().int().positive();
export const sha256Schema = z.string().regex(/^[0-9a-f]{64}$/);
export const idempotencyKeySchema = z.string().min(1).max(128);
export const utcTimestampSchema = z.iso.datetime({ offset: false }).refine(
  (value) => !Number.isNaN(Date.parse(value)) && value.endsWith("Z"),
  "Canonical UTC timestamp required",
);
export const writeEnvelopeFields = {
  idempotencyKey: idempotencyKeySchema,
  expectedRevision: positiveRevisionSchema,
  expectedDigest: sha256Schema,
};
export const writeEnvelopeSchema = z.object(writeEnvelopeFields).strict();

export const retrievalScopeSchema = z.enum(["customer", "shared", "combined"]);
export const retrievalUseSchema = z.enum(["discovery", "current_fact"]);
export const retrievalSourceKindSchema = z.enum([
  "accepted_profile", "approved_excerpt", "verified_research", "published_shared",
]);
export const retrievalSearchSchema = z.object({
  scope: retrievalScopeSchema,
  customerId: governedIdSchema.optional(),
  workloadId: governedIdSchema.optional(),
  query: z.string().trim().min(1).max(500),
  use: retrievalUseSchema.default("discovery"),
  limit: z.number().int().min(1).max(10).default(5),
}).strict().superRefine((input, context) => {
  if (input.scope === "shared" && (input.customerId || input.workloadId)) {
    context.addIssue({ code: "custom", path: ["scope"], message: "Shared search has no customer selector" });
  }
  if (input.scope !== "shared" && !input.customerId) {
    context.addIssue({ code: "custom", path: ["customerId"], message: "Customer required" });
  }
});
export type RetrievalSearchInput = z.infer<typeof retrievalSearchSchema>;

const locatorCommon = {
  start: z.number().int().nonnegative(),
  end: z.number().int().positive(),
};
export const citationLocatorSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("profile_field"), fieldPath: z.string().min(1).max(300) }).strict(),
  z.object({ kind: z.literal("artifact_unit"), unitId: governedIdSchema,
    original: artifactLocatorSchema, ...locatorCommon }).strict(),
  z.object({ kind: z.literal("research_passage"), canonicalUrl: z.url().max(2_048), ...locatorCommon }).strict(),
  z.object({ kind: z.literal("shared_field"), fieldPath: z.string().min(1).max(300), ...locatorCommon }).strict(),
]).refine((locator) => !("start" in locator) || locator.end > locator.start,
  "Text spans must use a positive half-open range");

export const evidenceQualitySchema = z.object({
  rubricVersion: z.literal("evidence-quality-v1"),
  R: z.number().int().min(0).max(4),
  F: z.number().int().min(0).max(4),
  D: z.number().int().min(0).max(4),
  C: z.number().int().min(0).max(4),
  Q: z.number().int().min(0).max(100),
  band: z.enum(["strong", "usable", "weak", "insufficient"]),
  freshness: z.enum(["Recent", "Aging", "Stale", "Unknown"]),
  rationale: z.string().max(2_000),
  asOf: utcTimestampSchema,
  validUntil: utcTimestampSchema,
}).strict();

export const retrievalResultSchema = z.object({
  citationId: governedIdSchema,
  sourceKind: retrievalSourceKindSchema,
  sourceRevisionId: governedIdSchema,
  passageDigest: sha256Schema,
  title: z.string().min(1).max(200),
  text: z.string().min(1).max(2_000),
  locators: z.array(citationLocatorSchema).min(1).max(50),
  quality: evidenceQualitySchema,
  caveats: z.array(z.string().max(500)).max(10),
  warnings: z.array(z.string().max(500)).max(10),
  productVersion: z.string().max(200).nullable(),
}).strict();
export const retrievalResponseSchema = z.object({
  version: z.literal(retrievalContractVersion),
  receiptId: governedIdSchema,
  asOf: utcTimestampSchema,
  validUntil: utcTimestampSchema,
  mode: z.enum(["hybrid", "lexical_degraded"]),
  language: z.literal("en"),
  completenessWarnings: z.array(z.string().max(500)).max(10),
  results: z.array(retrievalResultSchema).max(10),
}).strict().refine((value) => new TextEncoder().encode(JSON.stringify(value)).length <= 24_576,
  "Retrieval response exceeds 24 KiB");
export type RetrievalResponse = z.infer<typeof retrievalResponseSchema>;

export const retrievalLimits = {
  queryCharacters: 500,
  passageCharacters: 2_000,
  resultCount: 10,
  resultBytes: 24_576,
  perSourceRevision: 2,
  lexicalCandidates: 30,
  semanticCandidates: 30,
  rrfK: 60,
  embeddingDimensions: 1_536,
  embeddingBatch: 32,
  concurrentEmbeddingCalls: 2,
  embeddingTimeoutMs: 10_000,
  rankingTimeoutMs: 2_000,
  perPrincipalPerMinute: 30,
  activePerEnvironment: 5,
} as const;
