"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {expansionAdvicePrompt,type ExpansionAdviceResult} from '../../../lib/expansion/advice';
import type {readExpansionAdviceStatus} from '../../../lib/server/expansion/advice-status';
import type {ExpansionSource} from '../../../lib/server/expansion/schema';
import type {captureExpansionEvidence} from '../../../lib/server/expansion/evidence';
import {ExpansionEvidence} from './evidence';
import {ExpansionCitation} from './citation';
type Advice=Awaited<ReturnType<typeof readExpansionAdviceStatus>>;
export type ExpansionSuggestion={attemptId:string;outputDigest:string;suggestionIndex:number;content:ExpansionAdviceResult['proposals'][number]['content']};
type Remembered={attemptId?:string;requestKey?:string};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function ExpansionAdvice({customerId,workloadId,scopeGeneration,namespace,csrfToken,records,blocked,editor,onReview,onWithheld}:{customerId:string;workloadId:string|null;scopeGeneration:number;namespace:string;csrfToken:string;records:{id:string;title:string}[];blocked:boolean;editor:boolean;onReview:(suggestion:ExpansionSuggestion,sources:ExpansionSource[],engagements:string[])=>void;onWithheld:()=>void}){
 const [question,setQuestion]=useState('Which customer needs should we validate before considering additional Vercel products?'),[sources,setSources]=useState<ExpansionSource[]>([]),[selected,setSelected]=useState<string[]>([]),[engagements,setEngagements]=useState<string[]>([]),[choices,setChoices]=useState<{engagementId:string;title:string}[]>([]),[inspecting,setInspecting]=useState<ExpansionSource|null>(null);
 const [advice,setAdvice]=useState<Advice|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[remembered,setRemembered]=useState<Remembered|null>(null),[verified,setVerified]=useState(false);
 const active=useRef(false),identity=useRef<Remembered|null>(null),generation=useRef(0),withheld=useRef(onWithheld);withheld.current=onWithheld;
 const base=`/api/expansion/customers/${encodeURIComponent(customerId)}/advice`,storage=`turas-expansion-advice:${namespace}:${workloadId??'customer'}`;
 function remember(value:Remembered|null){identity.current=value;setRemembered(value);try{if(value)sessionStorage.setItem(storage,JSON.stringify(value));else sessionStorage.removeItem(storage);}catch{/* Only opaque identity is cached; memory still fences uncertainty. */}}
 const check=useCallback(async()=>{
  const value=identity.current;if(!value)return;const epoch=++generation.current;
  setVerified(false);
  try{const response=await fetch(value.attemptId?`${base}/${value.attemptId}`:`${base}/receipts/${value.requestKey}`,{cache:'no-store'});const body=await response.json();if(epoch!==generation.current)return;
   if(!response.ok||!body.data)throw Error(body.error?.message??'Advice remains unconfirmed. Check its status before continuing.');
   const current=body.data as Advice;identity.current={attemptId:current.attemptId};setRemembered(identity.current);try{sessionStorage.setItem(storage,JSON.stringify(identity.current));}catch{}
   setAdvice(current);setVerified(current.current&&current.retained);setStatus(current.current&&current.retained?'':'Advice content withheld. Prepare fresh advice with current evidence.');
   if(!current.current||!current.retained)withheld.current();
  }catch(error){if(epoch!==generation.current)return;setAdvice(null);setVerified(false);withheld.current();setStatus(error instanceof Error?error.message:'Advice unavailable.');}
 },[base,storage]);
 useEffect(()=>{generation.current++;identity.current=null;setAdvice(null);setRemembered(null);setVerified(false);setSources([]);setSelected([]);setEngagements([]);setInspecting(null);
  try{const raw=sessionStorage.getItem(storage);if(raw&&raw.length<1024){const value=JSON.parse(raw);if(Object.keys(value).length===1&&(uuid.test(value.attemptId??'')||uuid.test(value.requestKey??''))){identity.current=value;setRemembered(value);void check();}}}catch{}
  const controller=new AbortController();void fetch(`/api/expansion/customers/${customerId}/links${workloadId?`?workloadId=${workloadId}`:''}`,{cache:'no-store',signal:controller.signal}).then(async response=>{const body=await response.json();if(response.ok)setChoices(body.data?.engagements??[]);}).catch(()=>{});return()=>{generation.current++;controller.abort();};
 },[customerId,workloadId,storage,check]);
 useEffect(()=>{if(!remembered)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void check();},advice&&['prepared','running','unconfirmed'].includes(advice.state)?15000:60000);
  const visibility=()=>{if(document.visibilityState==='visible')void check();else{generation.current++;setVerified(false);setInspecting(null);withheld.current();}};
  const blur=()=>{generation.current++;setVerified(false);setInspecting(null);withheld.current();};const focus=()=>void check();document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);window.addEventListener('focus',focus);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur);window.removeEventListener('focus',focus);};
 },[remembered,advice?.state,check]);
 async function post(path:string,input:unknown,extra:Record<string,string>={}){const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrfToken,...extra},body:JSON.stringify(input)});const body=await response.json();if(!response.ok)throw Error(body.error?.message??body.message??'Advice operation unconfirmed. Check its status.');return body;}
 async function dispatch(current:Pick<Advice,'conversationId'|'operationId'|'nativeRequestId'>){const bound=await post('/eve/v1/session',{operationId:current.operationId},{'x-turas-conversation-id':current.conversationId});const response=await fetch(`/eve/v1/session/${encodeURIComponent(bound.sessionId)}`,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrfToken,'x-turas-conversation-id':current.conversationId,'x-turas-request-key':current.nativeRequestId},body:JSON.stringify({message:expansionAdvicePrompt})});await response.body?.cancel();if(!response.ok)throw Error('Advice dispatch unconfirmed. Check its status before continuing.');}
 async function ask(){if(active.current||blocked||editor||remembered)return;active.current=true;setBusy(true);setStatus('Preparing private expansion advice…');const requestKey=crypto.randomUUID();remember({requestKey});try{
   const body=await post(base,{contractVersion:'expansion-v1',expectedVersion:scopeGeneration,requestKey,workloadId,question,sourceRefs:sources,selectedEngagementIds:engagements,selectedHypothesisIds:selected});remember({attemptId:body.data.attemptId});await dispatch(body.data);await check();
  }catch(error){setVerified(false);setStatus(error instanceof Error?error.message:'Advice unconfirmed.');}finally{active.current=false;setBusy(false);}}
 async function stop(){if(active.current||!advice)return;active.current=true;setBusy(true);setVerified(false);withheld.current();try{const body=await post(`${base}/${advice.attemptId}/stop`,{});setAdvice({...advice,state:body.data.state,result:null});if(body.data.nativeSessionId&&body.data.nativeTurnId)try{await post(`/eve/v1/session/${body.data.nativeSessionId}/cancel`,{turnId:body.data.nativeTurnId},{'x-turas-conversation-id':advice.conversationId});}catch{/* Server cancellation already withholds late output. */}await check();}catch(error){setStatus(error instanceof Error?error.message:'Stop unconfirmed.');}finally{active.current=false;setBusy(false);}}
 const ongoing=advice&&['prepared','running','unconfirmed'].includes(advice.state),result=verified&&advice?.state==='completed'?advice.result:null;
 return <section className="profile-section" aria-labelledby="expansion-advice-title"><h2 id="expansion-advice-title">Turi Expansion Advice</h2><p>Choose inputs explicitly. Advice is private; account-owner decisions remain separate human actions.</p>
 {!remembered&&!editor&&<><label htmlFor="expansion-advice-question">Expansion Question<textarea id="expansion-advice-question" className="field" maxLength={2000} value={question} disabled={busy||blocked} onChange={event=>setQuestion(event.target.value)}/></label>
 <fieldset className="profile-card" disabled={busy||blocked}><legend>Hypotheses for Advice</legend>{records.map(record=><label key={record.id}><input type="checkbox" checked={selected.includes(record.id)} disabled={!selected.includes(record.id)&&selected.length>=20} onChange={event=>setSelected(event.target.checked?[...selected,record.id]:selected.filter(id=>id!==record.id))}/>{record.title}</label>)}<p>{selected.length} explicitly selected. Change the list filter to select additional hypotheses.</p><button type="button" className="secondary-button" onClick={()=>setSelected([])}>Clear Hypothesis Selection</button></fieldset>
 <fieldset className="profile-card" disabled={busy||blocked}><legend>Engagements for Advice</legend>{choices.map(choice=><label key={choice.engagementId}><input type="checkbox" checked={engagements.includes(choice.engagementId)} disabled={!engagements.includes(choice.engagementId)&&engagements.length>=10} onChange={event=>setEngagements(event.target.checked?[...engagements,choice.engagementId]:engagements.filter(id=>id!==choice.engagementId))}/>{choice.title}</label>)}</fieldset>
 <ExpansionEvidence customerId={customerId} workloadId={workloadId} csrfToken={csrfToken} selected={sources} onChange={setSources} onInspect={setInspecting}/>
 <button type="button" className="primary-button" disabled={busy||blocked||!question.trim()} onClick={()=>void ask()}>Ask Turi for Expansion Proposals</button></>}
 {inspecting&&!editor&&<ExpansionCitation customerId={customerId} workloadId={workloadId} source={inspecting} onClose={()=>setInspecting(null)}/>}
 {status&&<p role="status">{status}</p>}{advice&&<><p>Advice State: {advice.state}</p><p>Model steps: {advice.modelSteps}/6 · Context reads: {advice.readCalls}/6</p></>}
 {remembered&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>void check()}>Check Advice Status</button>}
 {ongoing&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>void stop()}>Stop Expansion Advice</button>}
 {advice?.state==='prepared'&&verified&&!busy&&<button type="button" className="secondary-button" disabled={blocked||editor} onClick={()=>{setBusy(true);void dispatch(advice).then(check).catch(()=>setStatus('Dispatch unconfirmed. Check advice status.')).finally(()=>setBusy(false));}}>Start Prepared Advice</button>}
 {advice&&!ongoing&&<button type="button" className="secondary-button" disabled={busy||editor||blocked} onClick={()=>{withheld.current();generation.current++;remember(null);setAdvice(null);setVerified(false);setStatus('');}}>Prepare Fresh Advice</button>}
 {result&&<div><h3>Current Advice</h3><p>{result.summary}</p>{result.facts.map((fact,index)=><p key={index}>{fact.classification.replaceAll('_',' ')}: {fact.statement} · Citations: {fact.citationKeys.join(', ')}</p>)}
 {(advice!.evidence as Awaited<ReturnType<typeof captureExpansionEvidence>>).map(source=><details className="profile-card" key={source.citationKey}><summary>Selected Source: {source.title}</summary><p style={{overflowWrap:'anywhere'}}>Citation: {source.citationKey}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{source.text}</p><p>Publication: {source.publicationAt??'Unknown'} · Observation: {source.observationAt??'Unknown'} · Event: {source.eventAt??'Unknown'} · Retrieval: {source.retrievalAt??'Unknown'} · Review: {source.reviewAt??'Unknown'}</p>{'planningReviewedAt' in source&&<p>Planning review: {source.planningReviewedAt} · Planning proposal</p>}<p>Quality: {source.quality?JSON.stringify(source.quality):'Unknown'}</p></details>)}
 <h3>Unknowns</h3>{result.unknowns.map((unknown,index)=><p key={index}>{unknown.text} — {unknown.reason}</p>)}<h3>Discovery Steps</h3>{result.discoverySteps.map((step,index)=><p key={index}>{step.action} · Validate: {step.validationCriterion}</p>)}
 {!result.proposals.length&&<p>No proposals. Use the discovery steps to establish the missing evidence.</p>}
 {result.proposals.map((proposal,index)=><article className="profile-card" key={index}><h3>{proposal.content.title}</h3><p>{proposal.content.problem}</p><p>{proposal.content.customerBenefit}</p><p>Proposed — Owner Review Required</p><p>Citations: {proposal.citationKeys.join(', ')||'None; discovery only'}</p><button type="button" className="secondary-button" disabled={busy||editor||blocked} onClick={()=>onReview({attemptId:advice!.attemptId,outputDigest:advice!.outputDigest!,suggestionIndex:index,content:proposal.content},advice!.sourceRefs as ExpansionSource[],advice!.selectedEngagementIds)}>Review Proposal {index+1}</button></article>)}
 </div>}
 </section>;
}
