"use client";
import { useId } from 'react';
import type { ExpansionHypothesis } from '../../../lib/contracts/expansion';
import type { ExpansionSource } from '../../../lib/server/expansion/schema';
type Structured = Pick<ExpansionHypothesis,'currentUse'|'benefit'|'assertions'|'unknowns'|'prerequisites'|'constraints'|'alternatives'>;
export function ExpansionStructuredFields({value,onChange,sources,owners}:{value:Structured;onChange:(value:Structured)=>void;sources:ExpansionSource[];owners:{id:string;name:string}[]}){
 const prefix=useId();
 const change=<K extends keyof Structured>(key:K,next:Structured[K])=>onChange({...value,[key]:next});
 function text(label:string,value:string,update:(value:string)=>void,max=2000){const id=`${prefix}-${label.replaceAll(' ','-')}`;return <div><label htmlFor={id}>{label}</label><textarea className="field" id={id} maxLength={max} value={value} onChange={event=>update(event.target.value)}/></div>;}
 function select<T extends string>(label:string,value:T,choices:readonly T[],update:(value:T)=>void){const id=`${prefix}-${label.replaceAll(' ','-')}`;return <div><label htmlFor={id}>{label}</label><select className="field" id={id} value={value} onChange={event=>update(event.target.value as T)}>{choices.map(choice=><option key={choice} value={choice}>{choice.replaceAll('_',' ')}</option>)}</select></div>;}
 function sourceKeys(label:string,keys:string[],update:(keys:string[])=>void){return <fieldset><legend>{label}</legend>{sources.length===0?<p>Select evidence above to support this field.</p>:sources.map((source,index)=><label key={source.id}><input type="checkbox" checked={keys.includes(source.id)} onChange={event=>update(event.target.checked?[...keys,source.id]:keys.filter(key=>key!==source.id))}/> Evidence {index+1}: {source.kind.replaceAll('_',' ')}</label>)}</fieldset>;}
 function owner(label:string,id:string|undefined,update:(id:string|undefined)=>void){const control=`${prefix}-${label.replaceAll(' ','-')}`;return <div><label htmlFor={control}>{label}</label><select className="field" id={control} value={id??''} onChange={event=>update(event.target.value||undefined)}><option value="">Unknown / Unassigned</option>{owners.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></div>;}
 const use=value.currentUse,benefit=value.benefit;
 return <details className="profile-section"><summary>Evidence, Benefit, and Validation Details</summary>
  <h3>Current Product Use</h3>{select('Current Use Evidence',use.kind,['unknown','evidenced'],kind=>change('currentUse',kind==='unknown'?{kind,reason:'Actual use has not been established.'}:{kind,state:'unknown',sourceKeys:[]}))}
  {use.kind==='unknown'?text('Current Use Reason',use.reason,reason=>change('currentUse',{...use,reason})): <>{select('Adoption State',use.state,['actual','evaluating','planned','retired','unknown'],state=>change('currentUse',{...use,state}))}{sourceKeys('Current Use Evidence Sources',use.sourceKeys,sourceKeys=>change('currentUse',{...use,sourceKeys}))}</>}
  <h3>Proposed Customer Benefit</h3>{select('Benefit Specificity',benefit.kind,['unknown','qualitative_outcome','measurable_target'],kind=>change('benefit',kind==='unknown'?{kind,reason:'Benefit requires customer validation.'}:kind==='qualitative_outcome'?{kind,rationale:'',validationCriterion:''}:{kind,rationale:'',metric:'',unit:'',target:'',baseline:{kind:'unknown',reason:'No accepted baseline measurement.'},validationCriterion:''}))}
  {benefit.kind==='unknown'?text('Benefit Reason',benefit.reason,reason=>change('benefit',{...benefit,reason})): <>
   {text('Benefit Rationale',benefit.rationale,rationale=>change('benefit',{...benefit,rationale}))}{text('Benefit Validation Criterion',benefit.validationCriterion,validationCriterion=>change('benefit',{...benefit,validationCriterion}))}
   {benefit.kind==='measurable_target'&&<>{text('Proposed Metric',benefit.metric,metric=>change('benefit',{...benefit,metric}),200)}{text('Proposed Unit',benefit.unit,unit=>change('benefit',{...benefit,unit}),200)}{text('Proposed Target',benefit.target,target=>change('benefit',{...benefit,target}),200)}
    {select('Baseline Evidence',benefit.baseline.kind,['unknown','evidenced'],kind=>change('benefit',{...benefit,baseline:kind==='unknown'?{kind,reason:'Baseline has not been measured.'}:{kind,text:'',sourceKeys:[]}}))}
    {benefit.baseline.kind==='unknown'?text('Baseline Unknown Reason',benefit.baseline.reason,reason=>change('benefit',{...benefit,baseline:{kind:'unknown',reason}})):<>{text('Accepted Baseline',benefit.baseline.text,text=>change('benefit',{...benefit,baseline:{...benefit.baseline,kind:'evidenced',text,sourceKeys:benefit.baseline.kind==='evidenced'?benefit.baseline.sourceKeys:[]}}))}{sourceKeys('Baseline Sources',benefit.baseline.sourceKeys,sourceKeys=>change('benefit',{...benefit,baseline:{kind:'evidenced',text:benefit.baseline.kind==='evidenced'?benefit.baseline.text:'',sourceKeys}}))}</>}
   </>}
  </>}
  <h3>Assertions and Attribution</h3><p>Accepted facts require reviewed eligible evidence. Public research remains attributed.</p>
  {value.assertions.map((assertion,index)=>{const update=(next:typeof assertion)=>change('assertions',value.assertions.map((item,i)=>i===index?next:item));return <fieldset key={index}><legend>Assertion {index+1}</legend>
   {select(`Assertion ${index+1} Purpose`,assertion.purpose,['customer_need','product_suitability','current_use','outcome','context'],purpose=>update({...assertion,purpose}))}
   {select(`Assertion ${index+1} Classification`,assertion.classification,['accepted_fact','attributed_observation'],classification=>update({...assertion,classification}))}
   {text(`Assertion ${index+1} Text`,assertion.text,text=>update({...assertion,text}))}{sourceKeys(`Assertion ${index+1} Sources`,assertion.sourceKeys,sourceKeys=>update({...assertion,sourceKeys}))}
   <button type="button" className="secondary-button" onClick={()=>change('assertions',value.assertions.filter((_,i)=>i!==index))}>Remove Assertion {index+1}</button></fieldset>;})}
  <button type="button" className="secondary-button" disabled={value.assertions.length>=20} onClick={()=>change('assertions',[...value.assertions,{purpose:'context',classification:'attributed_observation',text:'',sourceKeys:[]}])}>Add Assertion</button>
  <h3>Prerequisites</h3>{value.prerequisites.map((item,index)=>{const update=(next:typeof item)=>change('prerequisites',value.prerequisites.map((old,i)=>i===index?next:old));return <fieldset key={item.id}><legend>Prerequisite {index+1}</legend>
   {select(`Prerequisite ${index+1} Status`,item.status,['satisfied','validation_needed','blocked'],status=>update({...item,status}))}{text(`Prerequisite ${index+1} Rationale`,item.rationale,rationale=>update({...item,rationale}))}
   {sourceKeys(`Prerequisite ${index+1} Evidence`,item.sourceKeys,sourceKeys=>update({...item,sourceKeys}))}{text(`Prerequisite ${index+1} Unknown Reason`,item.unknownReason??'',unknownReason=>update({...item,unknownReason:unknownReason||undefined}))}
   {item.status==='validation_needed'&&<>{owner(`Prerequisite ${index+1} Owner`,item.ownerMembershipId,ownerMembershipId=>update({...item,ownerMembershipId}))}{text(`Prerequisite ${index+1} Validation Step`,item.validationStep??'',validationStep=>update({...item,validationStep:validationStep||undefined}))}</>}
   <button type="button" className="secondary-button" onClick={()=>change('prerequisites',value.prerequisites.filter((_,i)=>i!==index))}>Remove Prerequisite {index+1}</button></fieldset>;})}
  <button type="button" className="secondary-button" disabled={value.prerequisites.length>=10} onClick={()=>change('prerequisites',[...value.prerequisites,{id:crypto.randomUUID(),status:'blocked',rationale:'',sourceKeys:[],unknownReason:'Evidence has not been established.'}])}>Add Prerequisite</button>
  <h3>Constraints</h3>{value.constraints.map((item,index)=>{const update=(next:typeof item)=>change('constraints',value.constraints.map((old,i)=>i===index?next:old));return <fieldset key={index}><legend>Constraint {index+1}</legend>
   {text(`Constraint ${index+1} Text`,item.text,text=>update({...item,text}))}{sourceKeys(`Constraint ${index+1} Sources`,item.sourceKeys,sourceKeys=>update({...item,sourceKeys}))}{text(`Constraint ${index+1} Unknown Reason`,item.unknownReason??'',unknownReason=>update({...item,unknownReason:unknownReason||undefined}))}
   <button type="button" className="secondary-button" onClick={()=>change('constraints',value.constraints.filter((_,i)=>i!==index))}>Remove Constraint {index+1}</button></fieldset>;})}
  <button type="button" className="secondary-button" disabled={value.constraints.length>=10} onClick={()=>change('constraints',[...value.constraints,{text:'',sourceKeys:[],unknownReason:'Constraint requires validation.'}])}>Add Constraint</button>
  <h3>Explicit Unknowns</h3>{value.unknowns.map((item,index)=>{const update=(next:typeof item)=>change('unknowns',value.unknowns.map((old,i)=>i===index?next:old));return <fieldset key={index}><legend>Unknown {index+1}</legend>{text(`Unknown ${index+1} Question`,item.text,text=>update({...item,text}))}{text(`Unknown ${index+1} Reason`,item.reason,reason=>update({...item,reason}))}<button type="button" className="secondary-button" onClick={()=>change('unknowns',value.unknowns.filter((_,i)=>i!==index))}>Remove Unknown {index+1}</button></fieldset>;})}
  <button type="button" className="secondary-button" disabled={value.unknowns.length>=20} onClick={()=>change('unknowns',[...value.unknowns,{text:'',reason:''}])}>Add Unknown</button>
  <h3>Other Alternatives</h3>{value.alternatives.filter(item=>item.kind==='other').map((item,index)=>{const others=value.alternatives.filter(item=>item.kind==='other'),retained=value.alternatives.filter(item=>item.kind==='retain_current_practice');const update=(next:typeof item)=>change('alternatives',[...retained,...others.map((old,i)=>i===index?next:old)]);return <fieldset key={index}><legend>Alternative {index+1}</legend>{text(`Alternative ${index+1} Title`,item.title,title=>update({...item,title}),200)}{text(`Alternative ${index+1} Rationale`,item.rationale,rationale=>update({...item,rationale}))}<button type="button" className="secondary-button" onClick={()=>change('alternatives',[...retained,...others.filter((_,i)=>i!==index)])}>Remove Alternative {index+1}</button></fieldset>;})}
  <button type="button" className="secondary-button" disabled={value.alternatives.length>=5} onClick={()=>change('alternatives',[...value.alternatives,{kind:'other',title:'',rationale:''}])}>Add Alternative</button>
 </details>;
}
export type ExpansionStructuredValue=Structured;
