"use client";
import {DeliveryRecords,type DeliveryProps,type DeliveryFields} from "./delivery-records";
import {useExecutionSummary,ReviewedStatus} from "./forecast";
import type {ExecutionRecordContent} from "./types";
export function ExecutionHandoff(props:DeliveryProps){
  const {summary,message}=useExecutionSummary(props.view.engagementId,props.view.generation);
  return <><section className="profile-section" aria-label="Handoff and Closeout"><h2>Handoff and Closeout</h2><p className="muted">Deliverables, receiver acknowledgement, and measured outcomes with retained evidence.</p>
    <p>Delivery state: {props.view.state.replaceAll("_"," ")}</p>{props.view.closeoutReviewRequired&&<p role="status" className="profile-caution">Closeout requires a new review because delivery, time, or supporting evidence changed.</p>}
    <p>Closeout requires every milestone accepted or explicitly waived, resolved or accepted-exception high and critical concerns, no submitted time awaiting review, and an accepted handoff with evidenced receiver acknowledgement.</p>
    <p className="muted">A recorded acknowledgement documents an event and its evidence. It is not an electronic signature.</p>
    {message&&<p role="status">{message}</p>}{summary&&<ReviewedStatus summary={summary}/>}
  </section><DeliveryRecords {...props} kinds={["handoff","closeout","outcome"]} renderFields={HandoffFields} renderContent={HandoffContent}/></>;
}
function HandoffFields({draft,change,view,catalog}:DeliveryFields){
  if(draft.kind==="outcome")return <><label>Outcome status<select className="field" value={draft.status} onChange={e=>{const status=e.target.value as typeof draft.status;change(status==="observed"?{status,measure:draft.measure??"",unit:draft.unit??"",currentValue:"",measurementStart:draft.eventDate,measurementEnd:draft.eventDate,baselineUnknownReason:"No prior comparable measurement",comparisonUnknownReason:"No comparison group",limitationReason:null}:{status,currentValue:null,baselineValue:null,comparisonValue:null,baselineUnknownReason:null,comparisonUnknownReason:null,measurementStart:null,measurementEnd:null,limitationReason:"Measurement has not been collected"});}}><option value="not_measured">Not Measured</option><option value="inconclusive">Inconclusive</option><option value="observed">Observed</option></select></label>
    {draft.status==="observed"?<><div className="profile-form-grid"><label>Outcome measure<input className="field" required maxLength={80} value={draft.measure??""} onChange={e=>change({measure:e.target.value})}/></label><label>Measurement unit<input className="field" required maxLength={80} value={draft.unit??""} onChange={e=>change({unit:e.target.value})}/></label><label>Measured value<input className="field" required inputMode="decimal" value={draft.currentValue??""} onChange={e=>change({currentValue:e.target.value})}/></label>
      <label>Measurement start<input className="field" required type="date" value={draft.measurementStart??""} onChange={e=>change({measurementStart:e.target.value})}/></label><label>Measurement end<input className="field" required type="date" value={draft.measurementEnd??""} onChange={e=>change({measurementEnd:e.target.value})}/></label></div>
      <label>Baseline value (optional)<input className="field" inputMode="decimal" value={draft.baselineValue??""} onChange={e=>change({baselineValue:e.target.value||null,baselineUnknownReason:e.target.value?null:"No prior comparable measurement"})}/></label>{draft.baselineValue===null&&<label>Unknown baseline reason<input className="field" required maxLength={2000} value={draft.baselineUnknownReason??""} onChange={e=>change({baselineUnknownReason:e.target.value})}/></label>}
      <label>Comparison value (optional)<input className="field" inputMode="decimal" value={draft.comparisonValue??""} onChange={e=>change({comparisonValue:e.target.value||null,comparisonUnknownReason:e.target.value?null:"No comparison group"})}/></label>{draft.comparisonValue===null&&<label>Unknown comparison reason<input className="field" required maxLength={2000} value={draft.comparisonUnknownReason??""} onChange={e=>change({comparisonUnknownReason:e.target.value})}/></label>}
      <p className="muted">Select reviewed measurement evidence above. Values retain their entered precision; no maturity change is inferred.</p>
    </>:null}<label>{draft.status==="observed"?"Measurement limitations (optional)":"Outcome limitation"}<textarea className="field" aria-label={draft.status==="observed"?"Measurement limitations (optional)":"Outcome limitation"} required={draft.status!=="observed"} maxLength={2000} value={draft.limitationReason??""} onChange={e=>change({limitationReason:e.target.value||null})}/></label></>;
  if(draft.kind!=="handoff"&&draft.kind!=="closeout")return null;
  const references=draft.references.filter(ref=>catalog.some(r=>r.revisionId===ref.sourceRevisionId));
  return <>{draft.kind==="closeout"&&<label>Accepted handoff<select className="field" required value={draft.handoffRevisionId} onChange={e=>change({handoffRevisionId:e.target.value})}><option value="">Select the exact accepted handoff</option>{catalog.filter(r=>r.kind==="handoff").map(r=><option key={r.revisionId} value={r.revisionId}>{(r.content as ExecutionRecordContent).title} · revision {r.revisionNumber}</option>)}</select></label>}
    <div className="profile-form-grid"><label>Receiver kind<select className="field" value={draft.receiver.kind} onChange={e=>change({receiver:{...draft.receiver,kind:e.target.value as "internal"|"external"}})}><option value="external">External</option><option value="internal">Internal</option></select></label><label>Receiver label<input className="field" required maxLength={200} value={draft.receiver.label} onChange={e=>change({receiver:{...draft.receiver,label:e.target.value}})}/></label></div>
    <fieldset><legend>Deliverable Evidence</legend><p>Bind each included criterion to a reviewed evidence record. At least one is required.</p>{view.milestones.map(m=><label key={m.key}>Evidence for {m.title}<select className="field" value={draft.deliverables.find(d=>d.milestoneKey===m.key)?.evidenceReferenceId??""} onChange={e=>change({deliverables:[...draft.deliverables.filter(d=>d.milestoneKey!==m.key),...(e.target.value?[{milestoneKey:m.key,evidenceReferenceId:e.target.value}]:[])]})}><option value="">No deliverable evidence selected</option>{references.map(ref=><option key={ref.id} value={ref.id}>{(catalog.find(r=>r.revisionId===ref.sourceRevisionId)?.content as ExecutionRecordContent)?.title}</option>)}</select></label>)}</fieldset>
    <label>Receiver acknowledgement<select className="field" value={draft.acknowledgement.state} onChange={e=>change({acknowledgement:e.target.value==="recorded"?{state:"recorded",eventDate:draft.eventDate,evidenceReferenceIds:[]}:{state:"not_recorded",eventDate:null,evidenceReferenceIds:[]}})}><option value="not_recorded">Not Recorded</option><option value="recorded">Recorded with Evidence</option></select></label>
    {draft.acknowledgement.state==="recorded"&&<><label>Acknowledgement date<input className="field" required type="date" value={draft.acknowledgement.eventDate??""} onChange={e=>change({acknowledgement:{...draft.acknowledgement,eventDate:e.target.value}})}/></label><fieldset><legend>Acknowledgement Evidence</legend>{references.map(ref=><label className="execution-check" key={ref.id}><input type="checkbox" checked={draft.acknowledgement.evidenceReferenceIds.includes(ref.id)} onChange={e=>change({acknowledgement:{...draft.acknowledgement,evidenceReferenceIds:e.target.checked?[...draft.acknowledgement.evidenceReferenceIds,ref.id]:draft.acknowledgement.evidenceReferenceIds.filter(id=>id!==ref.id)}})}/>{(catalog.find(r=>r.revisionId===ref.sourceRevisionId)?.content as ExecutionRecordContent)?.title}</label>)}</fieldset></>}
    <fieldset><legend>Open Obligations</legend><p className="muted">Retain explicit reviewed follow-up records.</p>{catalog.filter(r=>r.kind==="raid"||r.kind==="decision"||r.kind==="scope_change").map(r=><label className="execution-check" key={r.id}><input type="checkbox" checked={draft.openObligationIds.includes(r.id)} onChange={e=>change({openObligationIds:e.target.checked?[...draft.openObligationIds,r.id]:draft.openObligationIds.filter(id=>id!==r.id)})}/>{(r.content as ExecutionRecordContent).title}</label>)}</fieldset>
  </>;
}
function HandoffContent(content:ExecutionRecordContent){
  if(content.kind==="handoff"||content.kind==="closeout")return <><p>Receiver: {content.receiver.label} · {content.receiver.kind}</p><p>Acknowledgement: {content.acknowledgement.state==="recorded"?`recorded on ${content.acknowledgement.eventDate}, with ${content.acknowledgement.evidenceReferenceIds.length} evidence references`:"not recorded"}</p><p>{content.deliverables.length} evidenced criteria · {content.openObligationIds.length} open obligations</p></>;
  if(content.kind!=="outcome")return null;
  return <><p>Outcome: {content.status.replaceAll("_"," ")}</p>{content.status==="observed"&&<><p>{content.measure}: {content.currentValue} {content.unit} · {content.measurementStart} to {content.measurementEnd}</p><p>Baseline: {content.baselineValue??content.baselineUnknownReason}</p><p>Comparison: {content.comparisonValue??content.comparisonUnknownReason}</p></>}{content.limitationReason&&<p>Limitation: {content.limitationReason}</p>}</>;
}
