"use client";
import { useState } from 'react';
import type {Overview,RecordView,Candidate,Owner,Mutation} from './types';
const transitions:Record<string,string[]>={not_started:['start','waive'],in_progress:['block','request_review','waive'],blocked:['resume','request_review','waive'],ready_for_review:['accept','waive'],accepted:['reopen'],waived:['reopen']};
export function ExecutionMilestones({view,records,owners,disabled,onReview,save}:{view:Overview;records:RecordView[];owners:Owner[];disabled:boolean;onReview:(candidate:Candidate)=>void;save:Mutation}){
  const [selected,setSelected]=useState(''),[evidence,setEvidence]=useState<string[]>([]),[owner,setOwner]=useState(''),[date,setDate]=useState(''),[unknownDate,setUnknownDate]=useState('Schedule remains unknown'),[unknownOwner,setUnknownOwner]=useState('Owner remains unknown');
  return <section className="profile-section" aria-label="Execution milestones"><h2>Milestone Delivery</h2><p>Milestones require explicit reviewed decisions and evidence. Logged hours do not mark them complete.</p>
    {!view.milestones.length&&<p>No bound milestone decisions yet.</p>}
    {view.milestones.map(m=><article className="profile-card" key={m.id}><h3>{m.title}</h3><p>{m.state.replaceAll('_',' ')}</p>{m.reviewRequired&&<p role="status">Review required. Recorded state: {m.recordedState.replaceAll('_',' ')}.</p>}
      <p>Owner: {m.ownerLabel??m.unknownOwnerReason??'Unknown'}</p><p>Planned date: {m.plannedDate??m.unknownPlannedDateReason}</p>
      <p className="evidence-citation">Baseline item {m.key} · accepted plan revision {view.baselineRevisionId}</p>{m.exitEvidence&&<p>Exit evidence: {m.exitEvidence}</p>}{m.customerValidation&&<p>Customer validation: {m.customerValidation}</p>}{m.dependencies.length>0&&<p>Dependencies: {m.dependencies.join(", ")}</p>}
      {view.capabilities.review&&!view.reviewRequired&&<>{m.recordedState==='ready_for_review'&&<fieldset><legend>Reviewed evidence for {m.title}</legend>{records.filter(r=>r.state==='accepted'&&!r.reviewRequired&&r.content&&r.baselineId===view.baselineId&&(view.audience==='internal'||r.audience==='delivery')).map(r=><label key={r.id}><input type="checkbox" checked={evidence.includes(r.revisionId)} onChange={event=>setEvidence(current=>event.target.checked?[...current,r.revisionId]:current.filter(id=>id!==r.revisionId))}/>{(r.content as {title:string}).title}</label>)}</fieldset>}
      {(transitions[m.recordedState]??[]).map(action=><button type="button" className="secondary-button" key={action} disabled={disabled||(action==='accept'&&!evidence.length)} onClick={()=>onReview({version:'execution-v1',action:'milestone.decide',expectedVersions:{execution:view.version,milestone:m.version},payload:{baselineId:view.baselineId,milestoneKey:m.key,decision:action,evidenceRevisionIds:action==='accept'?evidence:[]}})}>{action.replaceAll('_',' ')} {m.title}</button>)}</>}
      {!view.capabilities.review&&['in_progress','blocked'].includes(m.recordedState)&&<button type="button" className="secondary-button" disabled={disabled||view.reviewRequired} onClick={()=>void save('record.create',{execution:view.version},{baselineId:view.baselineId,record:{kind:'activity',subtype:'milestone_review_request',title:`Review requested: ${m.title}`,narrative:'Contributor requests an explicit human review of milestone evidence.',audience:'delivery',eventDate:new Date().toISOString().slice(0,10),timezone:'UTC',workPackageKey:null,milestoneKeys:[m.key],ownerMembershipId:null,unknownOwnerReason:'Owner remains to be confirmed',references:[],milestoneKey:m.key,milestoneVersion:m.version}})}>Propose review request for {m.title}</button>}
      <button type="button" className="secondary-button" disabled={disabled||view.reviewRequired} onClick={()=>setSelected(m.key)}>Propose owner or date for {m.title}</button>
    </article>)}
    {selected&&<form className="plan-editor" onSubmit={event=>{event.preventDefault();const m=view.milestones.find(i=>i.key===selected)!;void save('record.create',{execution:view.version},{baselineId:view.baselineId,record:{kind:'activity',subtype:'milestone_plan',title:`Milestone plan proposal: ${m.title}`,narrative:'Contributor proposes the displayed owner and planned date for human review.',audience:'delivery',eventDate:new Date().toISOString().slice(0,10),timezone:'UTC',workPackageKey:null,milestoneKeys:[m.key],ownerMembershipId:owner||null,unknownOwnerReason:owner?null:unknownOwner,references:[],milestoneKey:m.key,milestoneVersion:m.version,plannedDate:date||null,unknownPlannedDateReason:date?null:unknownDate}},()=>setSelected(''));}}>
      <h3>Propose Milestone Owner and Date</h3><label>Milestone owner<select className="field" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Unknown owner</option>{owners.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
      {!owner&&<label>Milestone unknown owner reason<input className="field" required maxLength={500} value={unknownOwner} onChange={e=>setUnknownOwner(e.target.value)}/></label>}
      <label>Planned milestone date<input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{!date&&<label>Unknown planned date reason<input className="field" required maxLength={500} value={unknownDate} onChange={e=>setUnknownDate(e.target.value)}/></label>}
      <button type="submit" className="primary-button" disabled={disabled||view.reviewRequired}>Save milestone plan proposal</button><button type="button" className="secondary-button" onClick={()=>setSelected('')}>Cancel milestone proposal</button>
    </form>}
  </section>;
}
