LogTime yes
Foreground yes
DatabaseDirectory /signatures
LocalSocket /tmp/clamd.sock
LocalSocketMode 600
MaxScanTime 30000
MaxScanSize 100M
MaxFileSize 20M
MaxRecursion 8
MaxFiles 2000
AlertExceedsMax yes
StreamMaxLength 20M
ReadTimeout 30
