"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArchiveIcon, CheckIcon, MessageSquareIcon, PanelLeftIcon, PencilIcon, PlusIcon, XIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Conversation = { id: string; eveSessionId: string | null; title: string; version: number; archivedAt: string | null };
export function AppShell({ children, username, role }: { children: React.ReactNode; username: string; role: string }) {
  const [open, setOpen] = useState(false); const [conversations, setConversations] = useState<Conversation[]>([]); const [query, setQuery] = useState(""); const [renaming, setRenaming] = useState<string>(); const [title, setTitle] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch(`/api/conversations?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then((response) => response.ok ? response.json() : { conversations: [] }).then((data) => setConversations(data.conversations ?? [])).catch(() => undefined); return () => controller.abort(); }, [query]);
  const sidebar = <aside className="flex h-full w-72 shrink-0 flex-col border-r bg-card p-3">
    <div className="mb-5 flex items-center px-2"><Link className="font-semibold tracking-tight" href="/portfolio">Turas</Link></div>
    <Button asChild className="mb-3 justify-start" size="sm"><Link href="/s"><PlusIcon /> New chat</Link></Button>
    <Input aria-label="Search conversation titles" onChange={(event) => setQuery(event.target.value)} placeholder="Search chats" value={query} />
    <nav className="mt-4 space-y-1" aria-label="Primary"><Link className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent" href="/customers">Customer evidence</Link><Link className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent" href="/portfolio">Portfolio review</Link><Link className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent" href="/memo">Memo & architecture</Link><Link className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent" href="/operating-model">Services operating plan</Link></nav>
    <div className="mt-5 flex min-h-0 flex-1 flex-col"><p className="px-2 text-xs font-medium text-muted-foreground">Recent conversations</p><div className="mt-2 space-y-1 overflow-y-auto">{conversations.length ? conversations.map((conversation) => <div className="group flex items-center gap-1" key={conversation.id}>{renaming === conversation.id ? <><Input aria-label="Conversation title" className="h-8 min-w-0" maxLength={80} onChange={(event) => setTitle(event.target.value)} value={title} /><button aria-label="Save conversation title" className="p-1 text-muted-foreground" onClick={async () => { const response = await fetch(`/api/conversations/${conversation.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, version: conversation.version }) }); if (response.ok) { const data = await response.json() as { conversation: Conversation }; setConversations((items) => items.map((item) => item.id === conversation.id ? data.conversation : item)); setRenaming(undefined); } }}><CheckIcon className="size-3.5" /></button><button aria-label="Cancel rename" className="p-1 text-muted-foreground" onClick={() => setRenaming(undefined)}><XIcon className="size-3.5" /></button></> : <><Link className="min-w-0 flex-1 truncate rounded-md px-2 py-1.5 text-sm hover:bg-accent" href={conversation.eveSessionId ? `/s/${encodeURIComponent(conversation.eveSessionId)}` : "/s"}><MessageSquareIcon className="mr-2 inline size-3.5" />{conversation.title}</Link><button aria-label={`Rename ${conversation.title}`} className="p-1 text-muted-foreground opacity-0 group-hover:opacity-100 focus:opacity-100" onClick={() => { setRenaming(conversation.id); setTitle(conversation.title); }}><PencilIcon className="size-3.5" /></button><button aria-label={`Archive ${conversation.title}`} className="p-1 text-muted-foreground opacity-0 group-hover:opacity-100 focus:opacity-100" onClick={async () => { const response = await fetch(`/api/conversations/${conversation.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ archived: true, version: conversation.version }) }); if (response.ok) setConversations((items) => items.filter((item) => item.id !== conversation.id)); }}><ArchiveIcon className="size-3.5" /></button></>}</div>) : <p className="px-2 py-3 text-xs text-muted-foreground">Your sent chats will appear here.</p>}</div></div>
    <div className="shrink-0 border-t pt-3 text-xs text-muted-foreground"><p className="truncate">{username} · {role}</p><form action="/api/auth/logout" method="post"><button className="mt-1 underline underline-offset-2" type="submit">Sign out</button></form></div>
  </aside>;
  return <div className="flex min-h-dvh bg-background"><div className="hidden md:sticky md:top-0 md:block md:h-dvh md:self-start">{sidebar}</div><div className="min-w-0 flex-1"> <button aria-label="Open navigation" className="fixed left-3 top-3 z-40 rounded border bg-card p-2 md:hidden" onClick={() => setOpen(true)}><PanelLeftIcon className="size-4" /></button>{open ? <div className="fixed inset-0 z-50 bg-black/30 md:hidden" onClick={() => setOpen(false)}><div className="h-full w-72 bg-card" onClick={(event) => event.stopPropagation()}>{sidebar}</div></div> : null}{children}</div></div>;
}
