'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {readLearningCandidate,readLearningCandidateOriginal} from '../../../lib/server/learning/reviews';
import {useLearningView,useLearningMutation} from './view';
import {titleCaseLabel} from '../title-case-label';
import {LearningEvaluationPreparation,LearningPublicationControl,LearningPublishCandidate} from './release';
const checks=[['namesAndDomainsRemoved','Names and domains removed'],['repositoriesAndLinksRemoved','Repositories and identifying links removed'],['peopleAndCommercialDetailsRemoved','People and commercial details removed'],['identifyingConfigurationAndOutcomesRemoved','Identifying configuration and outcomes removed'],['countsAndCombinedInferenceReviewed','Counts and combined inference reviewed']] as const;
export function LearningCandidateDetail({id}:{id:string}){
 const client=useLearningView<Awaited<ReturnType<typeof readLearningCandidate>>>(`/api/learning/candidates/${id}`),command=useLearningMutation(client.auth,`candidate:${id}`,client.refresh);
 const [checked,setChecked]=useState<Record<string,boolean>>({}),[rights,setRights]=useState(false),[decision,setDecision]=useState('reject'),[rationale,setRationale]=useState(''),[error,setError]=useState(''),[sourceId,setSourceId]=useState<string|null>(null);
 const original=useLearningView<Awaited<ReturnType<typeof readLearningCandidateOriginal>>>(client.view&&sourceId?`/api/learning/candidates/${id}/originals/${sourceId}`:null);
 const view=client.view,busy=command.busy||!!command.pending;
 useEffect(()=>{setChecked({});setRights(false);setDecision('reject');setRationale('');setSourceId(null);},[view?.revisionId,view?.closureDigest,view?.canReview,view?.reviews[0]?.id]);
 return <section className="profile-page"><Link href="/learning/candidates">Learning Candidates</Link><header className="profile-header"><div><h1>Candidate Review</h1><p>Review exact wording and original evidence before granting reuse.</p></div><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Candidate</button></header>
 {client.notice&&<p role="status">{client.notice}</p>}{command.notice&&<p role="status">{command.notice}</p>}{error&&<p role="alert">{error}</p>}{command.pending&&<div className="profile-state"><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Pending Request</button></div>}
 {view&&<><article className="profile-card"><h2>{view.payload.title}</h2><p>{titleCaseLabel(view.state)} · Revision {view.revision}</p>{Object.entries(view.payload).filter(([key])=>key!=='title').map(([key,value])=><section key={key}><h3>{titleCaseLabel(key.replace(/([A-Z])/g,' $1'))}</h3><p>{value}</p></section>)}</article>
 <section className="profile-card"><h2>Selected Originals</h2><p>Reuse review also binds the current supporting evidence closure.</p>{view.originals.map((source,index)=><button key={source.revisionId} className="secondary-button" onClick={()=>{original.clear();setSourceId(source.revisionId);}}>Read Original {index+1}</button>)}{original.notice&&<p role="status">{original.notice}</p>}{original.view&&<article><h3>Current Original</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{typeof original.view.content==='string'?original.view.content:JSON.stringify(original.view.content,null,2)}</pre></article>}</section>
 {view.canReview&&view.state==='submitted'&&<form className="profile-card" onSubmit={async event=>{event.preventDefault();try{setError('');await command.mutate(`/api/learning/candidates/${id}/reviews`,{expectedVersion:view.revision,revisionId:view.revisionId,contentDigest:view.digest,closureDigest:view.closureDigest,decision,rationale,...(decision==='accept'?{rightsAttested:rights,checklist:checked}:{})});}catch(error){setError(error instanceof Error?error.message:'Review unavailable');}}}><h2>Administrator Reuse Decision</h2><label>Reuse Decision<select className="field" value={decision} disabled={busy} onChange={event=>setDecision(event.target.value)}><option value="reject">Reject</option><option value="accept">Accept Exact Revision</option></select></label>{decision==='accept'&&<fieldset disabled={busy}><legend>Independent Sanitization and Rights Review</legend>{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={!!checked[key]} onChange={event=>setChecked({...checked,[key]:event.target.checked})}/>{label}</label>)}<label><input type="checkbox" checked={rights} onChange={event=>setRights(event.target.checked)}/>I verified original reuse rights</label></fieldset>}<label>Review Rationale<textarea className="field" required maxLength={2000} disabled={busy} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><button type="submit" className="primary-button" disabled={busy||decision==='accept'&&(!rights||checks.some(([key])=>!checked[key]))}>Record Reuse Decision</button></form>}
 {client.auth&&<><LearningEvaluationPreparation view={view} auth={client.auth} refresh={client.refresh}/><LearningPublishCandidate view={view} auth={client.auth} refresh={client.refresh}/></>}<section className="profile-card"><h2>Reuse Reviews</h2>{view.reviews.length?view.reviews.map(review=><p key={review.id}>{titleCaseLabel(review.decision)} · {review.revoked?'Revoked':'Recorded'}</p>):<p>No reuse decision recorded.</p>}</section>{view.canReview&&<section className="profile-card"><h2>Paired Evaluations</h2>{view.evaluations?.length?view.evaluations.map(evaluation=><p key={evaluation.id}><Link href={`/learning/evaluations/${evaluation.id}`}>{titleCaseLabel(evaluation.state)}</Link></p>):<p>No evaluation admitted.</p>}{view.hasMoreEvaluations&&<p>Showing the most recent 20 evaluations.</p>}</section>}</>}
 <LearningPublicationControl id={id} candidateState={view?.state}/></section>;
}
