'use client';
import {useEffect,useState} from 'react';
import type {readLearningEvaluation,readLearningEvaluationCapture} from '../../../lib/server/learning/evaluation-captures';
import type {LearningAuth} from './client';
import {useLearningView,useLearningMutation} from './view';
type Evaluation=Awaited<ReturnType<typeof readLearningEvaluation>>;
type Capture=Awaited<ReturnType<typeof readLearningEvaluationCapture>>;
const dimensions=['fidelity','applicability','unknownHandling','usefulness'] as const;
const labels={fidelity:'Fidelity',applicability:'Applicability',unknownHandling:'Unknown Handling',usefulness:'Usefulness'};
export function LearningCaseReview({evaluation,caseId,auth,refresh}:{evaluation:Evaluation;caseId:string;auth:LearningAuth;refresh:()=>Promise<void>}){
 const baseline=useLearningView<Capture>(evaluation.bodyAvailable?`/api/learning/evaluations/${evaluation.id}/cases/${caseId}/arms/baseline`:null),candidate=useLearningView<Capture>(evaluation.bodyAvailable?`/api/learning/evaluations/${evaluation.id}/cases/${caseId}/arms/candidate`:null),command=useLearningMutation(auth,`case-review:${evaluation.id}:${caseId}`,refresh);
 const [scores,setScores]=useState<Record<string,string>>({}),[flags,setFlags]=useState<Record<string,boolean>>({}),[rationale,setRationale]=useState(''),[error,setError]=useState('');
 const b=baseline.view?.arm,c=candidate.view?.arm,fixture=evaluation.cases.find(item=>item.id===caseId),available=baseline.view?.bodyAvailable&&candidate.view?.bodyAvailable&&b&&c&&'output' in b&&'output' in c;
 useEffect(()=>{setScores({});setFlags({});setRationale('');setError('');},[evaluation.version,b&&'outputDigest' in b?b.outputDigest:null,c&&'outputDigest' in c?c.outputDigest:null,available]);
 const busy=command.busy||!!command.pending;
 return <section className="profile-card"><h2>Review {caseId}</h2>{baseline.notice&&<p role="status">{baseline.notice}</p>}{candidate.notice&&<p role="status">{candidate.notice}</p>}{!available?<p>Both current complete captures are required. Protected text is withheld.</p>:<>{fixture?.fixture&&<section><h3>Fixed Synthetic Case Context</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(fixture.fixture,null,2)}</pre></section>}{fixture?.expected&&<section><h3>Human Review Expectations</h3><ul>{fixture.expected.map(item=><li key={item}>{item}</li>)}</ul></section>}{[['Baseline',b],['Candidate',c]].map(([label,arm])=>{const capture=arm as typeof b;return capture&&'output' in capture&&capture.output?<article key={label as string}><h3>{label as string} Response</h3><p>{capture.output.text}</p><p>Citations: {capture.output.citationKeys.join(', ')||'None'}</p><h4>Unknowns</h4>{capture.output.unknowns.length?<ul>{capture.output.unknowns.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>No unknowns stated.</p>}</article>:null;})}
 {evaluation.canReview&&!fixture?.review&&<form onSubmit={async event=>{event.preventDefault();try{setError('');await command.mutate(`/api/learning/evaluations/${evaluation.id}/case-reviews`,{expectedVersion:evaluation.version,caseId,baselineCaptureDigest:b.outputDigest,candidateCaptureDigest:c.outputDigest,baseline:Object.fromEntries(dimensions.map(key=>[key,Number(scores[`baseline:${key}`])])),candidate:Object.fromEntries(dimensions.map(key=>[key,Number(scores[`candidate:${key}`])])),safetyPassed:!!flags.safety,citationPassed:!!flags.citation,authorityPassed:!!flags.authority,rationale});}catch(error){setError(error instanceof Error?error.message:'Assessment unavailable');}}}>{(['baseline','candidate'] as const).map(arm=><fieldset key={arm} disabled={busy}><legend>{arm==='baseline'?'Baseline':'Candidate'} Human Scores</legend>{dimensions.map(key=><label key={key}>{labels[key]}<select className="field" required value={scores[`${arm}:${key}`]??''} onChange={event=>setScores({...scores,[`${arm}:${key}`]:event.target.value})}><option value="">Select a Score</option>{[0,1,2].map(score=><option key={score} value={score}>{score} — {evaluation.rubric.dimensions[key][score]}</option>)}</select></label>)}</fieldset>)}<fieldset disabled={busy}><legend>Mandatory Human Checks</legend>{(['safety','citation','authority'] as const).map(flag=><label key={flag}><input type="checkbox" checked={!!flags[flag]} onChange={event=>setFlags({...flags,[flag]:event.target.checked})}/>{flag==='safety'?'Safety':flag==='citation'?'Citation Fidelity':'Authority Boundaries'} Passed</label>)}</fieldset><label>Case Assessment Rationale<textarea className="field" required maxLength={2000} disabled={busy} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><p>Scores and pass flags remain your judgment. Failed assessments are retained and require a fresh full run.</p><button className="primary-button" type="submit" disabled={busy||(['baseline','candidate'] as const).some(arm=>dimensions.some(key=>scores[`${arm}:${key}`]===undefined||scores[`${arm}:${key}`]===''))}>Record Immutable Case Assessment</button></form>}</>}{error&&<p role="alert">{error}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Case Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Case Request</button></>}</section>;
}
