'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {readLearningCohort,readLearningCohortOptions} from '../../../lib/server/learning/cohorts';
import {useLearningView,useLearningMutation} from './view';
export function LearningOutcomeTrends(){
 const options=useLearningView<Awaited<ReturnType<typeof readLearningCohortOptions>>>('/api/learning/cohorts/options'),[metric,setMetric]=useState<'deployment_lead_time'|'change_failure_rate'>('deployment_lead_time'),[quarter,setQuarter]=useState(''),[error,setError]=useState('');
 const client=useLearningView<Awaited<ReturnType<typeof readLearningCohort>>>(options.view&&quarter?`/api/learning/cohorts?metricId=${metric}&quarter=${encodeURIComponent(quarter)}`:null),command=useLearningMutation(options.auth,`cohort:${metric}:${quarter}`,client.refresh);
 useEffect(()=>{if(!options.view)setQuarter('');else if(!options.view.quarters[metric].includes(quarter))setQuarter(options.view.quarters[metric][0]??'');},[options.view,quarter,metric]);
 const protocol=options.view?.protocols[metric];
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>Outcome Trends</h1><p>Fixed quarterly comparisons of separately reviewed accepted observations.</p></div><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Outcome Summary</button></header>{options.notice&&<p role="status">{options.notice}</p>}{client.notice&&<p role="status">{client.notice}</p>}{error&&<p role="alert">{error}</p>}
 {options.view&&<><section className="profile-card"><label>Outcome Metric<select className="field" value={metric} disabled={command.busy||!!command.pending} onChange={event=>{client.clear();setError('');setMetric(event.target.value as typeof metric);}}><option value="deployment_lead_time">Deployment Lead Time</option><option value="change_failure_rate">Change Failure Rate</option></select></label><label>Completed UTC Quarter<select className="field" value={quarter} disabled={command.busy||!!command.pending} onChange={event=>{setError('');if(event.target.value===quarter)void client.refresh();else{client.clear();setQuarter(event.target.value);}}}>{options.view.quarters[metric].map(item=><option key={item} value={item}>{item}</option>)}</select></label><p>{protocol?.definition}</p><p>Compare the first 14 days and last 14 days of the quarter, using half-open UTC windows. Failure rate also waits 24 hours for attribution.</p></section>{client.view&&<article className="profile-card"><h2>{client.view.status==='released'?'Observed Mean Change':'Comparable Summary Unavailable'}</h2><p>Baseline: {client.view.windows.baseline.start.slice(0,10)} to {client.view.windows.baseline.end.slice(0,10)} (exclusive), UTC.</p><p>Current: {client.view.windows.current.start.slice(0,10)} to {client.view.windows.current.end.slice(0,10)} (exclusive), UTC.</p>{client.view.status==='released'&&'meanChange' in client.view?<><p>{client.view.meanChange.startsWith('-')?'':'+'}{client.view.meanChange} {client.view.unit}</p><p>{client.view.limitation}</p></>:<p>No comparable outcome summary is available. No customer counts or revised subsets are disclosed.</p>}</article>}{options.auth?.membership.role==='admin'&&options.view.enabled&&client.view?.status==='unavailable'&&<section className="profile-card"><h2>Administrator Release</h2><p>Release the complete fixed population only after separate measurement reuse approval. A withheld family cannot be replaced.</p><button className="primary-button" disabled={command.busy||!!command.pending} onClick={async()=>{try{setError('');await command.mutate('/api/learning/cohorts/releases',{expectedVersion:0,metricId:metric,quarter,protocolVersion:protocol!.version});}catch(error){setError(error instanceof Error?error.message:'Outcome release unavailable');}}}>Release Fixed Quarterly Summary</button></section>}{!options.view.enabled&&<p>New outcome releases are disabled. Current eligible summaries remain readable.</p>}</>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Outcome Release Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Outcome Release Request</button></>}
 </section>;
}
