'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useRef,useState } from 'react';
import type { listLearningFeedback } from '../../../lib/server/learning/feedback';
import type { listLearningOriginals,listLearningBaselines } from '../../../lib/server/learning/catalog';
import type { learningDraftMeta } from '../../../lib/server/learning/advisory';
import type { readLearningDraft } from '../../../lib/server/learning/drafts';
import { learningDraftPrompt } from '../../../lib/contracts/learning';
import { useLearningView,useLearningMutation } from './view';
import { learningFetch,learningPost,type LearningAuth } from './client';
import { titleCaseLabel } from '../title-case-label';
type Original=Awaited<ReturnType<typeof listLearningOriginals>>['items'][number];
type Customer={id:string;displayName:string};
export function LearningDraftNew(){
 const router=useRouter(),[customer,setCustomer]=useState(''),[customerCursor,setCustomerCursor]=useState<string|null>(null),[sourceCursor,setSourceCursor]=useState<string|null>(null),[selected,setSelected]=useState<Original[]>([]),[rights,setRights]=useState(''),[question,setQuestion]=useState(''),[budget,setBudget]=useState(''),[error,setError]=useState(''),[feedbackIds,setFeedbackIds]=useState<string[]>([]),[feedbackCursor,setFeedbackCursor]=useState<string|null>(null),[publicationId,setPublicationId]=useState(''),[baselineCursor,setBaselineCursor]=useState<string|null>(null);
 const customers=useLearningView<{items:Customer[];nextCursor:string|null}>(`/api/customers?limit=20${customerCursor?`&cursor=${encodeURIComponent(customerCursor)}`:''}`),sources=useLearningView<Awaited<ReturnType<typeof listLearningOriginals>>>(customer?`/api/learning/customers/${customer}/originals?limit=20${sourceCursor?`&cursor=${encodeURIComponent(sourceCursor)}`:''}`:null);
 const feedback=useLearningView<Awaited<ReturnType<typeof listLearningFeedback>>>(customers.auth?.membership.kind==='internal'?`/api/learning/feedback?limit=20${feedbackCursor?`&cursor=${encodeURIComponent(feedbackCursor)}`:''}`:null);
 const baselines=useLearningView<Awaited<ReturnType<typeof listLearningBaselines>>>(customer?`/api/learning/customers/${customer}/baselines?limit=20${baselineCursor?`&cursor=${encodeURIComponent(baselineCursor)}`:''}`:null);
 const owner=useRef<string|null>(null);
 const command=useLearningMutation(customers.auth,'draft.prepare',customers.refresh),busy=command.busy||!!command.pending;
 useEffect(()=>{setSelected([]);setSourceCursor(null);setRights('');setQuestion('');setBudget('');setFeedbackIds([]);setFeedbackCursor(null);setPublicationId('');setBaselineCursor(null);},[customer]);
 useEffect(()=>{const next=customers.auth?.membership.id;if(!next){setCustomer('');setSelected([]);setQuestion('');setRights('');setBudget('');setFeedbackIds([]);setPublicationId('');return;}if(owner.current&&owner.current!==next){setCustomer('');setSelected([]);setQuestion('');setRights('');setBudget('');setFeedbackIds([]);}owner.current=next;},[customers.auth?.membership.id]);
 if(customers.auth&&customers.auth.membership.kind!=='internal')return <section className="profile-page"><h1>Learning Drafts</h1><p>Draft preparation is available to internal members.</p><Link href="/learning">My Feedback</Link></section>;
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>New Learning Draft</h1><p>Turi proposes one reusable practice from selected accepted originals. Administrators review and publish separately.</p></div></header>{customers.notice&&<p role="status">{customers.notice}</p>}{sources.notice&&customer&&<p role="status">{sources.notice}</p>}{command.notice&&<p role="status">{command.notice}</p>}{error&&<p role="alert">{error}</p>}
 {command.pending&&<div className="profile-state"><p>Draft preparation is unconfirmed.</p><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Pending Request</button></div>}
 {customers.auth?.membership.kind==='internal'&&<form className="profile-card" onSubmit={async e=>{e.preventDefault();if(!customer||!selected.length||busy)return;try{setError('');const receipt=await command.mutate('/api/learning/drafts',{expectedVersion:0,customerId:customer,lineage:selected.map(({label,...source})=>({...source,rightsBasis:rights})),feedbackIds,question,budgetUsd:budget,...(publicationId?{publicationId}:{})});if(receipt.targetId)router.push(`/learning/drafts/${receipt.targetId}`);}catch(error){setError(error instanceof Error?error.message:'Draft unavailable');}}}>
 <label>Customer<select className="field" disabled={busy} value={customer} required onChange={e=>setCustomer(e.target.value)}><option value="">Select a Customer</option>{customers.view?.items?.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>{customers.view?.nextCursor&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{customers.clear();setCustomerCursor(customers.view!.nextCursor);}}>More Customers</button>}{customerCursor&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{customers.clear();setCustomerCursor(null);}}>First Customer Page</button>}
 {customer&&<fieldset disabled={busy}><legend>Selected Accepted Originals</legend><p>Choose up to 20 originals from this customer. Feedback cannot be selected as accepted evidence.</p>{sources.view?.items?.map(item=><label key={item.sourceRevisionId} className="checkbox-label"><input type="checkbox" checked={selected.some(s=>s.sourceRevisionId===item.sourceRevisionId)} onChange={e=>setSelected(current=>e.target.checked?[...current,item]:current.filter(s=>s.sourceRevisionId!==item.sourceRevisionId))} disabled={!selected.some(s=>s.sourceRevisionId===item.sourceRevisionId)&&selected.length>=20}/>{titleCaseLabel(item.label)}</label>)}{sources.view?.items?.length===0&&<p>No eligible originals on this page.</p>}{sources.view?.cursor&&<button type="button" className="secondary-button" onClick={()=>{sources.clear();setSourceCursor(sources.view!.cursor);}}>More Originals</button>}{sourceCursor&&<button type="button" className="secondary-button" onClick={()=>{sources.clear();setSourceCursor(null);}}>First Original Page</button>}<p>{selected.length} originals selected.</p></fieldset>}

 {customer&&<fieldset disabled={busy}><legend>Unverified Feedback (Optional)</legend><p>Select up to 10 observations. They do not become accepted evidence.</p>{feedback.notice&&<p role="status">{feedback.notice}</p>}{feedback.view?.items.filter(item=>item.customerId===null||item.customerId===customer).map(item=><label key={item.id} className="checkbox-label"><input type="checkbox" checked={feedbackIds.includes(item.id)} disabled={!feedbackIds.includes(item.id)&&feedbackIds.length>=10} onChange={e=>setFeedbackIds(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{item.label} · {titleCaseLabel(item.category.replaceAll('_',' '))}</label>)}{feedback.view?.cursor&&<button type="button" className="secondary-button" onClick={()=>{feedback.clear();setFeedbackCursor(feedback.view!.cursor);}}>More Feedback Observations</button>}{feedbackCursor&&<button type="button" className="secondary-button" onClick={()=>{feedback.clear();setFeedbackCursor(null);}}>First Feedback Page</button>}</fieldset>}
 {customer&&<section><label>Published Practice to Improve (Optional)<select className="field" disabled={busy} value={publicationId} onChange={e=>setPublicationId(e.target.value)}><option value="">Create a New Practice Candidate</option>{baselines.view?.items.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><p>Only practices you may revise are listed. Saving an improvement appends a private revision; publication still requires new review and evaluation.</p>{baselines.notice&&<p role="status">{baselines.notice}</p>}{baselines.view?.cursor&&<button type="button" className="secondary-button" onClick={()=>{baselines.clear();setPublicationId('');setBaselineCursor(baselines.view!.cursor);}}>More Practices to Improve</button>}{baselineCursor&&<button type="button" className="secondary-button" onClick={()=>{baselines.clear();setPublicationId('');setBaselineCursor(null);}}>First Practice Page</button>}</section>}
 <label>Proposed Reuse Basis<textarea className="field" required maxLength={2000} disabled={busy} value={rights} onChange={e=>setRights(e.target.value)}/></label><p className="muted">This authoring claim still requires an independent administrator rights review.</p>
 <label>Question for Turi<textarea className="field" required maxLength={2000} disabled={busy} value={question} onChange={e=>setQuestion(e.target.value)}/></label>
 <label>Maximum Spend (USD)<input className="field" inputMode="decimal" required maxLength={10} pattern="(?:0|[1-9][0-9]{0,2})(?:\.[0-9]{1,6})?" disabled={busy} value={budget} onChange={e=>setBudget(e.target.value)}/></label><p className="muted">Maximum $25 per draft. Preparation makes no paid call. Starting the prepared draft uses this budget; admission requires the verified provider cost ceiling.</p>
 <button type="submit" className="primary-button" disabled={busy||!customer||!selected.length||!customers.auth}>Prepare Draft</button>
 </form>}</section>;
}
type Draft=Awaited<ReturnType<typeof learningDraftMeta>>&Partial<Awaited<ReturnType<typeof readLearningDraft>>>;
export function LearningDraftDetail({id}:{id:string}){
 const client=useLearningView<Draft>(`/api/learning/drafts/${id}`),command=useLearningMutation(client.auth,`draft:${id}`,client.refresh),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[saved,setSaved]=useState<string|null>(null);
 const dispatching=useRef(false);
 const view=client.view,active=view&&['prepared','admitted','running','unconfirmed'].includes(view.state),blocked=busy||command.busy||!!command.pending;
 async function dispatch(auth:LearningAuth,draft:Draft){if(dispatching.current)return;dispatching.current=true;setBusy(true);client.clear();try{const bound=await learningPost<{sessionId:string}>(auth,'/eve/v1/session',{operationId:draft.operationId},{'x-turas-conversation-id':draft.conversationId});const response=await fetch(`/eve/v1/session/${encodeURIComponent(bound.sessionId)}`,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':auth.csrfToken,'x-turas-conversation-id':draft.conversationId,'x-turas-request-key':draft.nativeRequestId},body:JSON.stringify({message:learningDraftPrompt})});await response.body?.cancel();if(!response.ok)throw Error('Dispatch unconfirmed. Check draft status before continuing.');setNotice('Draft started. Check status for its confirmed result.');}catch(error){setNotice(error instanceof Error?error.message:'Dispatch unconfirmed');}finally{dispatching.current=false;setBusy(false);await client.refresh();}}
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>Learning Draft</h1><p>Proposed guidance remains private until independent review and evaluated publication.</p></div><button type="button" className="secondary-button" disabled={busy} onClick={()=>void client.refresh()}>Check Draft Status</button></header>{client.notice&&<p role="status">{client.notice}</p>}{notice&&<p role="status">{notice}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Pending Request</button></>}
 {view&&<article className="profile-card"><h2>{titleCaseLabel(view.state.replaceAll('_',' '))}</h2>{view.failureCode&&<p>Unavailable: {view.failureCode.replaceAll('_',' ')}</p>}{view.state==='prepared'&&client.auth&&<button type="button" className="primary-button" disabled={blocked||Date.parse(view.preparedUntil)<=Date.now()} onClick={()=>void dispatch(client.auth!,view)}>Start Prepared Draft</button>}{active&&<button type="button" className="secondary-button" disabled={blocked} onClick={async()=>{try{const auth=client.auth;if(!auth)return;await command.mutate(`/api/learning/drafts/${id}/cancel`,{expectedVersion:view.version,rationale:'Operator cancelled the draft'});if(view.nativeSessionId&&view.nativeTurnId)try{await learningPost(auth,`/eve/v1/session/${encodeURIComponent(view.nativeSessionId)}/cancel`,{turnId:view.nativeTurnId},{'x-turas-conversation-id':view.conversationId});}catch{/* The durable domain fence already blocks late output. */}}catch(error){setNotice(error instanceof Error?error.message:'Cancellation unconfirmed');}}}>Cancel Draft</button>}
 {view.state==='completed'&&view.output&&<><h2>{view.output.proposal.title}</h2>{Object.entries(view.output.proposal).filter(([key])=>key!=='title').map(([key,value])=><section key={key}><h3>{titleCaseLabel(key)}</h3><p>{value}</p></section>)}<h3>Unknowns</h3><ul>{view.output.unknowns.map((unknown,index)=><li key={index}>{unknown}</li>)}</ul><p>Intended improvement: {view.output.intendedImprovement}</p><p>Original citations: {view.output.citationKeys.join(', ')}</p><p className="muted">Save the exact proposal as a private candidate. Use ordinary candidate authoring and new evidence to change factual content.</p><button type="button" className="primary-button" disabled={blocked||!!saved} onClick={async()=>{try{const receipt=await command.mutate(`/api/learning/drafts/${id}/save`,{expectedVersion:view.version,outputDigest:view.outputDigest,proposalIndex:0,payload:view.output!.proposal});setSaved(receipt.targetId);}catch(error){setNotice(error instanceof Error?error.message:'Save unconfirmed');}}}>Save Private Candidate</button>{saved&&<Link href="/knowledge">Review My Candidate in Shared Knowledge</Link>}</>}
 </article>}</section>;
}
