'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,useId } from 'react';
import { learningFeedbackCategories,type LearningTarget } from '../../../lib/contracts/learning';
import { learningFetch,learningPost,type LearningAuth,type LearningReceipt } from './client';
import { titleCaseLabel } from '../title-case-label';
export function LearningFeedbackButton({kind,id,revisionId}:{kind:LearningTarget['kind'];id:string;revisionId?:string}){
 const formId=useId();
 const [open,setOpen]=useState(false),[auth,setAuth]=useState<LearningAuth|null>(null),[target,setTarget]=useState<LearningTarget|null>(null),[text,setText]=useState(''),[category,setCategory]=useState<typeof learningFeedbackCategories[number]>('unclear'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState<string|null>(null),[saved,setSaved]=useState<string|null>(null);
 const sequence=useRef(0),storageKey=useRef<string|null>(null),heading=useRef<HTMLHeadingElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const ticket=++sequence.current;setTarget(null);setAuth(null);setNotice('');
  void Promise.all([learningFetch<LearningAuth>('/api/auth/session'),learningFetch<{target:LearningTarget}>(`/api/learning/targets/${kind}/${id}${revisionId?`?revisionId=${revisionId}`:''}`)]).then(([current,resolved])=>{if(ticket!==sequence.current)return;setAuth(current);setTarget(resolved.target);storageKey.current=`learning-feedback:${current.workspace.id}:${current.membership.id}:${kind}:${id}:${resolved.target.revisionId}`;setPending(sessionStorage.getItem(storageKey.current));heading.current?.focus();}).catch(error=>{if(ticket===sequence.current)setNotice(error.message);});
  const clear=()=>{++sequence.current;setTarget(null);setAuth(null);setText('');setNotice('Refresh the target before submitting feedback.');};
  window.addEventListener('blur',clear);return()=>{++sequence.current;window.removeEventListener('blur',clear);};
 },[open,kind,id,revisionId]);
 function clearPending(){if(storageKey.current)sessionStorage.removeItem(storageKey.current);setPending(null);}
 async function reconcile(abandon=false){if(!auth||!pending||busy)return;setBusy(true);try{const receipt=abandon?await learningPost<LearningReceipt>(auth,`/api/learning/requests/${pending}/resolve`,{contractVersion:'learning-v1',requestId:pending,expectedVersion:0,action:'abandon'}):await learningFetch<LearningReceipt>(`/api/learning/requests/${pending}`);if(receipt.outcome==='committed'){setSaved(receipt.targetId);clearPending();setText('');setNotice('Feedback recorded.');}else if(['abandoned','retired'].includes(receipt.outcome)){clearPending();setNotice('Previous request closed. You can submit new feedback.');}else setNotice(receipt.outcome==='pending'?'Request is still pending. Check again.':'No committed request found. Close it before starting a new request.');}catch(error){setTarget(null);setNotice(error instanceof Error?error.message:'Status unavailable');}finally{setBusy(false);}}
 return <div className="learning-feedback"><button ref={trigger} type="button" className="secondary-button" aria-expanded={open} aria-controls={formId} onClick={()=>{setOpen(v=>!v);if(open)trigger.current?.focus();}}>Give Feedback</button>{open&&<form id={formId} className="profile-state" onSubmit={async event=>{event.preventDefault();if(!auth||!target||busy||pending)return;const requestId=crypto.randomUUID();if(storageKey.current)sessionStorage.setItem(storageKey.current,requestId);setPending(requestId);setBusy(true);try{const receipt=await learningPost<LearningReceipt>(auth,'/api/learning/feedback',{contractVersion:'learning-v1',requestId,expectedVersion:0,target,category,text});setSaved(receipt.targetId);clearPending();setText('');setNotice('Feedback recorded as an unverified observation.');}catch(error){setTarget(null);setNotice(error instanceof Error?error.message:'Feedback unconfirmed');}finally{setBusy(false);}}}>
  <h4 ref={heading} tabIndex={-1}>Feedback on This Revision</h4><p className="muted">Feedback is an unverified observation. It does not change accepted evidence or approve reuse.</p>
  <label>Issue Type<select className="field" value={category} disabled={busy||!!pending} onChange={e=>setCategory(e.target.value as typeof category)}>{learningFeedbackCategories.map(value=><option key={value} value={value}>{titleCaseLabel(value.replaceAll('_',' '))}</option>)}</select></label>
  <label>Your Observation<textarea className="field" maxLength={2000} required value={text} disabled={busy||!!pending} onChange={e=>setText(e.target.value)}/></label>
  <button type="submit" className="primary-button" disabled={!target||busy||!!pending}>Submit Feedback</button>{pending&&<><button type="button" className="secondary-button" disabled={busy} onClick={()=>void reconcile()}>Check Request Status</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>void reconcile(true)}>Close Pending Request</button></>}
  {!target&&!busy&&<button type="button" className="secondary-button" onClick={()=>{setOpen(false);setTimeout(()=>setOpen(true),0);}}>Refresh Target</button>}{notice&&<p role="status">{notice}</p>}{saved&&<Link href={`/learning/feedback/${saved}`}>View My Feedback</Link>}
 </form>}</div>;
}
