'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import type {listLearningCandidates} from '../../../lib/server/learning/reviews';
import type { readLearningFeedback,listLearningFeedback } from '../../../lib/server/learning/feedback';
import { useLearningView,useLearningMutation } from './view';
import { titleCaseLabel } from '../title-case-label';
export function LearningFeedbackList(){
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[cursor,setCursor]=useState<string|null>(null);
 const client=useLearningView<Awaited<ReturnType<typeof listLearningFeedback>>>(`/api/learning/feedback?limit=20&search=${encodeURIComponent(query)}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
 return <section className="profile-page"><header className="profile-header"><div><h1>Learning Feedback</h1><p>Private observations on exact guidance revisions. Feedback does not establish accepted facts.</p></div><button type="button" className="secondary-button" onClick={()=>void client.refresh()}>Refresh Feedback</button></header>{client.auth?.membership.kind==='internal'&&<p><Link href="/learning/drafts/new">Prepare a Learning Draft</Link> · <Link href="/learning/candidates">Review Learning Candidates</Link> · <Link href="/learning/measurements">Private Measurement Review</Link> · <Link href="/learning/trends">Outcome Trends</Link> · <Link href="/learning/health">Learning Health</Link></p>}{client.notice&&<p role="status">{client.notice}</p>}{client.loading&&<p role="status">Checking current access…</p>}
 <form className="profile-card" onSubmit={e=>{e.preventDefault();client.clear();setCursor(null);setQuery(search);}}><label>Search My Accessible Feedback<input className="field" maxLength={200} value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="secondary-button" type="submit">Search Feedback</button></form>
 {client.view&&<>{client.view.items.length?<div className="profile-grid">{client.view.items.map(item=><article className="profile-card" key={item.id}><h2><Link href={`/learning/feedback/${item.id}`}>{item.label}</Link></h2><p>{titleCaseLabel(item.category.replaceAll('_',' '))} · {titleCaseLabel(item.disposition.replaceAll('_',' '))}</p><p className="muted">Unverified observation · {new Date(item.createdAt).toLocaleString()}</p></article>)}</div>:<div className="profile-state"><h2>No Accessible Feedback</h2><p>Open shared guidance, a report, a product gap observation, a partner guide or your own training checkpoint to give feedback.</p></div>}{cursor&&<button type="button" className="secondary-button" onClick={()=>{client.clear();setCursor(null);}}>First Feedback Page</button>}{client.view.cursor&&<button type="button" className="secondary-button" onClick={()=>{client.clear();setCursor(client.view!.cursor);}}>More Feedback</button>}</>}
 </section>;
}
export function LearningFeedbackDetail({id}:{id:string}){
 const client=useLearningView<Awaited<ReturnType<typeof readLearningFeedback>>>(`/api/learning/feedback/${id}`),command=useLearningMutation(client.auth,`feedback:${id}`,client.refresh);
 const [text,setText]=useState(''),[editing,setEditing]=useState(false),[disposition,setDisposition]=useState('under_review'),[rationale,setRationale]=useState(''),[candidate,setCandidate]=useState(''),[error,setError]=useState('');
 const view=client.view,busy=command.busy||!!command.pending;
 const [candidateCursor,setCandidateCursor]=useState<string|null>(null);
 const candidates=useLearningView<Awaited<ReturnType<typeof listLearningCandidates>>>(view?.canTriage&&disposition==='linked'?`/api/learning/candidates?limit=20${candidateCursor?`&cursor=${encodeURIComponent(candidateCursor)}`:''}`:null);
 const accessibleCandidates=candidates.view?.items.filter(item=>!view?.customerId||item.customerId===view.customerId)??[];
 useEffect(()=>{if(!candidates.view||!accessibleCandidates.some(item=>item.revisionId===candidate))setCandidate('');},[candidates.view,view?.customerId,candidate]);
 useEffect(()=>{setEditing(false);setText('');setRationale('');setCandidate('');setCandidateCursor(null);},[view?.version,view?.canEdit,view?.canTriage]);
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>Feedback Detail</h1><p>Unverified observation; accepted evidence and reuse rights are separate.</p></div><button type="button" className="secondary-button" onClick={()=>{setEditing(false);setText('');setRationale('');void client.refresh();}}>Refresh Feedback</button></header>{client.notice&&<p role="status">{client.notice}</p>}{command.notice&&<p role="status">{command.notice}</p>}{error&&<p role="alert">{error}</p>}{command.pending&&<div className="profile-state"><p>Resolve the unconfirmed request before making another change.</p><button type="button" className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Request Status</button><button type="button" className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Pending Request</button></div>}
 {view&&<><article className="profile-card"><h2>{titleCaseLabel(view.category.replaceAll('_',' '))}</h2><p>{view.text}</p><p>Disposition: {titleCaseLabel(view.disposition.replaceAll('_',' '))}</p><p className="muted">Target: {titleCaseLabel(view.target.kind.replaceAll('_',' '))} · Generation {view.target.generation}</p>{view.canEdit&&!editing&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{setText(view.text);setEditing(true);}}>Edit My Observation</button>}
 {editing&&view.canEdit&&<form onSubmit={async e=>{e.preventDefault();try{setError('');await command.mutate(`/api/learning/feedback/${id}/revisions`,{expectedVersion:view.version,text});setEditing(false);setText('');}catch(error){setError(error instanceof Error?error.message:'Edit unavailable');}}}><label>Revised Observation<textarea className="field" required maxLength={2000} value={text} disabled={busy} onChange={e=>setText(e.target.value)}/></label><button type="submit" className="primary-button" disabled={busy}>Save Observation</button><button type="button" className="secondary-button" onClick={()=>{setEditing(false);setText('');}}>Cancel Edit</button></form>}</article>
 {view.canTriage&&<form className="profile-card" onSubmit={async e=>{e.preventDefault();try{setError('');await command.mutate(`/api/learning/feedback/${id}/dispositions`,{expectedVersion:view.version,state:disposition,rationale,...(disposition==='linked'?{candidateRevisionId:candidate}:{})});setRationale('');setCandidate('');}catch(error){setError(error instanceof Error?error.message:'Review unavailable');}}}><h2>Internal Disposition</h2><label>Disposition<select className="field" disabled={busy} value={disposition} onChange={e=>setDisposition(e.target.value)}>{['open','under_review','linked','deferred','dismissed'].map(value=><option key={value} value={value}>{titleCaseLabel(value.replaceAll('_',' '))}</option>)}</select></label><label>Internal Rationale<textarea className="field" maxLength={2000} required disabled={busy} value={rationale} onChange={e=>setRationale(e.target.value)}/></label>{disposition==='linked'&&<><label>Current Accessible Candidate<select className="field" required disabled={busy||candidates.loading} value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Select a current candidate revision</option>{accessibleCandidates.map(item=><option key={item.revisionId} value={item.revisionId}>{item.title} · Revision {item.revision}</option>)}</select></label>{candidates.notice&&<p role="status">{candidates.notice}</p>}{!candidates.loading&&!accessibleCandidates.length&&<p>No accessible candidate for this customer on this page.</p>}<button type="button" className="secondary-button" disabled={busy} onClick={()=>{setCandidate('');void candidates.refresh();}}>Refresh Accessible Candidates</button>{candidateCursor&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{setCandidate('');candidates.clear();setCandidateCursor(null);}}>First Candidate Page</button>}{candidates.view?.cursor&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{setCandidate('');candidates.clear();setCandidateCursor(candidates.view!.cursor);}}>More Accessible Candidates</button>}</>}<p className="muted">Linking a candidate does not grant access or approve its reuse.</p><button type="submit" className="primary-button" disabled={busy||(disposition==='linked'&&!candidate)}>Record Disposition</button></form>}
 <section className="profile-card"><h2>Disposition History</h2>{view.history.length?view.history.map(item=><article key={item.id}><h3>{titleCaseLabel(item.state.replaceAll('_',' '))}</h3><p>{new Date(item.at).toLocaleString()}</p>{item.rationale&&<p>{item.rationale}</p>}</article>):<p>No disposition decisions yet.</p>}{view.hasMoreHistory&&<p>Showing the most recent 20 decisions.</p>}</section></>}
 </section>;
}
