'use client';
import Link from 'next/link';
import {useState} from 'react';
import type {readLearningDashboard} from '../../../lib/server/learning/dashboard';
import {useLearningView} from './view';
export function LearningHealth(){
 const [cursor,setCursor]=useState<string|null>(null),client=useLearningView<Awaited<ReturnType<typeof readLearningDashboard>>>(`/api/learning/dashboard?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`),view=client.view;
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>Learning Health</h1><p>Separate evidence, evaluation and operational views. Each read checks current access.</p></div><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Learning Health</button></header>{client.notice&&<p role="status">{client.notice}</p>}{view&&<>{!view.enabled&&<p className="profile-state">New learning work is disabled. Eligible reads, withdrawal, reconciliation and cleanup remain available.</p>}<p className="muted">{view.scope}</p><section className="profile-card"><h2>Evidence Quality</h2><p>Quality is a review aid, not factual approval or probability. Original dates are never reset by learning.</p>{view.evidence.length?view.evidence.map(item=><article key={item.candidateId}><h3>{item.title}</h3><p>Revision {item.revision} · {item.quality.rubricVersion} · Quality {item.quality.Q} · {item.quality.band} · {item.quality.freshness}</p><p>R {item.quality.R} · F {item.quality.F} · D {item.quality.D} · C {item.quality.C}</p>{item.originalDates.map((date,index)=><p key={index}>Original {index+1}: observed {date.observationAt??'Unknown'}; published {date.publicationAt??'Unknown'}; reviewed {date.reviewAt??'Unknown'}.</p>)}<Link href={`/learning/candidates/${item.candidateId}`}>Review Current Practice</Link></article>):<p>No currently eligible practices on this authorized page.</p>}</section><section className="profile-card"><h2>Release Evaluation</h2><p>Coverage does not confer publication approval. Open an evaluation for current release checks.</p>{view.evaluations.length?view.evaluations.map(item=><article key={item.evaluationId}><h3>{item.state.replaceAll('_',' ')}</h3><p>{item.completedArms} of {item.requiredArms} arms captured; {item.reviewedCases} of {item.requiredPairs} pairs reviewed.</p><p>{item.exactCurrentRevision?'Exact current wording':'Historical wording; current review required'}</p><Link href={`/learning/evaluations/${item.evaluationId}`}>Review Exact Evaluation</Link></article>):<p>No evaluations on this authorized page.</p>}</section><section className="profile-card"><h2>Operations</h2><p>Due work prepares review only. External research and improvement drafts require separate scope and budget admission.</p>{view.operations.length?view.operations.map(item=><article key={item.jobId}><h3>{item.kind} review · {item.state.replaceAll('_',' ')}</h3><p>Due {item.dueAt}; overdue {item.overdueSeconds} seconds.</p><p>{item.action}</p><Link href={`/learning/refresh/${item.jobId}`}>Open Due Evidence Review</Link></article>):<p>No due evidence reviews in your authorized queue.</p>}</section>{view.cursor&&<button className="secondary-button" onClick={()=>{client.clear();setCursor(view.cursor);}}>Next Health Page</button>}{cursor&&<button className="secondary-button" onClick={()=>{client.clear();setCursor(null);}}>First Health Page</button>}</>}</section>;
}
