'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {listLearningMeasurements,readLearningMeasurement,readLearningMeasurementOriginal} from '../../../lib/server/learning/measurements';
import {learningMetricProtocols} from '../../../lib/learning/metric-protocols';
import {useLearningView,useLearningMutation} from './view';
import {titleCaseLabel} from '../title-case-label';
export function LearningMeasurementQueue(){
 const [cursor,setCursor]=useState<string|null>(null),client=useLearningView<Awaited<ReturnType<typeof listLearningMeasurements>>>(`/api/learning/measurements?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
 return <section className="profile-page"><Link href="/learning">Learning Feedback</Link><header className="profile-header"><div><h1>Private Measurement Review</h1><p>Review individual proposed mappings and original reuse rights separately from Outcome Trends.</p></div><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Measurement Queue</button></header>{client.notice&&<p role="status">{client.notice}</p>}{client.view&&<>{client.view.items.length?<div className="profile-grid">{client.view.items.map((item,index)=><article className="profile-card" key={item.id}><h2><Link href={`/learning/measurements/${item.id}`}>Measurement Proposal {index+1}</Link></h2><p>{titleCaseLabel(item.metricId.replaceAll('_',' '))} · {item.quarter} · {titleCaseLabel(item.state)}</p></article>)}</div>:<p>No accessible measurement proposals on this page.</p>}{client.view.cursor&&<button className="secondary-button" onClick={()=>{client.clear();setCursor(client.view!.cursor);}}>More Measurement Proposals</button>}{cursor&&<button className="secondary-button" onClick={()=>{client.clear();setCursor(null);}}>First Measurement Page</button>}</>}</section>;
}
export function LearningMeasurementDetail({id}:{id:string}){
 const client=useLearningView<Awaited<ReturnType<typeof readLearningMeasurement>>>(`/api/learning/measurements/${id}`),command=useLearningMutation(client.auth,`measurement:${id}`,client.refresh),[decision,setDecision]=useState('reject'),[rights,setRights]=useState(false),[rationale,setRationale]=useState(''),[withdrawal,setWithdrawal]=useState(''),[sourceId,setSourceId]=useState<string|null>(null),[error,setError]=useState('');
 const view=client.view,original=useLearningView<Awaited<ReturnType<typeof readLearningMeasurementOriginal>>>(view?.content&&sourceId?`/api/learning/measurements/${id}/originals/${sourceId}`:null),busy=command.busy||!!command.pending;
 useEffect(()=>{setDecision('reject');setRights(false);setRationale('');setWithdrawal('');setSourceId(null);},[view?.version,view?.closureDigest,view?.content===null]);
 const sources=view?.content?[...new Set([...view.content.outcomeRevisionIds,...view.content.baseline.fieldLocators.map(source=>source.revisionId),...view.content.current.fieldLocators.map(source=>source.revisionId)])]:[];
 return <section className="profile-page"><Link href="/learning/measurements">Private Measurement Review</Link><header className="profile-header"><div><h1>Measurement Proposal</h1><p>Accepted factual observations and measurement reuse approval are separate decisions.</p></div><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Measurement</button></header>{client.notice&&<p role="status">{client.notice}</p>}{error&&<p role="alert">{error}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Measurement Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Measurement Request</button></>}
 {view&&<><article className="profile-card"><h2>{view.customerName}</h2><p>{titleCaseLabel(view.metricId.replaceAll('_',' '))} · {view.quarter} · {titleCaseLabel(view.state)}</p>{view.content?<><p>{learningMetricProtocols[view.content.metricId].definition}</p><p>Complete population rule: {view.content.populationRule}</p><p>Predeclared workload identities: {view.content.workloadIds.join(', ')}</p>{(['baseline','current'] as const).map(key=><section key={key}><h3>{titleCaseLabel(key)} Accepted Window</h3><p>{view.content![key].start} to {view.content![key].end} (exclusive), UTC</p><p>All deployments: {view.content![key].deployments}</p>{view.content!.metricId==='deployment_lead_time'?<p>Total elapsed minutes: {view.content![key].totalMinutes}</p>:<p>Failed deployments within 24 hours: {view.content![key].failedDeployments}</p>}</section>)}<p>Zero deployments mean unavailable. Values are never interpreted as causal or commercial outcomes.</p><h3>Accepted Original Evidence</h3>{sources.map((source,index)=><button className="secondary-button" key={source} onClick={()=>{original.clear();setSourceId(source);}}>Read Measurement Original {index+1}</button>)}{original.notice&&<p role="status">{original.notice}</p>}{original.view&&<section><h4>Current Accepted Original</h4><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{typeof original.view.content==='string'?original.view.content:JSON.stringify(original.view.content,null,2)}</pre></section>}</>:<p>Protected mapping text is withheld because accepted evidence is unavailable or changed.</p>}</article>
 {view.canReview&&<form className="profile-card" onSubmit={async event=>{event.preventDefault();try{setError('');await command.mutate(`/api/learning/measurements/${id}/reviews`,{expectedVersion:view.version,revisionId:view.revisionId,closureDigest:view.closureDigest,decision,reuseApproved:decision==='approve'&&rights,rationale});}catch(error){setError(error instanceof Error?error.message:'Measurement review unavailable');}}}><h2>Separate Measurement Reuse Review</h2><label>Measurement Decision<select className="field" value={decision} disabled={busy} onChange={event=>{setDecision(event.target.value);setRights(false);}}><option value="reject">Reject</option><option value="approve">Approve Exact Mapping</option></select></label>{decision==='approve'&&<label><input type="checkbox" checked={rights} disabled={busy} onChange={event=>setRights(event.target.checked)}/>I verified comparable complete populations and original measurement reuse rights</label>}<label>Measurement Review Rationale<textarea className="field" required maxLength={2000} value={rationale} disabled={busy} onChange={event=>setRationale(event.target.value)}/></label><button className="primary-button" type="submit" disabled={busy||decision==='approve'&&!rights}>Record Measurement Reuse Decision</button></form>}
 {client.auth?.membership.role==='admin'&&view.state!=='withdrawn'&&<form className="profile-card" onSubmit={async event=>{event.preventDefault();try{setError('');await command.mutate(`/api/learning/measurements/${id}/withdraw`,{expectedVersion:view.version,rationale:withdrawal});}catch(error){setError(error instanceof Error?error.message:'Withdrawal unavailable');}}}><h2>Withdraw Measurement Reuse</h2><p>Withdrawal withholds any released quarterly family containing this revision. No replacement subset can be released.</p><label>Measurement Withdrawal Rationale<textarea className="field" required maxLength={2000} disabled={busy} value={withdrawal} onChange={event=>setWithdrawal(event.target.value)}/></label><button className="secondary-button" type="submit" disabled={busy}>Withdraw Measurement Contribution</button></form>}</>}
 </section>;
}
