'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {readLearningCandidate} from '../../../lib/server/learning/reviews';
import type {LearningAuth} from './client';
import {useLearningMutation} from './view';
import {useLearningView} from './view';
import {LearningRollback} from './rollback';
import type {readLearningCandidateControl} from '../../../lib/server/learning/reviews';

export function LearningPublicationControl({id,candidateState}:{id:string;candidateState?:string}){
 const client=useLearningView<Awaited<ReturnType<typeof readLearningCandidateControl>>>(`/api/learning/candidates/${id}/control`,true),command=useLearningMutation(client.auth,`publication:${id}`,client.refresh),[rationale,setRationale]=useState(''),[error,setError]=useState('');
 const head=client.view?.publication;
 useEffect(()=>{if(candidateState)void client.refresh();},[candidateState,client.refresh]);
 useEffect(()=>{setRationale('');},[head?.generation,client.view?.id]);
 if(client.auth?.membership.kind!=='internal'||client.auth.membership.role!=='admin')return null;
 return <section className="profile-card"><h2>Published Practice</h2>{head?<p>Actual published head: revision {head.revision}, generation {head.generation} · {head.state}</p>:<p>No published head.</p>}{head?.state==='published'&&client.view?.activated&&<form onSubmit={async event=>{event.preventDefault();try{setError('');await command.knowledge(`/api/knowledge/${head.id}/withdraw`,{expectedRevision:head.revision,expectedDigest:head.digest,expectedPublicationGeneration:head.generation,rationale});}catch(error){setError(error instanceof Error?error.message:'Withdrawal unconfirmed');}}}><p>Withdrawal applies to this published head, including when a newer draft is unavailable. It remains available while new learning work is disabled.</p><label>Withdrawal Rationale<textarea className="field" required maxLength={2000} disabled={command.busy||!!command.pending} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><button type="submit" className="secondary-button" disabled={command.busy||!!command.pending}>Withdraw Published Practice</button></form>}{error&&<p role="alert">{error}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Publication Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Publication Request</button></>}{client.view&&<LearningRollback view={client.view} auth={client.auth} refresh={client.refresh}/>}</section>;
}
type Candidate=Awaited<ReturnType<typeof readLearningCandidate>>;
const publicationChecks=[['namesAndDomainsRemoved','Names and domains removed'],['repositoriesAndLinksRemoved','Repositories and identifying links removed'],['peopleAndCommercialDetailsRemoved','People and commercial details removed'],['identifyingConfigurationAndOutcomesRemoved','Identifying configuration and outcomes removed'],['countsAndCombinedInferenceReviewed','Counts and combined inference reviewed']] as const;
export function LearningPublishCandidate({view,auth,refresh}:{view:Candidate;auth:LearningAuth;refresh:()=>Promise<void>}){
 const command=useLearningMutation(auth,`publish:${view.id}`,refresh),[evaluationId,setEvaluationId]=useState(''),[checked,setChecked]=useState<Record<string,boolean>>({}),[rights,setRights]=useState(false),[rationale,setRationale]=useState(''),[error,setError]=useState('');
 const control=useLearningView<Awaited<ReturnType<typeof readLearningCandidateControl>>>(view.canReview?`/api/learning/candidates/${view.id}/control`:null);
 const review=view.reviews[0],passed=view.evaluations?.filter(item=>item.state==='passed'&&item.revisionId===view.revisionId)??[];
 useEffect(()=>{setEvaluationId('');setChecked({});setRights(false);setRationale('');},[view.revisionId,view.closureDigest,review?.id,control.view?.publication?.generation]);
 if(!view.canReview)return null;
 const eligible=control.view?.activated&&control.view.enabled&&control.view.revisionId===view.revisionId&&view.state==='submitted'&&review?.decision==='accept'&&!review.revoked&&passed.length>0;
 return <section className="profile-card"><h2>Publish Reviewed Candidate</h2>{!eligible?<p>The exact current candidate needs a passing full paired evaluation and an enabled publication gate.</p>:<form onSubmit={async event=>{event.preventDefault();try{setError('');await command.knowledge(`/api/knowledge/contributions/${view.id}/decisions`,{expectedRevision:view.revision,expectedDigest:view.digest,...(control.view?.publication?{expectedPublicationGeneration:control.view.publication.generation}:{}),action:'publish',rightsAttested:rights,checklist:checked,sanitizationRationale:rationale,learningEvaluationId:evaluationId,learningReviewId:review.id,expectedBaselineGeneration:view.baselineGeneration??null});}catch(error){setError(error instanceof Error?error.message:'Publication unconfirmed');}}}><label>Passing Full Evaluation<select className="field" required value={evaluationId} onChange={event=>setEvaluationId(event.target.value)}><option value="">Select Evaluation</option>{passed.map((item,index)=><option key={item.id} value={item.id}>Passing Evaluation {index+1}</option>)}</select></label><fieldset disabled={command.busy||!!command.pending}><legend>Final Publication Review</legend>{publicationChecks.map(([key,label])=><label key={key}><input type="checkbox" checked={!!checked[key]} onChange={event=>setChecked({...checked,[key]:event.target.checked})}/>{label}</label>)}<label><input type="checkbox" checked={rights} onChange={event=>setRights(event.target.checked)}/>I verified current original reuse rights</label></fieldset><label>Publication Rationale<textarea className="field" required maxLength={2000} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><p>Publication uses the exact evaluated wording. The server rechecks originals, reuse rights, human review authority and the published baseline.</p><button type="submit" className="primary-button" disabled={command.busy||!!command.pending||!evaluationId||!rights||publicationChecks.some(([key])=>!checked[key])}>Publish Exact Evaluated Revision</button></form>}{error&&<p role="alert">{error}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Publish Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Publish Request</button></>}</section>;
}
export function LearningEvaluationPreparation({view,auth,refresh}:{view:Candidate;auth:LearningAuth;refresh:()=>Promise<void>}){
 const command=useLearningMutation(auth,`evaluation-prepare:${view.id}`,refresh),router=useRouter(),[budget,setBudget]=useState(''),[error,setError]=useState('');
 const review=view.reviews[0],eligible=view.canReview&&view.state==='submitted'&&review?.decision==='accept'&&!review.revoked&&review.contentDigest===view.digest&&review.closureDigest===view.closureDigest&&review.rightsDigest===view.rightsDigest;
 useEffect(()=>{setBudget('');setError('');},[view.revisionId,view.closureDigest,review?.id]);
 if(!view.canReview)return null;
 return <section className="profile-card"><h2>Prepare Full Paired Evaluation</h2><p>Runs all eight fixed cases against the current published baseline and this exact candidate. Preparation makes no model call; each arm requires explicit start. A failed run requires a fresh full evaluation and budget.</p>{!eligible?<p>A current accepted reuse review of the submitted revision is required.</p>:<form onSubmit={async event=>{event.preventDefault();try{setError('');const receipt=await command.mutate(`/api/learning/candidates/${view.id}/evaluations`,{expectedVersion:view.revision,reviewId:review.id,baselineGeneration:view.baselineGeneration??null,catalogDigest:view.evaluationCatalogDigest,budgetUsd:budget});if(receipt.targetId)router.push(`/learning/evaluations/${receipt.targetId}`);}catch(error){setError(error instanceof Error?error.message:'Evaluation unavailable');}}}><p>{view.baselineGeneration===null?'No published baseline; the baseline arm receives no practice.':`Published baseline generation ${view.baselineGeneration}`}</p><label>Evaluation Maximum Spend (USD)<input className="field" required inputMode="decimal" maxLength={10} value={budget} disabled={command.busy||!!command.pending} onChange={event=>setBudget(event.target.value)}/></label><p>Maximum $25. Each paid call must fit the remaining budget using the verified provider cost ceiling.</p><button className="primary-button" type="submit" disabled={command.busy||!!command.pending}>Prepare Paired Evaluation</button></form>}{error&&<p role="alert">{error}</p>}{command.notice&&<p role="status">{command.notice}</p>}{command.pending&&<><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile()}>Check Evaluation Request Status</button><button className="secondary-button" disabled={command.busy} onClick={()=>void command.reconcile(true)}>Close Evaluation Request</button></>}</section>;
}
