"use client";
import { useRef,useState } from "react";
import { partnerGuideContentSchema,type PartnerGuideContent,type PartnerSource } from "../../../lib/contracts/partners";
import { PartnerEvidencePicker } from "./evidence-picker";
const fields=["objective","what","how","why","alternatives","limitations","validation","escalation"] as const;
const labels={objective:"Objective",what:"What to Do",how:"How to Do It",why:"Why It Works",alternatives:"Alternatives",limitations:"Limitations",validation:"Validation",escalation:"Escalation"};
export function emptyPartnerGuide():PartnerGuideContent{const lessonId=crypto.randomUUID();return {title:"",lessons:[{id:lessonId,order:1,objective:"",what:"",how:"",why:"",alternatives:"",limitations:"",validation:"",escalation:"",prerequisites:[],unknowns:[],sourceIds:[]}],checkpoints:[{id:crypto.randomUUID(),lessonId,order:1,title:"",criterion:"",required:true,prerequisiteIds:[],sourceIds:[]}],sources:[]};}
export function PartnerGuideEditor({customerId,engagementId,content,onChange,onSave,onCancel,busy}:{customerId:string;engagementId:string;content:PartnerGuideContent;onChange:(content:PartnerGuideContent)=>void;onSave:()=>Promise<void>;onCancel:()=>void;busy:boolean}){
 const [error,setError]=useState(""),summary=useRef<HTMLParagraphElement>(null);
 const change=(run:(next:PartnerGuideContent)=>void)=>{const next=structuredClone(content);run(next);onChange(next);};
 const mapSource=(ids:string[],id:string,checked:boolean)=>checked?[...ids,id]:ids.filter(s=>s!==id);
 const sourceMappings=(ids:string[],update:(ids:string[])=>void)=><fieldset><legend>Supporting Sources</legend>{content.sources.map((source,index)=><label key={source.id}><input type="checkbox" checked={ids.includes(source.id)} disabled={busy} onChange={e=>update(mapSource(ids,source.id,e.target.checked))}/> Source {index+1}: {source.kind.replaceAll("_"," ")} · {source.classification.replaceAll("_"," ")}</label>)}</fieldset>;
 const selectSources=(sources:PartnerSource[])=>change(next=>{const current=new Set(sources.map(s=>s.id));next.sources=sources;for(const item of [...next.lessons,...next.checkpoints])item.sourceIds=item.sourceIds.filter(id=>current.has(id));});
 return <form className="profile-card partner-form" onSubmit={async event=>{event.preventDefault();const parsed=partnerGuideContentSchema.safeParse(content);if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.join(" / ")||"Guide"}: ${i.message}`).join(". "));requestAnimationFrame(()=>summary.current?.focus());return;}try{setError("");await onSave();}catch(reason){setError(reason instanceof Error?reason.message:"Save failed");requestAnimationFrame(()=>summary.current?.focus());}}}>
  <h2>Author Delivery Guide</h2><p>Draft learning guidance against this exact accepted baseline. Publishing remains a separate reviewed decision.</p>{error&&<p ref={summary} tabIndex={-1} role="alert">{error}</p>}
  <label>Guide Title<input id="partner-guide-title" className="field" value={content.title} onChange={e=>change(c=>{c.title=e.target.value;})} required disabled={busy}/></label>
  <PartnerEvidencePicker customerId={customerId} engagementId={engagementId} selected={content.sources} onSelect={selectSources} disabled={busy}/>
  {content.sources.map((source,index)=><label key={source.id}>Source {index+1} Supports<select className="field" disabled={busy} value={source.classification} onChange={e=>change(c=>{c.sources[index].classification=e.target.value as PartnerSource['classification'];})}><option value="customer_fact" disabled={!["accepted_profile","approved_excerpt"].includes(source.kind)}>Accepted Customer Fact</option><option value="product_evidence">Product Behavior</option><option value="shared_practice" disabled={source.kind!=="shared_knowledge"}>Shared Practice</option></select></label>)}
  {content.lessons.map((lesson,index)=><fieldset className="profile-card" key={lesson.id}><legend>Lesson {index+1}</legend>{fields.map(field=><label key={field}>{labels[field]} — Lesson {index+1}<textarea id={`partner-lesson-${lesson.id}-${field}`} className="field" rows={3} value={lesson[field]} required disabled={busy} onChange={e=>change(c=>{c.lessons[index][field]=e.target.value;})}/></label>)}
   <label>Prerequisites — Lesson {index+1}<textarea className="field" rows={2} value={lesson.prerequisites.join("\n")} disabled={busy} onChange={e=>change(c=>{c.lessons[index].prerequisites=e.target.value.split("\n").filter(Boolean);})}/></label><label>Unknowns — Lesson {index+1}<textarea className="field" rows={2} value={lesson.unknowns.join("\n")} disabled={busy} onChange={e=>change(c=>{c.lessons[index].unknowns=e.target.value.split("\n").filter(Boolean);})}/></label>
   {sourceMappings(lesson.sourceIds,ids=>change(c=>{c.lessons[index].sourceIds=ids;}))}
   {index>0&&<button type="button" className="secondary-button" disabled={busy||content.checkpoints.some(cp=>cp.lessonId===lesson.id)} onClick={()=>change(c=>{c.lessons.splice(index,1);c.lessons.forEach((item,n)=>item.order=n+1);})}>Remove Lesson {index+1}</button>}
  </fieldset>)}
  <button type="button" className="secondary-button" disabled={busy||content.lessons.length>=20} onClick={()=>change(c=>{c.lessons.push({...emptyPartnerGuide().lessons[0],order:c.lessons.length+1});})}>Add Lesson</button>
  {content.checkpoints.map((checkpoint,index)=><fieldset className="profile-card" key={checkpoint.id}><legend>Checkpoint {index+1}</legend><label>Checkpoint Title — {index+1}<input className="field" required value={checkpoint.title} disabled={busy} onChange={e=>change(c=>{c.checkpoints[index].title=e.target.value;})}/></label><label>Demonstration Criterion — {index+1}<textarea className="field" required rows={3} value={checkpoint.criterion} disabled={busy} onChange={e=>change(c=>{c.checkpoints[index].criterion=e.target.value;})}/></label>
   <label>Lesson — Checkpoint {index+1}<select className="field" value={checkpoint.lessonId} disabled={busy} onChange={e=>change(c=>{c.checkpoints[index].lessonId=e.target.value;})}>{content.lessons.map((lesson,n)=><option key={lesson.id} value={lesson.id}>Lesson {n+1}</option>)}</select></label><label><input type="checkbox" checked={checkpoint.required} disabled={busy} onChange={e=>change(c=>{c.checkpoints[index].required=e.target.checked;})}/> Required Checkpoint {index+1}</label>
   <fieldset><legend>Verified Prerequisites — Checkpoint {index+1}</legend>{content.checkpoints.filter(cp=>cp.id!==checkpoint.id).map(cp=><label key={cp.id}><input type="checkbox" disabled={busy} checked={checkpoint.prerequisiteIds.includes(cp.id)} onChange={e=>change(c=>{c.checkpoints[index].prerequisiteIds=mapSource(checkpoint.prerequisiteIds,cp.id,e.target.checked);})}/> Checkpoint {cp.order}: {cp.title||"Untitled"}</label>)}</fieldset>
   {sourceMappings(checkpoint.sourceIds,ids=>change(c=>{c.checkpoints[index].sourceIds=ids;}))}<button type="button" className="secondary-button" disabled={busy||content.checkpoints.length<=1} onClick={()=>change(c=>{c.checkpoints.splice(index,1);c.checkpoints.forEach((item,n)=>{item.order=n+1;item.prerequisiteIds=item.prerequisiteIds.filter(id=>id!==checkpoint.id);});})}>Remove Checkpoint {index+1}</button>
  </fieldset>)}
  <button type="button" className="secondary-button" disabled={busy||content.checkpoints.length>=40} onClick={()=>change(c=>{c.checkpoints.push({...emptyPartnerGuide().checkpoints[0],lessonId:c.lessons[0].id,order:c.checkpoints.length+1});})}>Add Checkpoint</button>
  <div className="gap-filters"><button type="submit" className="primary-button" disabled={busy}>Save Guide Draft</button><button type="button" className="secondary-button" disabled={busy} onClick={onCancel}>Cancel Guide Draft</button></div>
 </form>;
}
