"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import type { readPartnerGuide,listPartnerGuides } from "../../../lib/server/partners/guides";
import type { PartnerGuideContent,PartnerReceipt } from "../../../lib/contracts/partners";
import { usePartnerView } from "./revalidation";
import { usePartnerMutations } from "./mutations";
import { PartnerGuideEditor,emptyPartnerGuide } from "./guide-editor";
import {PartnerAssignmentList,PartnerAssignmentPicker} from "./learning";
import { PartnerGuideReview } from "./guide-review";
const explanationLabels={objective:"Objective",what:"What",how:"How",why:"Why",alternatives:"Alternatives",limitations:"Limitations",validation:"Validation",escalation:"Escalation"} as const;
export function PendingRequest({client}:{client:ReturnType<typeof usePartnerMutations>}){return <>{client.status&&<p role="status">{client.status}</p>}{client.pending&&<div className="profile-card"><p>A request is unconfirmed. Check or resolve it before starting another action.</p><button type="button" className="secondary-button" disabled={client.busy} onClick={()=>void client.reconcile()}>Check Request Status</button><button type="button" className="secondary-button" disabled={client.busy} onClick={()=>void client.reconcile(true)}>Resolve Old Request</button></div>}</>;}
export function PartnerGuideList({customerId,engagementId}:{customerId:string;engagementId:string;acceptedRevisionId:string;baselineId:string}){
 const [cursor,setCursor]=useState<string|null>(null),query=new URLSearchParams({customerId,engagementId,limit:"10",...(cursor?{cursor}:{})});
 const client=usePartnerView<Awaited<ReturnType<typeof listPartnerGuides>>>(`/api/partners/guides?${query}`),{view}=client;
 return <section><h3>Reviewed Guides</h3>{client.status&&<p role="status">{client.status}</p>}{view&&<>
  {view.canAuthor&&view.baselineEligible&&<Link prefetch={false} href={`/partners/guides/new?customerId=${customerId}&engagementId=${engagementId}`}>New Delivery Guide</Link>}
  {view.items.length?view.items.map(item=><div className="profile-card" key={item.guideId}><Link prefetch={false} href={item.href}>{item.title}</Link><p>{item.reviewState} · {item.availability.replaceAll("_"," ")}</p></div>):<p>No published guides are available on this page.</p>}
  {cursor&&<button type="button" className="secondary-button" onClick={()=>{client.clear();setCursor(null);}}>First Guide Page</button>}{view.nextCursor&&<button type="button" className="secondary-button" onClick={()=>{client.clear();setCursor(view.nextCursor);}}>More Guides</button>}
 </>}</section>;
}
export function PartnerGuideCreate({customerId,engagementId}:{customerId:string;engagementId:string}){
 const router=useRouter(),query=new URLSearchParams({customerId,engagementId,limit:"1"}),protectedView=usePartnerView<Awaited<ReturnType<typeof listPartnerGuides>>>(`/api/partners/guides?${query}`),{view}=protectedView,client=usePartnerMutations(view,protectedView.session,protectedView.clear),[draft,setDraft]=useState<PartnerGuideContent|null>(null),[error,setError]=useState("");
 useEffect(()=>{setDraft(emptyPartnerGuide());const clear=()=>{setDraft(emptyPartnerGuide());setError("");};window.addEventListener("turas.partner.access-cleared",clear);return()=>window.removeEventListener("turas.partner.access-cleared",clear);},[]);
 return <section className="profile-page" data-partner-view={`/api/partners/guides?${query}`}><h1>New Delivery Guide</h1>{protectedView.status&&<p role="status">{protectedView.status}</p>}<PendingRequest client={client}/>{error&&<p role="alert">{error}</p>}{view&&view.canAuthor&&view.baselineEligible&&draft&&<PartnerGuideEditor customerId={customerId} engagementId={engagementId} content={draft} onChange={setDraft} onCancel={()=>router.push(`/partners/customers/${customerId}`)} busy={client.busy||!!client.pending} onSave={async()=>{try{const receipt=await client.mutate<PartnerReceipt>("/api/partners/commands",{action:"guide.create",customerId,engagementId,acceptedRevisionId:view.acceptedRevisionId,baselineId:view.baselineId,expectedVersion:0,content:draft},null);setDraft(null);router.push(`/partners/guides/${receipt.targetId}`);}catch(reason){setError(reason instanceof Error?reason.message:"Save failed");throw reason;}}}/>}{view&&(!view.canAuthor||!view.baselineEligible)&&<p>Guide authoring is unavailable for this delivery baseline.</p>}</section>;
}
export function PartnerGuideDetail({guideId}:{guideId:string}){
 const protectedView=usePartnerView<Awaited<ReturnType<typeof readPartnerGuide>>>(`/api/partners/guides/${guideId}`),{view}=protectedView,client=usePartnerMutations(view,protectedView.session,protectedView.clear);
 const [draft,setDraft]=useState<PartnerGuideContent|null>(null),[error,setError]=useState(""),editorVersion=useRef<number|null>(null),result=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{const clear=()=>{setDraft(null);setError("");editorVersion.current=null;};window.addEventListener("turas.partner.access-cleared",clear);return()=>window.removeEventListener("turas.partner.access-cleared",clear);},[]);
 useEffect(()=>{if(view&&editorVersion.current!==null&&view.version!==editorVersion.current){setDraft(null);editorVersion.current=null;}if(view&&view.availability!=="eligible")setDraft(null);},[view]);
 const busy=client.busy||Boolean(client.pending);
 return <section className="profile-page"><header className="profile-header"><div><h1>{view?.content?.title??"Delivery Guide"}</h1><p>Reviewed learning guidance tied to an accepted delivery baseline.</p></div><button className="secondary-button" type="button" onClick={()=>void protectedView.refresh()}>Refresh Guide</button></header>
  {protectedView.status&&<p role="status">{protectedView.status}</p>}<PendingRequest client={client}/>{error&&<p ref={result} tabIndex={-1} role="alert">{error}</p>}
  {view&&<div data-testid="partner-protected-body" data-partner-view={`/api/partners/guides/${guideId}`}><p>Revision {view.revisionNumber} · Version {view.version} · {view.reviewState} · {view.availability.replaceAll("_"," ")}</p><p><Link prefetch={false} href={`/customers/${view.customerId}/plans/${view.planId}`}>Accepted Delivery Plan</Link> · <Link prefetch={false} href={`/partners/customers/${view.customerId}`}>Customer Delivery Work</Link></p>
   {view.content&&!draft&&<>{view.content.lessons.map(lesson=><article className="profile-card" key={lesson.id}><h2>Lesson {lesson.order}: {lesson.objective}</h2>{Object.entries(explanationLabels).map(([key,label])=><div key={key}><h3>{label}</h3><p>{lesson[key as keyof typeof explanationLabels]}</p></div>)}<h3>Prerequisites</h3>{lesson.prerequisites.length?<ul>{lesson.prerequisites.map((text,n)=><li key={n}>{text}</li>)}</ul>:<p>No additional prerequisites declared.</p>}<h3>Unknowns</h3>{lesson.unknowns.length?<ul>{lesson.unknowns.map((text,n)=><li key={n}>{text}</li>)}</ul>:<p>No additional unknowns declared.</p>}<h3>Supporting Evidence</h3>{lesson.sourceIds.map(id=>{const source=view.content!.sources.find(s=>s.id===id)!;return <p key={id}>{source.kind.replaceAll("_"," ")} · Quality {source.quality.Q}/100 · {source.quality.freshness} · {source.quality.rationale}</p>;})}
   {view.content!.checkpoints.filter(cp=>cp.lessonId===lesson.id).map(cp=><section className="profile-card" key={cp.id}><h3>Checkpoint {cp.order}: {cp.title}</h3><p>{cp.required?"Required":"Optional"}</p><p>{cp.criterion}</p><p>{cp.prerequisiteIds.length?`Requires verified checkpoints: ${cp.prerequisiteIds.map(id=>view.content!.checkpoints.find(other=>other.id===id)!.order).join(", ")}`:"No verified checkpoint prerequisites."}</p></section>)}</article>)}
   <section className="profile-card"><h2>Original Evidence Dates</h2>{view.content.sources.map((source,index)=><div key={source.id}><h3>Source {index+1}: {source.classification.replaceAll("_"," ")}</h3><p>Observed {source.observationAt??"not publicly specified"}; published {source.publicationAt??"not publicly specified"}; review due {source.reviewAt??"not publicly specified"}.</p><p>Assessed {source.quality.asOf}; valid until {source.quality.validUntil}.</p><blockquote>{view.citations.find(c=>c.sourceId===source.id)?.text}</blockquote><Link prefetch={false} href={source.kind==="shared_knowledge"?"/knowledge":`/customers/${view.customerId}`}>{source.kind==="shared_knowledge"?"Sanitized Shared Knowledge":"Accepted Customer Context"}</Link></div>)}</section></>}
   {!view.content&&<p>Guide content is withheld under current evidence or authority. Refresh after an authorized review.</p>}
   {view.canAuthor&&view.content&&!draft&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>{editorVersion.current=view.version;setDraft(structuredClone(view.content));}}>Edit Guide Draft</button>}
   {draft&&view.canAuthor&&view.availability==="eligible"&&editorVersion.current===view.version&&<PartnerGuideEditor customerId={view.customerId} engagementId={view.engagementId} content={draft} onChange={setDraft} onCancel={()=>setDraft(null)} busy={busy} onSave={async()=>{await client.mutate("/api/partners/commands",{action:"guide.revise",guideId,expectedVersion:view.version,acceptedRevisionId:view.acceptedRevisionId,baselineId:view.baselineId,content:draft},guideId);setDraft(null);await protectedView.refresh();}}/>}
   {view.canAuthor&&view.reviewState==="draft"&&!draft&&<button type="button" className="primary-button" disabled={busy||view.availability!=="eligible"} onClick={async()=>{try{setError("");await client.mutate("/api/partners/commands",{action:"guide.submit",guideId,revisionId:view.revisionId,contentDigest:view.contentDigest,expectedVersion:view.version},guideId);await protectedView.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Submission failed");requestAnimationFrame(()=>result.current?.focus());}}}>Submit Guide for Review</button>}
   <PartnerAssignmentList customerId={view.customerId} guideId={view.guideId}/>
   <section className="profile-card"><h2>Guide Decision History</h2>{view.history.length?view.history.map(item=><div key={item.decisionId}><p>{item.action} · {item.decidedAt??"Date minimized"}</p>{item.rationale&&<p>{item.rationale}</p>}</div>):<p>No decisions for this revision.</p>}</section>
  </div>}
  <PartnerAssignmentPicker view={view} client={client} onDecided={protectedView.refresh}/>
  <PartnerGuideReview view={view} client={client} onDecided={protectedView.refresh}/>
 </section>;
}
