"use client";
import { useEffect,useRef,useState } from "react";
import type { readPartnerGuide } from "../../../lib/server/partners/guides";
import type { previewPartnerGuide } from "../../../lib/server/partners/previews";
import type { usePartnerMutations } from "./mutations";
import type { PartnerClientScope } from "./revalidation";
type View=Awaited<ReturnType<typeof readPartnerGuide>> & PartnerClientScope;
type ReviewAction="guide.publish"|"guide.reject"|"guide.retire";
export function PartnerGuideReview({view,client,onDecided}:{view:View|null;client:ReturnType<typeof usePartnerMutations>;onDecided:()=>Promise<void>}){
 const [action,setAction]=useState<ReviewAction>("guide.publish"),[rationale,setRationale]=useState(""),[selfReview,setSelfReview]=useState(false),[prepared,setPrepared]=useState<{preview:Awaited<ReturnType<typeof previewPartnerGuide>>;input:Record<string,unknown>;namespace:string}|null>(null),[error,setError]=useState("");const summary=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{const clear=()=>{setPrepared(null);setRationale("");setSelfReview(false);setError("");};window.addEventListener("turas.partner.access-cleared",clear);return()=>window.removeEventListener("turas.partner.access-cleared",clear);},[]);
 useEffect(()=>{if(view&&prepared&&(view.commandNamespace!==prepared.namespace||view.version!==prepared.preview.version))setPrepared(null);},[view,prepared]);
 if(!view?.canReview)return null;
 const busy=client.busy||Boolean(client.pending),eligible=view.availability==="eligible",submitted=view.reviewState==="submitted";
 return <section className="profile-card" data-partner-view={`/api/partners/guides/${view.guideId}`}><h2 id="partner-guide-review-result" tabIndex={-1}>Review Exact Guide</h2><p>Version {view.version} · Revision {view.revisionNumber} · {view.availability.replaceAll("_"," ")}</p>{error&&<p ref={summary} tabIndex={-1} role="alert">{error}</p>}
  <label>Guide Decision<select className="field" value={action} disabled={busy} onChange={e=>{setPrepared(null);setAction(e.target.value as ReviewAction);}}><option value="guide.publish" disabled={!submitted||!eligible||view.newWorkDisabled}>Publish</option><option value="guide.reject" disabled={!submitted||view.newWorkDisabled}>Request a New Guide Revision</option><option value="guide.retire">Retire Guide</option></select></label>
  <label>Guide Review Rationale<textarea id="partner-guide-review-rationale" className="field" rows={3} maxLength={2000} value={rationale} disabled={busy} onChange={e=>{setPrepared(null);setRationale(e.target.value);}}/></label>
  <label><input type="checkbox" checked={selfReview} disabled={busy} onChange={e=>{setPrepared(null);setSelfReview(e.target.checked);}}/> I acknowledge reviewing my own authored content when applicable</label>
  <button id="partner-prepare-guide-review" type="button" className="secondary-button" disabled={busy||!rationale.trim()||view.newWorkDisabled&&action!=="guide.retire"||action!=="guide.retire"&&!submitted||action==="guide.publish"&&!eligible} onClick={async()=>{try{setError("");const input={action,guideId:view.guideId,revisionId:view.revisionId,contentDigest:view.contentDigest,expectedVersion:view.version,rationale,selfReview},preview=await client.mutate<Awaited<ReturnType<typeof previewPartnerGuide>>>("/api/partners/previews",input,view.guideId);setPrepared({preview,input,namespace:view.commandNamespace});}catch(reason){setError(reason instanceof Error?reason.message:"Review preview failed");}requestAnimationFrame(()=>summary.current?.focus());}}>Prepare Guide Review</button>
  {prepared&&prepared.preview.version===view.version&&<div className="profile-card"><h3>Exact Decision Preview</h3><p>{action.replace("guide.","")} · Guide version {prepared.preview.version} · {prepared.preview.availability.replaceAll("_"," ")}</p><p>{rationale}</p><p>Review expires {prepared.preview.expiresAt}</p>{prepared.preview.citations.map(citation=><blockquote key={citation.sourceId}>{citation.text}</blockquote>)}<button type="button" className="primary-button" disabled={busy||Date.parse(prepared.preview.expiresAt)<=Date.now()} onClick={async()=>{try{setError("");await client.mutate("/api/partners/commands",{...prepared.input,previewId:prepared.preview.previewId},view.guideId);setPrepared(null);setRationale("");await onDecided();requestAnimationFrame(()=>document.getElementById("partner-guide-review-result")?.focus());}catch(reason){setError(reason instanceof Error?reason.message:"Decision failed");}requestAnimationFrame(()=>summary.current?.focus());}}>Confirm Guide Decision</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>{setPrepared(null);requestAnimationFrame(()=>document.getElementById("partner-prepare-guide-review")?.focus());}}>Cancel Guide Review</button></div>}
 </section>;
}
