'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {readPendingGap,writePendingGap,requireGapReceipt,type PendingGap} from './pending';
type Session={membership:{id:string;kind:string};workspace:{id:string};csrfToken:string};
type Meta={commandNamespace:string;scopeGeneration:string|number};
type Receipt={id:string;operation:string;recordId:string|null;resultId:string|null;bindingDigest:string|null;outcome:string;version:number};
export function useGapView<T extends Meta>(path:string){
 const [view,setView]=useState<T|null>(null),[session,setSession]=useState<Session|null>(null),[status,setStatus]=useState('Loading current product gaps…'),[busy,setBusy]=useState(false),[pending,setPending]=useState<PendingGap|null>(null),[generation,setGeneration]=useState(0);
 const prior=useRef<Meta|null>(null),active=useRef<PendingGap|null>(null),sequence=useRef(0),controllers=useRef(new Set<AbortController>());
 const clear=useCallback(()=>{sequence.current++;for(const controller of controllers.current)controller.abort();controllers.current.clear();setView(null);setSession(null);setGeneration(g=>g+1);},[]);
 const refresh=useCallback(async()=>{const seq=++sequence.current,controller=new AbortController();controllers.current.add(controller);try{const [auth,response]=await Promise.all([fetch('/api/auth/session',{cache:'no-store',signal:controller.signal}),fetch(path,{cache:'no-store',signal:controller.signal})]);if(seq!==sequence.current)return;if(!auth.ok||!response.ok){clear();setStatus(response.status===409?'The view changed. Refresh the first page.':'Product gaps are unavailable to your account.');return;}const a=await auth.json(),v=await response.json();if(seq!==sequence.current)return;if(a.data?.membership.kind!=='internal'||!v.data?.commandNamespace)throw Error('Unavailable');const next=v.data as T;if(prior.current&&(prior.current.commandNamespace!==next.commandNamespace||prior.current.scopeGeneration!==next.scopeGeneration))setGeneration(g=>g+1);prior.current=next;setSession(a.data);setView(next);const remembered=readPendingGap(next.commandNamespace);active.current=remembered;setPending(remembered);setStatus(remembered?'A previous request is unconfirmed. Check its status before continuing.':'');}catch(error){if((error as Error).name!=='AbortError'&&seq===sequence.current){clear();setStatus('Product gaps are unavailable. Refresh to retry.');}}finally{controllers.current.delete(controller);}},[path,clear]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},15000);const focus=()=>{clear();void refresh();};const visibility=()=>{clear();if(!document.hidden)void refresh();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',visibility);return()=>{sequence.current++;clearInterval(timer);for(const c of controllers.current)c.abort();window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visibility);};},[refresh,clear]);
 async function mutate(url:string,operation:string,recordId:string|null,input:Record<string,unknown>):Promise<Receipt>{if(!view||!session||active.current||busy)throw Error('Check the pending request before continuing.');const requestKey=crypto.randomUUID(),command={requestKey,operation,recordId},namespace=view.commandNamespace,controller=new AbortController();active.current=command;setPending(command);writePendingGap(namespace,command);setBusy(true);controllers.current.add(controller);try{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify({...input,contractVersion:'product-gaps-v1',requestKey}),signal:controller.signal});const body=await response.json();if(!response.ok){if(response.status<500){writePendingGap(namespace,null);active.current=null;setPending(null);}if([401,404,409].includes(response.status))clear();throw Error(body.error?.message??'Request unconfirmed');}requireGapReceipt(body.data,command);writePendingGap(namespace,null);active.current=null;setPending(null);return body.data as Receipt;}catch(error){setStatus((error as Error).message);throw error;}finally{setBusy(false);controllers.current.delete(controller);}}
 async function reconcile(){if(!view||!active.current)return;const command=active.current;try{const response=await fetch(`/api/product-gaps/requests/${command.requestKey}?operation=${encodeURIComponent(command.operation)}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error('Request remains unconfirmed.');requireGapReceipt(body.data,command);writePendingGap(view.commandNamespace,null);active.current=null;setPending(null);await refresh();setStatus('Request confirmed.');}catch(error){setStatus((error as Error).message);}}
 return {view,session,status,busy,pending,generation,refresh,mutate,reconcile};
}
export type GapClient=ReturnType<typeof useGapView<Meta>>;
