'use client';
import {useState} from 'react';
import type {GapClient} from './client';
import type {readGapReport} from '../../../lib/server/gaps/reports';
type View=Awaited<ReturnType<typeof readGapReport>>;
export function GapDisclosure({report,client}:{report:View;client:GapClient}){
 const [action,setAction]=useState('approve'),[ack,setAck]=useState<string[]>([]),[audienceAck,setAudienceAck]=useState(false),[selfReview,setSelfReview]=useState(false),[rationale,setRationale]=useState(''),[preview,setPreview]=useState<{id:string;digest:string}|null>(null),[error,setError]=useState('');
 const document=report.document!,disabled=client.busy||!!client.pending,change=()=>setPreview(null);
 return <form className="profile-card gap-form" onSubmit={async e=>{e.preventDefault();setError('');try{if(preview){await client.mutate('/api/product-gaps/reports/'+report.id+'/decisions','review_report',report.id,{expectedVersion:report.version,previewId:preview.id,bindingDigest:preview.digest});setPreview(null);await client.refresh();}else{const result=await client.mutate('/api/product-gaps/reports/'+report.id+'/previews','preview_report',report.id,{expectedVersion:report.version,action,revisionId:report.revision!.id,customerDisclosures:ack,audienceDigest:report.revision!.audienceDigest,rationale,selfReview});setPreview({id:result.resultId!,digest:result.bindingDigest!});}}catch(err){setPreview(null);setError((err as Error).message);}}}><h2>Exact Report Review</h2><p>Team: {document.header.audience.team}</p><p>Recipients: {document.header.audience.recipients.join(', ')}</p><p>Purpose: {document.header.audience.purpose}</p><label>Report Review Action<select className="field" value={action} onChange={e=>{change();setAction(e.target.value);}}><option value="approve">Approve</option><option value="reject">Reject</option></select></label><fieldset><legend>Customer Disclosure for This Exact Audience</legend>{document.customers.map(customer=><label key={customer.id}><input type="checkbox" checked={ack.includes(customer.id)} onChange={e=>{const checked=e.currentTarget.checked;change();setAck(ids=>checked?[...ids,customer.id]:ids.filter(id=>id!==customer.id));}}/>I authorize disclosure of {customer.name} to the named recipients for this purpose.</label>)}{!document.customers.length&&<p>This exact draft includes no customer identity or customer passages.</p>}</fieldset><label><input type="checkbox" checked={audienceAck} onChange={e=>{change();setAudienceAck(e.target.checked);}}/>I reviewed the complete document, exact recipients, purpose and disclosure scope.</label><label>Report Review Rationale<textarea className="field" value={rationale} required maxLength={2000} onChange={e=>{change();setRationale(e.target.value);}}/></label><label><input type="checkbox" checked={selfReview} onChange={e=>{change();setSelfReview(e.target.checked);}}/>I acknowledge reviewing my own report preparation when applicable.</label>{error&&<p role="alert">{error}</p>}{preview&&<p role="status">The exact document, audience, sources and both candidate digests are bound for five minutes.</p>}<button className="primary-button" disabled={disabled||!audienceAck||action==='approve'&&ack.length!==document.customers.length}>{preview?'Confirm Report Review':'Preview Report Review'}</button></form>;
}
