'use client';
import {useState,type FormEvent} from 'react';
import {gapContentSchema,type GapContent,type GapSource,gapKinds,gapSeverities} from '../../../lib/contracts/product-gaps';
import {GapEvidence} from './evidence';
const narratives=[['problem','Problem'],['workflow','Workflow'],['desiredOutcome','Desired Outcome'],['reproduction','Reproduction'],['constraints','Constraints'],['workaround','Workaround'],['workaroundLimitations','Workaround Limitations'],['proposedCapability','Proposed Capability'],['alternatives','Alternatives'],['unknowns','Unknowns'],['requestedDecision','Requested Decision']] as const;
export function GapEditor({initial,sources=[],busy,onSave,onCancel}:{initial?:GapContent;sources?:GapSource[];busy:boolean;onSave:(content:GapContent,refs:GapSource[])=>Promise<void>;onCancel:()=>void}){
 const [refs,setRefs]=useState(sources),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),value=Object.fromEntries(data);try{if(value.customerIndependent!=='on')throw Error('Acknowledge the customer-independent narrative before saving.');const content=gapContentSchema.parse({...Object.fromEntries(narratives.map(([key])=>[key,value[key]])),kind:value.kind,title:value.title,productKey:value.productKey,capability:value.capability,productVersion:value.productVersion||null,triageTeam:value.triageTeam,acceptanceCriteria:String(value.acceptanceCriteria).split('\n').filter(s=>s.trim()),severity:value.severity,severityRationale:value.severityRationale,workaroundFeasibility:value.workaroundFeasibility});await onSave(content,refs);}catch(e){setError(e instanceof Error?e.message:'Invalid gap fields');}}
 return <form className="gap-form" onSubmit={submit}><h2>{initial?'Edit Proposed Gap':'New Gap Proposal'}</h2>{error&&<p role="alert">{error}</p>}<label>Gap Kind<select className="field" name="kind" defaultValue={initial?.kind??'product_gap'}>{gapKinds.map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label>{[['title','Gap Title',200],['productKey','Product Key',200],['capability','Capability',200],['productVersion','Product Version',100],['triageTeam','Triage Team',200]] .map(([key,label,max])=><label key={key}>{label}<input className="field" name={String(key)} required={key!=='productVersion'} maxLength={Number(max)} defaultValue={initial?.[key as keyof GapContent] as string??(key==='productKey'?'unknown':'')}/></label>)}{narratives.map(([key,label])=><label key={key}>{label}<textarea className="field" name={key} required maxLength={4000} defaultValue={initial?.[key]??''}/></label>)}<label>Acceptance Criteria (One per Line)<textarea className="field" name="acceptanceCriteria" required maxLength={20020} defaultValue={initial?.acceptanceCriteria.join('\n')??''}/></label><label>Severity<select className="field" name="severity" defaultValue={initial?.severity??'unknown'}>{gapSeverities.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Severity Rationale<textarea className="field" name="severityRationale" required maxLength={2000} defaultValue={initial?.severityRationale??''}/></label><label>Workaround Feasibility<select className="field" name="workaroundFeasibility" defaultValue={initial?.workaroundFeasibility??'unknown'}>{['none','limited','feasible','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><GapEvidence selected={refs} onChange={setRefs}/><label className="report-checkbox"><input name="customerIndependent" type="checkbox" required/>The common narrative contains no private customer passages or identifiers. Customer-specific evidence belongs in observations.</label><div className="report-actions"><button className="primary-button" disabled={busy} type="submit">Save as Proposed</button><button className="secondary-button" disabled={busy} type="button" onClick={onCancel}>Cancel Draft</button></div></form>;
}
