'use client';
import {useState} from 'react';
import {GapCustomer} from './customer';
import type {GapSource} from '../../../lib/contracts/product-gaps';
export function GapEvidence({selected,onChange,customerId:fixedCustomer}:{selected:GapSource[];onChange:(refs:GapSource[])=>void;customerId?:string}){
 const [customerId,setCustomer]=useState(fixedCustomer??''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[results,setResults]=useState<Array<{title:string;text:string;reference:GapSource}>>([]);
 async function search(){setResults([]);try{const response=await fetch(`/api/product-gaps/evidence?${new URLSearchParams({customerId,query,limit:'10'})}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error?.message??'Evidence unavailable');setResults(body.data.results);setStatus(body.data.results.length?'':'No eligible originals found. Keep unknowns explicit.');}catch(error){setStatus((error as Error).message);}}
 return <fieldset className="report-selection"><legend>Original Evidence</legend>{!fixedCustomer&&<GapCustomer label="Evidence Customer" value={customerId} onChange={id=>{setCustomer(id);setResults([]);}}/>}<label>Evidence Search<input className="field" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary-button" type="button" disabled={!customerId||!query.trim()} onClick={()=>void search()}>Search Evidence</button>{status&&<p role="status">{status}</p>}{results.map(r=><article className="profile-card" key={r.reference.id}><h3>{r.title}</h3><p>{r.text}</p><button className="secondary-button" type="button" disabled={selected.length>=50||selected.some(s=>s.kind===r.reference.kind&&s.sourceRevisionId===r.reference.sourceRevisionId)} onClick={()=>onChange([...selected,r.reference])}>Select Evidence</button></article>)}{selected.map((ref,i)=><div key={ref.id}><p>Evidence {i+1}: {ref.kind.replaceAll('_',' ')}</p><label>Evidence {i+1} Purpose<select className="field" value={ref.purpose} onChange={e=>onChange(selected.map(r=>r.id===ref.id?{...r,purpose:e.target.value as GapSource['purpose']}:r))}>{['customer_need','product_limitation','resolution','corroboration'].map(p=><option key={p} value={p}>{p.replaceAll('_',' ')}</option>)}</select></label><button className="secondary-button" type="button" onClick={()=>onChange(selected.filter(r=>r.id!==ref.id))}>Remove Evidence {i+1}</button></div>)}</fieldset>;
}
