'use client';
import {useState} from 'react';
import {GapEvidence} from './evidence';
import type {GapSource} from '../../../lib/contracts/product-gaps';
import type {readGapReport} from '../../../lib/server/gaps/reports';
import type {GapClient} from './client';
type View=Awaited<ReturnType<typeof readGapReport>>;
export function GapHandoff({report,client}:{report:View;client:GapClient}){
 const full=report.availability==='eligible'&&!!report.review,scopeEvents=full?report.handoffs.filter(event=>event.reviewId===report.review!.id):report.handoffs,latest=scopeEvents.at(-1);
 const [kind,setKind]=useState(latest?'acknowledged':'handed_off'),[eventAt,setEventAt]=useState(''),[note,setNote]=useState(''),[reference,setReference]=useState(''),[correctedId,setCorrectedId]=useState(latest?.id??''),[error,setError]=useState(''),[sourceRefs,setSources]=useState<GapSource[]>([]);
 return <section className="profile-card"><h2>Human-Reported Engineering Handoff</h2><p>Record an action already taken by a person. These records do not send a report or change customer resolution.</p>{report.document&&<p>Exact team: {report.document.header.audience.team}. Recipients: {report.document.header.audience.recipients.join(', ')}. Purpose: {report.document.header.audience.purpose}.</p>}
 <ol>{report.handoffs.map(event=><li key={event.id}><p>{event.kind.replaceAll('_',' ')} · {new Date(event.eventAt).toLocaleString()} · Human reported by membership {event.reporterMembershipId??'unavailable'}; recorded {new Date(event.recordedAt).toLocaleString()}.</p><p>Receipt: {event.id}{event.predecessorId?' · Follows '+event.predecessorId:''}{event.correctedId?' · Corrects '+event.correctedId:''}</p>{event.needsHumanFollowUp&&<p role="status">Human follow-up required; report or response evidence is unavailable or changed.</p>}{event.payload?<><p>{event.payload.note}</p>{event.payload.reference&&<p>Inert reference: <span>{event.payload.reference}</span></p>}<p>Classification: human reported; {event.payload.sourceRefs.length} attached source references.</p></>:<p>{event.metadataOnly?'Metadata-only record.':'Response prose withheld.'}</p>}</li>)}</ol>
 {report.reviewer&&(full||latest)&&<form className="gap-form" onSubmit={async e=>{e.preventDefault();setError('');try{await client.mutate('/api/product-gaps/reports/'+report.id+'/handoffs','handoff',report.id,{expectedVersion:report.version,kind,eventAt:eventAt?new Date(eventAt+'Z').toISOString():new Date().toISOString(),audienceDigest:full?report.review!.audienceDigest:latest!.audienceDigest,predecessorId:kind==='handed_off'?null:latest?.id??null,correctedId:kind==='correction'?correctedId:null,metadataOnly:!full,note:full?note:null,reference:full&&reference?reference:null,sourceRefs:full?sourceRefs:[]});await client.refresh();}catch(err){setError((err as Error).message);}}}>
 {!full&&<p>The report is unavailable. Only a metadata-only follow-up or correction can be recorded; no note, reference or evidence is retained.</p>}
 <label>Handoff Event<select className="field" value={kind} onChange={e=>setKind(e.target.value)}>{(latest?['acknowledged','investigating','resolution_reported','correction']:['handed_off']).map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>
 <label>Event Time (UTC; Blank Means Now)<input className="field" type="datetime-local" value={eventAt} onChange={e=>setEventAt(e.target.value)}/></label>
 {kind==='correction'&&<label>Corrected Receipt<select className="field" value={correctedId} onChange={e=>setCorrectedId(e.target.value)}>{scopeEvents.map(event=><option key={event.id} value={event.id}>{event.kind} · {event.id}</option>)}</select></label>}
 {full&&<><label>Human-Reported Note<textarea className="field" required maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Inert HTTPS Reference (Optional)<input className="field" type="url" maxLength={2000} value={reference} onChange={e=>setReference(e.target.value)}/></label><GapEvidence selected={sourceRefs} onChange={setSources}/></>}
 {error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={client.busy||!!client.pending}>Record Human-Reported Event</button></form>}</section>;
}
