'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import type {readGapReport} from '../../../lib/server/gaps/reports';
import {useGapView,type GapClient} from './client';
import {GapDisclosure} from './disclosure';
import {GapHandoff} from './handoff';
type View=Awaited<ReturnType<typeof readGapReport>>;
function ReportValue({value}:{value:unknown}){if(value===null||value===undefined)return <span>Unknown</span>;if(Array.isArray(value))return value.length?<ul>{value.map((v,i)=><li key={i}><ReportValue value={v}/></li>)}</ul>:<span>None</span>;if(typeof value==='object')return <dl className="gap-report-values">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k.replace(/([a-z])([A-Z])/g,'$1 $2')}</dt><dd><ReportValue value={v}/></dd></div>)}</dl>;return <span>{String(value)}</span>;}
function ReportDownloads({report,client}:{report:View;client:GapClient}){
 const controller=useRef<AbortController|null>(null),exportId=useRef<string|null>(null),[status,setStatus]=useState(''),[working,setWorking]=useState(false);
 useEffect(()=>()=>{controller.current?.abort();},[]);
 async function download(format:'markdown'|'json'){setWorking(true);setStatus('Preparing current-authorized export…');const abort=new AbortController();controller.current=abort;try{const receipt=await client.mutate('/api/product-gaps/reports/'+report.id+'/exports','export_report',report.id,{expectedVersion:report.version,format,reviewId:report.review!.id});exportId.current=receipt.resultId!;const response=await fetch('/api/product-gaps/reports/'+report.id+'/exports/'+receipt.resultId,{cache:'no-store',signal:abort.signal});if(!response.ok||!response.body)throw Error('Export unavailable; refresh the report.');if(response.headers.get('x-turas-review-id')!==report.review!.id||response.headers.get('x-turas-audience-digest')!==report.revision!.audienceDigest)throw Error('Export review envelope changed');const expected=Number(response.headers.get('x-turas-byte-length')),digest=response.headers.get('x-turas-content-digest');if(!Number.isInteger(expected)||expected<1||expected>5242880)throw Error('Invalid export byte bound');const reader=response.body.getReader(),parts:Uint8Array[]=[];let bytes=0;try{for(;;){const part=await reader.read();if(part.done)break;bytes+=part.value.length;if(bytes>expected)throw Error('Export byte parity failed');parts.push(part.value);}}finally{reader.releaseLock();}if(bytes!==expected)throw Error('Export interrupted; reconcile its identity before retrying.');const joined=new Uint8Array(bytes);let offset=0;for(const part of parts){joined.set(part,offset);offset+=part.length;}const sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',joined))].map(b=>b.toString(16).padStart(2,'0')).join('');if(sha!==digest||abort.signal.aborted)throw Error('Export stopped or changed');const url=URL.createObjectURL(new Blob([joined],{type:response.headers.get('content-type')??'application/octet-stream'})),anchor=document.createElement('a');anchor.href=url;anchor.download=receipt.resultId+'.'+(format==='json'?'json':'md');anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Export received. Approval '+report.review!.id+'; exact '+bytes+' bytes, SHA256 '+sha+'.');}catch(error){controller.current?.abort();setStatus((error as Error).name==='AbortError'?'Export stopped.':(error as Error).message);}finally{setWorking(false);controller.current=null;}}
 return <section className="profile-card"><h2>Approved Private Exports</h2><p>Approved at {new Date(report.review!.approvedAt).toLocaleString()} by the designated mcteer reviewer. Approval identity: {report.review!.id}.</p><p>These self-contained copies are for the exact named audience and purpose.</p><div className="gap-actions">{(['markdown','json'] as const).map(format=><button key={format} className="primary-button" disabled={working||client.busy||!!client.pending} onClick={()=>void download(format)}>Download {format==='json'?'JSON':'Markdown'}</button>)}{working&&<button className="secondary-button" onClick={async()=>{controller.current?.abort();if(exportId.current)try{await client.mutate('/api/product-gaps/reports/'+report.id+'/cancel','cancel_report',report.id,{expectedVersion:report.version,exportId:exportId.current});setStatus('Export cancelled; this identity cannot be reused.');}catch(error){setStatus((error as Error).message);}}}>Cancel Export</button>}</div>{status&&<p role="status">{status}</p>}</section>;
}
export function GapReport({reportId}:{reportId:string}){const client=useGapView<View>('/api/product-gaps/reports/'+reportId),report=client.view;
 return <section className="profile-page"><Link href="/product-gaps">Product Gaps</Link><h1>Engineering Report</h1>{client.status&&<p role="status">{client.status}</p>}{client.pending&&<button className="secondary-button" onClick={()=>void client.reconcile()}>Check Request Status</button>}{report&&<><div className="gap-actions"><button className="secondary-button" onClick={()=>void client.refresh()}>Refresh Report</button>{report.canCancel&&<button className="secondary-button" disabled={client.busy||!!client.pending} onClick={async()=>{try{await client.mutate('/api/product-gaps/reports/'+reportId+'/cancel','cancel_report',reportId,{expectedVersion:report.version});await client.refresh();}catch{}}}>Cancel Preparation</button>}</div><p role="status">Preparation: {report.job?.state??'unknown'} · Content: {report.availability}{report.job?.failureCode?' · '+report.job.failureCode.replaceAll('_',' '):''}</p>{!report.document&&<p>{report.availability==='expired'?'This report expired. Prepare and review a new report.':report.availability==='withheld'?'The original evidence or reviewed scope changed. This report is withheld.':report.job?.state==='failed'?'Preparation failed. Reconcile the request before explicitly preparing a new draft.':'No report prose is currently available.'}</p>}{report.document&&<><article className="profile-card"><h2>Exact Report Audience and Scope</h2><p>{report.document.header.templateVersion==='gap-detail-v1'?'Detail report':'Product-gap portfolio'} · {report.document.header.selectedGapIds.length} selected gap{report.document.header.selectedGapIds.length===1?'':'s'}</p><p>Engineering team: {report.document.header.audience.team}</p><p>Named recipients: {report.document.header.audience.recipients.join(', ')}</p><p>Purpose: {report.document.header.audience.purpose}</p><p>Impact cutoff: {new Date(report.document.header.asOf).toLocaleString()}{report.document.header.comparisonAt?' · Comparison: '+new Date(report.document.header.comparisonAt).toLocaleString():''}</p><p>{report.document.header.classification}</p><details><summary>Report identity, source view and method</summary><ReportValue value={report.document.header}/></details></article>{report.document.sections.map(section=><article className="profile-card" key={section.id}><h2>{section.id}. {section.title}</h2><ReportValue value={section.content}/></article>)}<article className="profile-card"><h2>Review Verification</h2><ReportValue value={report.document.review}/><p>{report.review?'Approved at '+new Date(report.review.approvedAt).toLocaleString()+'; receipt '+report.review.id+'.':'Prepared draft — no approval has been recorded.'}</p></article>{report.reviewer&&<GapDisclosure key={'review:'+client.generation} report={report} client={client}/>} {report.reviewer&&report.review&&<ReportDownloads key={'exports:'+client.generation} report={report} client={client}/>}</>}<GapHandoff key={'handoff:'+client.generation} report={report} client={client}/></>}</section>;
}
