'use client';
import {useState,type FormEvent} from 'react';
import type {GapRevisionProjection} from '../../../lib/server/gaps/projection';
type Receipt={resultId:string|null;bindingDigest:string|null};
export function GapReview({target,version,working,reviewed,busy,onPreview,onCommit}:{target:'gap'|'impact';version:number;working:GapRevisionProjection|null;reviewed:GapRevisionProjection|null;busy:boolean;onPreview:(input:Record<string,unknown>)=>Promise<Receipt>;onCommit:(input:Record<string,unknown>)=>Promise<unknown>}){
 const [action,setAction]=useState(target==='gap'?'accept':'accept'),[preview,setPreview]=useState<Receipt|null>(null),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const revision=['accept','reject'].includes(action)?working:reviewed??working;if(!revision)return;try{const result=await onPreview({expectedVersion:version,target,revisionId:revision.id,action,rationale:data.get('rationale'),revisitDate:action==='defer'?`${data.get('revisit')}:00.000Z`:null,selfReview:data.get('selfReview')==='on',...(target==='gap'&&action==='accept'?{customerIndependentAcknowledgment:data.get('customerIndependent')==='on'?true:undefined}:{})});setPreview(result);setError('');}catch(error){setError((error as Error).message);}}
 return <section className="profile-section"><h3>Review {target==='gap'?'Gap':'Impact'}</h3><p>Only mcteer can decide. Acceptance records judgment against these exact revisions and originals.</p><form className="gap-form" onSubmit={submit} onChange={()=>setPreview(null)}><label>Review Action<select className="field" value={action} onChange={e=>setAction(e.target.value)}>{(target==='gap'?['accept','reject','defer','dismiss','reopen']:['accept','reject','retire']).map(a=><option key={a}>{a}</option>)}</select></label><label>Review Rationale<textarea className="field" name="rationale" required maxLength={2000}/></label>{action==='defer'&&<label>Revisit Date (UTC)<input className="field" name="revisit" type="datetime-local" required/></label>}{target==='gap'&&action==='accept'&&<label className="report-checkbox"><input type="checkbox" name="customerIndependent" required/>I reviewed the common narrative and confirm it contains no private customer passages or identifiers.</label>}<label className="report-checkbox"><input type="checkbox" name="selfReview"/>I acknowledge reviewing my own authored proposal.</label><button className="secondary-button" disabled={busy} type="submit">Preview Decision</button></form>{error&&<p role="alert">{error}</p>}{preview&&<div className="profile-card"><p>Exact {action} preview is ready. Changing the form clears it; it expires in five minutes.</p><button className="primary-button" disabled={busy} type="button" onClick={()=>void onCommit({expectedVersion:version,previewId:preview.resultId,bindingDigest:preview.bindingDigest}).then(()=>setPreview(null)).catch(e=>{setPreview(null);setError(e.message);})}>Confirm Decision</button></div>}</section>;
}
