import {z} from 'zod';
import {expansionEvaluationCases,expansionReviewCriteria} from '../tests/fixtures/expansion/evaluation';
const digest=z.string().regex(/^[a-f0-9]{64}$/);
const criteria=z.object({criterion:z.enum(expansionReviewCriteria),passed:z.literal(true),rationale:z.string().trim().min(1).max(2000)}).strict();
const captured=z.object({id:z.enum(['E01','E02','E03','E04','E05','E06','E07','E08']),attemptId:z.string().uuid(),capturePath:z.string().min(1).max(500),captureDigest:digest,inputDigest:digest,sourceMapDigest:digest,outputDigest:digest.nullable(),terminalState:z.enum(['completed','failed','cancelled','expired','unconfirmed','invalidated']),released:z.boolean(),initialDispatches:z.literal(1),automaticPaidRetries:z.literal(0),paidSteps:z.number().int().min(1).max(6),inputTokens:z.number().int().nonnegative(),outputTokens:z.number().int().min(0).max(49152),costUsd:z.number().finite().nonnegative(),latencyMs:z.number().finite().nonnegative().max(120000),providerMetadataComplete:z.literal(true),domainUnchanged:z.literal(true),staleSuggestionSaveDenied:z.boolean(),review:z.array(criteria).length(6)}).strict();
export const expansionActualReviewSchema=z.object({version:z.literal('expansion-output-review-v1'),sourceDigest:digest,rootAgentDigest:digest,promptDigest:digest,cohortDigest:digest,model:z.string().min(1).max(200),actualConfiguredProvider:z.literal(true),budgetUsd:z.number().finite().positive(),reviewer:z.string().trim().min(1).max(200),reviewedAt:z.string().datetime(),cases:z.array(captured).length(8)}).strict();
/** This structural gate never awards semantic fidelity. A reviewer must read the
 * exact capture and supply each criterion's independent rationale. */
export function verifyExpansionActualReview(raw:unknown){const review=expansionActualReviewSchema.parse(raw);if(new Set(review.cases.map(item=>item.attemptId)).size!==8)throw Error('Distinct actual attempts required');if(review.cases.reduce((sum,item)=>sum+item.costUsd,0)>review.budgetUsd)throw Error('Actual review exceeds operator budget');for(const [index,item] of review.cases.entries()){if(item.id!==expansionEvaluationCases[index].id||item.review.some((criterion,i)=>criterion.criterion!==expansionReviewCriteria[i]))throw Error('Required cohort or independent criteria missing/reordered');if(index<7){if(!item.released||item.terminalState!=='completed'||!item.outputDigest)throw Error('Actual configured-provider output missing');}else if(item.released||item.terminalState==='completed'||item.outputDigest||!item.staleSuggestionSaveDenied)throw Error('Changed owner must withhold output and deny stale saving');}return review;}
