import {randomUUID,createHash} from 'node:crypto';
import {writeFile,readFile,mkdir,mkdtemp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {withGapEnvironment} from './gaps-eval-environment';
import {featureSourceDigest} from './execution-source-digest';
import {gapActors} from '../tests/fixtures/gaps/seed';
import {acceptedGapEvidence} from '../tests/fixtures/gaps/evidence';
import {gapEnvelope} from '../tests/fixtures/gaps/authoring';
import {syntheticGap} from '../tests/fixtures/gaps/ui';
import {withGapDatabase} from '../tests/fixtures/gaps/environment';
import {saveGap,readGap} from '../lib/server/gaps/service';
import {prepareGapReport,readGapReport,cancelGapReport} from '../lib/server/gaps/reports';
import {claimGapReportJobs} from '../lib/server/gaps/report-jobs';
import {stageGapObject,writeGapObject,readGapObject} from '../lib/server/gaps/store';
import {maintainGapRetention} from '../lib/server/gaps/maintenance';
import {withTransaction} from '../lib/server/db/client';
import {DEMO_IDS} from '../lib/server/bootstrap-ids';
function check(value:unknown,message:string):asserts value{if(!value)throw Error(message);}
async function main(){if(process.argv.length!==2)throw Error('Recovery accepts no connection overrides');const sourceDigest=await featureSourceDigest('012'),results:unknown[]=[];await mkdir('local-artifacts/012',{recursive:true,mode:0o700});const directory=await mkdtemp(resolve('local-artifacts/012/recovery-'));
 for(const prior of [undefined,47] as const)await withGapEnvironment(async environment=>{const actors=await gapActors(),evidence=await acceptedGapEvidence(actors.panel,actors.mcteer,DEMO_IDS.sharedCustomer,'corroboration','Synthetic predecessor source survives explicit upgrade.'),marker=randomUUID(),markerPath=join(environment.workflowRoot,'012-recovery-marker');await writeFile(markerPath,marker,{mode:0o600});if(prior){await environment.startSupervisor();await environment.stop();await environment.upgradeToCurrent();}const schema=(await withGapDatabase(db=>db.query('SELECT schema_version FROM turas_environment'))).rows[0].schema_version;check(Number(schema)===49,'Schema49 required');const command={...gapEnvelope(),content:syntheticGap(),sourceRefs:[evidence.reference],customerIndependentAcknowledgment:true},saved=await saveGap(actors.panel,command);check((await readGap(actors.panel,saved.recordId!)).working?.availability==='eligible','Predecessor evidence lost');check((await saveGap(actors.panel,command)).id===saved.id,'Decision identity repeated');
 const report=await prepareGapReport(actors.panel,{...gapEnvelope(),kind:'portfolio',gapIds:[],asOf:new Date().toISOString(),comparisonAt:null,audience:{team:'Synthetic engineering',recipients:['Synthetic Engineer'],purpose:'Owned crash and forward-recovery check'}}),job=(await claimGapReportJobs())[0];check(job?.id===report.resultId,'Exact running job required');const bytes=Buffer.from('Synthetic abandoned staging bytes'),digest=createHash('sha256').update(bytes).digest('hex'),key=await withTransaction(db=>stageGapObject(db,{workspaceId:actors.panel.workspaceId,jobId:job.id,revisionId:randomUUID()},'markdown',digest,bytes.length));await writeGapObject(bytes,key);process.env.TURAS_012_DISABLED='1';await environment.startWorker();await environment.crashWorker();await withGapDatabase(db=>db.query("UPDATE gap_report_jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=$1",[job.id]));await environment.startWorker();const until=Date.now()+195000;for(;;){const row=(await withGapDatabase(db=>db.query('SELECT state FROM gap_report_store_objects WHERE object_key=$1',[key]))).rows[0];if(row.state==='deleted')break;check(Date.now()<until,'Disabled cleanup did not recover staged file');await new Promise(r=>setTimeout(r,250));}check((await readGapReport(actors.panel,report.recordId!)).job?.state==='failed','Abandoned preparation restarted');await readGapObject(key,digest,bytes.length).then(()=>{throw Error('Deleted bytes restored');},()=>undefined);await cancelGapReport(actors.panel,report.recordId!,{...gapEnvelope(1)});await environment.stop();
 await withGapDatabase(async db=>{await db.query('BEGIN');try{await db.query('ALTER TABLE gap_request_receipts DISABLE TRIGGER gap_immutable');await db.query("UPDATE gap_request_receipts SET created_at=clock_timestamp()-interval '366 days' WHERE id=$1",[saved.id]);await db.query('ALTER TABLE gap_request_receipts ENABLE TRIGGER gap_immutable');await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}});await maintainGapRetention();const keys=JSON.parse(process.env.TURAS_012_RECEIPT_HASH_KEYS!);process.env.TURAS_012_RECEIPT_HASH_KEYS=JSON.stringify(['SyntheticRotatedGapKey-AtLeast32Bytes',...keys]);try{await saveGap(actors.panel,command);throw Error('Expired request resurrected');}catch(error){check((error as {code?:string}).code==='receipt_expired','Expired key was not fenced after rotation');}delete process.env.TURAS_012_DISABLED;await environment.startSupervisor();check(await readFile(markerPath,'utf8')===marker,'Workflow marker changed');check((await readGapReport(actors.panel,report.recordId!)).job?.state==='failed','Failed job retried on restart');await environment.stop();check((await withGapDatabase(db=>db.query('SELECT count(*)::int AS n FROM gap_expired_request_keys'))).rows[0].n>0,'Lifetime tombstone lost');results.push({path:prior?'047-to-049':'empty-to-049',schema:49,predecessorPreserved:true,workflowPreserved:true,crashRecovered:true,disabledCleanup:true,noAutomaticRetry:true,tombstoneRotation:true});},{priorSchema:prior,deadlineMs:600000});check(await featureSourceDigest('012')===sourceDigest,'Recovery source changed');const summary={sourceDigest,results,hostedProof:false};await writeFile(resolve(directory,'completed.json'),JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));}
main().catch(error=>{console.error(error instanceof Error?error.message:'Gap recovery failed');process.exitCode=1;});
