import {spawn} from 'node:child_process';
import {readFile,readdir,mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {withGapEnvironment} from './gaps-eval-environment';
import {featureSourceDigest} from './execution-source-digest';
import {executionUiDiscovery,verifyExecutionUiReport} from './execution-ui-report';
/** Keep the owner event loop free to drain its supervised app/worker pipes. */
export function gapNodeProcess(args:string[],timeoutMs:number,maxBuffer=10000000){return new Promise<{status:number|null;stdout:string;stderr:string;error?:{code:string}}>(done=>{
 const child=spawn(process.execPath,args,{env:process.env,stdio:['ignore','pipe','pipe']});let stdout='',stderr='',outBytes=0,errBytes=0,error:{code:string}|undefined,finished=false;
 const complete=(status:number|null)=>{if(finished)return;finished=true;clearTimeout(timer);if(error){child.stdout.destroy();child.stderr.destroy();}done({status,stdout,stderr,...(error?{error}:{})});};
 const stop=(code:string)=>{if(error)return;error={code};child.kill('SIGKILL');};
 const timer=setTimeout(()=>stop('ETIMEDOUT'),timeoutMs);
 child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');
 child.stdout.on('data',(chunk:string)=>{outBytes+=Buffer.byteLength(chunk);if(outBytes>maxBuffer)stop('ENOBUFS');else stdout+=chunk;});
 child.stderr.on('data',(chunk:string)=>{errBytes+=Buffer.byteLength(chunk);if(errBytes>maxBuffer)stop('ENOBUFS');else stderr+=chunk;});
 child.once('error',()=>{error={code:'SPAWN_FAILED'};complete(null);});child.once('exit',status=>{if(error)complete(status);});child.once('close',complete);
 });}
export const gapUiProjects=['webkit-desktop-light','webkit-desktop-dark','webkit-mobile-light','webkit-mobile-dark'] as const;
export function verifyGapUiFiles(actual:readonly string[],manifest:readonly string[]){if(manifest.length!==6||new Set(manifest).size!==6||JSON.stringify([...actual].sort())!==JSON.stringify([...manifest].sort()))throw Error('Gap UI requires all six journey files');}
/** Fixed metadata only: private browser errors and fixture prose stay in owned evidence. */
export function gapUiFailure(raw:unknown){const failures:Array<{file:string;line:number;status:string;category:string;call?:string;locations?:Array<{file:string;line:number;column:number}>;diagnostic?:unknown}>=[];let visited=0;function walk(value:unknown,depth=0){if(++visited>10000||depth>20||!value||typeof value!=='object')return;const row=value as Record<string,unknown>;const file=typeof row.file==='string'?row.file.match(/(?:^|\/)gap-(authoring|canonicalization|reports|handoff|revocation|accessibility)\.spec\.ts$/)?.[0].split('/').at(-1):undefined;if(file&&Number.isSafeInteger(row.line)&&Array.isArray(row.tests))for(const test of row.tests){if(!test||typeof test!=='object'||!Array.isArray(test.results))continue;for(const result of test.results){if(!result||result.status==='passed')continue;const message=JSON.stringify(result.errors??result.error??'');const primary=Array.isArray(result.errors)?result.errors[0]:result.error,firstLine=typeof primary?.message==='string'?primary.message.split('\n')[0]:'',call=firstLine.match(/(?:locator|page|apiRequestContext)\.(?:click|fill|check|selectOption|goto|waitForURL|post|evaluate)/)?.[0],locations=[...message.matchAll(/(gap-(?:authoring|canonicalization|reports|handoff|revocation|accessibility)\.spec\.ts):(\d+):(\d+)/g)].slice(0,3).map(match=>({file:match[1],line:Number(match[2]),column:Number(match[3])}));let diagnostic:unknown;for(const item of result.stdout??[]){if(typeof item?.text!=='string'||!item.text.startsWith('GAP_UI_FIXED_DIAGNOSTIC '))continue;try{const parsed=JSON.parse(item.text.slice(24));const routes=/^(?:session|login|canonicalization|report-(?:handoffs|previews|decisions|cancel|exports|detail|registry)|request-status|customer-workloads|evidence|gap-(?:impacts|revisions|previews|decisions|registry|detail))$/;const signals=['Product gaps are unavailable','Loading current product gaps','The view changed','Record changed','Content: withheld','Content: eligible','No reviewed revision yet.','Request unconfirmed','Preparation: prepared'];diagnostic={responses:(parsed.responses??[]).slice(-30).filter((r:any)=>routes.test(r.route)&&['GET','POST','PUT','DELETE','PATCH'].includes(r.method)&&Number.isInteger(r.status)&&r.status>=100&&r.status<=599).map((r:any)=>({route:r.route,method:r.method,status:r.status})),signals:(parsed.signals??[]).filter((signal:any)=>signals.includes(signal))};}catch{}}failures.push({...(call?{call}:{}),...(locations.length?{locations}:{}),...(diagnostic?{diagnostic}:{}),file,line:Number(row.line),status:['failed','timedOut','interrupted','skipped'].includes(result.status)?result.status:'unknown',category:/timed out|timeout/i.test(message)?'timeout':/strict mode/i.test(message)?'ambiguous_locator':/expect|AssertionError/.test(message)?'assertion':'case_failure'});}}for(const key of ['suites','specs'])if(Array.isArray(row[key]))for(const child of row[key])walk(child,depth+1);}walk(raw);return failures;}
export async function checkGapUi(){if(process.argv.length!==2)throw Error('Gap UI accepts no filters');const files=JSON.parse(await readFile('scripts/gaps-ui-journeys.json','utf8')) as string[];verifyGapUiFiles((await readdir('tests/ui')).filter(f=>/^gap-.*\.spec\.ts$/.test(f)).map(f=>'tests/ui/'+f),files);const digest=await featureSourceDigest('012');await mkdir('local-artifacts/012',{recursive:true,mode:0o700});const directory=await mkdtemp(resolve('local-artifacts/012/ui-'));let passed=0;await withGapEnvironment(async environment=>{await environment.start();
// Compile every owned journey route before the unchanged 30-second browser deadlines.
const routeFiles=(await readdir('app',{recursive:true})).filter(file=>file.includes('product-gaps')&&/(?:route\.ts|page\.tsx)$/.test(file)).sort();
for(const file of routeFiles){const path='/'+file.replace(/\([^/]+\)\//g,'').replace(/\/(?:route\.ts|page\.tsx)$/,'').replace(/\[[^/]+\]/g,'00000000-0000-4000-8000-000000000000');const response=await fetch(environment.origin+path,{redirect:'manual',signal:AbortSignal.timeout(90000)});await response.body?.cancel();if(response.status>=500)throw Error('Owned gap route compilation failed');}
await environment.startWorker();process.env.TURAS_UI_BASE_URL=environment.origin;process.env.TURAS_GAPS_UI_FIXTURE_READY='1';for(const project of gapUiProjects){const args=['node_modules/@playwright/test/cli.js','test',...files,'--project='+project,'--reporter=json','--forbid-only','--retries=0'];const discovery=await gapNodeProcess([...args,'--list'],60000);if(discovery.status!==0||discovery.error)throw Error('Gap UI discovery failed');const cases=executionUiDiscovery(JSON.parse(discovery.stdout),files,project),run=await gapNodeProcess([...args,'--output='+resolve(directory,project)],600000);await writeFile(resolve(directory,project+'.json'),run.stdout,{mode:0o600});await writeFile(resolve(directory,project+'.log'),run.stderr,{mode:0o600});if(run.status!==0||run.error){let report:unknown;try{report=JSON.parse(run.stdout);}catch{}console.error(JSON.stringify({gate:'gap-ui-failure',project,runnerTimedOut:(run.error as {code?:string}|undefined)?.code==='ETIMEDOUT',cases:gapUiFailure(report)}));throw Error('Gap UI failed: '+project);}passed+=verifyExecutionUiReport(JSON.parse(run.stdout),cases).expected;console.log(JSON.stringify({project,passed:cases.length,skipped:0}));}},{deadlineMs:2580000});if(await featureSourceDigest('012')!==digest)throw Error('Gap UI source changed');const summary={sourceDigest:digest,journeys:6,projects:4,passed,failed:0,skipped:0};await writeFile(resolve(directory,'summary.json'),JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)checkGapUi().catch(error=>{console.error(error instanceof Error?error.message:'Gap UI failed');process.exitCode=1;});
