import {spawnSync} from 'node:child_process';
import {readFile,readdir,mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {withGapEnvironment} from './gaps-eval-environment';
import {featureSourceDigest} from './execution-source-digest';
import {executionUiDiscovery,verifyExecutionUiReport} from './execution-ui-report';
export const gapUiProjects=['webkit-desktop-light','webkit-desktop-dark','webkit-mobile-light','webkit-mobile-dark'] as const;
export function verifyGapUiFiles(actual:readonly string[],manifest:readonly string[]){if(manifest.length!==6||new Set(manifest).size!==6||JSON.stringify([...actual].sort())!==JSON.stringify([...manifest].sort()))throw Error('Gap UI requires all six journey files');}
export async function checkGapUi(){if(process.argv.length!==2)throw Error('Gap UI accepts no filters');const files=JSON.parse(await readFile('scripts/gaps-ui-journeys.json','utf8')) as string[];verifyGapUiFiles((await readdir('tests/ui')).filter(f=>/^gap-.*\.spec\.ts$/.test(f)).map(f=>'tests/ui/'+f),files);const digest=await featureSourceDigest('012');await mkdir('local-artifacts/012',{recursive:true,mode:0o700});const directory=await mkdtemp(resolve('local-artifacts/012/ui-'));let passed=0;await withGapEnvironment(async environment=>{await environment.start();await environment.startWorker();process.env.TURAS_UI_BASE_URL=environment.origin;process.env.TURAS_GAPS_UI_FIXTURE_READY='1';for(const project of gapUiProjects){const args=['node_modules/@playwright/test/cli.js','test',...files,'--project='+project,'--reporter=json','--forbid-only','--retries=0'];const discovery=spawnSync(process.execPath,[...args,'--list'],{env:process.env,encoding:'utf8',timeout:60000,maxBuffer:10000000});if(discovery.status!==0)throw Error('Gap UI discovery failed');const cases=executionUiDiscovery(JSON.parse(discovery.stdout),files,project),run=spawnSync(process.execPath,[...args,'--output='+resolve(directory,project)],{env:process.env,encoding:'utf8',timeout:240000,maxBuffer:10000000});await writeFile(resolve(directory,project+'.json'),run.stdout,{mode:0o600});await writeFile(resolve(directory,project+'.log'),run.stderr,{mode:0o600});if(run.status!==0)throw Error('Gap UI failed: '+project);passed+=verifyExecutionUiReport(JSON.parse(run.stdout),cases).expected;console.log(JSON.stringify({project,passed:cases.length,skipped:0}));}},{deadlineMs:1080000});if(await featureSourceDigest('012')!==digest)throw Error('Gap UI source changed');const summary={sourceDigest:digest,journeys:6,projects:4,passed,failed:0,skipped:0};await writeFile(resolve(directory,'summary.json'),JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)checkGapUi().catch(error=>{console.error(error instanceof Error?error.message:'Gap UI failed');process.exitCode=1;});
