import {spawnSync} from 'node:child_process';
import {readFile,readdir,mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {withGapEnvironment} from './gaps-eval-environment';
import {featureSourceDigest} from './execution-source-digest';
import {executionUiDiscovery,verifyExecutionUiReport} from './execution-ui-report';
export const gapUiProjects=['webkit-desktop-light','webkit-desktop-dark','webkit-mobile-light','webkit-mobile-dark'] as const;
export function verifyGapUiFiles(actual:readonly string[],manifest:readonly string[]){if(manifest.length!==6||new Set(manifest).size!==6||JSON.stringify([...actual].sort())!==JSON.stringify([...manifest].sort()))throw Error('Gap UI requires all six journey files');}
/** Fixed metadata only: private browser errors and fixture prose stay in owned evidence. */
export function gapUiFailure(raw:unknown){const failures:Array<{file:string;line:number;status:string;category:string}>=[];let visited=0;function walk(value:unknown,depth=0){if(++visited>10000||depth>20||!value||typeof value!=='object')return;const row=value as Record<string,unknown>;const file=typeof row.file==='string'?row.file.match(/(?:^|\/)gap-(authoring|canonicalization|reports|handoff|revocation|accessibility)\.spec\.ts$/)?.[0].split('/').at(-1):undefined;if(file&&Number.isSafeInteger(row.line)&&Array.isArray(row.tests))for(const test of row.tests){if(!test||typeof test!=='object'||!Array.isArray(test.results))continue;for(const result of test.results){if(!result||result.status==='passed')continue;const message=JSON.stringify(result.errors??result.error??'');failures.push({file,line:Number(row.line),status:['failed','timedOut','interrupted','skipped'].includes(result.status)?result.status:'unknown',category:/timed out|timeout/i.test(message)?'timeout':/strict mode/i.test(message)?'ambiguous_locator':/expect|AssertionError/.test(message)?'assertion':'case_failure'});}}for(const key of ['suites','specs'])if(Array.isArray(row[key]))for(const child of row[key])walk(child,depth+1);}walk(raw);return failures;}
export async function checkGapUi(){if(process.argv.length!==2)throw Error('Gap UI accepts no filters');const files=JSON.parse(await readFile('scripts/gaps-ui-journeys.json','utf8')) as string[];verifyGapUiFiles((await readdir('tests/ui')).filter(f=>/^gap-.*\.spec\.ts$/.test(f)).map(f=>'tests/ui/'+f),files);const digest=await featureSourceDigest('012');await mkdir('local-artifacts/012',{recursive:true,mode:0o700});const directory=await mkdtemp(resolve('local-artifacts/012/ui-'));let passed=0;await withGapEnvironment(async environment=>{await environment.start();await environment.startWorker();process.env.TURAS_UI_BASE_URL=environment.origin;process.env.TURAS_GAPS_UI_FIXTURE_READY='1';for(const project of gapUiProjects){const args=['node_modules/@playwright/test/cli.js','test',...files,'--project='+project,'--reporter=json','--forbid-only','--retries=0'];const discovery=spawnSync(process.execPath,[...args,'--list'],{env:process.env,encoding:'utf8',timeout:60000,maxBuffer:10000000});if(discovery.status!==0)throw Error('Gap UI discovery failed');const cases=executionUiDiscovery(JSON.parse(discovery.stdout),files,project),run=spawnSync(process.execPath,[...args,'--output='+resolve(directory,project)],{env:process.env,encoding:'utf8',timeout:600000,maxBuffer:10000000});await writeFile(resolve(directory,project+'.json'),run.stdout,{mode:0o600});await writeFile(resolve(directory,project+'.log'),run.stderr,{mode:0o600});if(run.status!==0){let report:unknown;try{report=JSON.parse(run.stdout);}catch{}console.error(JSON.stringify({gate:'gap-ui-failure',project,runnerTimedOut:(run.error as {code?:string}|undefined)?.code==='ETIMEDOUT',cases:gapUiFailure(report)}));throw Error('Gap UI failed: '+project);}passed+=verifyExecutionUiReport(JSON.parse(run.stdout),cases).expected;console.log(JSON.stringify({project,passed:cases.length,skipped:0}));}},{deadlineMs:2580000});if(await featureSourceDigest('012')!==digest)throw Error('Gap UI source changed');const summary={sourceDigest:digest,journeys:6,projects:4,passed,failed:0,skipped:0};await writeFile(resolve(directory,'summary.json'),JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)checkGapUi().catch(error=>{console.error(error instanceof Error?error.message:'Gap UI failed');process.exitCode=1;});
