import {randomUUID} from "node:crypto";
import {mkdir,mkdtemp,readFile,writeFile} from "node:fs/promises";
import {resolve,join} from "node:path";
import {withPartnerEnvironment} from "./partners-environment";
import {featureSourceDigest} from "./execution-source-digest";
import {withPartnerDatabase} from "../tests/fixtures/partners/environment";
import {partnerTestActors,partnerDeliveryBaseline} from "../tests/fixtures/partners/seed";
import {partnerAcceptedEvidence,syntheticPartnerGuide} from "../tests/fixtures/partners/originals";
import {partnerCommandEnvelope} from "../tests/fixtures/partners/guides";
import {writePartnerGuide,readPartnerGuide} from "../lib/server/partners/guides";
import {previewPartnerGuide,decidePartnerGuide} from "../lib/server/partners/previews";
import {readPartnerRequest} from "../lib/server/partners/receipts";
import {partnerHash} from "../lib/server/partners/repository";
import {DEMO_IDS} from "../lib/server/bootstrap-ids";
import {partnerSharedEvidence} from "../tests/fixtures/partners/originals";
import {submitExecutionCommand} from "../lib/server/execution/service";
import {executionCommand,saveRegister,submitRegister,reviewRegister,registerBase} from "../tests/fixtures/execution/registers";
import {createOwnedConversation} from "../lib/server/conversations/repository";
function check(value:unknown,message:string):asserts value{if(!value)throw Error(message);}
async function predecessorDigest(){return withPartnerDatabase(async db=>{const records=[];for(const query of ["SELECT id,workspace_id,customer_id,state,revision FROM customer_grants ORDER BY id","SELECT id,login_name,active FROM principals ORDER BY id","SELECT id,workspace_id,display_name FROM customer_references ORDER BY id","SELECT id,accepted_revision_id FROM delivery_plans ORDER BY id","SELECT id,active_baseline_id FROM engagements ORDER BY id","SELECT id,current_accepted_revision_id FROM profile_records ORDER BY id","SELECT id,engagement_id,accepted_revision_id FROM execution_records ORDER BY id","SELECT revision_id,state,head_generation FROM knowledge_publications ORDER BY revision_id","SELECT id,owner_principal_id,customer_id,binding_state,creation_operation_id FROM conversations ORDER BY id"]){records.push((await db.query(query)).rows);}return partnerHash(records);});}
async function main(){
 if(process.argv.length!==2)throw Error("Recovery accepts no connection overrides");const sourceDigest=await featureSourceDigest("013");await mkdir("local-artifacts/013",{recursive:true,mode:0o700});const directory=await mkdtemp(resolve("local-artifacts/013/recovery-")),results:unknown[]=[];
 for(const priorSchema of [undefined,49] as const)await withPartnerEnvironment(async environment=>{
  const actors=await withPartnerDatabase(partnerTestActors),baseline=await withPartnerDatabase(async db=>{await db.query("BEGIN");try{const b=await partnerDeliveryBaseline(db,actors.author,actors.reviewer);await db.query("COMMIT");return b;}catch(error){await db.query("ROLLBACK");throw error;}}),evidence=await partnerAcceptedEvidence(actors.author,actors.reviewer,DEMO_IDS.sharedCustomer,"Synthetic predecessor recovery observation"),marker=randomUUID(),markerPath=join(environment.workflowRoot,"013-recovery-marker");await writeFile(markerPath,marker,{mode:0o600});await partnerSharedEvidence(actors.author,actors.reviewer,DEMO_IDS.deniedCustomer);await createOwnedConversation(actors.author,{customerId:DEMO_IDS.sharedCustomer,requestKey:randomUUID(),title:"Synthetic predecessor private conversation"});await submitExecutionCommand(actors.author,baseline.engagementId,executionCommand("setup",{baseline:1,plan:baseline.decision.aggregateVersion},{baselineId:baseline.baselineId}));const executionFixture={...actors,engagementId:baseline.engagementId,baselineId:baseline.baselineId},work=await saveRegister(executionFixture,{...registerBase(),kind:"activity",subtype:"work",title:"Synthetic predecessor accepted work",narrative:"Synthetic independently recorded predecessor activity",references:[]});await reviewRegister(executionFixture,await submitRegister(executionFixture,work));const before=await predecessorDigest();
  if(priorSchema){await environment.startWorker();await environment.stop();await environment.upgradeToCurrent();}check(await predecessorDigest()===before,"Earlier-domain identities changed during upgrade");check(Number((await withPartnerDatabase(db=>db.query("SELECT schema_version FROM turas_environment WHERE environment_id=$1",[environment.environmentId]))).rows[0].schema_version)===51,"Schema51 required");
  const command={...partnerCommandEnvelope(),action:"guide.create",customerId:DEMO_IDS.sharedCustomer,engagementId:baseline.engagementId,acceptedRevisionId:baseline.created.revisionId,baselineId:baseline.baselineId,content:syntheticPartnerGuide(evidence.reference,"Synthetic recovery guide")},saved=await writePartnerGuide(actors.author,command);check((await writePartnerGuide(actors.author,command)).targetId===saved.targetId,"Committed command repeated");const view=await readPartnerGuide(actors.author,saved.targetId!);
  const absent=randomUUID();check((await readPartnerRequest(actors.author,absent,true)).outcome==="abandoned","Absent command was not retired");await writePartnerGuide(actors.author,{...command,requestId:absent}).then(()=>{throw Error("Late original admitted after resolve");},error=>check(error.status===410,"Wrong late admission fence"));
  const interrupted={...command,requestId:randomUUID()};const guideCount=Number((await withPartnerDatabase(db=>db.query("SELECT count(*)::int AS n FROM partner_guides"))).rows[0].n);await withPartnerDatabase(async db=>{await db.query("CREATE FUNCTION turas_test_013_write_interruption() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic interrupted write';END $$");await db.query("CREATE TRIGGER turas_test_013_write_interruption BEFORE INSERT ON partner_guide_payloads FOR EACH ROW EXECUTE FUNCTION turas_test_013_write_interruption()");});try{await writePartnerGuide(actors.author,interrupted).then(()=>{throw Error("Interrupted command committed");},()=>undefined);}finally{await withPartnerDatabase(async db=>{await db.query("DROP TRIGGER turas_test_013_write_interruption ON partner_guide_payloads");await db.query("DROP FUNCTION turas_test_013_write_interruption()");});}check(Number((await withPartnerDatabase(db=>db.query("SELECT count(*)::int AS n FROM partner_guides"))).rows[0].n)===guideCount,"Interrupted aggregate persisted");check((await readPartnerRequest(actors.author,interrupted.requestId)).outcome==="not_found","Interrupted receipt persisted");const lost={...command,requestId:randomUUID()};await writePartnerGuide(actors.author,lost);check((await readPartnerRequest(actors.author,lost.requestId)).outcome==="committed","Committed result could not reconcile");
  const submitted=await writePartnerGuide(actors.author,{...partnerCommandEnvelope(),action:"guide.submit",guideId:view.guideId,revisionId:view.revisionId,contentDigest:view.contentDigest,expectedVersion:view.version}),review={...partnerCommandEnvelope(),action:"guide.publish",guideId:view.guideId,revisionId:view.revisionId,contentDigest:view.contentDigest,expectedVersion:submitted.version!,rationale:"Synthetic exact recovery review",selfReview:false},preview=await previewPartnerGuide(actors.reviewer,review);await withPartnerDatabase(async db=>{await db.query("BEGIN");try{await db.query("SELECT set_config('turas.partner_cleanup','yes',true)");await db.query("UPDATE partner_review_previews SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[preview.previewId]);await db.query("COMMIT");}catch(error){await db.query("ROLLBACK");throw error;}});await decidePartnerGuide(actors.reviewer,{...review,requestId:randomUUID(),previewId:preview.previewId}).then(()=>{throw Error("Expired preview committed");},error=>check(error.status===410,"Expired preview not fenced"));const fresh=await previewPartnerGuide(actors.reviewer,{...review,requestId:randomUUID()});await decidePartnerGuide(actors.reviewer,{...review,requestId:randomUUID(),previewId:fresh.previewId});
  await environment.start();await environment.stop();check(await readFile(markerPath,"utf8")===marker,"Workflow data changed on restart");check((await readPartnerGuide(actors.partner,view.guideId)).content!==null,"Committed guide missing after restart");check(await predecessorDigest()===before,"Partner commands changed earlier-domain data");
  await withPartnerDatabase(db=>db.query("UPDATE profile_records SET current_accepted_revision_id=NULL WHERE id=$1",[evidence.recordId]));const deadline=(await withPartnerDatabase(db=>db.query("SELECT purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[view.revisionId]))).rows[0].purge_at;check((await readPartnerGuide(actors.partner,view.guideId)).content===null,"Stopped worker restored unavailable prose");
  // Age the synthetic event without altering any selected environment or data.
  await withPartnerDatabase(db=>db.query("UPDATE partner_guide_revision_states SET invalidated_at=clock_timestamp()-interval '2 days',purge_at=clock_timestamp()-interval '1 day' WHERE revision_id=$1",[view.revisionId]));process.env.TURAS_013_DISABLED="1";await environment.startWorker();await environment.crashWorker();await environment.startWorker();const until=Date.now()+65000;for(;;){environment.signal.throwIfAborted();const payload=(await withPartnerDatabase(db=>db.query("SELECT 1 FROM partner_guide_payloads WHERE revision_id=$1",[view.revisionId]))).rowCount;if(!payload)break;check(Date.now()<until,"Disabled cleanup did not recover");await new Promise(resolve=>setTimeout(resolve,250));}await environment.stop();check((await withPartnerDatabase(db=>db.query("SELECT purge_at FROM partner_guide_revision_states WHERE revision_id=$1",[view.revisionId]))).rows[0].purge_at<=deadline,"Restart extended deletion deadline");
  await environment.start();check(await readFile(markerPath,"utf8")===marker,"Same-environment workflow marker lost");check((await readPartnerRequest(actors.author,absent)).outcome==="abandoned","Lifetime request identity lost");await environment.stop();check(await predecessorDigest()!==before,"Synthetic source withdrawal was not recorded");results.push({path:priorSchema?"049-to-051":"empty-to-051",schema:51,predecessorPreserved:true,workflowPreserved:true,sameDatabaseRestart:true,committedReplay:true,lateAdmissionDenied:true,beforeCommitRollback:true,afterCommitReconciled:true,expiredPreviewDenied:true,workerCrashRecovered:true,disabledRetention:true,deadlinePreserved:true});
 },{priorSchema,deadlineMs:300000});
 check(await featureSourceDigest("013")===sourceDigest,"Recovery source changed");const summary={sourceDigest,results,hostedProof:false};await writeFile(join(directory,"completed.json"),JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));
}
main().catch(error=>{console.error(error instanceof Error?error.message:"Partner recovery failed");process.exitCode=1;});
