import { readdirSync } from 'node:fs';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { withGapEnvironment } from './gaps-eval-environment';
import { featureSourceDigest } from './execution-source-digest';
export function verifyGapSuiteCoverage(root=process.cwd(),expected?:readonly string[]){const manifest=expected??JSON.parse(requireRead(resolve(root,'scripts/gaps-suites.json'))) as string[];const actual=['unit','contracts','integration'].flatMap(group=>readdirSync(resolve(root,'tests',group)).filter(name=>/^gap-.*\.test\.ts$/.test(name)).map(name=>`tests/${group}/${name}`)).sort();if(!manifest.length||new Set(manifest).size!==manifest.length||actual.length!==manifest.length||actual.some(p=>!manifest.includes(p)))throw Error('Gap suite manifest is missing, duplicated or orphaned');return [...manifest];}
import { readFileSync as requireReadFile } from 'node:fs';
function requireRead(path:string){return requireReadFile(path,'utf8');}
export function verifyGapTestReport(report:{success?:boolean;numFailedTests?:number;numPendingTests?:number;testResults?:Array<{name:string;assertionResults?:Array<{status:string}>}>},expected:readonly string[]){if(!expected.length||new Set(expected).size!==expected.length||!report.success||report.numFailedTests||report.numPendingTests||report.testResults?.length!==expected.length)throw Error('Gap acceptance report failed or has skipped/missing suites');let passed=0;for(const path of expected){const file=report.testResults.find(f=>f.name.endsWith(path));if(!file?.assertionResults?.length||file.assertionResults.some(t=>t.status!=='passed'))throw Error('Gap acceptance has missing/skipped assertions');passed+=file.assertionResults.length;}return passed;}
export async function runGapSuites(suites:readonly string[],reportPath:string){await withGapEnvironment(async()=>{const run=spawnSync(process.execPath,['node_modules/vitest/vitest.mjs','run',...suites,'--reporter=default','--reporter=json',`--outputFile=${reportPath}`],{env:process.env,stdio:'inherit',timeout:240000});if(run.status!==0||run.error)throw Error('Gap suites failed');},{deadlineMs:300000});return verifyGapTestReport(JSON.parse(await readFile(reportPath,'utf8')),suites);}
export async function testGaps(){if(process.argv.length!==2)throw Error('Gap acceptance accepts no path/database overrides');const suites=verifyGapSuiteCoverage(),digest=await featureSourceDigest('012');await mkdir(resolve('local-artifacts/012'),{recursive:true,mode:0o700});const reportPath=resolve('local-artifacts/012',`tests-${randomUUID()}.json`);const passed=await runGapSuites(suites,reportPath);if(await featureSourceDigest('012')!==digest)throw Error('Gap source changed during acceptance');const summary={sourceDigest:digest,suites:suites.length,passed,failed:0,skipped:0};await writeFile(`${reportPath}.summary.json`,JSON.stringify(summary),{mode:0o600});console.log(JSON.stringify(summary));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)testGaps().catch(()=>{console.error('Gap acceptance failed; inspect synthetic local evidence');process.exitCode=1;});
