import {readFile,realpath,stat} from 'node:fs/promises';
import {resolve,sep,dirname,join} from 'node:path';
import {createHash} from 'node:crypto';
import {learningHash} from '../lib/server/learning/repository';
import {actualCostMicroUsd} from '../lib/server/learning/budget';
import {featureSourceDigest} from './execution-source-digest';
import {verifyLearningFeatureAcceptance} from './learning-review-contract';
async function privateInput(path:string){const root=await realpath(resolve('local-artifacts/014')),file=await realpath(resolve(path));if(!file.startsWith(root+sep)||(await stat(file)).size>2097152)throw Error('Bounded private 014 review artifact required');return JSON.parse(await readFile(file,'utf8'));}
async function main(){if(process.argv.length!==6||process.argv[2]!=='--capture'||process.argv[4]!=='--review')throw Error('Explicit --capture private capture.json --review private review.json required');const verified=verifyLearningFeatureAcceptance(await privateInput(process.argv[3]),await privateInput(process.argv[5]));if(verified.capture.sourceDigest!==await featureSourceDigest('014')||verified.capture.rootAgentDigest!==createHash('sha256').update(await readFile('agent/agent.ts')).digest('hex'))throw Error('Actual evaluation no longer represents the current source and model configuration');for(const [index,arm] of verified.capture.arms.entries()){const raw=await privateInput(join(dirname(process.argv[3]),String(index+1).padStart(2,'0')+'-raw.json'));if(learningHash(raw)!==arm.rawCaptureDigest||raw.attempt.id!==arm.attemptId||raw.attempt.native_session_id!==arm.nativeSessionId||raw.attempt.native_turn_id!==arm.nativeTurnId||raw.attempt.state!=='completed'||raw.accounting.length!==1||!raw.accounting[0].provider_claimed_at)throw Error('Raw actual capture or provider claim changed');const context=raw.payloads.find((row:{kind:string})=>row.kind==='context'),output=raw.payloads.find((row:{kind:string})=>row.kind==='output'),settled=raw.accounting[0];if(!context||!output||learningHash(context.content)!==arm.contextDigest||context.content.input.caseId!==arm.caseId||context.content.input.purpose!==arm.purpose||learningHash(output.content)!==arm.outputDigest||String(settled.amount_micro_usd)!==arm.settlement.amountMicroUsd||settled.provider_generation_id!==arm.settlement.providerGenerationId)throw Error('Raw context/output/accounting differs from reviewed capture');if(settled.kind==='actual'&&actualCostMicroUsd(settled.settlement_evidence?.reportedUsd).toString()!==arm.settlement.amountMicroUsd)throw Error('Provider cost evidence does not support the reviewed charge');}console.info(JSON.stringify({gate:'learning-actual-model-independent-review',sourceDigest:verified.capture.sourceDigest,captureDigest:verified.captureDigest,cases:8,arms:16,chargedMicroUsd:verified.chargedMicroUsd,featureVerdict:verified.featureVerdict,publicationVerdict:verified.publicationVerdict,publicationPermitted:verified.publicationPermitted,hostedProof:false}));}
main().catch(error=>{console.error(error instanceof Error&&!(error.name==='ZodError')?error.message:'Actual learning review verification failed');process.exitCode=1;});
