import {createHash} from 'node:crypto';
import {lstat,readFile,realpath} from 'node:fs/promises';
import {dirname,isAbsolute,relative,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {z} from 'zod';
import {verifyExpansionActualReview} from './expansion-review-contract';
import {featureSourceDigest} from './execution-source-digest';
import {expansionHash} from '../lib/server/expansion/commands';
import {expansionAdvicePrompt,validateExpansionAdviceResult} from '../lib/expansion/advice';
import {expansionEvaluationCases} from '../tests/fixtures/expansion/evaluation';
export const expansionArtifactDigest=(bytes:string|Buffer)=>createHash('sha256').update(bytes).digest('hex');
const digest=z.string().regex(/^[a-f0-9]{64}$/);
export const expansionCaptureSchema=z.object({version:z.literal('expansion-live-capture-v1'),caseId:z.enum(['E01','E02','E03','E04','E05','E06','E07','E08']),attemptId:z.string().uuid(),sourceDigest:digest,rootAgentDigest:digest,promptDigest:digest,cohortDigest:digest,model:z.string().min(1),actualConfiguredProvider:z.literal(true),input:z.object({request:z.object({selectedHypothesisIds:z.array(z.string().uuid()).max(20)}).passthrough(),snapshot:z.object({snapshot:z.object({currentDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).passthrough()}).passthrough()}).strict(),sourceMap:z.array(z.object({id:z.string().uuid(),kind:z.string()}).passthrough()).max(200),output:z.unknown().nullable(),terminalState:z.string(),released:z.boolean(),initialDispatches:z.literal(1),automaticPaidRetries:z.literal(0),paidSteps:z.number().int().min(1).max(6),inputTokens:z.number().int().nonnegative(),outputTokens:z.number().int().min(0).max(49152),outputTokensByStep:z.array(z.number().int().min(0).max(8192)).min(1).max(6),costUsd:z.number().finite().nonnegative(),latencyMs:z.number().finite().nonnegative().max(120000),providerMetadataComplete:z.literal(true),domainUnchanged:z.literal(true),staleSuggestionSaveDenied:z.boolean()}).strict();
export function verifyExpansionCapture(raw:unknown,review:ReturnType<typeof verifyExpansionActualReview>,index:number){const capture=expansionCaptureSchema.parse(raw),item=review.cases[index];if(capture.outputTokensByStep.length!==capture.paidSteps||capture.outputTokensByStep.reduce((sum,total)=>sum+total,0)!==capture.outputTokens)throw Error('Per-step output usage mismatch');if(!item||capture.caseId!==item.id||capture.attemptId!==item.attemptId)throw Error('Capture identity mismatch');for(const key of ['sourceDigest','rootAgentDigest','promptDigest','cohortDigest','model'] as const)if(capture[key]!==review[key])throw Error('Capture version mismatch');for(const key of ['terminalState','released','initialDispatches','automaticPaidRetries','paidSteps','inputTokens','outputTokens','costUsd','latencyMs','providerMetadataComplete','domainUnchanged','staleSuggestionSaveDenied'] as const)if(capture[key]!==item[key])throw Error('Capture measurement mismatch');if(expansionHash(capture.input)!==item.inputDigest||expansionHash(capture.sourceMap)!==item.sourceMapDigest||(capture.output===null?null:expansionHash(capture.output))!==item.outputDigest)throw Error('Capture content digest mismatch');if(capture.released)validateExpansionAdviceResult(capture.output,capture.sourceMap.map(source=>({id:source.id,kind:source.kind})),capture.input.request.selectedHypothesisIds,new Date(`${capture.input.snapshot.snapshot.currentDate}T00:00:00Z`));else if(capture.output!==null)throw Error('Withheld output was retained as released');return capture;}
async function readPrivateArtifact(path:string,root:string){const info=await lstat(path);if(!info.isFile()||info.isSymbolicLink()||info.size>4000000||(info.mode&0o077)!==0)throw Error('Bounded private regular capture required');const actual=await realpath(path),within=relative(root,actual);if(!within||within.startsWith('..')||isAbsolute(within))throw Error('Capture escaped private root');return readFile(actual);}
async function main(){if(process.argv.length!==4||process.argv[2]!=='--review')throw Error('Expansion review requires --review <private-review.json>');const root=await realpath(resolve('local-artifacts/011')),path=resolve(process.argv[3]),review=verifyExpansionActualReview(JSON.parse((await readPrivateArtifact(path,root)).toString('utf8'))),agent=await readFile('agent/agent.ts','utf8'),model=agent.match(/const selectedModel = "([^"]+)";/)?.[1];if(!model||review.model!==model||review.rootAgentDigest!==expansionArtifactDigest(agent)||review.sourceDigest!==await featureSourceDigest('011')||review.promptDigest!==expansionArtifactDigest(expansionAdvicePrompt)||review.cohortDigest!==expansionHash(expansionEvaluationCases))throw Error('Review is not bound to current source/model/prompt/cohort');for(const [index,item] of review.cases.entries()){if(isAbsolute(item.capturePath))throw Error('Capture path must be relative');const bytes=await readPrivateArtifact(resolve(dirname(path),item.capturePath),root);if(expansionArtifactDigest(bytes)!==item.captureDigest)throw Error('Capture file hash mismatch');verifyExpansionCapture(JSON.parse(bytes.toString('utf8')),review,index);}console.log(JSON.stringify({gate:'expansion-actual-output-review',cases:8,sourceDigest:review.sourceDigest,actualConfiguredProvider:true,hostedProof:false}));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)main().catch(()=>{console.error('Expansion actual-output review failed; inspect private artifacts');process.exitCode=1;});
