import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {gapCanonicalPreviewSchema,gapCommitSchema,type GapCanonicalInput,type GapContent} from '../../contracts/product-gaps';
import {canonicalAssignments} from '../../product-gaps/canonical';
import {parseGapContent} from '../../product-gaps/content';
import {HttpFailure} from '../../contracts/http';
import {getServerConfig} from '../config';
import {type GapActor,requireGapReviewer} from './policy';
import {gapCommand,gapHash} from './commands';
import {gapRow,gapExpected,revisionHeader,insertGapRevision,gapAudit,type RevisionHeader} from './repository';
import {lockGapSourceUnion,verifyGapSources} from './sources';
import {projectGapRevision} from './projection';
import {saveGapPreview,loadGapPreview} from './previews';
import {invalidateGapReports} from './invalidation';
async function canonicalBinding(db:PoolClient,actor:GapActor,input:GapCanonicalInput,resultIds:Record<string,string>){
 requireGapReviewer(actor);const merge=input.operation==='merge';
 if(merge&&(input.gapIds.length<2||input.results.length)||!merge&&(input.gapIds.length!==1||input.results.length<2||input.results.filter(r=>r.retainOriginal).length!==1)||!input.gapIds.includes(input.survivorId)||Object.keys(input.versions).sort().join()!==[...input.gapIds].sort().join())throw new HttpFailure(400,'invalid_input','Invalid canonical selection');
 gapExpected(input.versions[input.survivorId],input.expectedVersion);
 const gaps=await Promise.all([...input.gapIds].sort().map(id=>gapRow(db,actor,id)));for(const gap of gaps){gapExpected(gap.version,input.versions[gap.id]);if(gap.canonical_state!=='active'||!gap.reviewed_revision_id)throw new HttpFailure(409,'stale_version','Reviewed active canonical gaps required');}
 const headers=await Promise.all(gaps.map(g=>revisionHeader(db,actor,g.reviewed_revision_id!)));
 const observations=(await db.query('SELECT o.*,a.canonical_gap_id,a.event_id FROM gap_impact_observations o JOIN gap_observation_assignments a ON a.observation_id=o.id WHERE a.canonical_gap_id=ANY($1::uuid[]) AND o.environment_id=$2 AND o.workspace_id=$3 ORDER BY o.id LIMIT 1001',[input.gapIds,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows;
 if(observations.length>1000)throw new HttpFailure(413,'scope_too_large','Canonical observation scope exceeds limit');
 const keys=merge?[input.survivorId]:input.results.map(r=>r.key);canonicalAssignments(observations.map(o=>o.id),keys,input.assignments);
 if(!merge&&(new Set(keys).size!==keys.length||input.results.some(r=>resultIds[r.key]===undefined)||input.results.some(r=>r.retainOriginal&&resultIds[r.key]!==input.survivorId)))throw new HttpFailure(400,'invalid_input','Invalid split result identities');
 const impactRevisionIds=[...new Set(observations.flatMap(o=>[o.working_revision_id,o.reviewed_revision_id]).filter(Boolean))].sort();
 const impactHeaders=(await db.query<RevisionHeader>('SELECT r.*,p.content,s.invalidated_at,s.purge_at,s.generation FROM gap_revisions r JOIN gap_revision_states s ON s.revision_id=r.id LEFT JOIN gap_revision_payloads p ON p.revision_id=r.id WHERE r.id=ANY($1::uuid[]) AND r.environment_id=$2 AND r.workspace_id=$3 ORDER BY r.id',[impactRevisionIds,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows;
 if(impactHeaders.length!==impactRevisionIds.length)throw new HttpFailure(409,'stale_version','Impact revision scope changed');
 const refs=[...impactHeaders.flatMap(h=>h.content?.sourceRefs??[]),...headers.flatMap(h=>h.content?.sourceRefs??[]),...input.results.flatMap(r=>r.sourceRefs)];await lockGapSourceUnion(db,actor,refs,20000,observations.map(o=>o.customer_id));
 const projections=await Promise.all(headers.map(h=>projectGapRevision(db,actor,h.id,false,h)));if(projections.some(p=>p?.availability!=='eligible'))throw new HttpFailure(409,'source_unavailable','Reviewed canonical evidence unavailable');
 const impactProjections=await Promise.all(impactHeaders.map(h=>projectGapRevision(db,actor,h.id,false,h)));
 const contents=projections.map(p=>p!.content as GapContent);if(merge&&contents.some(c=>c.kind!==contents[0].kind||c.productKey!==contents[0].productKey))throw new HttpFailure(400,'invalid_input','Merge requires identical kind and product');
 const results=[];for(const result of input.results){const content=parseGapContent(result.content),sources=await verifyGapSources(db,actor,result.sourceRefs,{alreadyLocked:true});results.push({key:result.key,id:resultIds[result.key],content,sourceDigest:sources.digest,dependencies:sources.dependencies});}
 for(const gap of gaps){const locked=await gapRow(db,actor,gap.id,true);gapExpected(locked.version,Number(gap.version));}
 if(observations.length)await db.query('SELECT id FROM gap_impact_observations WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE',[observations.map(o=>o.id)]);
 const generation=Number((await db.query('SELECT relation_generation FROM gap_workspace_state WHERE environment_id=$1 AND workspace_id=$2',[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0].relation_generation);
 const binding={input,gaps:gaps.map(g=>({id:g.id,version:Number(g.version),reviewed:g.reviewed_revision_id})),sources:projections.map(p=>p!.sourceDigest),impactSources:impactProjections.map(p=>({id:p!.id,generation:p!.generation,availability:p!.availability,sourceDigest:p!.sourceDigest})),observations:observations.map(o=>({id:o.id,version:Number(o.version),assignment:o.event_id,working:o.working_revision_id,reviewed:o.reviewed_revision_id,state:o.state})),resultIds,results:results.map(r=>({id:r.id,contentDigest:gapHash(r.content),sourceDigest:r.sourceDigest})),relationGeneration:generation,actor:actor.membershipId,session:actor.sessionId};return {binding,results,observations,generation};
}
export function previewGapCanonicalization(actor:GapActor,raw:unknown){const input=gapCanonicalPreviewSchema.parse(raw);return gapCommand(actor,'preview_canonicalization',input,async db=>{requireGapReviewer(actor);const resultIds=Object.fromEntries(input.results.map(r=>[r.key,r.retainOriginal?input.survivorId:randomUUID()]));const {binding}=await canonicalBinding(db,actor,input,resultIds);const preview=await saveGapPreview(db,actor,'canonicalize',null,binding,{input,resultIds});return {recordId:input.survivorId,resultId:preview.id,bindingDigest:preview.digest,outcome:'preview',version:input.expectedVersion};},{exclusive:true});}
export function commitGapCanonicalization(actor:GapActor,raw:unknown){const command=gapCommitSchema.parse(raw);return gapCommand(actor,'canonicalize',command,async db=>{requireGapReviewer(actor);const preview=await loadGapPreview(db,actor,command.previewId,'canonicalize',null,command.bindingDigest),payload=preview.payload as {input:unknown;resultIds:Record<string,string>},input=gapCanonicalPreviewSchema.parse(payload.input);gapExpected(input.expectedVersion,command.expectedVersion);const current=await canonicalBinding(db,actor,input,payload.resultIds);if(gapHash(current.binding)!==command.bindingDigest)throw new HttpFailure(409,'stale_version','Canonical inputs changed');const env=getServerConfig().TURAS_ENVIRONMENT_ID,id=randomUUID(),generation=current.generation+1;
 await db.query('INSERT INTO gap_canonicalization_decisions(id,environment_id,workspace_id,operation,binding_digest,reviewer_membership_id,relation_generation) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,env,actor.workspaceId,input.operation,command.bindingDigest,actor.membershipId,generation]);await gapAudit(db,actor,id,{rationale:input.rationale,assignments:input.assignments,results:payload.resultIds});
 if(input.operation==='merge'){const aliases=input.gapIds.filter(g=>g!==input.survivorId);await db.query("UPDATE product_gaps SET canonical_state='redirected',canonical_target=$1,version=version+1 WHERE environment_id=$2 AND workspace_id=$3 AND (id=ANY($4::uuid[]) OR canonical_target=ANY($4::uuid[]))",[input.survivorId,env,actor.workspaceId,aliases]);await db.query('UPDATE product_gaps SET version=version+1,last_review_at=clock_timestamp() WHERE id=$1',[input.survivorId]);}
 else for(const result of current.results){const original=result.id===input.survivorId;if(!original)await db.query('INSERT INTO product_gaps(id,environment_id,workspace_id,creator_membership_id) VALUES($1,$2,$3,$4)',[result.id,env,actor.workspaceId,actor.membershipId]);const version=original?input.expectedVersion+1:1,ref=input.results.find(r=>r.key===result.key)!;const revision=await insertGapRevision(db,actor,result.id,null,result.content,ref.sourceRefs,result.dependencies,version);await db.query('UPDATE product_gaps SET working_revision_id=$2,reviewed_revision_id=$2,version=$3,last_review_at=clock_timestamp() WHERE id=$1',[result.id,revision,version]);const decision=randomUUID();await db.query("INSERT INTO gap_decisions(id,environment_id,workspace_id,gap_id,revision_id,action,reviewer_membership_id,rationale_digest,binding_digest,disposition,self_review,customer_independent_acknowledgment) SELECT $1,$2,$3,$4,$5,'accept',$6,$7,$8,disposition,true,true FROM product_gaps WHERE id=$4",[decision,env,actor.workspaceId,result.id,revision,actor.membershipId,gapHash(input.rationale),command.bindingDigest]);await gapAudit(db,actor,decision,{rationale:input.rationale,canonicalizationId:id});}
 for(const assignment of canonicalAssignments(current.observations.map(o=>o.id),input.operation==='merge'?[input.survivorId]:input.results.map(r=>r.key),input.assignments)){const target=input.operation==='merge'?input.survivorId:payload.resultIds[assignment.resultKey],event=randomUUID();await db.query('INSERT INTO gap_assignment_events(id,environment_id,workspace_id,observation_id,canonical_gap_id,decision_id) VALUES($1,$2,$3,$4,$5,$6)',[event,env,actor.workspaceId,assignment.observationId,target,id]);await db.query('UPDATE gap_observation_assignments SET canonical_gap_id=$2,event_id=$3 WHERE observation_id=$1',[assignment.observationId,target,event]);}
 await db.query('UPDATE gap_workspace_state SET relation_generation=$3 WHERE environment_id=$1 AND workspace_id=$2',[env,actor.workspaceId,generation]);await invalidateGapReports(db,input.gapIds);return {recordId:input.survivorId,resultId:id,outcome:input.operation,version:input.expectedVersion+1};},{exclusive:true});}
