import { createHash,createHmac,randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { z } from 'zod';
import { HttpFailure,hiddenRecord } from '../../contracts/http';
import { getServerConfig } from '../config';
import { withTransaction } from '../db/client';
import { lockGapActor,requireGapReviewer,type GapActor } from './policy';
import { requireGapSchema } from './schema';
export function gapCanonical(value:unknown):string{if(value instanceof Date)return JSON.stringify(value.toISOString());if(Array.isArray(value))return `[${value.map(gapCanonical).join(',')}]`;if(value!==null&&typeof value==='object')return `{${Object.entries(value).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${gapCanonical(v)}`).join(',')}}`;const result=JSON.stringify(value);if(result===undefined)throw Error('Invalid digest input');return result;}
export const gapHash=(value:unknown)=>createHash('sha256').update(gapCanonical(value)).digest('hex');
export function gapOpaqueHashes(identity:readonly string[]){const keys:unknown=process.env.TURAS_012_RECEIPT_HASH_KEYS?JSON.parse(process.env.TURAS_012_RECEIPT_HASH_KEYS):[getServerConfig().TURAS_MAINTENANCE_SECRET];if(!Array.isArray(keys)||!keys.length||keys.length>32||keys.some(k=>typeof k!=='string'||Buffer.byteLength(k)<32))throw new HttpFailure(503,'key_unavailable','Request receipt keys unavailable');return keys.map(key=>createHmac('sha256',key).update(gapCanonical(identity)).digest('hex'));}
export type GapReceipt={id:string;operation:string;recordId:string|null;outcome:string;version:number;resultId?:string|null;bindingDigest?:string|null};
const identity=(actor:GapActor,operation:string,key:string)=>[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId,operation,key];
export async function lockGapRequest(db:PoolClient,actor:GapActor,operation:string,key:string){z.uuid().parse(key);const parts=identity(actor,operation,key);await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`gap-request:${parts.join(':')}`]);if((await db.query('SELECT 1 FROM gap_expired_request_keys WHERE key_hash=ANY($1::text[])',[gapOpaqueHashes(parts)])).rowCount)throw new HttpFailure(409,'receipt_expired','Request identity expired; use a new key');}
export async function gapReceipt(db:PoolClient,actor:GapActor,operation:string,key:string,digest?:string):Promise<GapReceipt|null>{const row=(await db.query('SELECT * FROM gap_request_receipts WHERE environment_id=$1 AND workspace_id=$2 AND actor_membership_id=$3 AND operation=$4 AND request_key=$5',identity(actor,operation,key))).rows[0];if(!row)return null;if(digest&&row.input_digest!==digest)throw new HttpFailure(409,'request_conflict','Request key has different input');return {id:row.id,operation:row.operation,recordId:row.record_id,outcome:row.outcome,version:Number(row.version),resultId:row.result_id,bindingDigest:row.binding_digest};}
export async function gapRate(db:PoolClient,actor:GapActor,kind:'read'|'write'|'preparation'){const env=getServerConfig().TURAS_ENVIRONMENT_ID,hash=gapOpaqueHashes(['rate',env,actor.workspaceId,actor.membershipId,kind])[0];await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`gap-rate:${hash}`]);const now=Date.now(),limit={read:120,write:30,preparation:5}[kind];const count=Number((await db.query('SELECT COALESCE(sum(count),0) AS count FROM rate_windows WHERE environment_id=$1 AND key_hash=$2 AND category=$3 AND window_start>$4',[env,hash,`gap_${kind}`,new Date(now-60000)])).rows[0].count);if(count>=limit)throw new HttpFailure(429,'rate_limited','Product gap request limit reached',60);await db.query('INSERT INTO rate_windows(environment_id,key_hash,category,window_start,count,expires_at) VALUES($1,$2,$3,$4,1,$5) ON CONFLICT(environment_id,key_hash,category,window_start) DO UPDATE SET count=rate_windows.count+1',[env,hash,`gap_${kind}`,new Date(now),new Date(now+60000)]);}
export async function authorizeGapReceipt(db:PoolClient,actor:GapActor,receipt:GapReceipt){if(['preview_decision','gap_decision','preview_canonicalization','canonicalize','preview_report','review_report','export_report','handoff'].includes(receipt.operation))requireGapReviewer(actor);if(!receipt.recordId)return;const reportOperation=['prepare_report','preview_report','review_report','export_report','handoff','cancel_report'].includes(receipt.operation);const table=reportOperation?'gap_reports':'product_gaps';const found=await db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND environment_id=$2 AND workspace_id=$3`,[receipt.recordId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId]);if(!found.rowCount)throw hiddenRecord();}
export async function gapCommand<T extends {requestKey:string}>(actor:GapActor,operation:string,input:T,run:(db:PoolClient)=>Promise<Omit<GapReceipt,'id'|'operation'>>,options:{exclusive?:boolean;reports?:boolean;cancel?:boolean}={}){
 const digest=gapHash(input);await withTransaction(async db=>{await lockGapActor(db,actor,false,options.reports);if(['preview_decision','gap_decision','preview_canonicalization','canonicalize','preview_report','review_report','export_report','handoff'].includes(operation))requireGapReviewer(actor);await lockGapRequest(db,actor,operation,input.requestKey);const prior=await gapReceipt(db,actor,operation,input.requestKey,digest);if(!prior&&!options.cancel)await requireGapSchema(db,true,options.reports);if(!options.cancel){await gapRate(db,actor,prior?'read':'write');if(!prior&&operation==='prepare_report')await gapRate(db,actor,'preparation');}});
 return withTransaction(async db=>{await lockGapActor(db,actor,options.exclusive,options.reports);if(['preview_decision','gap_decision','preview_canonicalization','canonicalize','preview_report','review_report','export_report','handoff'].includes(operation))requireGapReviewer(actor);await lockGapRequest(db,actor,operation,input.requestKey);const prior=await gapReceipt(db,actor,operation,input.requestKey,digest);if(prior){await authorizeGapReceipt(db,actor,prior);return prior;}if(!options.cancel)await requireGapSchema(db,true,options.reports);const result=await run(db),id=randomUUID();await db.query('INSERT INTO gap_request_receipts(id,environment_id,workspace_id,actor_membership_id,operation,request_key,input_digest,record_id,outcome,version,result_id,binding_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[id,...identity(actor,operation,input.requestKey),digest,result.recordId,result.outcome,result.version,result.resultId??null,result.bindingDigest??null]);return {id,operation,...result,resultId:result.resultId??null,bindingDigest:result.bindingDigest??null};});
}
export async function gapRead<T>(actor:GapActor,run:(db:PoolClient)=>Promise<T>,reports=false){await withTransaction(async db=>{await lockGapActor(db,actor,false,reports);await gapRate(db,actor,'read');});return withTransaction(async db=>{await lockGapActor(db,actor,false,reports);return run(db);});}
export function readGapReceipt(actor:GapActor,key:string,operation:string){return gapRead(actor,async db=>{await lockGapRequest(db,actor,operation,key);const receipt=await gapReceipt(db,actor,operation,key);if(!receipt)throw hiddenRecord();await authorizeGapReceipt(db,actor,receipt);return receipt;});}
