import type {PoolClient} from 'pg';
import {z} from 'zod';
import type {GapActor} from './policy';
import {lockGapCustomers} from './policy';
import {gapRead,gapHash} from './commands';
import {HttpFailure,hiddenRecord} from '../../contracts/http';
import {getServerConfig} from '../config';
import {impactSets,evidenceFreshness} from '../../product-gaps/impact';
import {gapProseEnabled} from './schema';
import {unsupportedProfileRevisionIds,knowledgeLineageIsCurrent} from '../profiles/eligibility';
import {retrievalQuality} from '../retrieval/context';
import {evidenceQualitySchema} from '../../contracts/retrieval';
import type {GapSource} from '../../contracts/product-gaps';
import {gapDependencyUnion} from './dependencies';
import {verifyExecutionSources} from '../execution/sources';
export type GapComparison={availability:'available';at:string;confirmed:number;suspectedOnly:number;resolvedHistory:number}|{availability:'unavailable';reason:string};
type Metadata={id:string;created_at:Date;invalidated_at:Date|null;purge_at:Date|null;generation:string;present:boolean;fields:{kind?:string;productKey?:string;title?:string;capability?:string;severity?:string;workaroundFeasibility?:string;classification?:'suspected'|'confirmed'|'resolved';observedAt?:string|null;resolvedAt?:string|null};refs:GapSource[]};
type Dependency={revision_id:string;source_kind:string;source_revision_id:string;source_generation:string;source_digest:string;customer_id:string|null;reference:Partial<GapSource>};
/** Fetches only count/search fields and exact evidence identities, never narrative or assertion prose. */
export async function gapCountMetadata(db:PoolClient,actor:GapActor,gapIds?:readonly string[],at=new Date(),additionalRefs:readonly GapSource[]=[],comparisonAt?:Date){
 const env=getServerConfig().TURAS_ENVIRONMENT_ID;
 const gaps=(await db.query('SELECT * FROM product_gaps WHERE environment_id=$1 AND workspace_id=$2 AND canonical_state=\'active\' AND ($3::uuid[] IS NULL OR id=ANY($3::uuid[])) ORDER BY id LIMIT 2001',[env,actor.workspaceId,gapIds??null])).rows;
 if(gaps.length>2000)throw new HttpFailure(413,'scope_too_large','Gap projection exceeds limit');if(gapIds&&gaps.length!==gapIds.length)throw hiddenRecord();
 const observations=(await db.query(`SELECT o.id,o.customer_id,o.state,o.version,a.canonical_gap_id,d.reviewed_kind,d.reviewed_product_key,d.created_at AS accepted_at,d.revision_id AS cutoff_revision_id,d.action AS cutoff_action,c.revision_id AS comparison_revision_id,c.action AS comparison_action,c.reviewed_kind AS comparison_kind,c.reviewed_product_key AS comparison_product_key,c.created_at AS comparison_accepted_at FROM gap_impact_observations o JOIN gap_observation_assignments a ON a.observation_id=o.id LEFT JOIN LATERAL(SELECT reviewed_kind,reviewed_product_key,created_at,revision_id,action FROM gap_decisions WHERE impact_id=o.id AND action IN('accept','retire') AND created_at<=$4 ORDER BY created_at DESC,id DESC LIMIT 1)d ON true LEFT JOIN LATERAL(SELECT revision_id,action,reviewed_kind,reviewed_product_key,created_at FROM gap_decisions WHERE impact_id=o.id AND action IN('accept','retire') AND created_at<=$5 ORDER BY created_at DESC,id DESC LIMIT 1)c ON true WHERE o.environment_id=$1 AND o.workspace_id=$2 AND a.canonical_gap_id=ANY($3::uuid[]) ORDER BY o.id LIMIT 10001`,[env,actor.workspaceId,gaps.map(g=>g.id),at,comparisonAt??null])).rows;
 if(observations.length>10000)throw new HttpFailure(413,'scope_too_large','Observation projection exceeds limit');
 const ids=[...new Set([...gaps.flatMap(g=>[g.reviewed_revision_id??g.working_revision_id]),...observations.flatMap(o=>[o.cutoff_revision_id,o.comparison_revision_id])].filter(Boolean))] as string[];
 const referenceArrays=new Map<string,GapSource[]>();
 const metadataRows=(await db.query<Omit<Metadata,'refs'>&{refs:string}>(`SELECT r.id,r.created_at,s.invalidated_at,s.purge_at,s.generation,p.revision_id IS NOT NULL AS present,jsonb_strip_nulls(jsonb_build_object('kind',p.content#>'{content,kind}','productKey',p.content#>'{content,productKey}','title',p.content#>'{content,title}','capability',p.content#>'{content,capability}','severity',p.content#>'{content,severity}','workaroundFeasibility',p.content#>'{content,workaroundFeasibility}','classification',p.content#>'{content,classification}','observedAt',p.content#>'{content,observedAt}','resolvedAt',p.content#>'{content,resolvedAt}')) AS fields,COALESCE(p.content->'sourceRefs','[]'::jsonb)::text AS refs FROM gap_revisions r JOIN gap_revision_states s ON s.revision_id=r.id LEFT JOIN gap_revision_payloads p ON p.revision_id=r.id WHERE r.id=ANY($1::uuid[]) AND r.environment_id=$2 AND r.workspace_id=$3 ORDER BY r.id`,[ids,env,actor.workspaceId])).rows;
 const metadata:Metadata[]=metadataRows.map(row=>{let refs=referenceArrays.get(row.refs);if(!refs){refs=JSON.parse(row.refs) as GapSource[];referenceArrays.set(row.refs,refs);}return {...row,refs};});
 const deps=(await db.query<Dependency>(`SELECT d.revision_id,d.source_kind,d.source_revision_id,d.source_generation,d.source_digest,d.customer_id,CASE WHEN d.source_kind IN('execution_record','milestone_baseline') THEN d.reference ELSE '{}'::jsonb END AS reference FROM gap_source_dependencies d JOIN gap_revisions r ON r.id=d.revision_id WHERE d.revision_id=ANY($1::uuid[]) AND r.environment_id=$2 AND r.workspace_id=$3 ORDER BY d.source_kind,d.source_revision_id,d.revision_id `,[ids,env,actor.workspaceId])).rows;
 const additional=await gapDependencyUnion(db,actor,additionalRefs,20000);for(const d of additional)deps.push({revision_id:'additional',source_kind:d.kind,source_revision_id:d.revisionId,source_generation:String(d.generation),source_digest:d.contentDigest,customer_id:d.customerId??additionalRefs.find(r=>r.kind===d.kind&&r.sourceRevisionId===d.revisionId)?.customerId??null,reference:additionalRefs.find(r=>r.kind===d.kind&&r.sourceRevisionId===d.revisionId)??{kind:d.kind,sourceRevisionId:d.revisionId,generation:d.generation,contentDigest:d.contentDigest}});
 const unique=new Map<string,Dependency>();for(const d of deps){const key=`${d.source_kind}:${d.source_revision_id}`,old=unique.get(key);if(old&&(old.source_digest!==d.source_digest||old.source_generation!==d.source_generation))throw new HttpFailure(409,'source_unavailable','Conflicting original evidence');unique.set(key,d);}if(unique.size>20000)throw new HttpFailure(413,'scope_too_large','Dependency projection exceeds limit');
 await lockGapCustomers(db,actor,[...observations.map(o=>o.customer_id),...deps.flatMap(d=>d.customer_id?[d.customer_id]:[])]);
 const sourceIds=[...unique.values()].map(d=>d.source_revision_id);
 // All original kinds precede execution suffixes, matching the single-release adapter.
 for(const [kind,sql] of Object.entries({accepted_profile:'SELECT r.id FROM profile_records r JOIN profile_revisions v ON v.record_id=r.id WHERE v.id=ANY($1::uuid[]) ORDER BY v.id FOR SHARE OF r',approved_excerpt:'SELECT v.id FROM artifact_versions v JOIN artifact_evidence_selections s ON s.version_id=v.id WHERE s.id=ANY($1::uuid[]) ORDER BY s.id FOR SHARE OF v',shared_knowledge:'SELECT revision_id FROM knowledge_publications WHERE revision_id=ANY($1::uuid[]) ORDER BY revision_id FOR SHARE',verified_research:'SELECT s.id FROM evidence_sources s JOIN evidence_source_revisions v ON v.source_id=s.id WHERE v.id=ANY($1::uuid[]) ORDER BY v.id FOR SHARE OF s'})){const selected=[...unique.values()].filter(d=>d.source_kind===kind).map(d=>d.source_revision_id);if(selected.length)await db.query(sql,[selected]);}
 const originals=(await db.query(`SELECT 'accepted_profile' AS kind,v.id,v.revision_number AS generation,v.content_digest AS digest,v.created_at,v.quality_input,v.payload->>'observedAt' AS observation_at,v.payload->>'reviewAt' AS review_at,NULL::timestamptz AS publication_at,v.payload->>'productKey' AS product_key,v.payload->>'state' AS profile_state,r.current_accepted_revision_id=v.id AS eligible FROM profile_revisions v JOIN profile_records r ON r.id=v.record_id WHERE v.id=ANY($1::uuid[]) UNION ALL SELECT 'verified_research',v.id,v.version,v.passage_digest,v.created_at,v.quality_input,v.observation_at::text,NULL,v.publication_at,NULL,NULL,s.origin='independent_research' AND EXISTS(SELECT 1 FROM research_checks c WHERE c.source_revision_id=v.id AND c.identity_result AND c.scope_result AND c.integrity_result AND c.content_result) AND NOT EXISTS(SELECT 1 FROM evidence_source_events e WHERE e.source_revision_id=v.id AND e.event_type IN('withdraw','supersede')) FROM evidence_source_revisions v JOIN evidence_sources s ON s.id=v.source_id WHERE v.id=ANY($1::uuid[]) UNION ALL SELECT 'approved_excerpt',s.id,s.lifecycle_generation,s.excerpt_digest,s.created_at,pr.quality_input,pr.payload->>'observedAt',pr.payload->>'reviewAt',NULL,pr.payload->>'productKey',pr.payload->>'state',v.state IN('ready','partial') AND v.lifecycle_generation=s.lifecycle_generation AND v.sha256_digest=s.original_digest AND er.state='published' AND ep.selection_id IS NOT NULL AND r.current_accepted_revision_id=pr.id FROM artifact_evidence_selections s JOIN artifact_versions v ON v.id=s.version_id JOIN artifact_extraction_runs er ON er.id=s.run_id LEFT JOIN artifact_evidence_payloads ep ON ep.selection_id=s.id JOIN profile_revisions pr ON pr.id=s.profile_revision_id JOIN profile_records r ON r.id=pr.record_id WHERE s.id=ANY($1::uuid[]) UNION ALL SELECT 'shared_knowledge',r.id,p.head_generation,r.content_digest,r.created_at,p.public_quality,NULL,NULL,NULL,NULL,NULL,p.state='published' AND payload.revision_id IS NOT NULL FROM knowledge_revisions r JOIN knowledge_publications p ON p.revision_id=r.id LEFT JOIN knowledge_revision_payloads payload ON payload.revision_id=r.id WHERE r.id=ANY($1::uuid[])`,[sourceIds])).rows;
 const originalMap=new Map(originals.map(o=>[`${o.kind}:${o.id}`,o]));
 const unsupported=await unsupportedProfileRevisionIds(db,originals.filter(o=>o.kind==='accepted_profile').map(o=>o.id),true);
 const conflicts=(await db.query(`SELECT first_kind AS kind,first_revision_id AS id FROM evidence_conflict_targets WHERE environment_id=$1 AND state='confirmed' AND first_revision_id=ANY($2::uuid[]) UNION SELECT second_kind,second_revision_id FROM evidence_conflict_targets WHERE environment_id=$1 AND state='confirmed' AND second_revision_id=ANY($2::uuid[]) UNION SELECT 'accepted_profile',first_revision_id FROM evidence_conflicts WHERE state='confirmed' AND first_revision_id=ANY($2::uuid[]) UNION SELECT 'accepted_profile',second_revision_id FROM evidence_conflicts WHERE state='confirmed' AND second_revision_id=ANY($2::uuid[])`,[env,sourceIds])).rows;
 const conflicted=new Set(conflicts.map(c=>`${c.kind==='published_shared'?'shared_knowledge':c.kind}:${c.id}`));
 for(const original of originals)if(original.kind==='shared_knowledge'&&original.eligible)original.eligible=await knowledgeLineageIsCurrent(db,original.id);
 const allRefs=[...metadata.flatMap(m=>m.refs),...additionalRefs,...deps.filter(d=>d.source_kind==='execution_record'||d.source_kind==='milestone_baseline').map(d=>({...d.reference,id:d.reference.id??d.source_revision_id,kind:d.source_kind,customerId:d.customer_id,sourceRevisionId:d.source_revision_id,generation:Number(d.source_generation),contentDigest:d.source_digest,purpose:'corroboration'} as GapSource))];
 const locatorKeys=new WeakMap<GapSource,string>();function locatorKey(ref:GapSource){let key=locatorKeys.get(ref);if(!key){key=JSON.stringify(ref);locatorKeys.set(ref,key);}return key;}
 const direct=[...new Map(allRefs.filter(r=>r.locator).map(ref=>[locatorKey(ref),{...ref,binding:locatorKey(ref)}])).values()];
 const located=(await db.query(`SELECT x.binding FROM jsonb_to_recordset($1::jsonb) AS x(binding text,id uuid,kind text,"customerId" uuid,"sourceRevisionId" uuid,generation bigint,"contentDigest" text,locator jsonb) WHERE EXISTS(SELECT 1 FROM retrieval_sources s JOIN retrieval_passages p ON p.source_id=s.id WHERE s.environment_id=$2 AND s.source_kind=CASE WHEN x.kind='shared_knowledge' THEN 'published_shared' ELSE x.kind END AND s.source_revision_id=x."sourceRevisionId" AND s.source_generation=x.generation AND s.content_digest=x."contentDigest" AND s.lifecycle_state='current' AND p.locators @> jsonb_build_array(x.locator) AND ((s.scope='shared' AND x.kind='shared_knowledge' AND s.workspace_id IS NULL AND s.customer_id IS NULL) OR (s.scope='customer' AND s.workspace_id=$3 AND s.customer_id=x."customerId")))`,[JSON.stringify(direct),env,actor.workspaceId])).rows;
 const locatedKeys=new Set(located.map(r=>r.binding));
 const executionEligible=new Map<string,boolean>();for(const ref of [...new Map(allRefs.filter(r=>!r.locator).map(r=>[`${r.kind}:${r.sourceRevisionId}`,r])).values()].sort((a,b)=>(a.engagementId??'').localeCompare(b.engagementId??'')||a.sourceRevisionId.localeCompare(b.sourceRevisionId))){try{await verifyExecutionSources(db,actor,ref.customerId!,ref.engagementId!,'internal',[{id:ref.id,kind:ref.kind as 'execution_record'|'milestone_baseline',sourceRevisionId:ref.sourceRevisionId,generation:ref.generation,contentDigest:ref.contentDigest}],true,true);executionEligible.set(`${ref.kind}:${ref.sourceRevisionId}`,true);}catch(error){if(!(error instanceof HttpFailure)||![404,409,422].includes(error.status))throw error;executionEligible.set(`${ref.kind}:${ref.sourceRevisionId}`,false);}}
 const lockedGaps=(await db.query('SELECT * FROM product_gaps WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE',[gaps.map(g=>g.id)])).rows;const currentGaps=new Map(lockedGaps.map(g=>[g.id,g]));for(const gap of gaps){const current=currentGaps.get(gap.id);if(!current||current.canonical_state!=='active'||current.reviewed_revision_id!==gap.reviewed_revision_id||(current.reviewed_revision_id??current.working_revision_id)!==(gap.reviewed_revision_id??gap.working_revision_id))throw new HttpFailure(409,'stale_version','Gap projection changed');Object.assign(gap,current);}
 const lockedObservations=(await db.query('SELECT id,version FROM gap_impact_observations WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE',[observations.map(o=>o.id)])).rows;const observationVersions=new Map(lockedObservations.map(o=>[o.id,String(o.version)]));if(observations.some(o=>observationVersions.get(o.id)!==String(o.version)))throw new HttpFailure(409,'stale_version','Impact projection changed');
 const currentAt=new Date(),proseEnabled=gapProseEnabled(),eligibleCache=new Map<string,boolean>(),criticalCache=new Map<string,boolean>(),qualityCache=new Map<string,ReturnType<typeof retrievalQuality>|null>(),observationsByGap=new Map<string,typeof observations>();for(const observation of observations){const list=observationsByGap.get(observation.canonical_gap_id)??[];list.push(observation);observationsByGap.set(observation.canonical_gap_id,list);}
 const byRevision=new Map<string,Dependency[]>();for(const d of deps){const list=byRevision.get(d.revision_id)??[];list.push(d);byRevision.set(d.revision_id,list);}
 function eligible(m:Metadata,cutoff=at){const key=m.id+':'+cutoff.getTime();if(eligibleCache.has(key))return eligibleCache.get(key)!;const value=evaluateEligibility(m,cutoff);eligibleCache.set(key,value);return value;}
 function evaluateEligibility(m:Metadata,cutoff:Date){if(!proseEnabled||!m.present||m.invalidated_at||m.purge_at&&m.purge_at<=currentAt||m.created_at>cutoff)return false;const ds=byRevision.get(m.id)??[];
  for(const d of ds){const key=`${d.source_kind}:${d.source_revision_id}`;if(d.source_kind==='execution_record'||d.source_kind==='milestone_baseline'){if(executionEligible.get(key)!==true)return false;continue;}const original=originalMap.get(key);if(!original?.eligible||original.created_at>cutoff||String(original.generation)!==String(d.source_generation)||original.digest!==d.source_digest||unsupported.has(original.id)||conflicted.has(key))return false;}
  return m.refs.every(ref=>ref.locator?locatedKeys.has(locatorKey(ref))&&(!(ref.kind==='shared_knowledge')||quality(ref,cutoff)?.validUntil&&Date.parse(quality(ref,cutoff)!.validUntil)>currentAt.getTime()):executionEligible.get(`${ref.kind}:${ref.sourceRevisionId}`));
 }
 function quality(ref:GapSource,cutoff:Date){const key=ref.kind+':'+ref.sourceRevisionId+':'+cutoff.getTime();if(qualityCache.has(key))return qualityCache.get(key)!;const o=originalMap.get(`${ref.kind}:${ref.sourceRevisionId}`);const result=!o?null:ref.kind==='shared_knowledge'?evidenceQualitySchema.safeParse(o.quality_input).data??null:retrievalQuality(o.quality_input,{observationAt:o.observation_at?new Date(o.observation_at):null,publicationAt:o.publication_at?new Date(o.publication_at):null,reviewAt:o.review_at?new Date(o.review_at):null},cutoff);qualityCache.set(key,result);return result;}
 function critical(ref:GapSource,product:boolean,cutoff:Date,productKey:string){const key=ref.kind+':'+ref.sourceRevisionId+':'+product+':'+cutoff.getTime()+':'+productKey;if(criticalCache.has(key))return criticalCache.get(key)!;const o=originalMap.get(`${ref.kind}:${ref.sourceRevisionId}`),q=quality(ref,cutoff),value=Boolean(q&&q.Q>=60&&q.R>=2&&q.D>=(product?4:3)&&['Recent','Aging'].includes(q.freshness)&&Date.parse(q.validUntil)>cutoff.getTime()&&(!product||q.freshness==='Recent'&&['product_capability','product_availability'].includes(o?.quality_input?.informationType??'product_capability')&&(!o?.product_key||o.product_key===productKey))&&(!o?.observation_at||Date.parse(o.observation_at)<=cutoff.getTime())&&(!o?.publication_at||Date.parse(o.publication_at)<=cutoff.getTime()));criticalCache.set(key,value);return value;}
 const map=new Map(metadata.map(m=>[m.id,m]));
 function calculate(cutoff:Date,comparison=false){return gaps.map(g=>{const head=map.get(g.reviewed_revision_id??g.working_revision_id),gapEligible=Boolean(head&&eligible(head,currentAt));const rows=(observationsByGap.get(g.id)??[]).map(o=>{const m=map.get(comparison?o.comparison_revision_id:o.cutoff_revision_id),classification=m?.fields.classification??'suspected';let valid=Boolean(g.reviewed_revision_id&&head&&gapEligible&&m&&eligible(m,cutoff)&&(comparison?o.comparison_accepted_at:o.accepted_at)<=cutoff&&(comparison?o.comparison_kind:o.reviewed_kind)===head.fields.kind&&(comparison?o.comparison_product_key:o.reviewed_product_key)===head.fields.productKey);if(valid&&classification!=='suspected'){if(!m!.fields.observedAt||Date.parse(m!.fields.observedAt)>cutoff.getTime()||classification==='resolved'&&(!m!.fields.resolvedAt||Date.parse(m!.fields.resolvedAt)>cutoff.getTime())||head!.fields.productKey==='unknown')valid=false;const purposes=classification==='resolved'?['resolution']:['customer_need','product_limitation'];for(const purpose of purposes){const selected=[...m!.refs,...(purpose==='product_limitation'?head!.refs:[])].filter(r=>r.purpose===purpose);if(!selected.length||selected.some(r=>!r.locator||purpose!=='product_limitation'&&(!['accepted_profile','approved_excerpt'].includes(r.kind)||r.customerId!==o.customer_id)||purpose==='customer_need'&&originalMap.get(`${r.kind}:${r.sourceRevisionId}`)?.profile_state&&originalMap.get(`${r.kind}:${r.sourceRevisionId}`)?.profile_state!=='actual'||!critical(r,purpose==='product_limitation',cutoff,head!.fields.productKey!)||!critical(r,purpose==='product_limitation',currentAt,head!.fields.productKey!)))valid=false;}}return {id:o.id,revisionId:m?.id??null,customerId:o.customer_id,classification,retired:o.state==='retired'||(comparison?o.comparison_action:o.cutoff_action)==='retire',eligible:valid};});const sets=impactSets(rows);const freshnessHeads=[head,...(observationsByGap.get(g.id)??[]).filter(o=>o.state!=='retired').map(o=>map.get(comparison?o.comparison_revision_id:o.cutoff_revision_id))].filter((m):m is Metadata=>Boolean(m));const sourceFreshness=evidenceFreshness(freshnessHeads.flatMap(m=>!eligible(m,currentAt)?['Unavailable' as const]:m.refs.map(ref=>quality(ref,currentAt)?.freshness??'Unknown')));return {id:g.id,evidenceFreshness:sourceFreshness,comparisonAvailability:(observationsByGap.get(g.id)??[]).some(o=>(comparison?o.comparison_revision_id:o.cutoff_revision_id)&&!map.get(comparison?o.comparison_revision_id:o.cutoff_revision_id)?.present)?'unavailable':'available',confirmed:sets.confirmed.length,suspectedOnly:sets.suspectedOnly.length,resolvedHistory:sets.resolvedHistory.length,sets,eligibleImpacts:rows.filter(r=>r.eligible&&!r.retired).map(r=>({id:r.id,revisionId:r.revisionId!,customerId:r.customerId,classification:r.classification})),eligible:gapEligible,head,record:g};});}
 const items=calculate(at).map(item=>({...item,comparison:null as GapComparison|null}));
 if(items.some(item=>item.comparisonAvailability==='unavailable'))throw new HttpFailure(409,'history_unavailable','Required impact history is unavailable');
 const previous=comparisonAt?calculate(comparisonAt,true):null;
 if(previous&&comparisonAt)for(const item of items){const prior=previous.find(p=>p.id===item.id)!;const history=(observationsByGap.get(item.id)??[]).flatMap(o=>[o.cutoff_revision_id,o.comparison_revision_id]).filter(Boolean).map(id=>map.get(id));const comparable=item.comparisonAvailability==='available'&&prior.comparisonAvailability==='available'&&history.every(m=>m&&eligible(m,currentAt)&&m.refs.every(ref=>{const original=originalMap.get(`${ref.kind}:${ref.sourceRevisionId}`);return !ref.locator||original?.created_at<=comparisonAt&&(!(m!.fields.classification==='confirmed'||m!.fields.classification==='resolved')||!['customer_need','product_limitation','resolution'].includes(ref.purpose)||critical(ref,ref.purpose==='product_limitation',comparisonAt,map.get(item.record.reviewed_revision_id)?.fields.productKey??'unknown'));}));item.comparison=comparable?{availability:'available',at:comparisonAt.toISOString(),confirmed:item.confirmed-prior.confirmed,suspectedOnly:item.suspectedOnly-prior.suspectedOnly,resolvedHistory:item.resolvedHistory-prior.resolvedHistory}:{availability:'unavailable',reason:'Required historical evidence or comparable original scope is unavailable'};}
 return {items,metadata,observations,generation:gapHash({gaps:gaps.map(g=>[g.id,g.version]),states:metadata.map(m=>[m.id,m.generation,m.invalidated_at,m.purge_at]),sets:items.map(i=>[i.id,i.eligible,i.sets,i.evidenceFreshness])}),methodVersion:'gap-impact-v1' as const,asOf:at.toISOString()};
}
export function readGapCounts(actor:GapActor,ids:readonly string[],at=new Date(),comparisonAt?:Date){if(!Number.isFinite(at.getTime())||at.getTime()>Date.now()||comparisonAt&&(!Number.isFinite(comparisonAt.getTime())||comparisonAt>=at||at.getTime()-comparisonAt.getTime()>90*86400000))throw new HttpFailure(400,'invalid_input','Invalid impact cutoff interval');z.array(z.uuid()).max(2000).refine(v=>new Set(v).size===v.length).parse(ids);return gapRead(actor,async db=>{const result=await gapCountMetadata(db,actor,ids,at,[],comparisonAt);return {...result,items:result.items.map(({head,record,eligibleImpacts,...item})=>item),metadata:undefined,observations:undefined};});}
