import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {gapHandoffSchema,type GapSource} from '../../contracts/product-gaps';
import {HttpFailure,hiddenRecord} from '../../contracts/http';
import {getServerConfig} from '../config';
import {gapCommand,gapRead,gapHash} from './commands';
import {type GapActor,requireGapReviewer} from './policy';
import {reportRow,currentGapReport} from './reports';
import {gapApprovedReport} from './report-release';
import {gapExpected} from './repository';
import {verifyGapSources,gapSourceMetadata} from './sources';
import {readGapObject} from './store';
import {isGapWithholding} from './eligibility';
type Payload={note:string;reference:string|null;sourceRefs:GapSource[];classification:'human_reported'};
type HandoffRow={id:string;actor_membership_id:string|null;created_at:Date;report_id:string;review_id:string;revision_id:string;kind:string;event_at:Date;audience_digest:string;predecessor_id:string|null;corrected_id:string|null;metadata_only:boolean;event_digest:string;source_digest:string;generation:string;needs_human_follow_up:boolean;invalidated_at:Date|null;purge_at:Date|null;content:Payload|null;release_candidate?:boolean};
export async function gapHandoffRows(db:PoolClient,actor:GapActor,id:string){await reportRow(db,actor,id);const rows=(await db.query<HandoffRow>('SELECT h.*,s.generation,s.needs_human_follow_up,s.invalidated_at,s.purge_at,p.content FROM gap_handoff_receipts h JOIN gap_handoff_states s ON s.receipt_id=h.id LEFT JOIN gap_handoff_payloads p ON p.receipt_id=h.id WHERE h.report_id=$1 AND h.environment_id=$2 AND h.workspace_id=$3 ORDER BY h.created_at,h.id LIMIT 1001',[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows;if(rows.length>1000)throw new HttpFailure(413,'scope_too_large','Handoff history exceeds limit');return rows;}
/** Metadata discovery only; release is rechecked under the subsequent whole-source fence. */
export async function gapHandoffSourceRefs(db:PoolClient,actor:GapActor,rows:HandoffRow[]){const refs:GapSource[]=[];for(const row of rows){row.release_candidate=false;if(!row.content||row.invalidated_at||row.purge_at&&row.purge_at.getTime()<=Date.now())continue;try{const verified=await verifyGapSources(db,actor,row.content.sourceRefs,{alreadyLocked:true});if(verified.digest===row.source_digest){row.release_candidate=true;refs.push(...row.content.sourceRefs);}}catch(error){if(!isGapWithholding(error))throw error;}}return refs;}
export async function projectGapHandoffs(db:PoolClient,actor:GapActor,rows:HandoffRow[],eligible:boolean,currentReviewId:string|null){const result=[];for(const row of rows){let payload:Payload|null=null;if(row.release_candidate&&eligible&&row.review_id===currentReviewId&&row.content&&!row.invalidated_at&&(!row.purge_at||row.purge_at.getTime()>Date.now()))try{const verified=await verifyGapSources(db,actor,row.content.sourceRefs,{alreadyLocked:true});if(verified.digest===row.source_digest){const fenced=(await db.query('SELECT s.generation,s.invalidated_at,s.purge_at,p.content FROM gap_handoff_states s JOIN gap_handoff_payloads p ON p.receipt_id=s.receipt_id WHERE s.receipt_id=$1 FOR SHARE OF s,p',[row.id])).rows[0];if(fenced&&!fenced.invalidated_at&&(!fenced.purge_at||fenced.purge_at.getTime()>Date.now())&&String(fenced.generation)===String(row.generation)&&gapHash(fenced.content)===gapHash(row.content))payload=row.content;}}catch(error){if(!isGapWithholding(error))throw error;}result.push({id:row.id,reviewId:row.review_id,kind:row.kind,eventAt:row.event_at.toISOString(),audienceDigest:row.audience_digest,predecessorId:row.predecessor_id,correctedId:row.corrected_id,metadataOnly:row.metadata_only,humanReported:true as const,reporterMembershipId:row.actor_membership_id,recordedAt:row.created_at.toISOString(),needsHumanFollowUp:row.needs_human_follow_up||!eligible||!row.metadata_only&&!payload,payload});}return result;}
export function readGapHandoffs(actor:GapActor,id:string){return gapRead(actor,async db=>{const rows=await gapHandoffRows(db,actor,id),refs=await gapHandoffSourceRefs(db,actor,rows),current=await currentGapReport(db,actor,id,refs);return projectGapHandoffs(db,actor,rows,current.availability==='eligible',current.report.approved_review_id);},true);}
export function recordGapHandoff(actor:GapActor,id:string,raw:unknown){const input=gapHandoffSchema.parse(raw);return gapCommand(actor,'handoff',{...input,reportId:id},async db=>{requireGapReviewer(actor);const report=await reportRow(db,actor,id),env=getServerConfig().TURAS_ENVIRONMENT_ID;gapExpected(report.version,input.expectedVersion);let predecessor:HandoffRow|undefined,reviewId:string,revisionId:string,markdownDigest:string,jsonDigest:string,sourceDigest=gapHash([]);
 if(input.predecessorId){predecessor=(await db.query<HandoffRow>('SELECT h.* FROM gap_handoff_receipts h WHERE h.id=$1 AND h.report_id=$2 AND h.environment_id=$3 AND h.workspace_id=$4',[input.predecessorId,id,env,actor.workspaceId])).rows[0];if(!predecessor)throw hiddenRecord();if(predecessor.audience_digest!==input.audienceDigest)throw new HttpFailure(409,'stale_version','Handoff audience is immutable');if(Date.parse(input.eventAt)<predecessor.event_at.getTime())throw new HttpFailure(400,'invalid_input','Follow-up cannot precede its predecessor');const latest=(await db.query('SELECT id FROM gap_handoff_receipts WHERE report_id=$1 AND review_id=$2 AND audience_digest=$3 ORDER BY created_at DESC,id DESC LIMIT 1',[id,predecessor.review_id,input.audienceDigest])).rows[0];if(latest?.id!==predecessor.id)throw new HttpFailure(409,'stale_version','Use the latest preceding event');if(input.correctedId){const corrected=(await db.query('SELECT id,event_at FROM gap_handoff_receipts WHERE id=$1 AND report_id=$2 AND review_id=$3 AND audience_digest=$4',[input.correctedId,id,predecessor.review_id,input.audienceDigest])).rows[0];if(!corrected)throw hiddenRecord();if(corrected.event_at.getTime()>Date.parse(input.eventAt))throw new HttpFailure(400,'invalid_input','Correction cannot precede the corrected event');}}
 if(input.metadataOnly){if(!predecessor)throw new HttpFailure(400,'invalid_input','Metadata follow-up requires prior handoff');reviewId=predecessor.review_id;revisionId=predecessor.revision_id;const artifacts=(await db.query('SELECT format,content_digest FROM gap_export_artifacts WHERE revision_id=$1 ORDER BY format',[revisionId])).rows;markdownDigest=artifacts.find(a=>a.format==='markdown')?.content_digest;jsonDigest=artifacts.find(a=>a.format==='json')?.content_digest;if(!markdownDigest||!jsonDigest)throw new HttpFailure(409,'artifact_unavailable','Prior handoff identity unavailable');}
 else{const current=await gapApprovedReport(db,actor,id,predecessor?.review_id,input.sourceRefs);if(input.audienceDigest!==current.review.audience_digest)throw new HttpFailure(409,'stale_version','Exact approved audience required');if(Date.parse(input.eventAt)<current.review.created_at.getTime())throw new HttpFailure(400,'invalid_input','Handoff cannot precede approval');for(const ref of input.sourceRefs){if(ref.customerId&&!current.document!.customers.some(c=>c.id===ref.customerId))throw new HttpFailure(409,'disclosure_required','New customer evidence requires new report disclosure');if((await gapSourceMetadata(db,ref,new Date(input.eventAt))).futureObservation)throw new HttpFailure(422,'source_unavailable','Response observation cannot follow its reported occurrence');}sourceDigest=(await verifyGapSources(db,actor,input.sourceRefs,{alreadyLocked:true})).digest;reviewId=current.review.id;revisionId=current.revision!.id;const artifacts=(await db.query('SELECT format,object_key,content_digest,size_bytes FROM gap_export_artifacts WHERE revision_id=$1',[revisionId])).rows;for(const artifact of artifacts)await readGapObject(artifact.object_key,artifact.content_digest,Number(artifact.size_bytes));markdownDigest=artifacts.find(a=>a.format==='markdown')?.content_digest;jsonDigest=artifacts.find(a=>a.format==='json')?.content_digest;}
 const locked=await reportRow(db,actor,id,true);gapExpected(locked.version,input.expectedVersion);const eventDigest=gapHash({kind:input.kind,eventAt:input.eventAt,audienceDigest:input.audienceDigest,predecessorId:input.predecessorId,correctedId:input.correctedId,metadataOnly:input.metadataOnly,note:input.note,reference:input.reference,sourceRefs:input.sourceRefs});if(input.kind==='handed_off'){const prior=(await db.query("SELECT id,event_digest FROM gap_handoff_receipts WHERE report_id=$1 AND review_id=$2 AND audience_digest=$3 AND kind='handed_off'",[id,reviewId,input.audienceDigest])).rows[0];if(prior){if(prior.event_digest!==eventDigest)throw new HttpFailure(409,'handoff_exists','An initial handoff is already recorded');return {recordId:id,resultId:prior.id,outcome:'already_recorded',version:Number(locked.version)};}}
 const eventId=randomUUID(),version=Number(locked.version)+1;await db.query('INSERT INTO gap_handoff_receipts(id,report_id,review_id,revision_id,environment_id,workspace_id,actor_membership_id,kind,event_at,audience_digest,markdown_digest,json_digest,predecessor_id,corrected_id,metadata_only,event_digest,source_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)',[eventId,id,reviewId,revisionId,env,actor.workspaceId,actor.membershipId,input.kind,input.eventAt,input.audienceDigest,markdownDigest,jsonDigest,input.predecessorId,input.correctedId,input.metadataOnly,eventDigest,sourceDigest]);await db.query('INSERT INTO gap_handoff_states(receipt_id,needs_human_follow_up) VALUES($1,$2)',[eventId,input.metadataOnly]);
 if(!input.metadataOnly){await db.query('INSERT INTO gap_handoff_payloads(receipt_id,content) VALUES($1,$2)',[eventId,JSON.stringify({note:input.note,reference:input.reference,sourceRefs:input.sourceRefs,classification:'human_reported'})]);const verified=await verifyGapSources(db,actor,input.sourceRefs,{alreadyLocked:true});await db.query('INSERT INTO gap_handoff_dependencies(id,receipt_id,source_kind,source_revision_id,source_generation,source_digest) SELECT gen_random_uuid(),$2,x.kind,x."revisionId",x.generation,x."contentDigest" FROM jsonb_to_recordset($1::jsonb) AS x(kind text,"revisionId" uuid,generation bigint,"contentDigest" text)',[JSON.stringify(verified.dependencies),eventId]);}
 if(predecessor)await db.query("UPDATE gap_handoff_states SET purge_at=LEAST(COALESCE(purge_at,clock_timestamp()+interval '90 days'),clock_timestamp()+interval '90 days') WHERE receipt_id=$1",[predecessor.id]);if(input.correctedId)await db.query('UPDATE gap_handoff_states SET needs_human_follow_up=true,generation=generation+1 WHERE receipt_id=$1',[input.correctedId]);await db.query('UPDATE gap_reports SET version=$2 WHERE id=$1',[id,version]);return {recordId:id,resultId:eventId,outcome:input.kind,version};
 },{reports:true});}
