import { z } from 'zod';
import { HttpFailure,hiddenRecord,failure,success } from '../../contracts/http';
import { getCurrentSession } from '../auth/sessions';
import { checkSessionCsrf } from '../auth/csrf';
import type { GapActor } from './policy';
import { gapId } from '../../contracts/product-gaps';
import { recordGapTelemetry } from './telemetry';
export const gapRouteId=(raw:unknown)=>gapId.parse(raw);
export async function gapBody(request:Request,limit=262144){if(!/^application\/json(?:\s*;|$)/i.test(request.headers.get('content-type')??''))throw new HttpFailure(415,'invalid_input','JSON body required');if(!request.body)throw new HttpFailure(400,'invalid_input','JSON body required');if(Number(request.headers.get('content-length')??0)>limit)throw new HttpFailure(413,'scope_too_large','Request exceeds byte limit');const reader=request.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>limit)throw new HttpFailure(413,'scope_too_large','Request exceeds byte limit');chunks.push(part.value);}}catch(error){await reader.cancel().catch(()=>undefined);throw error;}finally{reader.releaseLock();}try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks)));}catch{throw new HttpFailure(400,'invalid_input','Malformed JSON');}}
export function gapQuery(request:Request){const p=new URL(request.url).searchParams;if([...p.keys()].some(k=>p.getAll(k).length!==1))throw new HttpFailure(400,'invalid_input','Duplicate query');return Object.fromEntries(p);}
export async function gapRequest(request:Request,write:boolean,run:(actor:GapActor,body:unknown)=>Promise<unknown>,status=200,bodyLimit=262144){const start=performance.now(),correlationId=crypto.randomUUID();try{const actor=await getCurrentSession(request);if(!actor)throw new HttpFailure(401,'authentication_required','Sign in required');if(actor.kind!=='internal')throw hiddenRecord();if(write)checkSessionCsrf(request,actor);const result=await run(actor,write?await gapBody(request,bodyLimit):undefined);recordGapTelemetry({operation:write?'write':'read',outcome:'committed',correlationId,durationMs:performance.now()-start});if(result instanceof Response)return result;return success(result,status,correlationId);}catch(error){const known=error instanceof z.ZodError?new HttpFailure(400,'invalid_input','Invalid product gap input'):error;recordGapTelemetry({operation:write?'write':'read',outcome:known instanceof HttpFailure&&known.status<500?'denied':'failed',correlationId,durationMs:performance.now()-start});return failure(known,correlationId);}}
