import { randomUUID } from 'node:crypto';
import { gapImpactSaveSchema,type GapContent,type GapImpactContent } from '../../contracts/product-gaps';
import { parseGapImpact } from '../../product-gaps/content';
import type { GapActor } from './policy';
import { getServerConfig } from '../config';
import { gapCommand } from './commands';
import { gapRow,impactRow,gapExpected,insertGapRevision,revisionHeader } from './repository';
import { lockGapCustomers } from './policy';
import { verifyGapSources,gapConfirmationChecks,lockGapSourceUnion } from './sources';
import { projectGapRevision } from './projection';
import { HttpFailure,hiddenRecord } from '../../contracts/http';
export async function saveGapImpact(actor:GapActor,gapId:string,raw:unknown,id?:string){const input=gapImpactSaveSchema.parse(raw),content=parseGapImpact(input.content,input.sourceRefs);return gapCommand(actor,'save_impact',{...input,gapId,impactId:id??null},async db=>{
 const parent=await gapRow(db,actor,gapId);if(parent.canonical_state!=='active')throw new HttpFailure(409,'stale_version','Use the canonical gap');
 const priorIdentity=id??input.recurrenceParent;const priorObservation=priorIdentity?await impactRow(db,actor,gapId,priorIdentity):null;const priorHeader=priorObservation?.reviewed_revision_id?await revisionHeader(db,actor,priorObservation.reviewed_revision_id):undefined;
 const gapHeader=parent.reviewed_revision_id?await revisionHeader(db,actor,parent.reviewed_revision_id):undefined;const gapSources=gapHeader?.content?.sourceRefs??[];
 await lockGapSourceUnion(db,actor,[...gapSources,...input.sourceRefs,...(priorHeader?.content?.sourceRefs??[])],600,[input.customerId]);
 const gapRevision=await projectGapRevision(db,actor,parent.reviewed_revision_id,false,gapHeader);
 const verified=await verifyGapSources(db,actor,input.sourceRefs,{alreadyLocked:true});
 if(input.sourceRefs.some(r=>r.purpose!=='product_limitation'&&r.customerId!==input.customerId&&r.kind!=='shared_knowledge'))throw hiddenRecord();
 if(input.workloadId&&!(await db.query("SELECT 1 FROM customer_workloads WHERE id=$1 AND customer_id=$2 AND workspace_id=$3 AND lifecycle='active'",[input.workloadId,input.customerId,actor.workspaceId])).rowCount)throw hiddenRecord();
 if(input.engagementId&&!(await db.query('SELECT 1 FROM engagements WHERE id=$1 AND customer_id=$2 AND workspace_id=$3 AND environment_id=$4 AND ($5::uuid IS NULL OR workload_id=$5)',[input.engagementId,input.customerId,actor.workspaceId,getServerConfig().TURAS_ENVIRONMENT_ID,input.workloadId])).rowCount)throw hiddenRecord();
 if(content.classification!=='suspected'){if(!gapRevision?.content||gapRevision.availability!=='eligible')throw new HttpFailure(409,'source_unavailable','Review a current eligible gap first');await gapConfirmationChecks(db,actor,input.customerId,content,gapRevision.content as GapContent,input.sourceRefs,gapSources);}
 const locked=await gapRow(db,actor,gapId,true);gapExpected(locked.version,input.expectedGapVersion);if(locked.reviewed_revision_id!==parent.reviewed_revision_id)throw new HttpFailure(409,'stale_version','Reviewed gap changed');
 let observationId=id;
 if(id){const prior=await impactRow(db,actor,gapId,id,true);gapExpected(prior.version,input.expectedVersion);if(prior.customer_id!==input.customerId||prior.workload_id!==input.workloadId||prior.engagement_id!==input.engagementId||prior.recurrence_parent!==input.recurrenceParent)throw new HttpFailure(409,'invalid_input','Observation scope is immutable');if(prior.state==='retired')throw new HttpFailure(409,'stale_version','Retired observations cannot become current');const accepted=await projectGapRevision(db,actor,prior.reviewed_revision_id,false,priorHeader);if((accepted?.content as GapImpactContent|null)?.classification==='resolved'&&content.classification!=='resolved')throw new HttpFailure(409,'invalid_input','Create a new recurrence after resolution');}
 else {gapExpected(0,input.expectedVersion);if(input.recurrenceParent){const prior=await impactRow(db,actor,gapId,input.recurrenceParent);if(prior.customer_id!==input.customerId)throw hiddenRecord();const accepted=await projectGapRevision(db,actor,prior.reviewed_revision_id,false,priorHeader);const previous=accepted?.content as GapImpactContent|null;if(prior.state!=='active'||accepted?.availability!=='eligible'||previous?.classification!=='resolved'||!content.observedAt||!previous.resolvedAt||content.observedAt<previous.resolvedAt)throw new HttpFailure(409,'invalid_input','Recurrence requires a resolved predecessor and ordered observation date');}
  observationId=randomUUID();await db.query('INSERT INTO gap_impact_observations(id,environment_id,workspace_id,original_gap_id,customer_id,workload_id,engagement_id,recurrence_parent,creator_membership_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[observationId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,gapId,input.customerId,input.workloadId,input.engagementId,input.recurrenceParent,actor.membershipId]);const event=randomUUID();await db.query('INSERT INTO gap_assignment_events(id,environment_id,workspace_id,observation_id,canonical_gap_id) VALUES($1,$2,$3,$4,$5)',[event,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,observationId,gapId]);await db.query('INSERT INTO gap_observation_assignments(observation_id,environment_id,workspace_id,canonical_gap_id,event_id) VALUES($1,$2,$3,$4,$5)',[observationId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,gapId,event]);}
 const prior=await impactRow(db,actor,gapId,observationId!);const version=id?Number(prior.version)+1:1;const revision=await insertGapRevision(db,actor,prior.original_gap_id,observationId!,content,input.sourceRefs,verified.dependencies,version);await db.query('UPDATE gap_impact_observations SET working_revision_id=$2,version=$3 WHERE id=$1',[observationId,revision,version]);await db.query('UPDATE product_gaps SET version=version+1 WHERE id=$1',[gapId]);return {recordId:gapId,resultId:revision,outcome:'proposed',version};
 });}
