import {randomUUID} from 'node:crypto';
import {withTransaction} from '../db/client';
import {getServerConfig} from '../config';
import {requireGapSchema} from './schema';
import {gapOpaqueHashes} from './commands';
import {deleteGapObject} from './store';
import {recheckGapQualityExpiry} from './quality-expiry';
/** One environment lease; exact catalog identities only, with no directory scan. */
export async function maintainGapRetention(){const environment=getServerConfig().TURAS_ENVIRONMENT_ID,token=randomUUID(),started=Date.now();const claimed=await withTransaction(async db=>{await requireGapSchema(db,false,true);return !!(await db.query("INSERT INTO gap_cleanup_leases(environment_id,lease_token,lease_until) VALUES($1,$2,clock_timestamp()+interval '180 seconds') ON CONFLICT(environment_id) DO UPDATE SET lease_token=$2,lease_until=clock_timestamp()+interval '180 seconds' WHERE gap_cleanup_leases.lease_until<=clock_timestamp() RETURNING environment_id",[environment,token])).rowCount;});if(!claimed)return {claimed:false,deleted:0,quarantined:0};let deleted=0,quarantined=0;try{
 await withTransaction(async db=>{const expired=(await db.query("SELECT p.revision_id FROM knowledge_publications p WHERE p.state='published' AND (p.public_quality->>'validUntil')::timestamptz<=clock_timestamp() AND EXISTS(SELECT 1 FROM gap_source_dependencies d JOIN gap_revisions r ON r.id=d.revision_id JOIN gap_revision_states s ON s.revision_id=r.id WHERE r.environment_id=$1 AND d.source_kind='shared_knowledge' AND d.source_revision_id=p.revision_id AND s.invalidated_at IS NULL) OR p.state='published' AND (p.public_quality->>'validUntil')::timestamptz<=clock_timestamp() AND EXISTS(SELECT 1 FROM gap_handoff_dependencies d JOIN gap_handoff_receipts h ON h.id=d.receipt_id JOIN gap_handoff_states s ON s.receipt_id=h.id WHERE h.environment_id=$1 AND d.source_kind='shared_knowledge' AND d.source_revision_id=p.revision_id AND s.invalidated_at IS NULL) ORDER BY p.revision_id LIMIT 100",[environment])).rows;for(const source of expired)await db.query("SELECT turas_gap_invalidate_source('shared_knowledge',$1)",[source.revision_id]);await db.query('SELECT turas_gap_purge_payloads($1,100)',[environment]);await recheckGapQualityExpiry(db,environment,100);await db.query('SELECT turas_gap_retention_payloads($1,$2,100)',[environment,token]);});
 const receipts=await withTransaction(async db=>(await db.query("SELECT id,workspace_id,actor_membership_id,operation,request_key FROM gap_request_receipts WHERE environment_id=$1 AND created_at<=clock_timestamp()-interval '365 days' ORDER BY created_at,id LIMIT 100",[environment])).rows);for(const r of receipts){if(Date.now()-started>=175000)break;await withTransaction(db=>db.query('SELECT turas_gap_expire_receipt($1,$2,$3)',[environment,r.id,gapOpaqueHashes([environment,r.workspace_id,r.actor_membership_id,r.operation,r.request_key])]));}
 for(let i=0;i<100&&Date.now()-started<175000;i++){const outcome=await withTransaction(async db=>{if(!(await db.query('SELECT 1 FROM gap_cleanup_leases WHERE environment_id=$1 AND lease_token=$2 AND lease_until>clock_timestamp() FOR SHARE',[environment,token])).rowCount)return 'done';const object=(await db.query("SELECT * FROM gap_report_store_objects WHERE environment_id=$1 AND state='purge' AND purge_at<=clock_timestamp() AND (lease_until IS NULL OR lease_until<=clock_timestamp()) ORDER BY purge_at,object_key LIMIT 1 FOR UPDATE SKIP LOCKED",[environment])).rows[0];if(!object)return 'done';await db.query("UPDATE gap_report_store_objects SET lease_token=$2,lease_until=clock_timestamp()+interval '180 seconds' WHERE object_key=$1",[object.object_key,token]);if((await db.query('SELECT 1 FROM report_store_objects WHERE object_key=$1',[object.object_key])).rowCount){await db.query("UPDATE gap_report_store_objects SET state='quarantined',failure_code='identity_collision',lease_until=NULL WHERE object_key=$1 AND lease_token=$2",[object.object_key,token]);return 'quarantined';}let missing=false;try{await deleteGapObject(object.object_key,object.content_digest,Number(object.size_bytes));}catch(error){if((error as {code?:string}).code==='ENOENT')missing=true;else{await db.query("UPDATE gap_report_store_objects SET state='quarantined',failure_code='object_identity_unverified',lease_until=NULL WHERE object_key=$1 AND lease_token=$2",[object.object_key,token]);return 'quarantined';}}await db.query("UPDATE gap_report_store_objects SET state='deleted',failure_code=$3,lease_until=NULL WHERE object_key=$1 AND lease_token=$2 AND state='purge'",[object.object_key,token,missing?'already_missing':null]);return 'deleted';});if(outcome==='done')break;if(outcome==='deleted')deleted++;else quarantined++;}
 return {claimed:true,deleted,quarantined};
 }finally{await withTransaction(db=>db.query('UPDATE gap_cleanup_leases SET lease_until=clock_timestamp() WHERE environment_id=$1 AND lease_token=$2',[environment,token]));}}
