import type {PoolClient} from 'pg';
import type {GapSource} from '../../contracts/product-gaps';
import {gapSourceMetadata} from './sources';
import {invalidateGapReports} from './invalidation';
const windows:Record<string,number>={account_status:7,product_availability:14,product_capability:30,adoption_process:90,architecture:180,unknown:0};
function adequate(m:Awaited<ReturnType<typeof gapSourceMetadata>>,product:boolean,at:Date){const q=m.quality;return !!q&&q.Q>=60&&q.R>=2&&q.D>=(product?4:3)&&['Recent','Aging'].includes(q.freshness)&&(!product||q.freshness==='Recent'&&['product_capability','product_availability'].includes(m.informationType))&&Date.parse(q.validUntil)>at.getTime()&&!m.futureObservation;}
/** Global timer eligibility only. Membership/session loss never enters this path. */
export async function recheckGapQualityExpiry(db:PoolClient,environment:string,limit:number){if(!Number.isInteger(limit)||limit<1||limit>100)throw Error('Invalid quality recheck batch');const rows=(await db.query("SELECT r.id,r.gap_id,r.created_at,p.content,COALESCE(gp.content->'sourceRefs','[]'::jsonb) AS gap_refs,a.canonical_gap_id FROM gap_revisions r JOIN gap_revision_states s ON s.revision_id=r.id JOIN gap_revision_payloads p ON p.revision_id=r.id JOIN gap_impact_observations o ON o.id=r.impact_id JOIN gap_observation_assignments a ON a.observation_id=o.id JOIN product_gaps g ON g.id=a.canonical_gap_id LEFT JOIN LATERAL(SELECT reviewed_gap_revision_id FROM gap_decisions WHERE revision_id=r.id AND action='accept' ORDER BY created_at DESC,id DESC LIMIT 1)d ON true LEFT JOIN gap_revision_payloads gp ON gp.revision_id=COALESCE(d.reviewed_gap_revision_id,g.reviewed_revision_id) WHERE r.environment_id=$1 AND s.invalidated_at IS NULL AND s.eligibility_recheck_at<=clock_timestamp() AND (o.working_revision_id=r.id OR o.reviewed_revision_id=r.id) AND p.content#>>'{content,classification}' IN('confirmed','resolved') ORDER BY s.eligibility_recheck_at,r.id LIMIT $2",[environment,limit])).rows;const now=new Date();let invalidated=0;
 for(const row of rows){const refs:GapSource[]=[...(row.content.sourceRefs??[]),...row.gap_refs],purposes=row.content.content.classification==='resolved'?['resolution']:['customer_need','product_limitation'];let expiry:number|null=null,next=now.getTime()+86400000;for(const ref of refs.filter(r=>purposes.includes(r.purpose))){const product=ref.purpose==='product_limitation',metadata=await gapSourceMetadata(db,ref,now);if(adequate(metadata,product,now)){next=Math.min(next,Date.parse(metadata.quality!.validUntil));continue;}const span=(windows[metadata.informationType]??0)*86400000,candidates=[metadata.reviewAt,metadata.quality?.validUntil].filter((v):v is string=>!!v).map(v=>Date.parse(v));if(span)for(const origin of [metadata.observationAt,metadata.publicationAt])if(origin)for(const factor of [1,1.5,2])candidates.push(Date.parse(origin)+span*factor+1);let failedAt=now.getTime();for(const candidate of candidates.filter(n=>Number.isFinite(n)&&n>=row.created_at.getTime()&&n<=now.getTime()).sort((a,b)=>a-b)){if(!adequate(await gapSourceMetadata(db,ref,new Date(candidate)),product,new Date(candidate))){failedAt=candidate;break;}}expiry=Math.min(expiry??failedAt,failedAt);}
 if(expiry!==null){const changed=await db.query("UPDATE gap_revision_states SET invalidated_at=$2,purge_at=LEAST(COALESCE(purge_at,$2::timestamptz+interval '24 hours'),$2::timestamptz+interval '24 hours'),generation=generation+1 WHERE revision_id=$1 AND invalidated_at IS NULL RETURNING revision_id",[row.id,new Date(expiry)]);if(changed.rowCount){await invalidateGapReports(db,[row.canonical_gap_id],new Date(expiry));invalidated++;}}else await db.query('UPDATE gap_revision_states SET eligibility_recheck_at=$2 WHERE revision_id=$1 AND invalidated_at IS NULL',[row.id,new Date(Math.max(now.getTime()+1,next))]);}
 return {checked:rows.length,invalidated};}
