import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {gapReportReviewSchema,gapCommitSchema} from '../../contracts/product-gaps';
import {HttpFailure} from '../../contracts/http';
import {getServerConfig} from '../config';
import {gapCommand,gapHash} from './commands';
import {type GapActor,requireGapReviewer} from './policy';
import {gapExpected,gapAudit} from './repository';
import {currentGapReport,reportRow} from './reports';
import {saveGapPreview,loadGapPreview} from './previews';
import {readGapObject} from './store';
type ReviewInput=ReturnType<typeof gapReportReviewSchema.parse>;
async function reportReviewBinding(db:PoolClient,actor:GapActor,id:string,input:ReviewInput){requireGapReviewer(actor);const current=await currentGapReport(db,actor,id);if(current.availability!=='eligible'||!current.revision||!current.document)throw new HttpFailure(409,'source_unavailable','Exact prepared report unavailable');const {revision,document}=current;gapExpected(current.report.version,input.expectedVersion);if(input.revisionId!==revision.id||input.audienceDigest!==revision.audience_digest)throw new HttpFailure(409,'stale_version','Exact report audience changed');if(revision.author_membership_id===actor.membershipId&&!input.selfReview)throw new HttpFailure(400,'invalid_input','Explicit report self-review required');if(input.action==='approve'&&[...input.customerDisclosures].sort().join()!==document.customers.map(c=>c.id).sort().join())throw new HttpFailure(409,'disclosure_required','Acknowledge every included customer for this exact audience');const artifacts=(await db.query('SELECT * FROM gap_export_artifacts WHERE revision_id=$1 ORDER BY format',[revision.id])).rows;if(artifacts.length!==2)throw new HttpFailure(409,'artifact_unavailable','Both exact exports required');for(const artifact of artifacts)await readGapObject(artifact.object_key,artifact.content_digest,Number(artifact.size_bytes));const locked=await reportRow(db,actor,id,true);gapExpected(locked.version,input.expectedVersion);if(locked.current_revision_id!==revision.id)throw new HttpFailure(409,'stale_version','Report revision changed');return {input,reportId:id,revisionId:revision.id,contentDigest:revision.content_digest,sourceBinding:revision.binding_digest,generation:Number(revision.generation),audienceDigest:revision.audience_digest,artifacts:artifacts.map(a=>({id:a.id,format:a.format,digest:a.content_digest,size:Number(a.size_bytes)})),actor:actor.membershipId,session:actor.sessionId};}
export function previewGapReportReview(actor:GapActor,id:string,raw:unknown){const input=gapReportReviewSchema.parse(raw);return gapCommand(actor,'preview_report',{...input,reportId:id},async db=>{const binding=await reportReviewBinding(db,actor,id,input),preview=await saveGapPreview(db,actor,'review_report',id,binding,input);return {recordId:id,resultId:preview.id,bindingDigest:preview.digest,outcome:'preview',version:input.expectedVersion};},{reports:true});}
export function commitGapReportReview(actor:GapActor,id:string,raw:unknown){const command=gapCommitSchema.parse(raw);return gapCommand(actor,'review_report',{...command,reportId:id},async db=>{requireGapReviewer(actor);const preview=await loadGapPreview(db,actor,command.previewId,'review_report',id,command.bindingDigest),input=gapReportReviewSchema.parse(preview.payload);gapExpected(input.expectedVersion,command.expectedVersion);if(gapHash(await reportReviewBinding(db,actor,id,input))!==command.bindingDigest)throw new HttpFailure(409,'stale_version','Report review inputs changed');const reviewId=randomUUID(),version=command.expectedVersion+1;await db.query('INSERT INTO gap_report_reviews(id,report_id,revision_id,environment_id,workspace_id,action,reviewer_membership_id,rationale_digest,binding_digest,audience_digest,self_review) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[reviewId,id,input.revisionId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,input.action,actor.membershipId,gapHash(input.rationale),command.bindingDigest,input.audienceDigest,input.selfReview]);if(input.action==='approve')await db.query('INSERT INTO gap_report_disclosures(review_id,customer_id) SELECT $1,unnest($2::uuid[])',[reviewId,input.customerDisclosures]);await gapAudit(db,actor,reviewId,{rationale:input.rationale});await db.query('UPDATE gap_reports SET approved_review_id=$2,version=$3 WHERE id=$1',[id,input.action==='approve'?reviewId:null,version]);return {recordId:id,resultId:reviewId,outcome:input.action,version};},{reports:true});}
