import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {gapExportSchema,type GapSource} from '../../contracts/product-gaps';
import {HttpFailure,hiddenRecord} from '../../contracts/http';
import {withTransaction} from '../db/client';
import {getServerConfig} from '../config';
import {gapCommand,gapRead} from './commands';
import {type GapActor,lockGapActor,requireGapReviewer} from './policy';
import {gapExpected} from './repository';
import {currentGapReport} from './reports';
import {readGapObject} from './store';
export async function gapApprovedReport(db:PoolClient,actor:GapActor,id:string,reviewId?:string,additionalRefs:GapSource[]=[]){requireGapReviewer(actor);const current=await currentGapReport(db,actor,id,additionalRefs);if(current.availability!=='eligible'||!current.revision||!current.document||!current.report.approved_review_id||reviewId&&current.report.approved_review_id!==reviewId)throw new HttpFailure(409,'approval_unavailable','Current eligible report approval required');const review=(await db.query("SELECT * FROM gap_report_reviews WHERE id=$1 AND revision_id=$2 AND action='approve'",[current.report.approved_review_id,current.revision.id])).rows[0];if(!review||review.audience_digest!==current.revision.audience_digest)throw new HttpFailure(409,'approval_unavailable','Exact report review unavailable');const disclosures=(await db.query('SELECT customer_id FROM gap_report_disclosures WHERE review_id=$1 ORDER BY customer_id',[review.id])).rows;if(disclosures.map(d=>d.customer_id).join()!==current.document.customers.map(c=>c.id).sort().join())throw new HttpFailure(409,'disclosure_required','Exact customer disclosures unavailable');return {...current,review};}
export function admitGapExport(actor:GapActor,id:string,raw:unknown){const input=gapExportSchema.parse(raw);return gapCommand(actor,'export_report',{...input,reportId:id},async db=>{const current=await gapApprovedReport(db,actor,id,input.reviewId);gapExpected(current.report.version,input.expectedVersion);const artifact=(await db.query('SELECT * FROM gap_export_artifacts WHERE revision_id=$1 AND format=$2',[current.revision!.id,input.format])).rows[0];if(!artifact)throw new HttpFailure(409,'artifact_unavailable','Exact prepared artifact required');await readGapObject(artifact.object_key,artifact.content_digest,Number(artifact.size_bytes));const exportId=randomUUID();await db.query('INSERT INTO gap_export_receipts(id,report_id,review_id,artifact_id,environment_id,workspace_id,actor_membership_id,audience_digest,content_digest,size_bytes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[exportId,id,current.review.id,artifact.id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId,current.review.audience_digest,artifact.content_digest,artifact.size_bytes]);return {recordId:id,resultId:exportId,outcome:'ready',version:input.expectedVersion};},{reports:true});}
async function exportFence(db:PoolClient,actor:GapActor,id:string,exportId:string){const header=(await db.query('SELECT e.*,a.object_key,a.format FROM gap_export_receipts e JOIN gap_export_artifacts a ON a.id=e.artifact_id WHERE e.id=$1 AND e.report_id=$2 AND e.environment_id=$3 AND e.workspace_id=$4 AND e.actor_membership_id=$5',[exportId,id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId])).rows[0];if(!header)throw hiddenRecord();if(header.state==='cancelled')throw new HttpFailure(409,'export_cancelled','Export cancelled');const current=await gapApprovedReport(db,actor,id,header.review_id);if(header.audience_digest!==current.revision!.audience_digest)throw new HttpFailure(409,'stale_version','Export audience changed');return {header,current};}
export async function* gapExportChunks(actor:GapActor,id:string,exportId:string,options:{chunkSize?:number}={}){const size=options.chunkSize??65536;if(!Number.isInteger(size)||size<1||size>65536||size!==65536&&process.env.TURAS_GAPS_OWNED!=='1')throw Error('Invalid export chunk bound');const lease=randomUUID();let completed=false,claimed=false;try{
 const bytes=await gapRead(actor,async db=>{requireGapReviewer(actor);const {header}=await exportFence(db,actor,id,exportId),buffer=await readGapObject(header.object_key,header.content_digest,Number(header.size_bytes));const changed=await db.query("UPDATE gap_export_receipts SET state='streaming',version=version+1,lease_token=$2,lease_until=clock_timestamp()+interval '30 seconds' WHERE id=$1 AND state<>'cancelled' AND (state<>'streaming' OR lease_until<=clock_timestamp()) RETURNING id",[exportId,lease]);if(!changed.rowCount)throw new HttpFailure(409,'export_busy','Export already streaming');claimed=true;return buffer;},true);
 for(let offset=0;offset<bytes.length;offset+=size){await withTransaction(async db=>{await lockGapActor(db,actor,false,true);requireGapReviewer(actor);await exportFence(db,actor,id,exportId);const renewed=await db.query("UPDATE gap_export_receipts SET lease_until=clock_timestamp()+interval '30 seconds' WHERE id=$1 AND state='streaming' AND lease_token=$2 AND lease_until>clock_timestamp() RETURNING id",[exportId,lease]);if(!renewed.rowCount)throw new HttpFailure(409,'export_cancelled','Export stopped');});yield bytes.subarray(offset,Math.min(offset+size,bytes.length));}
 completed=true;
 }finally{if(claimed)await withTransaction(async db=>{await db.query("UPDATE gap_export_receipts SET state=$3,completed_at=CASE WHEN $3='completed' THEN clock_timestamp() ELSE completed_at END,version=version+1,lease_until=NULL WHERE id=$1 AND environment_id=$4 AND state='streaming' AND lease_token=$2",[exportId,lease,completed?'completed':'interrupted',getServerConfig().TURAS_ENVIRONMENT_ID]);});}}
export function cancelGapExport(actor:GapActor,id:string,exportId:string){return gapCommand(actor,'cancel_report',{contractVersion:'product-gaps-v1',requestKey:randomUUID(),expectedVersion:0,reportId:id,exportId},async db=>{requireGapReviewer(actor);const found=await db.query("UPDATE gap_export_receipts SET state='cancelled',version=version+1,lease_until=NULL WHERE id=$1 AND report_id=$2 AND environment_id=$3 AND workspace_id=$4 AND actor_membership_id=$5 RETURNING version",[exportId,id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId]);if(!found.rowCount)throw hiddenRecord();return {recordId:id,resultId:exportId,outcome:'cancelled',version:Number(found.rows[0].version)};},{reports:true,cancel:true});}

export async function assertGapExportCurrent(actor:GapActor,id:string,exportId:string){await withTransaction(async db=>{await lockGapActor(db,actor,false,true);requireGapReviewer(actor);await exportFence(db,actor,id,exportId);});}
