import {randomUUID,createHash} from 'node:crypto';
import type {PoolClient} from 'pg';
import {withTransaction} from '../db/client';
import {getServerConfig} from '../config';
import {HttpFailure} from '../../contracts/http';
import {gapReportPrepareSchema} from '../../contracts/product-gaps';
import {gapReportBytes} from '../../product-gaps/report-manifest';
import {gapHash} from './commands';
import {lockGapActor,type GapActor} from './policy';
import {requireGapSchema,gapProseEnabled} from './schema';
import {captureGapReport,reportRow} from './reports';
import {stageGapObject,writeGapObject,readGapObject} from './store';
export type GapReportJob={id:string;report_id:string;environment_id:string;workspace_id:string;actor_membership_id:string;session_id:string;state:string;deadline_at:Date;lease_token:string;lease_until:Date};
export async function recoverGapReportJobs(){return withTransaction(async db=>{await requireGapSchema(db,false,true);const env=getServerConfig().TURAS_ENVIRONMENT_ID;const jobs=(await db.query("UPDATE gap_report_jobs SET state='failed',failure_code='deadline_or_lease_expired',finished_at=clock_timestamp() WHERE environment_id=$1 AND (state='queued' AND deadline_at<=clock_timestamp() OR state='running' AND (deadline_at<=clock_timestamp() OR lease_until<=clock_timestamp())) RETURNING id",[env])).rows;if(jobs.length)await db.query("UPDATE gap_report_store_objects SET state='purge',purge_at=clock_timestamp() WHERE job_id=ANY($1::uuid[]) AND state='staged'",[jobs.map(j=>j.id)]);return jobs.length;});}
export async function claimGapReportJobs(limit=1):Promise<GapReportJob[]>{if(!Number.isInteger(limit)||limit<1||limit>5)throw Error('Invalid bounded job claim');return withTransaction(async db=>{await requireGapSchema(db,false,true);if(!gapProseEnabled())return [];const token=randomUUID();return (await db.query<GapReportJob>("WITH claimed AS(SELECT id FROM gap_report_jobs WHERE environment_id=$1 AND state='queued' AND deadline_at>clock_timestamp() ORDER BY created_at,id LIMIT $2 FOR UPDATE SKIP LOCKED) UPDATE gap_report_jobs j SET state='running',lease_token=$3,lease_until=LEAST(j.deadline_at,clock_timestamp()+interval '30 seconds') WHERE j.id IN(SELECT id FROM claimed) RETURNING j.*",[getServerConfig().TURAS_ENVIRONMENT_ID,limit,token])).rows;});}
async function jobActor(db:PoolClient,job:GapReportJob):Promise<GapActor>{const row=(await db.query("SELECT m.principal_id,m.id AS membership_id,m.workspace_id,m.kind,m.role,p.login_name,p.display_name,s.expires_at FROM memberships m JOIN principals p ON p.id=m.principal_id JOIN login_sessions s ON s.id=$2 AND s.principal_id=p.id WHERE m.id=$1 AND m.workspace_id=$3 AND m.active AND p.active AND s.revoked_at IS NULL AND s.expires_at>clock_timestamp()",[job.actor_membership_id,job.session_id,job.workspace_id])).rows[0];if(!row)throw new HttpFailure(401,'unauthorized','Submitting session unavailable');return {principalId:row.principal_id,membershipId:row.membership_id,workspaceId:row.workspace_id,kind:row.kind,role:row.role,loginName:row.login_name,displayName:row.display_name,sessionId:job.session_id,token:'',expiresAt:row.expires_at};}
async function exactJob(db:PoolClient,job:GapReportJob,lock=false){const row=(await db.query('SELECT j.*,p.content FROM gap_report_jobs j LEFT JOIN gap_report_job_payloads p ON p.job_id=j.id WHERE j.id=$1 AND j.environment_id=$2 AND j.workspace_id=$3 '+(lock?'FOR UPDATE OF j':''),[job.id,getServerConfig().TURAS_ENVIRONMENT_ID,job.workspace_id])).rows[0];if(!row||row.state!=='running'||row.lease_token!==job.lease_token||row.deadline_at.getTime()<=Date.now()||row.lease_until.getTime()<=Date.now()||!row.content)throw new HttpFailure(409,'preparation_unavailable','Preparation expired or cancelled');return row;}
export async function runGapReportJob(job:GapReportJob,hooks:{beforeFinalize?:()=>Promise<void>}={}){if(hooks.beforeFinalize&&process.env.TURAS_GAPS_OWNED!=='1')throw Error('Fault injection requires owned synthetic runner');if(job.environment_id!==getServerConfig().TURAS_ENVIRONMENT_ID)throw Error('Foreign report job');try{
 const captured=await withTransaction(async db=>{const actor=await jobActor(db,job);await lockGapActor(db,actor,false,true);await requireGapSchema(db,true,true);const current=await exactJob(db,job),payload=current.content,input=gapReportPrepareSchema.parse(payload.input),snapshot=await captureGapReport(db,actor,input,job.report_id,payload.revisionId,payload.preparedAt,payload.preparer);if(gapHash(snapshot.binding)!==payload.bindingDigest)throw new HttpFailure(409,'stale_version','Admitted report snapshot changed');return {actor,input,payload,snapshot};});
 const bytes=gapReportBytes(captured.snapshot.document),objects:{key:string;format:'markdown'|'json';digest:string;size:number}[]=[];for(const format of ['markdown','json'] as const){const buffer=bytes[format],digest=createHash('sha256').update(buffer).digest('hex'),key=await withTransaction(async db=>{await requireGapSchema(db,true,true);await exactJob(db,job,true);return stageGapObject(db,{workspaceId:job.workspace_id,jobId:job.id,revisionId:captured.payload.revisionId},format,digest,buffer.length);});await writeGapObject(buffer,key);objects.push({key,format,digest,size:buffer.length});}
 await hooks.beforeFinalize?.();
 await withTransaction(async db=>{await lockGapActor(db,captured.actor,false,true);await requireGapSchema(db,true,true);const snapshot=await captureGapReport(db,captured.actor,captured.input,job.report_id,captured.payload.revisionId,captured.payload.preparedAt,captured.payload.preparer);if(gapHash(snapshot.binding)!==captured.payload.bindingDigest)throw new HttpFailure(409,'stale_version','Preparation snapshot changed');const current=await exactJob(db,job,true),report=await reportRow(db,captured.actor,job.report_id,true);if(report.current_job_id!==job.id)throw new HttpFailure(409,'stale_version','Preparation replaced');for(const object of objects)await readGapObject(object.key,object.digest,object.size);if(Date.now()>=current.deadline_at.getTime())throw new HttpFailure(409,'deadline_expired','Preparation deadline expired');const revisionId=captured.payload.revisionId,env=getServerConfig().TURAS_ENVIRONMENT_ID;
  await db.query("INSERT INTO gap_report_revisions(id,report_id,job_id,environment_id,workspace_id,revision_number,author_membership_id,kind,gap_ids,as_of,comparison_at,relation_generation,content_digest,binding_digest,audience_digest,prepared_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16::timestamptz+interval '30 days')",[revisionId,job.report_id,job.id,env,job.workspace_id,Number(report.version),captured.actor.membershipId,captured.input.kind,captured.input.gapIds,captured.input.asOf,captured.input.comparisonAt,snapshot.relationGeneration,gapHash(snapshot.document),captured.payload.bindingDigest,gapHash(captured.input.audience),captured.payload.preparedAt]);await db.query('INSERT INTO gap_report_revision_payloads(revision_id,content) VALUES($1,$2)',[revisionId,JSON.stringify({input:captured.input,preparer:captured.payload.preparer,document:snapshot.document})]);await db.query('INSERT INTO gap_report_revision_states(revision_id) VALUES($1)',[revisionId]);
  await db.query('INSERT INTO gap_report_dependencies(id,report_revision_id,customer_id,source_kind,source_revision_id,source_generation,source_digest) SELECT gen_random_uuid(),$2,x."customerId",x.kind,x."revisionId",x.generation,x."contentDigest" FROM jsonb_to_recordset($1::jsonb) AS x("customerId" uuid,kind text,"revisionId" uuid,generation bigint,"contentDigest" text)',[JSON.stringify(snapshot.dependencies),revisionId]);
  for(const object of objects){await db.query('INSERT INTO gap_export_artifacts(id,revision_id,report_id,environment_id,workspace_id,format,object_key,content_digest,size_bytes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),revisionId,job.report_id,env,job.workspace_id,object.format,object.key,object.digest,object.size]);await db.query("UPDATE gap_report_store_objects SET state='attached' WHERE object_key=$1 AND state='staged'",[object.key]);}
  await db.query("UPDATE gap_report_jobs SET state='prepared',finished_at=clock_timestamp() WHERE id=$1",[job.id]);await db.query('UPDATE gap_reports SET current_revision_id=$2,version=version+1 WHERE id=$1',[job.report_id,revisionId]);
 });
 }catch(error){const code=error instanceof HttpFailure?error.code:'preparation_failed';await withTransaction(async db=>{const changed=await db.query("UPDATE gap_report_jobs SET state='failed',failure_code=$3,finished_at=clock_timestamp() WHERE id=$1 AND environment_id=$2 AND state='running' AND lease_token=$4 RETURNING id",[job.id,getServerConfig().TURAS_ENVIRONMENT_ID,code,job.lease_token]);if(changed.rowCount)await db.query("UPDATE gap_report_store_objects SET state='purge',purge_at=clock_timestamp() WHERE job_id=$1 AND state='staged'",[job.id]);});}
}
