import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {gapReportPrepareSchema,gapCancelSchema,type GapContent,type GapImpactContent,type GapSource} from '../../contracts/product-gaps';
import {HttpFailure,hiddenRecord} from '../../contracts/http';
import {composeGapReport,type GapReportDocument,type GapReportSnapshot} from '../../product-gaps/report-document';
import {compareGapRank} from '../../product-gaps/ranking';
import {getServerConfig} from '../config';
import {gapCommand,gapRead,gapHash} from './commands';
import {type GapActor,requireGapReviewer,isGapReviewer} from './policy';
import {gapExpected,revisionHeader} from './repository';
import {gapCountMetadata} from './counts';
import {gapRankingFactors} from './ranking';
import {projectGapRevision} from './projection';
import {gapDependencyUnion} from './dependencies';
import {readGapSourcePassages} from './sources';
import {requireGapStore} from './store';
import {gapHandoffRows,gapHandoffSourceRefs,projectGapHandoffs} from './handoffs';
import {gapProseEnabled} from './schema';
export type ReportInput=ReturnType<typeof gapReportPrepareSchema.parse>;
export async function reportRow(db:PoolClient,actor:GapActor,id:string,lock=false){const row=(await db.query('SELECT * FROM gap_reports WHERE id=$1 AND environment_id=$2 AND workspace_id=$3 '+(lock?'FOR UPDATE':''),[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0];if(!row)throw hiddenRecord();return row;}
export async function captureGapReport(db:PoolClient,actor:GapActor,input:ReportInput,reportId:string,revisionId:string,preparedAt:string,preparer:string,additionalRefs:GapSource[]=[]){
 const counts=await gapCountMetadata(db,actor,input.gapIds,new Date(input.asOf),additionalRefs,input.comparisonAt?new Date(input.comparisonAt):undefined),gaps:GapReportSnapshot['gaps']=[],allRefs=[],customerIds=new Set<string>();
 for(const item of counts.items){if(!item.record.reviewed_revision_id||!item.eligible)throw new HttpFailure(409,'source_unavailable','Every selected gap requires current reviewed evidence');if(input.kind==='portfolio'&&item.head?.fields.kind!=='product_gap')throw new HttpFailure(400,'invalid_input','Portfolio requires product gaps');if(item.comparisonAvailability==='unavailable')throw new HttpFailure(409,'history_unavailable','Required historical impact is unavailable');const revision=await projectGapRevision(db,actor,item.record.reviewed_revision_id,false);if(revision?.availability!=='eligible')throw new HttpFailure(409,'source_unavailable','Reviewed gap unavailable');const refs=new Map(revision.sourceRefs.map(r=>[r.id+':'+r.purpose,r])),impacts:GapReportSnapshot['gaps'][number]['impacts']=[];
  for(const observation of item.eligibleImpacts){const projected=await projectGapRevision(db,actor,observation.revisionId,false);if(projected?.availability!=='eligible')throw new HttpFailure(409,'source_unavailable','Impact changed during snapshot');const content=projected.content as GapImpactContent;customerIds.add(observation.customerId);for(const ref of projected.sourceRefs)refs.set(ref.id+':'+ref.purpose,ref);impacts.push({id:observation.id,revisionId:projected.id,customerId:observation.customerId,classification:content.classification,content,sourceRefs:projected.sourceRefs});}
  const selected=[...refs.values()];allRefs.push(...selected);for(const ref of selected)if(ref.customerId)customerIds.add(ref.customerId);
  const lineage=(await db.query('SELECT d.id,d.operation,d.relation_generation,d.created_at FROM gap_canonicalization_decisions d WHERE d.environment_id=$1 AND d.workspace_id=$2 AND d.created_at<=$4 AND EXISTS(SELECT 1 FROM gap_assignment_events e WHERE e.decision_id=d.id AND e.canonical_gap_id=$3) ORDER BY d.created_at,d.id LIMIT 1001',[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,item.id,preparedAt])).rows;if(lineage.length>1000)throw new HttpFailure(413,'scope_too_large','Relation history exceeds limit');
  const handoffHistory=(await db.query('SELECT h.id,h.kind,h.event_at,h.created_at,h.actor_membership_id,h.predecessor_id,h.corrected_id FROM gap_handoff_receipts h JOIN gap_report_revisions r ON r.id=h.revision_id WHERE h.environment_id=$1 AND h.workspace_id=$2 AND $3=ANY(r.gap_ids) AND h.created_at<=$4 AND h.event_at<=$4 ORDER BY h.created_at,h.id LIMIT 1001',[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,item.id,preparedAt])).rows;if(handoffHistory.length>1000)throw new HttpFailure(413,'scope_too_large','Engineering handoff history exceeds limit');
  gaps.push({id:item.id,revisionId:revision.id,content:revision.content as GapContent,disposition:item.record.disposition,revisitAt:item.record.revisit_at?.toISOString()??null,counts:{confirmed:item.confirmed,suspectedOnly:item.suspectedOnly,resolvedHistory:item.resolvedHistory},comparison:item.comparison,ranking:gapRankingFactors(item.record,revision.content as GapContent,item.confirmed,new Date(preparedAt)),impacts,sources:await readGapSourcePassages(db,actor,selected,new Date(preparedAt)),lineage,handoffs:handoffHistory.map(h=>({id:h.id,kind:h.kind,eventAt:h.event_at.toISOString(),recordedAt:h.created_at.toISOString(),reporterMembershipId:h.actor_membership_id,predecessorId:h.predecessor_id,correctedId:h.corrected_id,classification:'human_reported',payload:'Response prose omitted; this is historical metadata, not customer resolution evidence.'}))});
 }
 if(customerIds.size>200)throw new HttpFailure(413,'scope_too_large','Report customer scope exceeds limit');const dependencies=await gapDependencyUnion(db,actor,allRefs,2000);
 const labels=(await db.query('SELECT id,display_name FROM customer_references WHERE id=ANY($1::uuid[]) AND workspace_id=$2 ORDER BY id',[[...customerIds],actor.workspaceId])).rows;if(labels.length!==customerIds.size)throw hiddenRecord();gaps.sort((a,b)=>compareGapRank(a.ranking.factors,b.ranking.factors));
 const relationGeneration=Number((await db.query('SELECT relation_generation FROM gap_workspace_state WHERE environment_id=$1 AND workspace_id=$2',[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0].relation_generation),document=composeGapReport({reportId,revisionId,kind:input.kind,preparedAt,asOf:input.asOf,comparisonAt:input.comparisonAt,audience:input.audience,preparer,customers:labels.map(c=>({id:c.id,name:c.display_name})),gaps}),binding={inputDigest:gapHash(input),relationGeneration,countGeneration:counts.generation,dependencyDigest:gapHash(dependencies),contentDigest:gapHash(document)};
 return {document,binding,dependencies,relationGeneration};
}
export function prepareGapReport(actor:GapActor,raw:unknown){const input=gapReportPrepareSchema.parse(raw);return gapCommand(actor,'prepare_report',input,async db=>{const admittedAt=Date.now(),env=getServerConfig().TURAS_ENVIRONMENT_ID;await requireGapStore();await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`gap-report-admission:${env}:${actor.workspaceId}`]);const active=(await db.query("SELECT actor_membership_id FROM gap_report_jobs WHERE environment_id=$1 AND workspace_id=$2 AND state IN('queued','running')",[env,actor.workspaceId])).rows;if(active.some(j=>j.actor_membership_id===actor.membershipId)||active.length>=5)throw new HttpFailure(409,'preparation_busy','Engineering report preparation is busy');let reportId=input.reportId,version=1;if(reportId){const prior=await reportRow(db,actor,reportId);gapExpected(prior.version,input.expectedVersion);if(prior.creator_membership_id!==actor.membershipId)throw hiddenRecord();version=Number(prior.version)+1;}else{gapExpected(0,input.expectedVersion);reportId=randomUUID();}
 const revisionId=randomUUID(),preparedAt=new Date(admittedAt).toISOString(),snapshot=await captureGapReport(db,actor,input,reportId,revisionId,preparedAt,actor.displayName);if(Date.now()>=admittedAt+30000)throw new HttpFailure(409,'deadline_expired','Engineering report deadline expired');
 if(input.reportId){const locked=await reportRow(db,actor,reportId,true);gapExpected(locked.version,input.expectedVersion);await db.query('UPDATE gap_reports SET version=$2,approved_review_id=NULL,current_revision_id=NULL WHERE id=$1',[reportId,version]);}else await db.query('INSERT INTO gap_reports(id,environment_id,workspace_id,creator_membership_id) VALUES($1,$2,$3,$4)',[reportId,env,actor.workspaceId,actor.membershipId]);const jobId=randomUUID();await db.query('INSERT INTO gap_report_jobs(id,report_id,environment_id,workspace_id,actor_membership_id,session_id,input_digest,deadline_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[jobId,reportId,env,actor.workspaceId,actor.membershipId,actor.sessionId,gapHash(input),new Date(admittedAt+30000)]);await db.query('INSERT INTO gap_report_job_payloads(job_id,content) VALUES($1,$2)',[jobId,JSON.stringify({input,preparer:actor.displayName,revisionId,preparedAt,bindingDigest:gapHash(snapshot.binding)})]);await db.query('UPDATE gap_reports SET current_job_id=$2 WHERE id=$1',[reportId,jobId]);return {recordId:reportId,resultId:jobId,outcome:'queued',version};},{reports:true});}
export async function currentGapReport(db:PoolClient,actor:GapActor,id:string,additionalRefs:GapSource[]=[]){const report=await reportRow(db,actor,id);const revision=report.current_revision_id?(await db.query('SELECT r.*,s.generation,s.invalidated_at,s.purge_at,p.content FROM gap_report_revisions r JOIN gap_report_revision_states s ON s.revision_id=r.id LEFT JOIN gap_report_revision_payloads p ON p.revision_id=r.id WHERE r.id=$1',[report.current_revision_id])).rows[0]:null;if(!revision)return {report,revision:null,document:null as GapReportDocument|null,availability:'unprepared' as string};if(!gapProseEnabled())return {report,revision,document:null as GapReportDocument|null,availability:'disabled'};if(!revision.content||revision.expires_at.getTime()<=Date.now())return {report,revision,document:null as GapReportDocument|null,availability:'expired'};if(revision.invalidated_at||revision.purge_at&&revision.purge_at.getTime()<=Date.now())return {report,revision,document:null as GapReportDocument|null,availability:'withheld'};
 try{const input=gapReportPrepareSchema.parse(revision.content.input),current=await captureGapReport(db,actor,input,id,revision.id,revision.prepared_at.toISOString(),revision.content.preparer,additionalRefs);const fenced=(await db.query('SELECT s.generation,s.invalidated_at,s.purge_at,p.content FROM gap_report_revision_states s JOIN gap_report_revision_payloads p ON p.revision_id=s.revision_id WHERE s.revision_id=$1 FOR SHARE OF s,p',[revision.id])).rows[0];if(!fenced||fenced.invalidated_at||fenced.purge_at&&fenced.purge_at.getTime()<=Date.now()||String(fenced.generation)!==String(revision.generation))throw new HttpFailure(409,'source_unavailable','Report payload changed');if(gapHash(current.binding)!==revision.binding_digest||gapHash(revision.content.document)!==revision.content_digest||gapHash(current.document)!==revision.content_digest)throw new HttpFailure(409,'source_unavailable','Engineering report snapshot changed');return {report,revision,document:current.document,availability:'eligible'};}catch(error){if(!(error instanceof HttpFailure)||![400,404,409,413,422].includes(error.status))throw error;return {report,revision,document:null as GapReportDocument|null,availability:'withheld'};}
}
export function readGapReport(actor:GapActor,id:string){return gapRead(actor,async db=>{const handoffRows=await gapHandoffRows(db,actor,id),handoffRefs=await gapHandoffSourceRefs(db,actor,handoffRows),current=await currentGapReport(db,actor,id,handoffRefs),{report,revision,document}=current,job=report.current_job_id?(await db.query('SELECT id,state,deadline_at,failure_code FROM gap_report_jobs WHERE id=$1',[report.current_job_id])).rows[0]:null,review=report.approved_review_id?(await db.query('SELECT id,action,reviewer_membership_id,created_at,audience_digest,binding_digest FROM gap_report_reviews WHERE id=$1',[report.approved_review_id])).rows[0]:null,artifacts=revision?(await db.query('SELECT id,format,content_digest,size_bytes FROM gap_export_artifacts WHERE revision_id=$1 ORDER BY format',[revision.id])).rows:[];return {id:report.id,version:Number(report.version),reviewer:isGapReviewer(actor),canCancel:report.creator_membership_id===actor.membershipId&&['queued','running'].includes(job?.state),commandNamespace:gapHash([getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId,actor.sessionId]),scopeGeneration:gapHash([report.version,revision?.generation??null,current.availability,review?.id??null,handoffRows.map(h=>[h.id,h.generation,h.invalidated_at,h.purge_at,h.release_candidate??false])]),availability:current.availability,job:job?{id:job.id,state:String(job.state),deadlineAt:job.deadline_at.toISOString(),failureCode:job.failure_code}:null,revision:revision?{id:revision.id,contentDigest:revision.content_digest,audienceDigest:revision.audience_digest,preparedAt:revision.prepared_at.toISOString(),expiresAt:revision.expires_at.toISOString()}:null,document,artifacts:artifacts.map(a=>({id:a.id,format:a.format,contentDigest:a.content_digest,sizeBytes:Number(a.size_bytes)})),handoffs:await projectGapHandoffs(db,actor,handoffRows,current.availability==='eligible',report.approved_review_id),review:review?{id:review.id,action:review.action,reviewerMembershipId:review.reviewer_membership_id,approvedAt:review.created_at.toISOString(),audienceDigest:review.audience_digest}:null};},true);}
export function cancelGapReport(actor:GapActor,id:string,raw:unknown){const input=gapCancelSchema.parse(raw);return gapCommand(actor,'cancel_report',{...input,reportId:id},async db=>{const report=await reportRow(db,actor,id,true);gapExpected(report.version,input.expectedVersion);if(input.exportId){requireGapReviewer(actor);const exported=await db.query("UPDATE gap_export_receipts SET state='cancelled',version=version+1,lease_until=NULL WHERE id=$1 AND report_id=$2 AND environment_id=$3 AND workspace_id=$4 AND actor_membership_id=$5 RETURNING version",[input.exportId,id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,actor.membershipId]);if(!exported.rowCount)throw hiddenRecord();return {recordId:id,resultId:input.exportId,outcome:'cancelled',version:Number(exported.rows[0].version)};}if(report.creator_membership_id!==actor.membershipId)throw hiddenRecord();await db.query("UPDATE gap_report_jobs SET state='cancelled',cancelled_at=clock_timestamp(),finished_at=clock_timestamp() WHERE id=$1 AND state IN('queued','running')",[report.current_job_id]);await db.query("UPDATE gap_report_store_objects SET state='purge',purge_at=clock_timestamp() WHERE job_id=$1 AND state='staged'",[report.current_job_id]);return {recordId:id,resultId:report.current_job_id,outcome:'cancelled',version:Number(report.version)};},{reports:true,cancel:true});}
