import type { PoolClient } from 'pg';
import { randomUUID } from 'node:crypto';
import { hiddenRecord,HttpFailure } from '../../contracts/http';
import type { GapActor } from './policy';
import type { GapSource } from '../../contracts/product-gaps';
import type { GapDependency } from './dependencies';
import { getServerConfig } from '../config';
import { gapHash } from './commands';
import { persistGapDependencies } from './sources';
export type GapRow={id:string;environment_id:string;workspace_id:string;creator_membership_id:string;version:string;working_revision_id:string|null;reviewed_revision_id:string|null;disposition:'open'|'deferred'|'dismissed';revisit_at:Date|null;canonical_state:'active'|'redirected';canonical_target:string|null;last_review_at:Date|null;created_at:Date};
export type ImpactRow={id:string;original_gap_id:string;customer_id:string;workload_id:string|null;engagement_id:string|null;recurrence_parent:string|null;creator_membership_id:string;working_revision_id:string|null;reviewed_revision_id:string|null;version:string;state:'active'|'retired';created_at:Date;canonical_gap_id:string};
export async function gapRow(db:PoolClient,actor:GapActor,id:string,lock:false|true|'share'=false):Promise<GapRow>{const row=(await db.query<GapRow>(`SELECT * FROM product_gaps WHERE id=$1 AND environment_id=$2 AND workspace_id=$3 ${lock==='share'?'FOR SHARE':lock?'FOR UPDATE':''}`,[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0];if(!row)throw hiddenRecord();return row;}
export async function impactRow(db:PoolClient,actor:GapActor,gapId:string,id:string,lock:false|true|'share'=false):Promise<ImpactRow>{const row=(await db.query<ImpactRow>(`SELECT o.*,a.canonical_gap_id FROM gap_impact_observations o JOIN gap_observation_assignments a ON a.observation_id=o.id WHERE o.id=$1 AND a.canonical_gap_id=$2 AND o.environment_id=$3 AND o.workspace_id=$4 ${lock==='share'?'FOR SHARE OF o':lock?'FOR UPDATE OF o':''}`,[id,gapId,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0];if(!row)throw hiddenRecord();return row;}
export function gapExpected(actual:string|number,expected:number){if(Number(actual)!==expected)throw new HttpFailure(409,'stale_version','Record changed; refresh before deciding');}
export type GapPayload={content:unknown;sourceRefs:GapSource[]};
export type RevisionHeader={id:string;gap_id:string;impact_id:string|null;author_membership_id:string;created_at:Date;content_digest:string;source_digest:string;content:GapPayload|null;invalidated_at:Date|null;purge_at:Date|null;generation:string};
export async function revisionHeader(db:PoolClient,actor:GapActor,id:string):Promise<RevisionHeader>{const row=(await db.query<RevisionHeader>('SELECT r.*,p.content,s.invalidated_at,s.purge_at,s.generation FROM gap_revisions r JOIN gap_revision_states s ON s.revision_id=r.id LEFT JOIN gap_revision_payloads p ON p.revision_id=r.id WHERE r.id=$1 AND r.environment_id=$2 AND r.workspace_id=$3',[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0];if(!row)throw hiddenRecord();return row;}
export async function insertGapRevision(db:PoolClient,actor:GapActor,gapId:string,impactId:string|null,content:unknown,refs:GapSource[],dependencies:GapDependency[],number:number){const id=randomUUID();await db.query('INSERT INTO gap_revisions(id,environment_id,workspace_id,gap_id,impact_id,revision_number,author_membership_id,content_digest,source_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,gapId,impactId,number,actor.membershipId,gapHash(content),gapHash(dependencies)]);await db.query('INSERT INTO gap_revision_payloads(revision_id,content) VALUES($1,$2)',[id,JSON.stringify({content,sourceRefs:refs})]);await db.query('INSERT INTO gap_revision_states(revision_id) VALUES($1)',[id]);await persistGapDependencies(db,id,refs,dependencies);return id;}
export async function gapAudit(db:PoolClient,actor:GapActor,id:string,content:unknown){await db.query('INSERT INTO gap_audit_payloads(id,environment_id,workspace_id,content) VALUES($1,$2,$3,$4)',[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,JSON.stringify(content)]);}
