import { randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { gapPreviewSchema,gapCommitSchema,type GapContent,type GapImpactContent } from '../../contracts/product-gaps';
import { HttpFailure } from '../../contracts/http';
import { getServerConfig } from '../config';
import { requireGapReviewer,type GapActor } from './policy';
import { gapCommand,gapHash } from './commands';
import { gapRow,impactRow,revisionHeader,gapExpected,gapAudit } from './repository';
import { projectGapRevision } from './projection';
import { lockGapSourceUnion,verifyGapSources,gapConfirmationChecks } from './sources';
import { saveGapPreview,loadGapPreview } from './previews';
import { invalidateGapReports } from './invalidation';
type DecisionInput=ReturnType<typeof gapPreviewSchema.parse>;
async function decisionBinding(db:PoolClient,actor:GapActor,gapId:string,input:DecisionInput){requireGapReviewer(actor);const gap=await gapRow(db,actor,gapId);if(gap.canonical_state!=='active')throw new HttpFailure(409,'stale_version','Use canonical identity');const target=input.target==='impact'?await impactRow(db,actor,gapId,input.impactId!):gap;gapExpected(target.version,input.expectedVersion);
 const chosen=['accept','reject'].includes(input.action)?target.working_revision_id:target.reviewed_revision_id??target.working_revision_id;if(input.revisionId!==chosen)throw new HttpFailure(409,'stale_version','Select the exact current revision');const header=await revisionHeader(db,actor,input.revisionId);if(header.impact_id!==(input.impactId??null))throw new HttpFailure(409,'stale_version','Revision target changed');
 if(input.action==='accept'&&header.author_membership_id===actor.membershipId&&!input.selfReview)throw new HttpFailure(400,'invalid_input','Explicit self-review acknowledgment required');
 const gapHeader=gap.reviewed_revision_id?await revisionHeader(db,actor,gap.reviewed_revision_id):null;
 const metadataOnly=['defer','dismiss','reopen','retire'].includes(input.action);const refs=metadataOnly?[]:[...(header.content?.sourceRefs??[]),...(input.target==='impact'?gapHeader?.content?.sourceRefs??[]:[])];await lockGapSourceUnion(db,actor,refs,400);
 const revision=metadataOnly?null:await projectGapRevision(db,actor,header.id,false,header);if(!metadataOnly&&revision?.availability!=='eligible')throw new HttpFailure(409,'source_unavailable','Exact reviewed evidence unavailable');
 if(input.action==='accept'&&input.target==='impact'){const currentGap=await projectGapRevision(db,actor,gap.reviewed_revision_id,false,gapHeader??undefined);if(currentGap?.availability!=='eligible')throw new HttpFailure(409,'source_unavailable','Current reviewed gap required');const content=revision!.content as GapImpactContent;await gapConfirmationChecks(db,actor,(target as Awaited<ReturnType<typeof impactRow>>).customer_id,content,currentGap.content as GapContent,revision!.sourceRefs,currentGap.sourceRefs);}
 const lockedGap=await gapRow(db,actor,gapId,true);gapExpected(lockedGap.version,Number(gap.version));if(input.target==='impact')gapExpected((await impactRow(db,actor,gapId,input.impactId!,true)).version,input.expectedVersion);
 return {gapId,target:input.target,impactId:input.impactId??null,version:input.expectedVersion,gapVersion:Number(gap.version),revisionId:header.id,reviewedGapId:gap.reviewed_revision_id,sourceDigest:metadataOnly?null:revision!.sourceDigest,relationGeneration:Number((await db.query('SELECT relation_generation FROM gap_workspace_state WHERE environment_id=$1 AND workspace_id=$2',[getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId])).rows[0].relation_generation),actorId:actor.membershipId,sessionId:actor.sessionId,action:input.action,rationaleDigest:gapHash(input.rationale),revisitDate:input.revisitDate,selfReview:input.selfReview,customerIndependentAcknowledgment:input.customerIndependentAcknowledgment??false};
}
export function previewGapDecision(actor:GapActor,gapId:string,raw:unknown){const input=gapPreviewSchema.parse(raw);return gapCommand(actor,'preview_decision',{...input,gapId},async db=>{const binding=await decisionBinding(db,actor,gapId,input),preview=await saveGapPreview(db,actor,'gap_decision',gapId,binding,input);return {recordId:gapId,resultId:preview.id,bindingDigest:preview.digest,outcome:'preview',version:input.expectedVersion};});}
export function commitGapDecision(actor:GapActor,gapId:string,raw:unknown){const command=gapCommitSchema.parse(raw);return gapCommand(actor,'gap_decision',{...command,gapId},async db=>{requireGapReviewer(actor);const preview=await loadGapPreview(db,actor,command.previewId,'gap_decision',gapId,command.bindingDigest),input=gapPreviewSchema.parse(preview.payload);gapExpected(input.expectedVersion,command.expectedVersion);const binding=await decisionBinding(db,actor,gapId,input);if(gapHash(binding)!==command.bindingDigest)throw new HttpFailure(409,'stale_version','Preview inputs changed');const gap=await gapRow(db,actor,gapId,true),id=randomUUID();const disposition=input.target==='gap'?(input.action==='defer'?'deferred':input.action==='dismiss'?'dismissed':input.action==='reopen'?'open':gap.disposition):gap.disposition;const revisit=input.target==='gap'?(input.action==='defer'?input.revisitDate:input.action==='dismiss'||input.action==='reopen'?null:gap.revisit_at):gap.revisit_at;
 const header=await revisionHeader(db,actor,input.revisionId);await db.query('INSERT INTO gap_decisions(id,environment_id,workspace_id,gap_id,impact_id,revision_id,action,reviewer_membership_id,rationale_digest,binding_digest,disposition,revisit_at,self_review,customer_independent_acknowledgment,reviewed_gap_revision_id,reviewed_kind,reviewed_product_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)',[id,getServerConfig().TURAS_ENVIRONMENT_ID,actor.workspaceId,header.gap_id,input.impactId??null,input.revisionId,input.action,actor.membershipId,gapHash(input.rationale),command.bindingDigest,disposition,revisit,input.selfReview,input.target==='gap'&&input.action==='accept'&&Boolean(input.customerIndependentAcknowledgment),input.target==='impact'&&input.action==='accept'?gap.reviewed_revision_id:null,input.target==='impact'&&input.action==='accept'?((await revisionHeader(db,actor,gap.reviewed_revision_id!)).content!.content as GapContent).kind:null,input.target==='impact'&&input.action==='accept'?((await revisionHeader(db,actor,gap.reviewed_revision_id!)).content!.content as GapContent).productKey:null]);await gapAudit(db,actor,id,{rationale:input.rationale});
 let version;
 if(input.target==='gap'){version=Number(gap.version)+1;await db.query('UPDATE product_gaps SET reviewed_revision_id=CASE WHEN $2=\'accept\' THEN $3 ELSE reviewed_revision_id END,disposition=$4,revisit_at=$5,version=$6,last_review_at=clock_timestamp() WHERE id=$1',[gapId,input.action,input.revisionId,disposition,revisit,version]);}
 else{const impact=await impactRow(db,actor,gapId,input.impactId!,true);version=Number(impact.version)+1;await db.query('UPDATE gap_impact_observations SET reviewed_revision_id=CASE WHEN $2=\'accept\' THEN $3 ELSE reviewed_revision_id END,state=CASE WHEN $2=\'retire\' THEN \'retired\' ELSE state END,version=$4 WHERE id=$1',[input.impactId,input.action,input.revisionId,version]);await db.query('UPDATE product_gaps SET version=version+1 WHERE id=$1',[gapId]);}
 if(input.action!=='reject')await invalidateGapReports(db,[gapId]);return {recordId:gapId,resultId:id,outcome:input.action,version};});}
