import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {verifyExpansionActualReview} from '../../scripts/expansion-review-contract';
import {verifyExpansionCapture} from '../../scripts/verify-expansion-review';
import {expansionLiveBudgetSchema,expansionLivePricing,expansionCaseReservation,admitExpansionLiveCase} from '../../scripts/expansion-live-budget';
import {expansionEvaluationCases,expansionReviewCriteria} from '../fixtures/expansion/evaluation';
import {discoveryHypothesis} from '../fixtures/expansion';
import {expansionHash} from '../../lib/server/expansion/commands';
function example(){const digest='a'.repeat(64),input={request:{selectedHypothesisIds:[]},snapshot:{snapshot:{currentDate:new Date().toISOString().slice(0,10)}}},output={contractVersion:'expansion-advice-v1',summary:'Synthetic bounded discovery',facts:[],unknowns:[{text:'Operating need',reason:'Not evidenced'}],discoverySteps:[],proposals:[{content:discoveryHypothesis(),citationKeys:[],relatedHypothesisIds:[]}]};const captures=expansionEvaluationCases.map((scenario,index)=>({version:'expansion-live-capture-v1',caseId:scenario.id,attemptId:randomUUID(),sourceDigest:digest,rootAgentDigest:digest,promptDigest:digest,cohortDigest:digest,model:'synthetic-only-test-identity',actualConfiguredProvider:true,input,sourceMap:[],output:index===7?null:output,terminalState:index===7?'invalidated':'completed',released:index!==7,initialDispatches:1,automaticPaidRetries:0,paidSteps:1,inputTokens:1,outputTokens:1,outputTokensByStep:[1],costUsd:.01,latencyMs:1,providerMetadataComplete:true,domainUnchanged:true,staleSuggestionSaveDenied:index===7}));const review={version:'expansion-output-review-v1',sourceDigest:digest,rootAgentDigest:digest,promptDigest:digest,cohortDigest:digest,model:'synthetic-only-test-identity',actualConfiguredProvider:true,budgetUsd:10,reviewer:'Synthetic structural verifier fixture; not an actual-output review',reviewedAt:new Date().toISOString(),cases:captures.map(capture=>({id:capture.caseId,attemptId:capture.attemptId,capturePath:`${capture.caseId}.json`,captureDigest:digest,inputDigest:expansionHash(capture.input),sourceMapDigest:expansionHash(capture.sourceMap),outputDigest:capture.output?expansionHash(capture.output):null,...Object.fromEntries(['terminalState','released','initialDispatches','automaticPaidRetries','paidSteps','inputTokens','outputTokens','costUsd','latencyMs','providerMetadataComplete','domainUnchanged','staleSuggestionSaveDenied'].map(key=>[key,capture[key as keyof typeof capture]])),review:expansionReviewCriteria.map(criterion=>({criterion,passed:true,rationale:'Explicitly synthetic structural fixture; semantic review is not established'}))}))};return {review,captures};}
describe('Expansion actual capture verifier and live admission guards',()=>{
 it('matches a complete synthetic structural cohort without claiming actual semantic evidence',()=>{const f=example(),review=verifyExpansionActualReview(f.review);f.captures.forEach((capture,index)=>expect(verifyExpansionCapture(capture,review,index).caseId).toBe(review.cases[index].id));});
 it.each(['actualConfiguredProvider','providerMetadataComplete','domainUnchanged'] as const)('rejects absent required actual evidence: %s',key=>{const f=example();const review=verifyExpansionActualReview(f.review);expect(()=>verifyExpansionCapture({...f.captures[0],[key]:false},review,0)).toThrow();});
 it('rejects missing or reordered cases and repeated attempts',()=>{const f=example();expect(()=>verifyExpansionActualReview({...f.review,cases:f.review.cases.slice(1)})).toThrow();const cases=[...f.review.cases];[cases[0],cases[1]]=[cases[1],cases[0]];expect(()=>verifyExpansionActualReview({...f.review,cases})).toThrow();f.review.cases[1].attemptId=f.review.cases[0].attemptId;expect(()=>verifyExpansionActualReview(f.review)).toThrow();});
 it('requires each independent rubric decision and a rationale',()=>{const f=example();f.review.cases[0].review.pop();expect(()=>verifyExpansionActualReview(f.review)).toThrow();const g=example();g.review.cases[0].review[0].passed=false;expect(()=>verifyExpansionActualReview(g.review)).toThrow();const h=example();h.review.cases[0].review[0].rationale='';expect(()=>verifyExpansionActualReview(h.review)).toThrow();});
 it('rejects output/usage/attempt/model/source tampering',()=>{const f=example(),review=verifyExpansionActualReview(f.review);for(const change of [{attemptId:randomUUID()},{model:'changed'},{sourceDigest:'b'.repeat(64)},{costUsd:.02},{outputTokens:2},{output:{summary:'Changed output'}}])expect(()=>verifyExpansionCapture({...f.captures[0],...change},review,0)).toThrow();});
 it('does not accept a withheld changed-owner output or omit stale-save denial',()=>{const f=example();Object.assign(f.review.cases[7],{staleSuggestionSaveDenied:false});expect(()=>verifyExpansionActualReview(f.review)).toThrow();const g=example();g.review.cases[7].outputDigest='b'.repeat(64);expect(()=>verifyExpansionActualReview(g.review)).toThrow();});
 it('validates actual citation mapping, not only result JSON shape',()=>{const f=example(),capture=f.captures[0],key=randomUUID();capture.output!.facts=[{classification:'attributed_observation',statement:'Invented citation',citationKeys:[key]}] as never;f.review.cases[0].outputDigest=expansionHash(capture.output);expect(()=>verifyExpansionCapture(capture,verifyExpansionActualReview(f.review),0)).toThrow();});
 it('requires positive finite operator budgets and stops on unknown cost or insufficient reservation',()=>{for(const value of [0,-1,Infinity,NaN])expect(()=>expansionLiveBudgetSchema.parse(value)).toThrow();expect(()=>admitExpansionLiveCase(10,[null],1)).toThrow();expect(()=>admitExpansionLiveCase(10,[9],2)).toThrow();expect(admitExpansionLiveCase(10,[1],2)).toEqual({spentUsd:1,remainingUsd:9});});
 it('uses highest published rate including context/service tiers and never discounts a reservation',()=>{const price=expansionLivePricing({input:'0.000002',output:'0.000006',input_tiers:[{cost:'0.000004',min:100}],service_tiers:{priority:{input:'0.000005',long_context:{input:'0.000008',output:'0.000024'}}}});expect(price).toEqual({inputUsdPerToken:.000008,outputUsdPerToken:.000024});expect(expansionCaseReservation(price)).toBeGreaterThan(6);expect(()=>expansionLivePricing({input:'unknown',output:'0.1'})).toThrow();});
 it('rejects a review whose observed cumulative cost exceeds operator budget',()=>{const f=example();expect(()=>verifyExpansionActualReview({...f.review,budgetUsd:.01})).toThrow();});
 it('rejects an individual over-limit step even when aggregate usage is below six-step allowance',()=>{
  const f=example();f.captures[0].outputTokens=8193;f.captures[0].outputTokensByStep=[8193];Object.assign(f.review.cases[0],{outputTokens:8193});
  expect(()=>verifyExpansionCapture(f.captures[0],verifyExpansionActualReview(f.review),0)).toThrow();
 });
 it('reserves provider exposure independently of the unenforced requested cap',()=>{
  const reservation=expansionCaseReservation({inputUsdPerToken:.000002,outputUsdPerToken:.000006});
  expect(reservation).toBe(4);expect(()=>admitExpansionLiveCase(3.99,[],reservation)).toThrow();
 });

});
