import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {composeGapReport,type GapReportSnapshot} from '../../lib/product-gaps/report-document';
import {gapReportMarkdown} from '../../lib/product-gaps/report-markdown';
import {gapReportManifest,gapReportBytes} from '../../lib/product-gaps/report-manifest';
import {syntheticGap} from '../fixtures/gaps/ui';
const fixture=(kind:'detail'|'portfolio'='detail'):GapReportSnapshot=>({reportId:randomUUID(),revisionId:randomUUID(),kind,preparedAt:'2026-10-01T12:00:00.000Z',asOf:'2026-10-01T11:59:00.000Z',comparisonAt:null,audience:{team:'Functions engineering',recipients:['Synthetic Engineer'],purpose:'Assess the exact reviewed capability'},preparer:'Synthetic internal member',customers:[],gaps:kind==='detail'?[{id:randomUUID(),revisionId:randomUUID(),content:syntheticGap(),disposition:'open',revisitAt:null,counts:{confirmed:0,suspectedOnly:0,resolvedHistory:0},comparison:null,ranking:{methodVersion:'gap-order-v1',factors:{id:randomUUID(),due:false,severity:'high',confirmed:0,workaround:'limited',lastReviewAt:null},freshness:'review_due'},impacts:[],sources:[],lineage:[],handoffs:[]}]:[]});
describe('Complete deterministic recipient documents',()=>{
 it('preserves all seven detail sections, reviewed fields, unknowns and independent review envelope',()=>{const input=fixture(),document=composeGapReport(input);expect(document.sections.map(s=>s.title)).toEqual(['Problem','Evidence and scope','Impact','Workarounds','Proposed capability','Engineering handoff','Evidence appendix and review']);expect(document.header.templateVersion).toBe('gap-detail-v1');expect(JSON.stringify(document)).toContain(input.gaps[0].content.requestedDecision);expect(JSON.stringify(document)).toContain('Unknown');expect(document.review).toEqual({designatedReviewer:'mcteer',approval:'Approval is verified separately by the digest-matched download receipt'});expect(gapReportManifest(document)).toEqual(document);expect(gapReportMarkdown(document)).toContain('Resolved history is nonadditive');});
 it('retains all five portfolio sections for zero results and does not invent customer totals or ARR',()=>{const document=composeGapReport(fixture('portfolio'));expect(document.sections.map(s=>s.title)).toEqual(['Executive summary','Gap table','Prioritization','Actions','Method and limits']);expect(document.header.selectedGapIds).toEqual([]);expect(JSON.stringify(document)).toContain('No gaps selected');expect(JSON.stringify(document)).not.toMatch(/weightedScore|annualRecurringRevenue|objectKey/);});
 it('supports exactly 100 explicit product gaps and rejects a foreign kind or excessive selection',()=>{const input=fixture('portfolio'),base=fixture().gaps[0];input.gaps=Array.from({length:100},()=>({...base,id:randomUUID(),revisionId:randomUUID()}));expect(composeGapReport(input).header.selectedGapIds).toHaveLength(100);expect(()=>composeGapReport({...input,gaps:[...input.gaps,{...base,id:randomUUID()}]})).toThrow();expect(()=>composeGapReport({...input,gaps:[{...base,content:{...base.content,kind:'defect'}}]})).toThrow();});
 it('rejects missing citation, hidden customer and count/set discrepancies',()=>{const input=fixture(),customerId=randomUUID(),impactId=randomUUID();input.gaps[0].impacts=[{id:impactId,revisionId:randomUUID(),customerId,classification:'suspected',content:{observedAt:null,resolvedAt:null,classification:'suspected',consequences:'Unknown cost',workaroundBurden:'Unknown',severity:'unknown',severityRationale:'Unknown',assertions:[]},sourceRefs:[]}];expect(()=>composeGapReport(input)).toThrow();input.customers=[{id:customerId,name:'Synthetic disclosed account'}];expect(()=>composeGapReport(input)).toThrow();input.gaps[0].counts.suspectedOnly=1;expect(composeGapReport(input).customers).toEqual(input.customers);});
 it('escapes active Markdown/HTML and rejects secret-bearing source URLs without fetching',()=>{const input=fixture();input.gaps[0].content.problem='<script>run()</script> [click](javascript:bad)';const document=composeGapReport(input),markdown=gapReportMarkdown(document);expect(markdown).not.toContain('<script>');expect(markdown).not.toContain('[click](javascript:bad)');const ref={id:randomUUID(),kind:'verified_research' as const,customerId:randomUUID(),sourceRevisionId:randomUUID(),generation:1,contentDigest:'a'.repeat(64),locator:{kind:'research_passage' as const,canonicalUrl:'https://vercel.com/docs?token=secret',start:0,end:1},purpose:'corroboration' as const};input.gaps[0].sources=[{reference:ref,text:'Original',metadata:{}}];input.customers=[{id:ref.customerId,name:'Synthetic account'}];expect(()=>composeGapReport(input)).toThrow();});
 it('emits matching UTF-8 projections within exact byte bounds and stable bytes',()=>{const document=composeGapReport(fixture()),bytes=gapReportBytes(document);expect(JSON.parse(bytes.json.toString())).toEqual(document);expect(bytes.markdown.toString()).toBe(gapReportMarkdown(document));expect(gapReportBytes(document)).toEqual(bytes);expect(bytes.json.length).toBeGreaterThan(0);expect(bytes.json.length).toBeLessThanOrEqual(5*1024*1024);expect(()=>composeGapReport({...fixture(),preparer:'x'.repeat(2*1024*1024)})).toThrow();});
});
