import {describe,it,expect} from 'vitest';
import {impactSets,evidenceFreshness} from '../../lib/product-gaps/impact';
import {compareGapRank} from '../../lib/product-gaps/ranking';
import {canonicalAssignments} from '../../lib/product-gaps/canonical';
describe('Independent customer sets and canonical assignment rules',()=>{
 it('reports conservative source freshness independently of review age',()=>{expect(evidenceFreshness([])).toBe('no_evidence');for(const [values,expected] of [[['Recent'],'recent'],[['Recent','Aging'],'aging'],[['Aging','Unknown'],'unknown'],[['Unknown','Stale'],'stale'],[['Recent','Unavailable'],'unavailable']] as const)expect(evidenceFreshness(values)).toBe(expected);});
 it('deduplicates workloads, suppresses suspected-only and keeps resolved history nonadditive',()=>{const rows=[{customerId:'a',classification:'confirmed'},{customerId:'a',classification:'confirmed'},{customerId:'a',classification:'suspected'},{customerId:'b',classification:'suspected'},{customerId:'a',classification:'resolved'},{customerId:'c',classification:'confirmed',retired:true},{customerId:'d',classification:'confirmed',eligible:false}] as const;expect(impactSets(rows)).toEqual({confirmed:['a'],suspectedOnly:['b'],resolvedHistory:['a'],methodVersion:'gap-impact-v1'});});
 it('orders due, severity, confirmed count, workaround, review time and stable identity in that sequence',()=>{const base={id:'b',due:false,severity:'high' as const,confirmed:2,workaround:'limited' as const,lastReviewAt:'2026-01-01T00:00:00.000Z'};for(const better of [{...base,due:true},{...base,severity:'critical' as const},{...base,confirmed:3},{...base,workaround:'none' as const},{...base,lastReviewAt:null},{...base,id:'a'}])expect(compareGapRank(better,base)).toBeLessThan(0);expect(compareGapRank(base,{...base,due:true,severity:'low',confirmed:0})).toBeGreaterThan(0);});
 it('requires every observation exactly once and rejects foreign, duplicate and missing assignments',()=>{const rows=[{observationId:'a',resultKey:'left'},{observationId:'b',resultKey:'right'}];expect(canonicalAssignments(['a','b'],['left','right'],rows)).toEqual(rows);for(const bad of [rows.slice(0,1),[rows[0],rows[0]], [...rows,{observationId:'c',resultKey:'left'}],[rows[0],{observationId:'b',resultKey:'unknown'}]])expect(()=>canonicalAssignments(['a','b'],['left','right'],bad)).toThrow();});
});
