import { describe,it,expect } from 'vitest';
import { verifyGapTestReport } from '../../scripts/test-gaps';
describe('Gap acceptance coverage',()=>{
 it('refuses empty, skipped, missing and duplicate reports instead of claiming acceptance',()=>{expect(()=>verifyGapTestReport({success:true,testResults:[]},['tests/unit/gap-content.test.ts'])).toThrow();expect(()=>verifyGapTestReport({success:true,testResults:[{name:'/tests/unit/gap-content.test.ts',assertionResults:[{status:'pending'}]}]},['tests/unit/gap-content.test.ts'])).toThrow();expect(verifyGapTestReport({success:true,testResults:[{name:'/tests/unit/gap-content.test.ts',assertionResults:[{status:'passed'}]}]},['tests/unit/gap-content.test.ts'])).toBe(1);});
});

import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {verifyGapSuiteCoverage} from '../../scripts/test-gaps';
import {featureSourceDigest} from '../../scripts/execution-source-digest';
it('detects missing, duplicate and orphan suite files and changed implementation bytes',async()=>{const root=await mkdtemp(join(tmpdir(),'turas-gap-coverage-'));try{for(const group of ['unit','contracts','integration'])await mkdir(join(root,'tests',group),{recursive:true});const path='tests/unit/gap-example.test.ts';await writeFile(join(root,path),'synthetic suite');expect(verifyGapSuiteCoverage(root,[path])).toEqual([path]);expect(()=>verifyGapSuiteCoverage(root,[path,path])).toThrow();expect(()=>verifyGapSuiteCoverage(root,[])).toThrow();expect(()=>verifyGapSuiteCoverage(root,['tests/unit/gap-missing.test.ts'])).toThrow();const before=await featureSourceDigest('012',root);await writeFile(join(root,path),'changed implementation assertion');expect(await featureSourceDigest('012',root)).not.toBe(before);await writeFile(join(root,'tests/unit/gap-orphan.test.ts'),'orphan');expect(()=>verifyGapSuiteCoverage(root,[path])).toThrow();}finally{await rm(root,{recursive:true,force:true});}});

import {verifyGapUiFiles,gapUiProjects,gapUiFailure} from '../../scripts/gaps-ui-check';
it('rejects incomplete or duplicate browser journeys and pins all four WebKit projects',()=>{const files=Array.from({length:6},(_,i)=>'tests/ui/gap-'+i+'.spec.ts');expect(()=>verifyGapUiFiles(files,files)).not.toThrow();expect(()=>verifyGapUiFiles(files.slice(1),files)).toThrow();expect(()=>verifyGapUiFiles(files,[...files.slice(1),files[1]])).toThrow();expect(gapUiProjects).toEqual(['webkit-desktop-light','webkit-desktop-dark','webkit-mobile-light','webkit-mobile-dark']);});

import {verifyExecutionUiReport} from '../../scripts/execution-ui-report';
it('requires every discovered browser case and rejects skipped or different project evidence',()=>{const project=gapUiProjects[0],identity={file:'/synthetic/tests/ui/gap-authoring.spec.ts',id:'synthetic-gap-case',project,line:1},test={projectName:project,projectId:project,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0,errors:[]}]},report={config:{rootDir:'/synthetic'},suites:[{specs:[{id:identity.id,file:identity.file,line:1,ok:true,tests:[test]}]}],errors:[],stats:{expected:1,skipped:0,unexpected:0,flaky:0}};expect(verifyExecutionUiReport(report,[identity]).expected).toBe(1);expect(()=>verifyExecutionUiReport(report,[identity,{...identity,id:'missing-case'}])).toThrow();expect(()=>verifyExecutionUiReport(report,[{...identity,project:gapUiProjects[1]}])).toThrow();expect(()=>verifyExecutionUiReport({...report,stats:{...report.stats,skipped:1}},[identity])).toThrow();expect(()=>verifyExecutionUiReport({...report,suites:[{specs:[{...report.suites[0].specs[0],tests:[{...test,results:[{status:'skipped',retry:0,errors:[]}]}]}]}]},[identity])).toThrow();});

it('keeps private browser errors out of public failure diagnostics',()=>{const sentinel='PRIVATE_BROWSER_PROSE';const result=gapUiFailure({suites:[{specs:[{file:'/synthetic/tests/ui/gap-revocation.spec.ts',line:20,title:sentinel,tests:[{results:[{status:'timedOut',errors:[{message:'Timeout: '+sentinel}]}]}]}]}]});expect(result).toEqual([{file:'gap-revocation.spec.ts',line:20,status:'timedOut',category:'timeout'}]);expect(JSON.stringify(result)).not.toContain(sentinel);const detailed=gapUiFailure({specs:[{file:'gap-reports.spec.ts',line:15,tests:[{results:[{status:'failed',errors:[{message:'locator.fill: Timeout '+sentinel,stack:'/private/'+sentinel+'/gap-reports.spec.ts:15:100'}],stdout:[{text:'GAP_UI_FIXED_DIAGNOSTIC '+JSON.stringify({responses:[{route:'report-detail',method:'GET',status:404,private:sentinel},{route:sentinel,method:'GET',status:200}],signals:[sentinel,'Product gaps are unavailable'],private:sentinel})}]}]}]}]});expect(detailed[0]).toMatchObject({call:'locator.fill',locations:[{file:'gap-reports.spec.ts',line:15,column:100}],diagnostic:{responses:[{route:'report-detail',method:'GET',status:404}],signals:['Product gaps are unavailable']}});expect(JSON.stringify(detailed)).not.toContain(sentinel);});

import {spawn} from 'node:child_process';
import {gapNodeProcess} from '../../scripts/gaps-ui-check';
it('drains a supervised server pipe while awaiting its browser subprocess',async()=>{const root=await mkdtemp(join(tmpdir(),'turas-gap-pipe-')),ready=join(root,'ready');let drained=0;const server=spawn(process.execPath,['--input-type=module','-e',`import {writeFileSync} from 'node:fs';process.stdout.write(Buffer.alloc(8*1024*1024),()=>writeFileSync(process.argv[1],'ready'));`,ready],{stdio:['ignore','pipe','ignore']});server.stdout.on('data',chunk=>{drained+=chunk.length;});try{const run=await gapNodeProcess(['--input-type=module','-e',`import {existsSync} from 'node:fs';while(!existsSync(process.argv[1]))await new Promise(resolve=>setTimeout(resolve,10));console.log('ready');`,ready],5000);expect(run.status).toBe(0);expect(run.stdout.trim()).toBe('ready');expect(drained).toBe(8*1024*1024);}finally{if(server.exitCode===null&&server.signalCode===null){const closed=new Promise<void>(done=>server.once('close',()=>done()));server.kill('SIGKILL');await closed;}await rm(root,{recursive:true,force:true});}});
it('enforces browser subprocess deadline and captured-output bounds',async()=>{const timeout=await gapNodeProcess(['-e','setInterval(()=>{},1000)'],50);expect(timeout.error?.code).toBe('ETIMEDOUT');const overflow=await gapNodeProcess(['-e','process.stdout.write(Buffer.alloc(8192))'],5000,1024);expect(overflow.error?.code).toBe('ENOBUFS');expect(Buffer.byteLength(overflow.stdout)).toBeLessThanOrEqual(1024);});
