import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { syntheticGap,syntheticImpact } from '../fixtures/gaps/ui';
import { gapContentSchema,gapSourcesSchema,gapPreviewSchema,gapImpactContentSchema } from '../../lib/contracts/product-gaps';
import { parseGapImpact } from '../../lib/product-gaps/content';
describe('Gap fields and independent classifications',()=>{
 it('accepts unknown product/version and enforces every required narrative bound',()=>{expect(gapContentSchema.parse(syntheticGap({productKey:'unknown'})).productVersion).toBeNull();for(const field of ['problem','workflow','desiredOutcome','reproduction','constraints','workaround','workaroundLimitations','proposedCapability','alternatives','unknowns','requestedDecision']){expect(gapContentSchema.safeParse({...syntheticGap(),[field]:''}).success).toBe(false);expect(gapContentSchema.safeParse({...syntheticGap(),[field]:'x'.repeat(4001)}).success).toBe(false);}expect(gapContentSchema.safeParse(syntheticGap({title:'x'.repeat(201)})).success).toBe(false);});
 it('retains null observation as unknown and requires dates for confirmation/resolution',()=>{expect(gapImpactContentSchema.parse(syntheticImpact({observedAt:null})).observedAt).toBeNull();expect(gapImpactContentSchema.safeParse(syntheticImpact({observedAt:null,classification:'confirmed'})).success).toBe(false);expect(gapImpactContentSchema.safeParse(syntheticImpact({classification:'resolved',resolvedAt:new Date(0).toISOString()})).success).toBe(false);expect(gapImpactContentSchema.safeParse(syntheticImpact({observedAt:new Date(Date.now()+86400000).toISOString()})).success).toBe(false);});
 it('refuses source-less accepted facts and duplicate reference keys',()=>{expect(()=>parseGapImpact(syntheticImpact({assertions:[{text:'Unsupported claim',classification:'accepted_fact',sourceKeys:[]}]}),[])).toThrow();expect(gapSourcesSchema.safeParse(Array.from({length:51},()=>({}))).success).toBe(false);});
 it('requires explicit future revisit and rejects extra approval claims',()=>{const base={contractVersion:'product-gaps-v1',requestKey:randomUUID(),expectedVersion:1,target:'gap',revisionId:randomUUID(),action:'defer',rationale:'Revisit with current evidence',revisitDate:new Date(Date.now()+86400000).toISOString(),selfReview:false};expect(gapPreviewSchema.safeParse(base).success).toBe(true);expect(gapPreviewSchema.safeParse({...base,revisitDate:new Date(0).toISOString()}).success).toBe(false);expect(gapPreviewSchema.safeParse({...base,approved:true}).success).toBe(false);});
 it('enforces contextual field, criteria and assertion boundaries without accepting commercial fields',()=>{const gap=syntheticGap();for(const field of ['title','capability','triageTeam']){expect(gapContentSchema.safeParse({...gap,[field]:'x'.repeat(200)}).success).toBe(true);expect(gapContentSchema.safeParse({...gap,[field]:'x'.repeat(201)}).success).toBe(false);}expect(gapContentSchema.safeParse({...gap,productVersion:'x'.repeat(101)}).success).toBe(false);expect(gapContentSchema.safeParse({...gap,acceptanceCriteria:[]}).success).toBe(false);expect(gapContentSchema.safeParse({...gap,acceptanceCriteria:Array(21).fill('Criterion')}).success).toBe(false);expect(gapContentSchema.safeParse({...gap,acceptanceCriteria:['x'.repeat(1001)]}).success).toBe(false);expect(gapContentSchema.safeParse({...gap,severityRationale:'x'.repeat(2001)}).success).toBe(false);expect(gapContentSchema.safeParse({...gap,arr:1000000}).success).toBe(false);for(const field of ['consequences','workaroundBurden'])expect(gapImpactContentSchema.safeParse({...syntheticImpact(),[field]:'x'.repeat(4001)}).success).toBe(false);const assertion={text:'Original unknown',classification:'unknown',sourceKeys:[]};expect(gapImpactContentSchema.safeParse({...syntheticImpact(),assertions:Array(21).fill(assertion)}).success).toBe(false);expect(gapImpactContentSchema.safeParse({...syntheticImpact(),assertions:[{...assertion,text:'x'.repeat(2001)}]}).success).toBe(false);expect(gapImpactContentSchema.safeParse({...syntheticImpact(),assertions:[{...assertion,sourceKeys:Array.from({length:21},()=>randomUUID())}]}).success).toBe(false);});

});
