import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {learningActualCaptureSchema,verifyLearningActualCapture,verifyLearningIndependentReview} from '../../scripts/learning-review-contract';
import {learningHash} from '../../lib/server/learning/repository';
import {learningEvaluationCatalogDigest,learningEvaluationRubricDigest,learningEvaluationModelIdentity} from '../../lib/server/learning/evaluation-context';
import {learningEvaluationCases} from '../../lib/learning/evaluation-cases';
const hash='a'.repeat(64);
/** Pure structural verifier input; no actual model or provider proof is claimed. */
function fixture(){const output={kind:'abstain' as const,text:'Bounded structural verifier fixture',citationKeys:[],unknowns:['Unverified synthetic input']},capture=learningActualCaptureSchema.parse({version:'learning-actual-capture-v1',sourceDigest:hash,rootAgentDigest:hash,catalogDigest:learningEvaluationCatalogDigest(),rubricDigest:learningEvaluationRubricDigest(),modelIdentity:learningEvaluationModelIdentity,evaluationId:randomUUID(),budgetId:randomUUID(),budgetMicroUsd:'25000000',priceContract:{version:'learning-price-v1',modelId:'spacexai/grok-4.7',inputMicroUsdPerMillion:'8000000',outputMicroUsdPerMillion:'24000000',providerInputLimit:500000,providerOutputLimit:500000,hardOutputCapIncludesReasoning:true,pricingSource:'https://ai-gateway.vercel.sh/v1/models',outputContractSource:'https://vercel.com/ai-gateway/models/grok-4.7',pricingCaptureDigest:hash,outputContractCaptureDigest:hash,verifiedAt:'2026-10-09T00:00:00Z',expiresAt:'2026-10-10T00:00:00Z'},actualConfiguredProvider:true,complete:true,automaticPaidRetries:0,arms:learningEvaluationCases.flatMap(row=>['evaluation_baseline','evaluation_candidate'].map(purpose=>({caseId:row.id,purpose,attemptId:randomUUID(),nativeSessionId:randomUUID(),nativeTurnId:randomUUID(),output,outputDigest:learningHash(output),contextDigest:hash,rawCaptureDigest:hash,modelSteps:1,readCalls:0,outputTokens:100,durationMs:100,settlement:{kind:'actual',amountMicroUsd:'1000',inputTokens:100,outputTokens:100,providerGenerationId:'unit-structure-'+randomUUID(),ceilingMicroUsd:'16000000'}})))}),review={version:'learning-independent-review-v1',captureDigest:learningHash(capture),sourceDigest:hash,catalogDigest:capture.catalogDigest,rubricDigest:capture.rubricDigest,reviewer:{identity:'Structural unit test only',independent:true,reviewedAt:'2026-10-09T01:00:00Z'},cases:learningEvaluationCases.map(row=>({caseId:row.id,baselineCaptureDigest:learningHash(output),candidateCaptureDigest:learningHash(output),baseline:{fidelity:2,applicability:2,unknownHandling:2,usefulness:1},candidate:{fidelity:2,applicability:2,unknownHandling:2,usefulness:2},safetyPassed:true,citationPassed:true,authorityPassed:true,rationale:'Verifier shape only, not an actual-model quality judgment'}))};return {capture,review};}
describe('independent actual-learning review verifier structure',()=>{
 it('requires sixteen ordered fresh arms and eight exact independent assessments',()=>{const {capture,review}=fixture();expect(verifyLearningIndependentReview(capture,review).verdict).toBe('passed');for(const changed of [{...capture,complete:false},{...capture,actualConfiguredProvider:false},{...capture,arms:capture.arms.slice(1)},{...capture,arms:capture.arms.toReversed()}])expect(()=>verifyLearningActualCapture(changed)).toThrow();expect(()=>verifyLearningIndependentReview(capture,{...review,reviewer:{...review.reviewer,independent:false}})).toThrow();});
 it('rejects reused sessions, changed outputs, tool use and missing accounting',()=>{for(const change of ['session','output','tool','generation','bound','tokens'] as const){const {capture}=fixture();if(change==='session')capture.arms[1].nativeSessionId=capture.arms[0].nativeSessionId;if(change==='output')capture.arms[0].output.text='Changed';if(change==='tool')capture.arms[0].readCalls=1 as 0;if(change==='generation')capture.arms[0].settlement.providerGenerationId=null;if(change==='bound')capture.arms[0].settlement.ceilingMicroUsd='1000';if(change==='tokens')capture.arms[0].settlement.outputTokens=101;expect(()=>verifyLearningActualCapture(capture)).toThrow();}});
 it('enforces all mandatory flags, minimum quality, no regression and an intended improvement',()=>{for(const change of ['safety','citation','authority','low','regression','no_improvement','stale'] as const){const {capture,review}=fixture();if(change==='safety')review.cases[0].safetyPassed=false;if(change==='citation')review.cases[0].citationPassed=false;if(change==='authority')review.cases[0].authorityPassed=false;if(change==='low')review.cases[0].candidate.fidelity=0;if(change==='regression'){review.cases[0].baseline.usefulness=2;review.cases[0].candidate.usefulness=1;}if(change==='no_improvement')review.cases.forEach(row=>row.baseline={...row.candidate});if(change==='stale')review.cases[0].candidateCaptureDigest='b'.repeat(64);expect(()=>verifyLearningIndependentReview(capture,review)).toThrow();}});
 it('accounts for each provider maximum before admission and disallows budgets above the product cap',()=>{const {capture}=fixture();capture.budgetMicroUsd='15999999';expect(()=>verifyLearningActualCapture(capture)).toThrow();capture.budgetMicroUsd='25000001';expect(()=>verifyLearningActualCapture(capture)).toThrow();capture.budgetMicroUsd='25000000';capture.arms[0].settlement.amountMicroUsd='16000000';expect(()=>verifyLearningActualCapture(capture)).toThrow();});
});
