import { describe,it,expect } from "vitest";
import { randomUUID } from "node:crypto";
import { partnerGuideContentSchema,partnerSourceSchema } from "../../lib/contracts/partners";
import { combineSharedEvidenceQuality } from "../../lib/server/knowledge/quality";
function fixture(){const source=randomUUID(),lesson=randomUUID();return {title:"Synthetic guide",lessons:[{id:lesson,order:1,objective:"Objective",what:"What",how:"How",why:"Why",alternatives:"Alternative",limitations:"Limit",validation:"Validate",escalation:"Escalate",prerequisites:[],unknowns:[],sourceIds:[source]}],checkpoints:[{id:randomUUID(),lessonId:lesson,order:1,title:"Checkpoint",criterion:"Demonstrate exact result",required:true,prerequisiteIds:[] as string[],sourceIds:[source]}],sources:[{id:source,kind:"accepted_profile",sourceRevisionId:randomUUID(),generation:1,contentDigest:"a".repeat(64),locator:{kind:"profile_field",fieldPath:"usageDescription"},classification:"customer_fact",observationAt:"2026-10-09T00:00:00.000Z",publicationAt:null,reviewAt:null,quality:{rubricVersion:"evidence-quality-v1" as const,R:4,F:4,D:4,C:2,Q:95,band:"strong" as const,freshness:"Recent" as const,rationale:"Synthetic primary evidence",asOf:"2026-10-09T00:00:00.000Z",validUntil:"2026-10-10T00:00:00.000Z"}}]};}
describe("partner guide content",()=>{
 it("preserves the weakest original shared evidence and never resets its age at publication",()=>{
  const strong=fixture().sources[0].quality,at=new Date(strong.asOf),known=combineSharedEvidenceQuality([strong],at);expect(known.Q).toBe(78);expect(known.D).toBe(3);expect(known.freshness).toBe("Recent");expect(known.validUntil).toBe(strong.validUntil);
  const undated={...strong,F:0,Q:65,freshness:"Unknown" as const};expect(combineSharedEvidenceQuality([strong,undated],at).freshness).toBe("Unknown");const expired=combineSharedEvidenceQuality([strong],new Date("2026-10-11T00:00:00.000Z"));expect(expired.freshness).toBe("Stale");expect(Date.parse(expired.validUntil)).toBeLessThan(Date.parse(expired.asOf));
 });
 it("requires complete bounded structured lessons and exact source descriptors",()=>{expect(partnerGuideContentSchema.safeParse(fixture()).success).toBe(true);const content=fixture();for(const field of ["objective","what","how","why","alternatives","limitations","validation","escalation"]){const copy=structuredClone(content);delete (copy.lessons[0] as unknown as Record<string,unknown>)[field];expect(partnerGuideContentSchema.safeParse(copy).success).toBe(false);}expect(partnerGuideContentSchema.safeParse({...content,privateNote:"PRIVATE"}).success).toBe(false);});
 it("rejects duplicate identity, noncontiguous order, orphan mappings and foreign checkpoints",()=>{const content=fixture();for(const change of [(c:ReturnType<typeof fixture>)=>c.lessons.push(c.lessons[0]),(c:ReturnType<typeof fixture>)=>{c.lessons[0].order=2;},(c:ReturnType<typeof fixture>)=>{c.lessons[0].sourceIds=[randomUUID()];},(c:ReturnType<typeof fixture>)=>{c.checkpoints[0].lessonId=randomUUID();},(c:ReturnType<typeof fixture>)=>{c.sources.push({...c.sources[0],id:randomUUID()});}]){const copy=structuredClone(content);change(copy);expect(partnerGuideContentSchema.safeParse(copy).success).toBe(false);}});
 it("requires a DAG and prevents required checkpoints depending on optional work",()=>{const content=fixture(),first=content.checkpoints[0];content.checkpoints.push({...first,id:randomUUID(),order:2,required:false});first.prerequisiteIds=[content.checkpoints[1].id];expect(partnerGuideContentSchema.safeParse(content).success).toBe(false);content.checkpoints[1].required=true;expect(partnerGuideContentSchema.safeParse(content).success).toBe(true);content.checkpoints[1].prerequisiteIds=[first.id];expect(partnerGuideContentSchema.safeParse(content).success).toBe(false);first.prerequisiteIds=[];content.checkpoints.forEach(c=>c.required=false);expect(partnerGuideContentSchema.safeParse(content).success).toBe(false);});
 it("counts Unicode characters and enforces serialized UTF-8 bytes",()=>{const content=fixture();content.title="😀".repeat(200);expect(partnerGuideContentSchema.safeParse(content).success).toBe(true);content.title+="😀";expect(partnerGuideContentSchema.safeParse(content).success).toBe(false);content.title="Large";content.lessons=Array.from({length:20},(_,n)=>({...content.lessons[0],id:randomUUID(),order:n+1,objective:"😀".repeat(2000),what:"😀".repeat(2000),how:"😀".repeat(2000),why:"😀".repeat(2000)}));content.checkpoints[0].lessonId=content.lessons[0].id;expect(partnerGuideContentSchema.safeParse(content).success).toBe(false);});
 it("rejects execution as guide support and incompatible fact classifications",()=>{const source=fixture().sources[0];expect(partnerSourceSchema.safeParse({...source,kind:"verified_research",classification:"customer_fact"}).success).toBe(false);expect(partnerGuideContentSchema.safeParse({...fixture(),sources:[{...source,kind:"accepted_execution",engagementId:randomUUID(),locator:undefined}]}).success).toBe(false);});
});
