import {describe,it,expect} from 'vitest';
import {composeExecutiveReport} from '../../lib/server/reports/executive';
import {EXECUTIVE_SECTIONS} from '../../lib/reports/document';
function snapshot(){return {selection:{kind:'monthly',audience:'delivery',timezone:'UTC'},period:{fromDate:'2026-09-01',toDate:'2026-09-30',partial:false,timezone:'UTC'},asOf:'2026-10-03T12:00:00Z',cutoffDate:'2026-10-03',synthetic:true,engagements:[{id:'engagement-a',baselineId:'baseline-a',workloadId:null,state:'active'}],records:[{revisionId:'reviewed-a',engagementId:'engagement-a',kind:'outcome',eventDate:'2026-09-20',content:{title:'Accepted outcome',narrative:'A verified delivery result'}},{revisionId:'reviewed-b',engagementId:'engagement-a',kind:'raid',eventDate:'2026-09-21',content:{title:'Reviewed risk',narrative:'Decision required'}},{revisionId:'reviewed-c',engagementId:'engagement-a',kind:'activity',eventDate:'2026-09-25',content:{subtype:'milestone_plan',title:'Next milestone',narrative:'Proposed work'}}],dependencies:[{kind:'execution_record',revisionId:'reviewed-a'},{kind:'execution_record',revisionId:'reviewed-b'},{kind:'execution_record',revisionId:'reviewed-c'}],calculations:[],coverage:{reviewRequiredRecords:0}} as any;}
describe('deterministic executive report composition',()=>{
 it('uses the required sections and accepted evidence without inventing maturity or effort',()=>{const doc=composeExecutiveReport(snapshot());expect(doc.sections.map(section=>section.heading)).toEqual([...EXECUTIVE_SECTIONS]);expect(doc.sections[2].blocks).toContainEqual({type:'fact',text:'Accepted outcome (2026-09-20): A verified delivery result',citations:['S1']});expect(doc.sections[1].blocks.every(block=>block.type==='gap')).toBe(true);expect(doc.metrics).toEqual([]);expect(JSON.stringify(doc)).not.toContain('customer maturity increased');});
 it('shows accepted maturity and adoption precisely without embedding private assessor metadata',()=>{
  const input=snapshot();input.dependencies.push({kind:'accepted_profile',revisionId:'maturity-a'},{kind:'accepted_profile',revisionId:'adoption-a'});
  input.profiles=[{revisionId:'maturity-a',workloadId:null,payload:{kind:'maturity_assessment',rubricVersion:'customer-maturity-v1',observationStart:'2026-09-01T00:00:00Z',observationEnd:'2026-09-25T00:00:00Z',assessor:'PRIVATE_ASSESSOR_SENTINEL',journeyStage:'Activate',dimensions:[{key:'operational_trust',state:'Measured',rationale:'Accepted operational evidence',nextCapability:'Review continuity'}],rationale:'Accepted journey evidence',nextCapability:'Review next capability',reviewAt:'2026-11-01T00:00:00Z'}},{revisionId:'adoption-a',workloadId:null,payload:{kind:'product_use',displayName:'Edge capability',state:'planned',usageDescription:'Planned rollout',observedAt:'2026-09-25T00:00:00Z'}}];
  const doc=composeExecutiveReport(input);expect(JSON.stringify(doc.sections[1])).toContain('Activate');expect(JSON.stringify(doc.sections[1])).toContain('Measured');expect(doc.sections[2].blocks.some(block=>block.type==='proposal' && block.text.includes('planned'))).toBe(true);expect(JSON.stringify(doc)).not.toContain('PRIVATE_ASSESSOR_SENTINEL');
 });
 it('marks next steps as proposals and annotations as annotations',()=>{const doc=composeExecutiveReport(snapshot(),['Reviewer asks for a decision']);expect(doc.sections[5].blocks[0].type).toBe('proposal');expect(doc.annotations).toEqual(['Reviewer asks for a decision']);expect(doc.sections.flatMap(section=>section.blocks).some(block=>block.text.includes('Reviewer asks'))).toBe(false);});
 it('keeps quarterly/partial/correction identity exact and leaves missing inputs explicit',()=>{const input=snapshot();input.selection.kind='quarterly';input.period.partial=true;input.records=[];const doc=composeExecutiveReport(input,[],'published-predecessor');expect(doc.kind).toBe('quarterly');expect(doc.partial).toBe(true);expect(doc.correctionOf).toBe('published-predecessor');expect(doc.sections.every(section=>section.blocks.length>0)).toBe(true);expect(doc.gaps.length).toBeGreaterThan(0);});
});
